### PR TITLE
arch/*/src/Makefile: Generate dependencies for "head" files.

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
Changing a configuration from menuconfig and then recompiling wasn't affecting "head" files.
## Impact
Should recompile head files when configuration changes.
## Testing
esp32 board configs.

### CODE REVIEW

**Comment by Ouss4** [comment]
Other arch/ also need something similar.

**Comment by v01d** [comment]
Looks OK. Did you verify that dep entries are added correctly to the Make.dep? You can also run with V=1 and see the mkdep calls.

**Comment by Ouss4** [comment]
> Looks OK. Did you verify that dep entries are added correctly to the Make.dep? You can also run with V=1 and see the mkdep calls.

Yes, actually I looked there first.

**Comment by v01d** [comment]
Could you apply the change to other arch as well?

**Comment by Ouss4** [comment]
> Could you apply the change to other arch as well?

Yes, will do that in a moment.

**Comment by v01d** [comment]
Ok, I'm converting to draft in the meantime just in case.

**Comment by Ouss4** [comment]
Done.  Please take a look.

Can you or @xiaoxiang781216 double check that this is not needed for the simulator?

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by SYKAP** [comment]
@Ouss4 would u like to contact me?Thanks

**Pull request merged**
