### PR TITLE
Remove the unnecessary math.h inclusion

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Fix the problem reported here: https://github.com/apache/incubator-nuttx/issues/3456

## Impact
Reduce the dependence on math.h

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@antmerlino Could you try this patch?

**Comment by antmerlino** [comment]
> 
> 
> @antmerlino Could you try this patch?

@xiaoxiang781216 The build worked now. Thanks!

**Comment by antmerlino** [comment]
@xiaoxiang781216 I saw you were still working on this - I assume to get past CI. Is this good to merge now?

**Comment by xiaoxiang781216** [comment]
Yes, it is ready for merge.

**Review by antmerlino — APPROVED** [review]

**Pull request merged**
