### PR TITLE
net/: Fix typos in comments.

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
Correct some comments.
## Impact
N/A
## Testing
N/A

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by hartmannathan — APPROVED** [review]
LGTM

**Comment by hartmannathan** [comment]
Let us know if you're done pushing to this branch and it's ready for merging...

**Comment by Ouss4** [comment]
Yes,  this one should be ready to go.

**Comment by hartmannathan** [comment]
Done. Thank you!

**Pull request merged**
