### PR TITLE
Add support for Sparkfun NRF52832 Breakout board

### PR DESCRIPTION
**Pull request by v01d**
## Summary

Add (basic) support for this board

## Impact

New board

## Testing

Boots correctly, gives nsh prompt via serial.

### CODE REVIEW

**Comment by v01d** [comment]
The CI is failing but I don't really understand the problem. Anyone could take a look?

**Comment by Ouss4** [comment]
> The CI is failing but I don't really understand the problem. Anyone could take a look?

You need to run ./tools/refresh.sh --silent nrf52832-sparkfun:nsh to update the defconfig, it's using some old values.

**Comment by Ouss4** [comment]
BTW @v01d, the files have BSD licenses, that needs to be changed to Apache.
I see some simple files with a certain Janne as author, similar files exist from Greg or Mateusz who both have ICLAs.

**Comment by v01d** [comment]
Sorry I missed it, this was from a fork I only recently rebased to master. I used one of the other nrf52 boards as a base.
I will update the headers and push again.

**Comment by v01d** [comment]
BTW, it seems Janne Rosberg is @jrosberg. He does not appear to be active on GitHub for some time but hopefully he gets notified and we can sort the licensing of existing files.

**Comment by v01d** [comment]
Ok, I recreated files from Apache licensed similar files and remove those copyrighted by Janne (userleds and buttons).

**Pull request merged**
