### PR TITLE
Fix nxstyle warning

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
boards/arm/imxrt: Fix nxstyle warning in imxrt1060-evk/src/imxrt_boot.c 
arch/arm: Fix nxstyle warning in stm32h7/stm32_dma.c

## Impact
Should no, only style change

## Testing
Pass the build

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]
LGTM

**Comment by xiaoxiang781216** [comment]
@davids5 : the warning left in https://github.com/apache/incubator-nuttx/pull/3143 is fixed here.

**Review by davids5 — APPROVED** [review]
@xiaoxiang781216 - Thank you.

Question: It this to the coding standard or just make the tool happy?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 - Thank you.
> 
> Question: It this to the coding standard or just make the tool happy?

I trust tool. Different people may interpret the coding standard in the different way.

**Pull request merged**
