### PR TITLE
boards/xtensa/esp32/esp32-core/include/board.h: nxstyle fixes

### PR DESCRIPTION
**Pull request by yamt**
The remaining errors:

    Long line found

I didn't fix it because it's on a URL.
There's no good way to wrap a URL as far as I know.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@patacongo should we waive this warning?

**Comment by yamt** [comment]
my suggestion is to make nxstyle skip the check if the line includes a URL-like string.
because:
* usually URLs are not under our control
* there's no good way to wrap URLs

**Comment by patacongo** [comment]
To me, I don't mind waiving some style warnings.  The job is very big right now but will bet better in the future, I hope.  I think we should think about community first and make sure that we are supportive of people who make a good effort.  We will catch the error again another day.

So, if you are satisified, I have no problem waiving the single remaining issue.  I think you do not need my concurrence, I will always trust your judgement on things like this.  This all only works because people have good intentions and we trust each other.

**Comment by xiaoxiang781216** [comment]
> my suggestion is to make nxstyle skip the check if the line includes a URL-like string.
> because:
> 
> * usually URLs are not under our control
> * there's no good way to wrap URLs

@yamt and @patacongo since the tool need time to improve what we face during the daliy development, how about we don't make the build test depends on style check? So we can ensure the change pass the build, but waive the style problem case by base.

**Comment by patacongo** [comment]
> @yamt and @patacongo since the tool need time to improve what we face during the daliy development, how about we don't make the build test depends on style check? So we can ensure the change pass the build, but waive the style problem case by base.

I think that is a great idea.  I like giving the final decision to the committer.  There are too many special cases like this where dividing a long line is worse the keeping the line too long.

And we have to have some way to continue and make progress.  It is important to fix style errors, but not as important as making progress and trying not to annoy our contributors too much.

**Comment by xiaoxiang781216** [comment]
> > @yamt and @patacongo since the tool need time to improve what we face during the daliy development, how about we don't make the build test depends on style check? So we can ensure the change pass the build, but waive the style problem case by base.
> 
> I think that is a great idea. I like giving the final decision to the committer. There are too many special cases like this where dividing a long line is worse the keeping the line too long.
> 
> And we have to have some way to continue and make progress. It is important to fix style errors, but not as important as making progress and trying not to annoy our contributors too much.

@liuguo09 please help change the workflow a litlte bit.

**Comment by patacongo** [comment]
Did you notic in PR #459, the contributor fixed the long line problem with extending the "ruler", that is the top and bottom of all block comments to 180 characters!  What is your thought on that?  I would rather have the nxstyle failure.

**Comment by patacongo** [comment]
>     * there's no good way to wrap URLs

On the other hand, there is no reason to necessarily preserve a URL in its exact form.  it is just a comment and a help, it is not a hyper-link and need not be fully syntacticlly correct.  There is really nothing wrong with arbitrarily break in URL into at clean points in the path.  The URL is still usable, just cannot be used with a single copy-paste.

**Comment by justinmclean** [comment]
You could also use the apache URL shortener https://s.apache.org

**Pull request merged**
