### PR TITLE
Fix ci warning

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- lm3s6965-ek/qemu-kostest: Fix warning: selects NETDEVICES which has unmet direct dependencies (NET)
- boards/b-l475e-iot01a: Fix selects WL_SPIRIT which has unmet direct dependencies (DRIVERS_WIRELESS && ALLOW_BSD_COMPONENTS)
- arch/arm: Fix target 'arm_vectortab.o' given more than once in the same rule
- arch/sim: Fix warning: overriding recipe for target 'config.h'

## Impact
Minor

## Testing
Pass CI

### CODE REVIEW

**Comment by masayuki2009** [comment]
https://github.com/apache/incubator-nuttx/pull/5597

**Comment by masayuki2009** [comment]
@xiaoxiang781216 

I found the root cause of lm3s6965-ek:qemu-kostest.
I will create a new PR later, so please remove the commit for it.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> 
> I found the root cause of lm3s6965-ek:qemu-kostest. I will create a new PR later, so please remove the commit for it.

I can add the dependence back if you want, I just think that it isn't necessary to enable ethernet in kotest.

**Comment by xiaoxiang781216** [comment]
@masayuki2009 please review again.

**Comment by masayuki2009** [comment]
>@masayuki2009 please review again.

I think the qemu-ostest/defconfig is still incorrect.

I created a new PR instead of the commit.
https://github.com/apache/incubator-nuttx/pull/6233

**Comment by xiaoxiang781216** [comment]
> > @masayuki2009 please review again.
> 
> I think the qemu-ostest/defconfig is still incorrect.
> 
> I created a new PR instead of the commit. #6233

The change look better, I have dropped the related change from this PR.

**Pull request merged**
