### PR TITLE
tools: add option to reuse boards common files for custom boards

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
I'm having a custom board configuration, but still would like to use common code for boards with the same architecture. Add option to reuse boards common files for custom boards

## Impact
None

## Testing
Pass CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by Ouss4** [comment]
The custom boards can have their own common folder.  How would this work in that case?

**Comment by pkarashchenko** [comment]
> The custom boards can have their own common folder.  How would this work in that case?

The NuttX board arch common is used only if custom board common is not there. Please see one line above

**Comment by Ouss4** [comment]
> > The custom boards can have their own common folder.  How would this work in that case?
> 
> The NuttX board arch common is used only if custom board common is not there. Please see one line above

I see now, sorry.
One thing to not here is that if one is using custom boards at some point a custom device driver can be used.  In this case, it will either go to each custom boards' source folder, or the common custom folder needs to be created.
I think however that copying the in-tree one would be straightforward and doesn't need any configuration/modification.

**Review by Ouss4 — APPROVED** [review]

**Comment by pkarashchenko** [comment]
> > > The custom boards can have their own common folder.  How would this work in that case?
> > 
> > The NuttX board arch common is used only if custom board common is not there. Please see one line above
> 
> I see now, sorry.
> One thing to not here is that if one is using custom boards at some point a custom device driver can be used.  In this case, it will either go to each custom boards' source folder, or the common custom folder needs to be created.
> I think however that copying the in-tree one would be straightforward and doesn't need any configuration/modification.

Yes. Exactly.

**Pull request merged**
