### PR TITLE
bcm43xxx: supported ARM CR4 core and bcm43455 chip in particular

### PR DESCRIPTION
**Pull request by a-lunev**
## Summary

Supported ARM CR4 core in bcm43xxx driver and bcm43455 chip in particular.

## Impact

bcm43xxx driver

## Testing

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@a-lunev could you share some performance and stability data about bcm43xxx? We are very interested in the quality of this driver.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by a-lunev** [comment]
> @a-lunev could you share some performance and stability data about bcm43xxx? We are very interested in the quality of this driver.

I have tested the performance neither based on a raw network traffic nor based on UDP.
Concerning TCP network traffic the peak payload throughput I observed is about 22-23 Mbit/s for BCM43362 chip, about 25 Mbit/s for BCM43438 chip, and about 40 Mbit/s for BCM43455 chip. The performance depends on different factors such as the performance of host CPU, radio-frequency interference etc.
The driver stability looks not bad if the network traffic is not high (less than the peak). If the network traffic is about to the peak, the driver (or chip) sometimes hangs up for some reason. In my previous PRs I fixed some stability issues, however as I can see there are still some hidden ones.

**Comment by xiaoxiang781216** [comment]
BTW, how much frequency do your host MCU run on?

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by a-lunev** [comment]
> BTW, how much frequency do your host MCU run on?

I tested at 120 MHz, 200 MHz and 400 MHz (ARM CM3/CM7). The higher host MCU frequency, the higher the driver performance. I suppose it may be even better at frequencies higher than 400 MHz.

**Comment by haodi-ioe** [comment]
Thanks a lot for your performance results，we are now debuging on bcm43438 and will refer your reply.

@xiaoxiang781216  ♡

**Comment by xiaoxiang781216** [comment]
One more question:), @a-lunev how much throughput you can achieve at 120MHz?

**Comment by a-lunev** [comment]
> One more question:), @a-lunev how much throughput you can achieve at 120MHz?

I prepared configuration file (#5130) for Photon board (120 MHz host MCU, BCM43362 Wi-Fi chip) to measure wlan performance.
Based on the current state of the master branch:
- the peak TCP payload throughput (unbuffered mode) is about 13 Mbit/s
- the peak UDP payload throughput (unbuffered mode, CRC enabled) is about 17 Mbit/s
- the peak UDP payload throughput (unbuffered mode, CRC disabled) is about 20 Mbit/s

**Comment by xiaoxiang781216** [comment]
Thanks @a-lunev we are trying your new config:).

**Pull request merged**
