### PR TITLE
libc: Make perror work without CONFIG_FILE_STREAM

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Impact
Minor

## Testing
Pass CI

### CODE REVIEW

**Review by davids5 — COMMENTED** [review]
@xiaoxiang781216 What was the motivation for this change?

**Comment by xiaoxiang781216** [comment]
Let, the stdio(implicitly accept stdin/stdout/stderr) API work even the general stdio(fopen, fclose) API doesn't exist. This is the practice already used for printf:
https://github.com/apache/incubator-nuttx/blob/master/libs/libc/stdio/lib_printf.c#L43-L47
and relate to make nsh work even without FILE related API:
https://github.com/apache/incubator-nuttx/pull/4819
https://github.com/apache/incubator-nuttx-apps/pull/892

**Comment by xiaoxiang781216** [comment]
@davids5 do you have any more concern?

**Review by davids5 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@davids5 could you merge this PR?

**Pull request merged**
