### PR TITLE
arch: Fix rtcb can't found error 

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
use the same condition check in declaration and reference

## Impact
Fix the compile error in some config combination

## Testing
Pass internal build

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 What combination caused an error?

**Comment by xiaoxiang781216** [comment]
CONFIG_TASK_NAME_SIZE > 0 and CONFIG_SMP = y, but CONFIG_DEBUG_ALERT not defined:
https://github.com/apache/incubator-nuttx/pull/4152/files#diff-39daf9be449b46cf6cf46b466802ed6d9208015158c17842f642c314e4cbaa81R396-R412
rtcb(line 399) is skipped, but line 411 reference rtcb.

**Comment by davids5** [comment]
Then the proper fix is to add `defined(CONFIG_DEBUG_ALERT)` because _alert is gated by it

**Comment by xiaoxiang781216** [comment]
> Then the proper fix is to add `defined(CONFIG_DEBUG_ALERT)` because _alert is gated by it

No, it's better to not guard the code, so the compiler can detect the syntax error. Please see this PR to see how many typo error found so far:
https://github.com/apache/incubator-nuttx/commit/5f3a98b5a8d39a7a9ee1823c6f7eaf05b1822ad7

**Comment by davids5** [comment]
> > Then the proper fix is to add `defined(CONFIG_DEBUG_ALERT)` because _alert is gated by it
> 
> No, it's better to not guard the code, so the compiler can detect the syntax error. Please see this PR to see how many typo error found so far: [5f3a98b](https://github.com/apache/incubator-nuttx/commit/5f3a98b5a8d39a7a9ee1823c6f7eaf05b1822ad7)

I agree we have got to have better testing (test vectors) but shorting the test vectors by increasing code size (in non debug code) is wasting resources and has REAL world limits.  

Nuttx has carelessly grown in BOTH RAM and FLASH resources since the last release. Stack penetration is way up. Ton's of code that should be behind Kconfig knob has been added with out limit. The biggest SoC that can do file system functions should not be dictating the FLASH size on a little SoC that does not need chmod, et all. 

We use to prioritize  SMALL FLASH size a lot now it seems like wanting to be Linux is more a priority

**Comment by acassis** [comment]
> > > Then the proper fix is to add `defined(CONFIG_DEBUG_ALERT)` because _alert is gated by it
> > 
> > 
> > No, it's better to not guard the code, so the compiler can detect the syntax error. Please see this PR to see how many typo error found so far: [5f3a98b](https://github.com/apache/incubator-nuttx/commit/5f3a98b5a8d39a7a9ee1823c6f7eaf05b1822ad7)
> 
> I agree we have got to have better testing (test vectors) but shorting the test vectors by increasing code size (in non debug code) is wasting resources and has REAL world limits.
> 
> Nuttx has carelessly grown in BOTH RAM and FLASH resources since the last release. Stack penetration is way up. Ton's of code that should be behind Kconfig knob has been added with out limit. The biggest SoC that can do file system functions should not be dictating the FLASH size on a little SoC that does not need chmod, et all.
> 
> We use to prioritize SMALL FLASH size a lot now it seems like wanting to be Linux is more a priority

@davids5 during the release of a new version I always test against fw size increasing, but I agree we should have some "bloatware" test in the CI to alarm when the code increase more than 500 bytes or so. Are you tracking it? Just saying that size is increasing it not enough, it will not help much here. :-)

**Comment by davids5** [comment]
> @davids5 during the release of a new version I always test against fw size increasing, but I agree we should have some "bloatware" test in the CI to alarm when the code increase more than 500 bytes or so. 

Yep. It is too late at the point of the  release.

>Are you tracking it? 


PX4 master (on 10.0.0+) Vs PX4 master + changes to run on current upstream + (the idle tcb fix)

You can see the nuttx changes and ignore PX4 Code. 
Except to consider the effect the changes in nuttx are having on user code 
Remember this is the same version of PX4 with mostly (defconfig change)

image
image


```
<pre>     VM SIZE    
 -------------- 
  [NEW] +3.31Ki    mag_calibrate_all(void**, long)
  +0.8% +1.47Ki    g_cromfs_image
  +2.5% +1.05Ki    [578 Others]
  [NEW]    +592    px4::logger::Logger::Logger(unsigned char, unsigned int, unsigned long, char const*, px4::logger::Logger::LogMode, bool)
  [NEW]    +504    px4::logger::util::check_free_space(char const*, long, void*&amp;, int&amp;)
  +0.3%    +495    [section .text]
  [NEW]    +480    nx_pthread_create
  [NEW]    +464    PreFlightCheck::magnetometerCheck(void**, vehicle_status_s&amp;, unsigned char, bool, long&amp;, bool)
  [NEW]    +452    uavcan_stm32::CanIface::init(unsigned long, uavcan_stm32::CanIface::OperatingMode)
  [NEW]    +388    icmp_recvmsg
  [NEW]    +376    PreFlightCheck::accelerometerCheck(void**, vehicle_status_s&amp;, unsigned char, bool, long&amp;, bool)
  [NEW]    +348    icmp_sendmsg
  [NEW]    +342    getopt_common
  [NEW]    +316    DataValidator::put(unsigned long long, float const*, unsigned long, unsigned char)
  [NEW]    +288    PreFlightCheck::gyroCheck(void**, vehicle_status_s&amp;, unsigned char, bool, long&amp;, bool)
   +21%    +272    proc_read
  [NEW]    +264    ADC::ADC(unsigned long, unsigned long)
  [NEW]    +242    file_vopen
  [NEW]    +236    PreFlightCheck::baroCheck(void**, vehicle_status_s&amp;, unsigned char, bool, long&amp;, bool)
  [NEW]    +236    inet_socketpair
  [NEW]    +228    getopt_long_option
  [NEW]    +228    tcp_recvhandler
  [NEW]    +224    MavlinkMissionManager::update_active_mission(dm_item_t, unsigned short, long)
  [NEW]    +224    UavcanNode::start(uavcan::NodeID, unsigned long)
  [NEW]    +222    inet_sendmsg
  [NEW]    +208    px4::logger::Logger::handle_event_updates(unsigned long&amp;)
  [NEW]    +206    nx_unlink
  [NEW]    +204    unlink_recursive
  +238%    +200    nxtask_assign_pid
   +16%    +194    tcp_ipv4_input
  [NEW]    +188    uORB::SubscriptionBlocking&lt;sensor_accel_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned long, unsigned char)
  [NEW]    +188    uORB::SubscriptionBlocking&lt;sensor_gyro_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned long, unsigned char)
  [NEW]    +188    uORB::SubscriptionBlocking&lt;sensor_mag_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned long, unsigned char)
  [NEW]    +188    uavcan_stm32::CanIface::computeTimings(unsigned long, uavcan_stm32::CanIface::Timings&amp;)
  [NEW]    +176    pipe_register.isra.0.part.0.constprop.0
  +221%    +172    files_allocate
   +59%    +172    psock_tcp_send
  [NEW]    +172    send_vehicle_command(unsigned long, float, float, float, float, double, double, float)
  [NEW]    +172    uavcan_stm32::CanInitHelper&lt;21u&gt;::CanInitHelper(unsigned long)
  [NEW]    +152    MavlinkLogHandler::_get_log_time_size(char const*, char const*, unsigned long&amp;, unsigned long&amp;)
  [NEW]    +148    MavlinkLogHandler::_get_entry(int, unsigned long&amp;, unsigned long&amp;, char*, int)
  [NEW]    +146    VtolType::set_motor_state(motor_state, long, int)
  [NEW]    +144    MavlinkLogHandler::_scan_logs(file_struct*, char const*, unsigned long&amp;)
  [NEW]    +140    default_gpios.9855
  [NEW]    +140    gpio.11169
  +464%    +130    file_vioctl
  [NEW]    +130    net_ioctl_arglen
  [NEW]    +126    events::send(unsigned long, events::LogLevels const&amp;, char const*) (.isra.0)
  [NEW]    +120    commands.23375
  [NEW]    +120    fat_computefreeclusters
  [NEW]    +116    PX4Accelerometer::PX4Accelerometer(unsigned long, Rotation)
   +38%    +116    meminfo_read
  [NEW]    +112    PX4Gyroscope::PX4Gyroscope(unsigned long, Rotation)
  [NEW]    +112    sPort_send_data(int, unsigned short, unsigned long)
  +500%    +110    nx_dup2
  [NEW]    +108    px4::logger::Logger::ack_vehicle_command(vehicle_command_s*, unsigned long)
  [NEW]    +108    void px4::logger::Logger::write_info_template&lt;long&gt;(px4::logger::LogType, char const*, long, char const*)
  [NEW]    +108    void px4::logger::Logger::write_info_template&lt;unsigned long&gt;(px4::logger::LogType, char const*, unsigned long, char const*)
  [NEW]    +104    calibration::Accelerometer::Accelerometer(unsigned long, bool)
  [NEW]    +104    calibration::FindCalibrationIndex(char const*, unsigned long)
  [NEW]    +104    uavcan_stm32::CanDriver::init(unsigned long, uavcan_stm32::CanIface::OperatingMode, unsigned long)
  [NEW]    +100    CSWTCH.137
  [NEW]    +100    MavlinkLogHandler::_get_session_date(char const*, char const*, unsigned long&amp;)
  [NEW]    +100    files_duplist
  [NEW]    +100    udp_setsockopt
  [NEW]     +96    _print_sub(char const*, vehicle_status_s const&amp;, unsigned long)
  [NEW]     +96    calibration::Gyroscope::Gyroscope(unsigned long, bool)
  +2.0%     +96    g_iob_pool
  [NEW]     +96    uavcan::Scheduler::pollCleanup(uavcan::MonotonicTime, unsigned long)
  +427%     +94    nx_close
  [NEW]     +92    calibration::SetCalibrationParam(char const*, char const*, unsigned char, long)
  [NEW]     +92    vmount::OutputMavlinkV2::OutputMavlinkV2(long, long, vmount::OutputConfig const&amp;)
  [NEW]     +88    VL53L1X::VL53L1X_SetInterMeasurementInMs(unsigned long)
  [NEW]     +88    calibration::Magnetometer::Magnetometer(unsigned long, bool)
  [NEW]     +88    device::SPI::SPI(unsigned char, char const*, int, unsigned long, spi_mode_e, unsigned long)
   +14%     +88    psock_vioctl
  [NEW]     +86    uavcan::dynamic_node_id_server::StorageMarshaller::get(uavcan::Array&lt;uavcan::IntegerSpec&lt;8u, (uavcan::Signedness)0, (uavcan::CastMode)0&gt;, (uavcan::ArrayMode)1, 32u&gt; const&amp;, unsigned long&amp;) const
  [NEW]     +84    Navigator::buffer_air_traffic(unsigned long)
  [NEW]     +82    files_extend
  [NEW]     +80    device::Device::device_id_print_buffer(char*, int, unsigned long)
  [NEW]     +80    vmount::InputMavlinkGimbalV2::_set_control_data_from_set_attitude(unsigned long, matrix::Quaternion&lt;float&gt; const&amp;, matrix::Vector3&lt;float&gt; const&amp;)
  [NEW]     +76    BMP280_SPI::BMP280_SPI(unsigned char, unsigned long, int, spi_mode_e)
  [NEW]     +76    inet_recvmsg
   +12%     +74    psock_send_eventhandler
  [NEW]     +72    BMP280_I2C::BMP280_I2C(unsigned char, unsigned long, int)
  [NEW]     +72    CSWTCH.258
  [NEW]     +72    nx_pthread_exit
  [NEW]     +72    tcp_should_send_recvwindow
  [NEW]     +68    MavlinkMissionManager::send_mission_current(long)
  [NEW]     +68    calibration::Accelerometer::set_device_id(unsigned long, bool)
  [NEW]     +68    calibration::Gyroscope::set_device_id(unsigned long, bool)
  [NEW]     +68    inode_getpath
   +44%     +68    netdev_register
  [NEW]     +68    px4_find_spi_bus(unsigned long)
  [NEW]     +64    PWMIN::publish(unsigned short, unsigned long, unsigned long)
  [NEW]     +64    device::I2C::I2C(unsigned char, char const*, int, unsigned short, unsigned long)
  +6.5%     +64    g_tcp_connections
  [NEW]     +64    px4::device_bus_to_wq(unsigned long)
  [NEW]     +60    MS5611_SPI::MS5611_SPI(unsigned char, unsigned long, ms5611::prom_u&amp;, int, spi_mode_e)
  [NEW]     +60    VL53L1X::VL53L1_WrDWord(unsigned short, unsigned long)
  [NEW]     +60    calibration::Magnetometer::set_device_id(unsigned long, bool)
  [NEW]     +60    inode_alloc.isra.0
  [NEW]     +58    tls_destruct
  [NEW]     +56    BMP388_SPI::BMP388_SPI(unsigned char, unsigned long, int, spi_mode_e)
  [NEW]     +56    PX4IO_Uploader::get_info(int, unsigned long&amp;)
  [DEL]     -56    BMP388_SPI::BMP388_SPI(unsigned char, unsigned int, int, spi_mode_e)
  [DEL]     -56    PX4IO_Uploader::get_info(int, unsigned int&amp;)
 -80.6%     -58    pthread_exit
  [DEL]     -60    MS5611_SPI::MS5611_SPI(unsigned char, unsigned int, ms5611::prom_u&amp;, int, spi_mode_e)
  [DEL]     -60    VL53L1X::VL53L1_WrDWord(unsigned short, unsigned int)
  [DEL]     -60    calibration::Magnetometer::set_device_id(unsigned int, bool)
  [DEL]     -60    files_close
  [DEL]     -60    inode_alloc
  [DEL]     -62    fs_dupfd2
  [DEL]     -64    PWMIN::publish(unsigned short, unsigned int, unsigned int)
  [DEL]     -64    device::I2C::I2C(unsigned char, char const*, int, unsigned short, unsigned int)
  [DEL]     -64    inet_recvfrom
  [DEL]     -64    px4::device_bus_to_wq(unsigned int)
  [DEL]     -68    MavlinkMissionManager::send_mission_current(int)
  [DEL]     -68    calibration::Accelerometer::set_device_id(unsigned int, bool)
  [DEL]     -68    calibration::Gyroscope::set_device_id(unsigned int, bool)
  [DEL]     -68    mq_inode_release
  [DEL]     -68    px4_find_spi_bus(unsigned int)
  [DEL]     -72    BMP280_I2C::BMP280_I2C(unsigned char, unsigned int, int)
  [DEL]     -72    CSWTCH.256
  [DEL]     -72    nxmq_alloc_desblock
  [DEL]     -76    BMP280_SPI::BMP280_SPI(unsigned char, unsigned int, int, spi_mode_e)
  [DEL]     -76    net_dup2
  [DEL]     -80    device::Device::device_id_print_buffer(char*, int, unsigned int)
  [DEL]     -80    vmount::InputMavlinkGimbalV2::_set_control_data_from_set_attitude(unsigned int, matrix::Quaternion&lt;float&gt; const&amp;, matrix::Vector3&lt;float&gt; const&amp;)
  [DEL]     -84    Navigator::buffer_air_traffic(unsigned int)
  [DEL]     -86    uavcan::dynamic_node_id_server::StorageMarshaller::get(uavcan::Array&lt;uavcan::IntegerSpec&lt;8u, (uavcan::Signedness)0, (uavcan::CastMode)0&gt;, (uavcan::ArrayMode)1, 32u&gt; const&amp;, unsigned int&amp;) const
  [DEL]     -88    VL53L1X::VL53L1X_SetInterMeasurementInMs(unsigned int)
  [DEL]     -88    calibration::Magnetometer::Magnetometer(unsigned int, bool)
  [DEL]     -88    device::SPI::SPI(unsigned char, char const*, int, unsigned int, spi_mode_e, unsigned int)
  [DEL]     -88    mkfatfs_devwrite.isra.0
  [DEL]     -90    psock_dup
  [DEL]     -92    calibration::SetCalibrationParam(char const*, char const*, unsigned char, int)
  [DEL]     -92    nxmq_free_msg
  [DEL]     -92    vmount::OutputMavlinkV2::OutputMavlinkV2(int, int, vmount::OutputConfig const&amp;)
  [DEL]     -96    _print_sub(char const*, vehicle_status_s const&amp;, unsigned int)
  [DEL]     -96    calibration::Gyroscope::Gyroscope(unsigned int, bool)
  [DEL]     -96    uavcan::Scheduler::pollCleanup(uavcan::MonotonicTime, unsigned int)
  [DEL]    -100    CSWTCH.138
  [DEL]    -100    MavlinkLogHandler::_get_session_date(char const*, char const*, unsigned int&amp;)
  [DEL]    -104    calibration::Accelerometer::Accelerometer(unsigned int, bool)
  [DEL]    -104    calibration::FindCalibrationIndex(char const*, unsigned int)
  [DEL]    -104    uavcan_stm32::CanDriver::init(unsigned int, uavcan_stm32::CanIface::OperatingMode, unsigned int)
 -75.0%    -108    fat_nfreeclusters
  [DEL]    -108    nxmq_initialize
  [DEL]    -108    px4::logger::Logger::ack_vehicle_command(vehicle_command_s*, unsigned int)
  [DEL]    -108    void px4::logger::Logger::write_info_template&lt;int&gt;(px4::logger::LogType, char const*, int, char const*)
  [DEL]    -108    void px4::logger::Logger::write_info_template&lt;unsigned int&gt;(px4::logger::LogType, char const*, unsigned int, char const*)
  [DEL]    -112    PX4Gyroscope::PX4Gyroscope(unsigned int, Rotation)
  [DEL]    -112    sPort_send_data(int, unsigned short, unsigned int)
  [DEL]    -116    PX4Accelerometer::PX4Accelerometer(unsigned int, Rotation)
  [DEL]    -120    commands.23507
  [DEL]    -126    events::send(unsigned int, events::LogLevels const&amp;, char const*) (.isra.0)
  [DEL]    -129    g_bootcodeblob
  [DEL]    -140    default_gpios.9966
  [DEL]    -140    gpio.11260
  [DEL]    -144    MavlinkLogHandler::_scan_logs(file_struct*, char const*, unsigned int&amp;)
  [DEL]    -146    VtolType::set_motor_state(motor_state, int, int)
  [DEL]    -148    MavlinkLogHandler::_get_entry(int, unsigned int&amp;, unsigned int&amp;, char*, int)
  [DEL]    -150    nx_vioctl
  [DEL]    -152    MavlinkLogHandler::_get_log_time_size(char const*, char const*, unsigned int&amp;, unsigned int&amp;)
 -75.0%    -156    nx_vopen
 -62.5%    -160    nx_pipe
  [DEL]    -172    send_vehicle_command(unsigned int, float, float, float, float, double, double, float)
  [DEL]    -172    uavcan_stm32::CanInitHelper&lt;21u&gt;::CanInitHelper(unsigned int)
  [DEL]    -184    psock_vfcntl
  [DEL]    -188    uORB::SubscriptionBlocking&lt;sensor_accel_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned int, unsigned char)
  [DEL]    -188    uORB::SubscriptionBlocking&lt;sensor_gyro_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned int, unsigned char)
  [DEL]    -188    uORB::SubscriptionBlocking&lt;sensor_mag_s&gt;::SubscriptionBlocking(orb_metadata const*, unsigned int, unsigned char)
  [DEL]    -188    uavcan_stm32::CanIface::computeTimings(unsigned int, uavcan_stm32::CanIface::Timings&amp;)
  [DEL]    -194    tcp_eventhandler
 -87.4%    -194    unlink
  [DEL]    -208    px4::logger::Logger::handle_event_updates(unsigned int&amp;)
  [DEL]    -224    MavlinkMissionManager::update_active_mission(dm_item_t, unsigned short, int)
  [DEL]    -224    UavcanNode::start(uavcan::NodeID, unsigned int)
  [DEL]    -236    PreFlightCheck::baroCheck(void**, vehicle_status_s&amp;, unsigned char, bool, int&amp;, bool)
  [DEL]    -264    ADC::ADC(unsigned int, unsigned int)
  [DEL]    -288    PreFlightCheck::gyroCheck(void**, vehicle_status_s&amp;, unsigned char, bool, int&amp;, bool)
 -94.2%    -290    getopt
  [DEL]    -296    cmd_mkfatfs
  [DEL]    -312    icmp_sendto
  [DEL]    -312    mkfatfs
  [DEL]    -316    DataValidator::put(unsigned long long, float const*, unsigned int, unsigned char)
 -98.9%    -364    g_mmheap
  [DEL]    -372    icmp_recvfrom
  [DEL]    -376    PreFlightCheck::accelerometerCheck(void**, vehicle_status_s&amp;, unsigned char, bool, int&amp;, bool)
  [DEL]    -400    mkfatfs_initmbr
 -92.9%    -416    pthread_create
  [DEL]    -452    uavcan_stm32::CanIface::init(unsigned int, uavcan_stm32::CanIface::OperatingMode)
  [DEL]    -464    PreFlightCheck::magnetometerCheck(void**, vehicle_status_s&amp;, unsigned char, bool, int&amp;, bool)
  [DEL]    -484    mkfatfs_writefatfs
  [DEL]    -504    px4::logger::util::check_free_space(char const*, int, void*&amp;, int&amp;)
 -99.2%    -508    g_pidhash
  [DEL]    -592    px4::logger::Logger::Logger(unsigned char, unsigned int, unsigned int, char const*, px4::logger::Logger::LogMode, bool)
  [DEL]    -896    mkfatfs_configfatfs
  [DEL] -3.31Ki    mag_calibrate_all(void**, int)
  +0.1% +2.29Ki    TOTAL
```
> Just saying that size is increasing it not enough, it will not help much here. :-)

if you checkout px4 and use `pr-nuttx-10.1.0+-upstream` branch

you can build a target 

`make px4_fmu-v5x`
Then run 

`make bloaty_compare_master` 

and see how Nuttx is growing.


I hope this is more help for you Alan.

**Comment by xiaoxiang781216** [comment]
> > > Then the proper fix is to add `defined(CONFIG_DEBUG_ALERT)` because _alert is gated by it
> > 
> > 
> > No, it's better to not guard the code, so the compiler can detect the syntax error. Please see this PR to see how many typo error found so far: [5f3a98b](https://github.com/apache/incubator-nuttx/commit/5f3a98b5a8d39a7a9ee1823c6f7eaf05b1822ad7)
> 
> I agree we have got to have better testing (test vectors) but shorting the test vectors by increasing code size (in non debug code) is wasting resources and has REAL world limits.
> 
> Nuttx has carelessly grown in BOTH RAM and FLASH resources since the last release. Stack penetration is way up. Ton's of code that should be behind Kconfig knob has been added with out limit. The biggest SoC that can do file system functions should not be dictating the FLASH size on a little SoC that does not need chmod, et all.
> 
> We use to prioritize SMALL FLASH size a lot now it seems like wanting to be Linux is more a priority

Yes, but the compiler optimize out running_task call and rtcb variable in this case. You can verify it from the disassemble:
```
Dump of assembler code for function up_assert:
   0x000000000000d020 <+0>:     push   %rbp
   0x000000000000d021 <+1>:     mov    %rsp,%rbp
   0x000000000000d024 <+4>:     sub    $0x10,%rsp
   0x000000000000d028 <+8>:     mov    %rdi,-0x8(%rbp)
   0x000000000000d02c <+12>:    mov    %esi,-0xc(%rbp)
   0x000000000000d02f <+15>:    callq  0x24eea <syslog_flush>
   0x000000000000d034 <+20>:    callq  0x3c36c <up_cpu_index>
   0x000000000000d039 <+25>:    mov    %eax,%edx
   0x000000000000d03b <+27>:    mov    -0xc(%rbp),%ecx
   0x000000000000d03e <+30>:    mov    -0x8(%rbp),%rax
   0x000000000000d042 <+34>:    mov    %ecx,%r8d
   0x000000000000d045 <+37>:    mov    %rax,%rcx
   0x000000000000d048 <+40>:    lea    0x2fc41(%rip),%rsi        # 0x3cc90
   0x000000000000d04f <+47>:    mov    $0x3,%edi
   0x000000000000d054 <+52>:    mov    $0x0,%eax
   0x000000000000d059 <+57>:    callq  0xad7e <syslog>
```
The compiler is smart enough to remove the dead code from the final image:
https://github.com/apache/incubator-nuttx/blob/master/include/debug.h#L93-L115

**Comment by acassis** [comment]
@davids5 I think a bloaty test should exist on NuttX mainline CI to avoid depending on you seeing it on PX4 and reporting here. Do you think it is possible to contribute it on our CI test?

**Comment by xiaoxiang781216** [comment]
@davids5 I move the caller of running_task to _alert which should resovle your concern, please review again.

**Review by davids5 — APPROVED** [review]
@xiaoxiang781216 - Thank you for doing that. It is much cleaner!

**Comment by davids5** [comment]
> @davids5 I think a bloaty test should exist on NuttX mainline CI to avoid depending on you seeing it on PX4 and reporting here. Do you think it is possible to contribute it on our CI test?

Thought @btashton had some plans and possible issues for/with it. (Do we have persistence?)

**Comment by davids5** [comment]
@yamt - any feedback?

**Comment by acassis** [comment]
Well, if you can submit it we could include it in the CI test.

**Pull request merged**
