### PR TITLE
boards: sim: Update smp/defconfig

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- Add CONFIG_DRIVER_NOTE=y
- Add CONFIG_NSH_READLINE=y
- Add CONFIG_READLINE_CMD_HISTORY=y
- Add CONFIG_SCHED_INSTRUMENTATION=y

## Impact

- Affects sim:smp only

## Testing

- Tested with uname/ps/free/hello/smp/ostest

### CODE REVIEW

**Comment by sebastianene07** [comment]
Do we want `CONFIG_SCHED_INSTRUMENTATION ` enabled by default ? I guess that we should keep it turned off and only during an investigation to activate it.

**Comment by masayuki2009** [comment]
> Do we want `CONFIG_SCHED_INSTRUMENTATION ` enabled by default ? I guess that we should keep it turned off and only during an investigation to activate it.

@sebastianene07 
Once the NuttX smp feature becomes mature and stable, it should be removed by default.
However, I recommend to enable the feature.

**Comment by btashton** [comment]
It would also be nice from a CI standpoint at least for SIM to have fewer configs that are feature heavy than lots of configs for each feature.

**Comment by sebastianene07** [comment]
> > Do we want `CONFIG_SCHED_INSTRUMENTATION ` enabled by default ? I guess that we should keep it turned off and only during an investigation to activate it.
> 
> @sebastianene07
> Once the NuttX smp feature becomes mature and stable, it should be removed by default.
> However, I recommend enabling the feature.

Right, I agree with you. I am also looking into increasing the SMP stability for sim target.

**Review by xiaoxiang781216 — APPROVED** [review]
So let's merge it.

**Pull request merged**
