### PR TITLE
refresh spresense configs

### PR DESCRIPTION
**Pull request by yamt**
## Summary

run tools/refresh.sh on these configs.

### CODE REVIEW

**Comment by jerpelea** [comment]
@yamt
we need:
-audio in the audio config 
and 
-camera sensor in the camera config

**Comment by yamt** [comment]
> @yamt
> we need:
> -audio in the audio config
> and
> -camera sensor in the camera config

i just run tools/refresh.sh on these configs. in there something special for these configs?

**Comment by yamt** [comment]
> > @yamt
> > we need:
> > -audio in the audio config
> > and
> > -camera sensor in the camera config
> 
> i just run tools/refresh.sh on these configs. in there something special for these configs?

is this related to CONFIG_SPECIFIC_DRIVERS?

**Comment by jerpelea** [comment]
yes they are both specific drivers

**Comment by yamt** [comment]
@jerpelea
ok. thank you for explanation.
i noticed this when doing a bulk refresh for https://github.com/apache/incubator-nuttx/pull/3835
do you think it's something which can be fixed in tools/refresh.sh?
or should i just add them to my local exclude list? (it already has a bunch of configs for cygpath things)

**Comment by jerpelea** [comment]
please add them to your local exclude list

**Comment by yamt** [comment]
> please add them to your local exclude list

ok. thank you.

**Pull request closed without merging**
