### PR TITLE
sched/sched: Appease nxstyle errors

### PR DESCRIPTION
**Pull request by yamt**
The remaining errors ("Missing space before closing C comment")
don't make sense. Maybe a bug in nxstyle.

### CODE REVIEW

**Comment by yamt** [comment]
> Maybe a bug in nxstyle.

https://github.com/apache/incubator-nuttx/issues/540

**Comment by patacongo** [comment]
Let's wait for #542 to be merged and let the checks run again.

**Comment by xiaoxiang781216** [comment]
> Let's wait for #542 to be merged and let the checks run again.

@yamt you can rebase this PR now.

**Comment by patacongo** [comment]
Now I see that some lone line fixes that I did in sched/sched/sched_mergepending.c are conflicting with something else.  The version from #542 with the shorter lines is the one that is correct.

**Pull request merged**
