### PR TITLE
Added Support for more TI Tiva Microcontrollers:

### PR DESCRIPTION
**Pull request by fckruegel**
* TM4C123GH6PZ (100 pin version of TM4C123GH6PM)
* TM4C123GH6PGE (144 pin version of TM4C123GH6PM)
* TM4C129ENCPDT (TM4C1294 with Crypto hardware added, TQFP package)
* TM4C129ENCZAD (TM4C1294 with Crypto hardware added, BGA package)

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@fckruegel please fix the nxstyle warning here:
https://github.com/apache/incubator-nuttx/pull/2161/checks?check_run_id=1327083440
you can run locally too by:
./tools/checkpatch.sh -g HEAD~...HEAD

**Review by hartmannathan — COMMENTED** [review]
The changes look good to me.

There are only the nxstyle complaints, which are easy to fix. When it complains about "Wrong column position of comment right of code" just align the beginning of comments at the same column. It doesn't have to be the whole file, just the group of lines until the next blank line.

**Comment by xiaoxiang781216** [comment]
There are other errors too:
```
nuttx/arch/arm/src/tiva/hardware/tm4c/tm4c_memorymap.h:616:1: error: Missing blank line after comment
nuttx/arch/arm/src/tiva/hardware/tm4c/tm4c_pinmap.h:1:85: error: Long line found
```
If there is the unreasonable warning like "Wrong column position of comment right of code" mention in PR, we can then ignore it.

**Comment by hartmannathan** [comment]
Does anyone know why the check indicates a failure on nxstyle errors in arch/xtensa/src/esp32/esp32_spiflash.c? That file is not changed by this PR!!!

**Comment by btashton** [comment]
> Does anyone know why the check indicates a failure on nxstyle errors in arch/xtensa/src/esp32/esp32_spiflash.c? That file is not changed by this PR!!!

It has to do with how the commits are determined on the PR. You can ignore the non relevant ones or do a rebase.

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM, let's ignore the unrelated nxstyle warning.

**Pull request merged**
