### PR TITLE
ci: Freeze pipenv version for avoiding issue on documentation generation

### PR DESCRIPTION
**Pull request by gustavonihei**
## Summary
This PR intends to add a quick fix for an issue with the latest release of `pipenv`.

From my investigation seems related to this issue: https://github.com/pypa/pipenv/issues/4828

## Impact
No impact, fix for CI job.

## Testing
CI build pass.

### CODE REVIEW

**Comment by Ouss4** [comment]
So what's the root cause?  I had some desperate attempts locally.

**Comment by gustavonihei** [comment]
> So what's the root cause? I had some desperate attempts locally.

It seems that `pipenv run` is failing to actually execute the command inside the virtual environment.
The alternative method works: running `make run html` inside `pipenv shell`.

**Comment by Ouss4** [comment]
It looks like there is a fix for this already but still not part of any release, we'll have to merge this then.

**Comment by gustavonihei** [comment]
> It looks like there is a fix for this already but still not part of any release, we'll have to merge this then.

Just for future reference, the fix is already merged upstream:
https://github.com/pypa/pipenv/issues/4838

Once the hotfix is published to **pypi**, we can unfreeze `pipenv` version by reverting this commit.

**Review by Ouss4 — APPROVED** [review]

**Pull request merged**
