### PR TITLE
Integration between nuttx and pysimCoder

### PR DESCRIPTION
**Pull request by robertobucher**
## Summary
First try to integrate pysimCoder and nuttx in order to automatically generate code for control purposes

There is a correction in two files by adding "#include "stm32_rcc.h" after compilation erros by PWM multichannels and the qencoder.

The more nucleo-144 files allows to integrate in pysimCoder the following devices:
- 3 ADC channels on PA3, PC0 and PC3
- 4 PWM channels (Timer 3) on PA6, PA7, PB0 and PB1
- 1 encoder on pins PA15 and PB3
- 4 GPIO IN (PE8 / PE7 / PE10 / PE 12)
- 4 GPIO OUT (PF13 / PE9 / PE11 / PF14)
- CAN bus (CAN1) on pin PD0 and PD1

## Impact
Only some files under stm32f7 (arch and boards) have been modified

## Testing
The modifications have been tested on a NUCLEO-F746ZG board

### CODE REVIEW

**Comment by acassis** [comment]
Hi @robertobucher the CI reported some silly issues that need to be fixed. This issues were already there, but because this is the first time a PR includes these file we need to fix them:

```
can/can.c: In function 'can_rtrread':
Error: can/can.c:992:34: error: passing argument 2 of 'can_write' from incompatible pointer type [-Werror=incompatible-pointer-types]
  992 |                           request->ci_msg,
      |                           ~~~~~~~^~~~~~~~
      |                                  |
      |                                  struct can_msg_s *
can/can.c:781:66: note: expected 'const char *' but argument is of type 'struct can_msg_s *'
  781 | static ssize_t can_write(FAR struct file *filep, FAR const char *buffer,
      |                                                      ~~~~~~~~~~~~^~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:108: can.o] Error 1
In file included from sensors/qencoder.c:51:
sensors/qencoder.c: In function 'qe_close':
Error: sensors/qencoder.c:225:14: error: format '%d' expects a matching 'int' argument [-Werror=format=]
  225 |       sninfo("calling shutdown: %d\n");
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
sensors/qencoder.c:225:34: note: format string is defined here
  225 |       sninfo("calling shutdown: %d\n");
      |                                 ~^
      |                                  |
      |                                  int
cc1: all warnings being treated as errors
make[1]: *** [Makefile:108: qencoder.o] Error 1
In file included from rwbuffer.c:36:
rwbuffer.c: In function 'rwb_initialize':
Error: rwbuffer.c:865:16: error: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  865 |           ferr("Read-ahead buffer kmm_malloc(%d) failed\n", allocsize);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~
      |                                                             |
      |                                                             uint32_t {aka long unsigned int}
rwbuffer.c:865:47: note: format string is defined here
  865 |           ferr("Read-ahead buffer kmm_malloc(%d) failed\n", allocsize);
      |                                              ~^
      |                                               |
      |                                               int
      |                                              %ld
In file included from rwbuffer.c:36:
Error: rwbuffer.c:869:13: error: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  869 |       finfo("Read-ahead buffer size: %d bytes\n", allocsize);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~
      |                                                   |
      |                                                   uint32_t {aka long unsigned int}
rwbuffer.c:869:39: note: format string is defined here
  869 |       finfo("Read-ahead buffer size: %d bytes\n", allocsize);
      |                                      ~^
      |                                       |
      |                                       int
      |                                      %ld
At top level:
Error: rwbuffer.c:83:12: error: 'rwb_forcetake' defined but not used [-Werror=unused-function]
   83 | static int rwb_forcetake(FAR sem_t *sem)
      |            ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:108: rwbuffer.o] Error 1
make[1]: Target 'libdrivers.a' not remade because of errors.
make: *** [tools/LibTargets.mk:89: drivers/libdrivers.a] Error 2
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_adc.c:51:
chip/stm32_adc.c: In function 'adc_timinit':
Error: chip/stm32_adc.c:738:9: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  738 |   ainfo("Initializing timers extsel = 0x%08x\n", priv->extsel);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~
      |                                                      |
      |                                                      uint32_t {aka long unsigned int}
chip/stm32_adc.c:738:44: note: format string is defined here
  738 |   ainfo("Initializing timers extsel = 0x%08x\n", priv->extsel);
      |                                         ~~~^
      |                                            |
      |                                            unsigned int
      |                                         %08lx
cc1: all warnings being treated as errors
make[1]: *** [Makefile:138: stm32_adc.o] Error 1
In file included from chip/stm32_qencoder.c:46:
chip/stm32_qencoder.c: In function 'stm32_shutdown':
Error: chip/stm32_qencoder.c:1004:10: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1004 |   sninfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~
      |                                            |
      |                                            uint32_t {aka long unsigned int}
chip/stm32_qencoder.c:1004:23: note: format string is defined here
 1004 |   sninfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |                    ~~~^
      |                       |
      |                       unsigned int
      |                    %08lx
In file included from chip/stm32_qencoder.c:46:
Error: chip/stm32_qencoder.c:1004:10: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1004 |   sninfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           ~~~~~~~~
      |                                                     |
      |                                                     uint32_t {aka long unsigned int}
chip/stm32_qencoder.c:1004:38: note: format string is defined here
 1004 |   sninfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |                                   ~~~^
      |                                      |
      |                                      unsigned int
      |                                   %08lx
cc1: all warnings being treated as errors
make[1]: *** [Makefile:138: stm32_qencoder.o] Error 1
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
chip/stm32_can.c: In function 'stm32can_ioctl':
Error: chip/stm32_can.c:954:19: error: format '%d' expects argument of type 'int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  954 |           caninfo("TS1: %d TS2: %d BRP: %d\n",
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  955 |                   bt->bt_tseg1, bt->bt_tseg2, brp);
      |                                               ~~~
      |                                               |
      |                                               uint32_t {aka long unsigned int}
chip/stm32_can.c:954:42: note: format string is defined here
  954 |           caninfo("TS1: %d TS2: %d BRP: %d\n",
      |                                         ~^
      |                                          |
      |                                          int
      |                                         %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
chip/stm32_can.c: In function 'stm32can_txready':
Error: chip/stm32_can.c:1412:11: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1412 |   caninfo("CAN%d TSR: %08x\n", priv->port, regval);
      |           ^~~~~~~~~~~~~~~~~~~              ~~~~~~
      |                                            |
      |                                            uint32_t {aka long unsigned int}
chip/stm32_can.c:1412:26: note: format string is defined here
 1412 |   caninfo("CAN%d TSR: %08x\n", priv->port, regval);
      |                       ~~~^
      |                          |
      |                          unsigned int
      |                       %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
chip/stm32_can.c: In function 'stm32can_txempty':
Error: chip/stm32_can.c:1444:11: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1444 |   caninfo("CAN%d TSR: %08x\n", priv->port, regval);
      |           ^~~~~~~~~~~~~~~~~~~              ~~~~~~
      |                                            |
      |                                            uint32_t {aka long unsigned int}
chip/stm32_can.c:1444:26: note: format string is defined here
 1444 |   caninfo("CAN%d TSR: %08x\n", priv->port, regval);
      |                       ~~~^
      |                          |
      |                          unsigned int
      |                       %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
chip/stm32_can.c: In function 'stm32can_bittiming':
Error: chip/stm32_can.c:1750:11: error: format '%d' expects argument of type 'int', but argument 4 has type 'long unsigned int' [-Werror=format=]
 1750 |   caninfo("CAN%d PCLK1: %d baud: %d\n",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
chip/stm32_can.c:1750:26: note: format string is defined here
 1750 |   caninfo("CAN%d PCLK1: %d baud: %d\n",
      |                         ~^
      |                          |
      |                          int
      |                         %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
Error: chip/stm32_can.c:1750:11: error: format '%d' expects argument of type 'int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1750 |   caninfo("CAN%d PCLK1: %d baud: %d\n",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1751 |           priv->port, STM32_PCLK1_FREQUENCY, priv->baud);
      |                                              ~~~~~~~~~~
      |                                                  |
      |                                                  uint32_t {aka long unsigned int}
chip/stm32_can.c:1750:35: note: format string is defined here
 1750 |   caninfo("CAN%d PCLK1: %d baud: %d\n",
      |                                  ~^
      |                                   |
      |                                   int
      |                                  %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
Error: chip/stm32_can.c:1803:11: error: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
      |                                        |
      |                                        uint32_t {aka long unsigned int}
chip/stm32_can.c:1803:18: note: format string is defined here
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |                 ~^
      |                  |
      |                  int
      |                 %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
Error: chip/stm32_can.c:1803:11: error: format '%d' expects argument of type 'int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~       ~~~
      |                                             |
      |                                             uint32_t {aka long unsigned int}
chip/stm32_can.c:1803:26: note: format string is defined here
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |                         ~^
      |                          |
      |                          int
      |                         %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
Error: chip/stm32_can.c:1803:11: error: format '%d' expects argument of type 'int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~            ~~~
      |                                                  |
      |                                                  uint32_t {aka long unsigned int}
chip/stm32_can.c:1803:34: note: format string is defined here
 1803 |   caninfo("TS1: %d TS2: %d BRP: %d\n", ts1, ts2, brp);
      |                                 ~^
      |                                  |
      |                                  int
      |                                 %ld
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_can.c:45:
chip/stm32_can.c: In function 'stm32can_exitinitmode':
Error: chip/stm32_can.c:1920:14: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1920 |       canerr("ERROR: Timed out waiting to exit initialization mode: %08x\n",
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1921 |              regval);
      |              ~~~~~~
      |              |
      |              uint32_t {aka long unsigned int}
chip/stm32_can.c:1920:72: note: format string is defined here
 1920 |       canerr("ERROR: Timed out waiting to exit initialization mode: %08x\n",
      |                                                                     ~~~^
      |                                                                        |
      |                                                                        unsigned int
      |                                                                     %08lx
cc1: all warnings being treated as errors
make[1]: *** [Makefile:138: stm32_can.o] Error 1
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_timer':
Error: chip/stm32_pwm.c:1130:11: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'const long unsigned int'} [-Werror=format=]
 1130 |   pwminfo("TIM%u frequency: %u\n",
      |           ^~~~~~~~~~~~~~~~~~~~~~~
 1131 |           priv->timid, info->frequency);
      |                        ~~~~~~~~~~~~~~~
      |                            |
      |                            uint32_t {aka const long unsigned int}
chip/stm32_pwm.c:1130:30: note: format string is defined here
 1130 |   pwminfo("TIM%u frequency: %u\n",
      |                             ~^
      |                              |
      |                              unsigned int
      |                             %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1213:11: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1214 |           "TIMCLK: %u prescaler: %u reload: %u\n",
 1215 |           priv->timid, priv->pclk, info->frequency,
      |                        ~~~~~~~~~~
      |                            |
      |                            uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1213:25: note: format string is defined here
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |                        ~^
      |                         |
      |                         unsigned int
      |                        %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1213:11: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'uint32_t' {aka 'const long unsigned int'} [-Werror=format=]
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1214 |           "TIMCLK: %u prescaler: %u reload: %u\n",
 1215 |           priv->timid, priv->pclk, info->frequency,
      |                                    ~~~~~~~~~~~~~~~
      |                                        |
      |                                        uint32_t {aka const long unsigned int}
chip/stm32_pwm.c:1213:39: note: format string is defined here
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |                                      ~^
      |                                       |
      |                                       unsigned int
      |                                      %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1213:11: error: format '%u' expects argument of type 'unsigned int', but argument 6 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
 1216 |           timclk, prescaler, reload);
      |           ~~~~~~
      |           |
      |           uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1214:21: note: format string is defined here
 1214 |           "TIMCLK: %u prescaler: %u reload: %u\n",
      |                    ~^
      |                     |
      |                     unsigned int
      |                    %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1213:11: error: format '%u' expects argument of type 'unsigned int', but argument 7 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
 1216 |           timclk, prescaler, reload);
      |                   ~~~~~~~~~
      |                   |
      |                   uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1214:35: note: format string is defined here
 1214 |           "TIMCLK: %u prescaler: %u reload: %u\n",
      |                                  ~^
      |                                   |
      |                                   unsigned int
      |                                  %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1213:11: error: format '%u' expects argument of type 'unsigned int', but argument 8 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1213 |   pwminfo("TIM%u PCLK: %u frequency: %u "
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
 1216 |           timclk, prescaler, reload);
      |                              ~~~~~~
      |                              |
      |                              uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1214:46: note: format string is defined here
 1214 |           "TIMCLK: %u prescaler: %u reload: %u\n",
      |                                             ~^
      |                                              |
      |                                              unsigned int
      |                                             %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1417:15: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1417 |       pwminfo("ccr: %u\n", ccr);
      |               ^~~~~~~~~~~  ~~~
      |                            |
      |                            uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1417:22: note: format string is defined here
 1417 |       pwminfo("ccr: %u\n", ccr);
      |                     ~^
      |                      |
      |                      unsigned int
      |                     %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_update_duty':
Error: chip/stm32_pwm.c:1679:11: error: format '%x' expects argument of type 'unsigned int', but argument 5 has type 'ub16_t' {aka 'long unsigned int'} [-Werror=format=]
 1679 |   pwminfo("TIM%u channel: %u duty: %08x\n",
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1680 |           priv->timid, channel, duty);
      |                                 ~~~~
      |                                 |
      |                                 ub16_t {aka long unsigned int}
chip/stm32_pwm.c:1679:39: note: format string is defined here
 1679 |   pwminfo("TIM%u channel: %u duty: %08x\n",
      |                                    ~~~^
      |                                       |
      |                                       unsigned int
      |                                    %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:1698:11: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 1698 |   pwminfo("ccr: %u\n", ccr);
      |           ^~~~~~~~~~~  ~~~
      |                        |
      |                        uint32_t {aka long unsigned int}
chip/stm32_pwm.c:1698:18: note: format string is defined here
 1698 |   pwminfo("ccr: %u\n", ccr);
      |                 ~^
      |                  |
      |                  unsigned int
      |                 %lu
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_set_apb_clock':
Error: chip/stm32_pwm.c:2010:11: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2010 |   pwminfo("RCC_APBxENR base: %08x  bits: %04x\n", regaddr, en_bit);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~
      |                                                   |
      |                                                   uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2010:33: note: format string is defined here
 2010 |   pwminfo("RCC_APBxENR base: %08x  bits: %04x\n", regaddr, en_bit);
      |                              ~~~^
      |                                 |
      |                                 unsigned int
      |                              %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:2010:11: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2010 |   pwminfo("RCC_APBxENR base: %08x  bits: %04x\n", regaddr, en_bit);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           ~~~~~~
      |                                                            |
      |                                                            uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2010:45: note: format string is defined here
 2010 |   pwminfo("RCC_APBxENR base: %08x  bits: %04x\n", regaddr, en_bit);
      |                                          ~~~^
      |                                             |
      |                                             unsigned int
      |                                          %04lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_setup':
Error: chip/stm32_pwm.c:2066:15: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2066 |       pwminfo("pincfg: %08x\n", pincfg);
      |               ^~~~~~~~~~~~~~~~  ~~~~~~
      |                                 |
      |                                 uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2066:27: note: format string is defined here
 2066 |       pwminfo("pincfg: %08x\n", pincfg);
      |                        ~~~^
      |                           |
      |                           unsigned int
      |                        %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_shutdown':
Error: chip/stm32_pwm.c:2117:15: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2117 |       pwminfo("pincfg: %08x\n", pincfg);
      |               ^~~~~~~~~~~~~~~~  ~~~~~~
      |                                 |
      |                                 uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2117:27: note: format string is defined here
 2117 |       pwminfo("pincfg: %08x\n", pincfg);
      |                        ~~~^
      |                           |
      |                           unsigned int
      |                        %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
chip/stm32_pwm.c: In function 'pwm_stop':
Error: chip/stm32_pwm.c:2377:11: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2377 |   pwminfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~
      |                                             |
      |                                             uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2377:24: note: format string is defined here
 2377 |   pwminfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |                     ~~~^
      |                        |
      |                        unsigned int
      |                     %08lx
In file included from /github/workspace/sources/nuttx/include/nuttx/mm/shm.h:30,
                 from /github/workspace/sources/nuttx/include/nuttx/sched.h:41,
                 from /github/workspace/sources/nuttx/include/sched.h:36,
                 from /github/workspace/sources/nuttx/include/stdio.h:32,
                 from chip/stm32_pwm.c:45:
Error: chip/stm32_pwm.c:2377:11: error: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
 2377 |   pwminfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           ~~~~~~~~
      |                                                      |
      |                                                      uint32_t {aka long unsigned int}
chip/stm32_pwm.c:2377:39: note: format string is defined here
 2377 |   pwminfo("regaddr: %08x resetbit: %08x\n", regaddr, resetbit);
      |                                    ~~~^
      |                                       |
      |                                       unsigned int
      |                                    %08lx
cc1: all warnings being treated as errors
```

**Comment by acassis** [comment]
You don't need to close this PR, just create a new commit and submit, it will appear here.

**Comment by xiaoxiang781216** [comment]
@robertobucher once the compiler issue get resolved, it's better to reorganize your patchset to fix the problem in the initial patch which introduce the problem, instead fix in a new patch.

**Comment by xiaoxiang781216** [comment]
@robertobucher you can fix the confict by:
```
git remote add apache git@github.com:apache/incubator-nuttx.git
git fetch apache
git rebase apache/master
git push -f origin master
```
Before push the new patchset, please reorganize your change into the reasonable patchset:
```
git rebase --interactive HEAD~16
```

**Pull request closed without merging**
