### PR TITLE
arch: arm: max326xx: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM @jerpelea - are you using some scripting you can share?

**Comment by jerpelea** [comment]
@davids5 partial but unfortunately is not shareable

**Comment by v01d** [comment]
@davids5 Have a look at `tools/licensing/apachize.py`, I haven't tested it much though.

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by jerpelea** [comment]
can we merge it ?

**Comment by jerpelea** [comment]
@davids5 I have all licenses already prepared locally

**Pull request merged**
