### PR TITLE
arch/armv7-a: Fix the wrong idle stack setup for SMP case

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
1.Add the idle stack base as The first field of .Lstkinit
2.Make g_idle_topstack point to the end of the idle stack

## Impact
Fix the error in ARMV7-A SMP

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Note: this PR also fix the idle thread stack overlap between cpu0 and cpu1.

**Comment by masayuki2009** [comment]
LGTM

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
Shall we backport this PR to 10.0.0?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> Shall we backport this PR to 10.0.0?

Sure, I add backport/10.0.0 label.

**Pull request merged**
