### PR TITLE
tools/ci/docker/linux/Dockerfile: Install CodeChecker and requirement…

### PR DESCRIPTION
**Pull request by W-Mai**
## Summary
tools/ci/docker/linux/Dockerfile: Install CodeChecker and requirements(clang, clang-tidy)

## Impact
N/A

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> ## Summary
> tools/ci/docker/linux/Dockerfile: Install CodeChecker and requirements(clang, clang-tidy)
> 

Let's update https://github.com/apache/incubator-nuttx/blob/master/tools/ci/cibuild.sh for no docker case.

**Comment by W-Mai** [comment]
> > ## Summary
> > tools/ci/docker/linux/Dockerfile: Install CodeChecker and requirements(clang, clang-tidy)
> 
> Let's update https://github.com/apache/incubator-nuttx/blob/master/tools/ci/cibuild.sh for no docker case.

Why do `cibuild.sh` and `Dockerfile` use different ways to download and deploy the environment

**Comment by xiaoxiang781216** [comment]
> > > ## Summary
> > > tools/ci/docker/linux/Dockerfile: Install CodeChecker and requirements(clang, clang-tidy)
> > 
> > 
> > Let's update https://github.com/apache/incubator-nuttx/blob/master/tools/ci/cibuild.sh for no docker case.
> 
> Why do `cibuild.sh` and `Dockerfile` use different ways to download and deploy the environment

Not all people use Dockerfile.

**Comment by W-Mai** [comment]
Add CodeChecker requirements for `https://github.com/apache/incubator-nuttx/blob/master/tools/ci/cibuild.sh`

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
