### PR TITLE
Integration of pysimCoder with NUTTX

### PR DESCRIPTION
**Pull request by robertobucher**
## Summary
Changed the following files to fit nuttx style
- arch/arm/src/stm32f7/stm32_adc.c
- arch/arm/src/stm32f7/stm32_can.c
- drivers/rwbuffer.c

Added the following files:
- boards/arm/stm32f7/nucleo-144/configs/f746-pysim
- boards/arm/stm32f7/nucleo-144/include/board.h
- boards/arm/stm32f7/nucleo-144/src/stm32_can.c
- boards/arm/stm32f7/nucleo-144/src/stm32_qencoder.c

## Impact
arm/stm32f7/.

## Testing
Tested on NUCLEO-F746-ZG.

### CODE REVIEW

**Comment by acassis** [comment]
Hi @robertobucher it is fine now! The warning converted to error was already in the USB Host driver:
```
Error: chip/stm32_usbhost.c:42:33: error: excess elements in array initializer [-Werror]
   42 | #define TRENTRY(id,fmt1,string) {string}
      |                                 ^
chip/stm32_usbhost.c:96:3: note: in expansion of macro 'TRENTRY'
   96 |   TRENTRY(OTGHS_TRACE1_TRNSFRFAILED,       TR_FMT1, "OTGHS  ERROR: Transfer Failed. ret=%d\n"),
      |   ^~~~~~~
chip/stm32_usbhost.c:42:33: note: (near initialization for 'g_trace1')
   42 | #define TRENTRY(id,fmt1,string) {string}
      |                                 ^
chip/stm32_usbhost.c:96:3: note: in expansion of macro 'TRENTRY'
   96 |   TRENTRY(OTGHS_TRACE1_TRNSFRFAILED,       TR_FMT1, "OTGHS  ERROR: Transfer Failed. ret=%d\n"),
      |   ^~~~~~~
```
@davids5 and @raiden00pl some idea about this issue?

I propose to merge the current PR because it is not the root of the issue and we cannot pass the burden of fixing existent BUGs to new contributors that are already enfforting to make their PR into NuttX.

**Comment by davids5** [comment]
> Hi @robertobucher it is fine now! The warning converted to error was already in the USB Host driver:
> 
> ```
> Error: chip/stm32_usbhost.c:42:33: error: excess elements in array initializer [-Werror]
>    42 | #define TRENTRY(id,fmt1,string) {string}
>       |                                 ^
> chip/stm32_usbhost.c:96:3: note: in expansion of macro 'TRENTRY'
>    96 |   TRENTRY(OTGHS_TRACE1_TRNSFRFAILED,       TR_FMT1, "OTGHS  ERROR: Transfer Failed. ret=%d\n"),
>       |   ^~~~~~~
> chip/stm32_usbhost.c:42:33: note: (near initialization for 'g_trace1')
>    42 | #define TRENTRY(id,fmt1,string) {string}
>       |                                 ^
> chip/stm32_usbhost.c:96:3: note: in expansion of macro 'TRENTRY'
>    96 |   TRENTRY(OTGHS_TRACE1_TRNSFRFAILED,       TR_FMT1, "OTGHS  ERROR: Transfer Failed. ret=%d\n"),
>       |   ^~~~~~~
> ```
> 
> @davids5 and @raiden00pl some idea about this issue?
> 
> I propose to merge the current PR because it is not the root of the issue and we cannot pass the burden of fixing existent BUGs to new contributors that are already enfforting to make their PR into NuttX.

@acassis What is the value in TRACE1_NSTRINGS?

>I propose to merge the current PR because it is not the root of the issue and we cannot pass the burden of fixing existent BUGs to new contributors that are already enfforting to make their PR into NuttX.

I am not apposed to this, but the, since the CI did not finish we will not know if it break something else.

**Comment by davids5** [comment]
@acassis - Master was broken, there is a PR that merged that I believe fixed the issue. It is still boilings. Once that is done. 

this PR should be rebased on it, so we can get a clean CI run.

**Comment by acassis** [comment]
arch/arm/src/stm32/stm32_usbhost.h:#  define TRACE1_NSTRINGS  TRACE1_INDEX(__TRACE1_NSTRINGS)

#  define TRACE1_INDEX(id) ((int)(id) - TRACE1_FIRST)

**Comment by acassis** [comment]
> @acassis - Master was broken, there is a [PR](https://github.com/apache/incubator-nuttx/commit/6657d151ca15a4c1c143b699c64155e689d1c15e) that merged that I believe fixed the issue. It is still building. Once that is done.
> 
> this PR should be rebased on it, so we can get a clean CI run.

Thank you, I'll restart it!

**Pull request merged**
