### PR TITLE
Fix some build issues when CONFIG_PWM_PULSECOUNT is enabled.

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**

### CODE REVIEW

**Comment by acassis** [comment]
Hi Daniel, there are some conflict with master and this PR cannot be merged! Please sync your repository and resubmit the PR.

**Comment by xiaoxiang781216** [comment]
@acassis it's better to keep the PR open and let's contributor update the PR instead creating a new one.

**Comment by Ouss4** [comment]
@xiaoxiang781216 I believe the change got incorporated: 3054ade
Probably Alan pulled from Daniel's fork and cherry picked.

**Comment by acassis** [comment]
Yes, I already applied it. So, let's to close. Next PR with issues I will left open and ask the submitter to try again. Thank you @xiaoxiang781216 and @Ouss4

**Pull request closed without merging**
