### PR TITLE
Add debug.h selection choice to support include chip debug.h

### PR DESCRIPTION
**Pull request by liuguo09**
## Summary
Add Select debug.h choice which may be under include/arch or include/arch/chip.

## Testing
Test and verify with using chip debug.h and none debug.h locally.

### CODE REVIEW

**Comment by davids5** [comment]
Should these be 2 independent settings?

I can have none, either one or both.

**Comment by xiaoxiang781216** [comment]
> Should these be 2 independent settings?
> 
> I can have none, either one or both.

No, we can't select both. Because only one function named __arch_syslog can be redefined by either arch or chip:

**Comment by davids5** [comment]
Can this be cascaded with priority of chip -> arch -> system:
```
/* The actual logger function may be overridden in arch/debug.h if needed.
 * (Currently only if the pre-processor supports variadic macros)
 */

#ifndef __arch_syslog
#  define __arch_syslog syslog
#endif
```

Would you provide the 2 debug.h files for example.

**Comment by xiaoxiang781216** [comment]
> Can this be cascaded with priority of chip -> arch -> system:

Yes, you can achieve this by select one of:

1. CONFIG_ARCH_CHIP_DEBUG_H->chip
2. CONFIG_ARCH_DEBUG_H           ->arch
3. CONFIG_ARCH_NONE_DEBUG_H->system

> 
> ```
> /* The actual logger function may be overridden in arch/debug.h if needed.
>  * (Currently only if the pre-processor supports variadic macros)
>  */
> 
> #ifndef __arch_syslog
> #  define __arch_syslog syslog
> #endif
> ```
> 
> Would you provide the 2 debug.h files for example.

Yes, you can provide two:
arch/include/chip.h
arch/include/xxx/chip.h
But only one can be selected by defconfig.

If you have better idea, please modify PR directly.

**Comment by xiaoxiang781216** [comment]
@davids5 do you think my anwser resolve your concern?

**Comment by davids5** [comment]
> @davids5 do you think my anwser resolve your concern?

No. but let's merge it for what it is.

> Would you provide the 2 debug.h files for example.

I was asking for 2 example files to be added as attachments to the PR.

My hope was the the arch and chip level debug files could add arch and chip level focused debug statements. 
I.E. I do not want all the high level output when fs has debugging enabled. But I do care about SDMMC messages.

**Comment by xiaoxiang781216** [comment]
> > @davids5 do you think my anwser resolve your concern?
> 
> No. but let's merge it for what it is.
> 
> > Would you provide the 2 debug.h files for example.
> 
> I was asking for 2 example files to be added as attachments to the PR.
> 

Sorry, I can't provide example header file now, because it's the 3rd party code I don't have right to share it without the permission. But, the patch provided here work with the 3rd party special log mechanism very well.

> My hope was the the arch and chip level debug files could add arch and chip level focused debug statements.
> I.E. I do not want all the high level output when fs has debugging enabled. But I do care about SDMMC messages.

This feature is provided a hook to let arch/chip to redirect ALL log to some special hardware but without implementing syslog_channel_s.

The feature you want could be achieved by adding more debugging macro in debug.h?

**Pull request merged**
