### PR TITLE
libxx: Move the partial c++ abi implementation to libcxxmini sub folder

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Align the layout with other similar libraries(e.g. libcxxabi, libcxx, uClibc++).

## Impact
Code refactor, no real change

## Testing
Pass CI

### CODE REVIEW

**Comment by gustavonihei** [comment]
Just for curiosity, where did the `libminiabi` name come from?

**Comment by xiaoxiang781216** [comment]
> Just for curiosity, where did the `libminiabi` name come from?

replace cxx in libcxxabi with mini.

**Comment by gustavonihei** [comment]
> > Just for curiosity, where did the `libminiabi` name come from?
> 
> replace cxx in libcxxabi with mini.

Hahaha ok, allow me be a little more specific.
I searched for `libminiabi`, and I found zero references on the web.
My question is: `what is the background for the idea of caliing it `miniabi`?
If there is no background, maybe we should follow a similar approach as other libs, e.g. newlib-nano.
`libminiabi` does not seen a very intuitive name for a C++ ABI implementation library.

**Comment by xiaoxiang781216** [comment]
> > > Just for curiosity, where did the `libminiabi` name come from?
> > 
> > 
> > replace cxx in libcxxabi with mini.
> 
> Hahaha ok, allow me to be a little more specific.
> I searched for `libminiabi`, and I found zero references on the web.
> My question is: what is the background for the idea of caliing it `miniabi`?
> If there is no background, maybe we should follow a similar approach as other libs, e.g. newlib-nano.
> `libminiabi` does not seen a very intuitive name for a C++ ABI implementation library.

So, you like libnanoabi? I am fine with either.

**Comment by gustavonihei** [comment]
> So, you like libnanoabi? I am fine with either.

No, the problem I see is that neither `libminiabi` nor `libnanoabi` indicate that it is related to the C++ ABI.
Bringing `newlib-nano` I intended to propose something like `libcxxabi-nano`, something along this line.

**Comment by xiaoxiang781216** [comment]
> > So, you like libnanoabi? I am fine with either.
> 
> No, the problem I see is that neither `libminiabi` nor `libnanoabi` indicate that the library is related to the C++ ABI.
> Bringing `newlib-nano` I intended to propose something like `libcxxabi-nano`, something along this line.

How about name it as libcxxmini? because standard c++ library and c++ abi library combine into one in this case.

**Comment by gustavonihei** [comment]
> How about name it as libcxxmini? because standard c++ library and c++ abi library combine into one in this case.

Fine by me. Just by having `cxx` in the library name makes me prefer the new proposal.

**Review by gustavonihei — APPROVED** [review]

**Comment by gustavonihei** [comment]
My bad, I've merged the other PR which modified `cxx.defs`, now this one needs to be rebased.

**Comment by xiaoxiang781216** [comment]
> My bad, I've merged the other PR which modified `cxx.defs`, now this one needs to be rebased.

No problem, fixed.

**Pull request merged**
