### PR TITLE
arch/arm/stm32h7: multiple fixes for stm32h7 flash interface

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
This PR contain few fixes for stm32h7 flash interface:
- Fix cache invalidation before reading flash data after flash erase operation
- Fix `stm32h7_israngeerased` operation to use the correct address on byte read
- Fix error checking in `stm32h7_israngeerased`
- Replace exclusive semaphore with mutex
- Fix few style issues

## Impact
Bug fix

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
please rebase the change to fix the ci error.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@tito97sp should we merge this patch instead yours(#7397)?

**Comment by pkarashchenko** [comment]
> > @tito97sp should we merge this patch instead yours(#7397)?
> 
> @xiaoxiang781216  Yes. This PR substitutes mine.

Could you please approve the PR if all the tests pass at your end?

**Comment by tito97sp** [comment]
> > > @tito97sp should we merge this patch instead yours(#7397)?
> > 
> > 
> > @xiaoxiang781216  Yes. This PR substitutes mine.
> 
> Could you please approve the PR if all the tests pass at your end?

I'm on it

**Comment by tito97sp** [comment]
> > > > @tito97sp should we merge this patch instead yours(#7397)?
> > > 
> > > 
> > > @xiaoxiang781216  Yes. This PR substitutes mine.
> > 
> > 
> > Could you please approve the PR if all the tests pass at your end?
> 
> I'm on it

Hi @pkarashchenko how can I move to your PR on local??

**Review by davids5 — APPROVED** [review]

**Pull request merged**
