### PR TITLE
arch/stm32h7: Fix nxstyle errors

### PR DESCRIPTION
**Pull request by hartmannathan**
## Summary

Fix nxstyle errors in arch/arm/src/stm32h7/stm32_otgdev.c.

## Impact

Removes nxstyle errors.

## Testing

nxstyle

### CODE REVIEW

**Comment by hartmannathan** [comment]
Oops looks like duplicated work already done by @jerpelea

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by hartmannathan** [comment]
> LGTM

Race condition! :-)

**Comment by davids5** [comment]
si

**Pull request closed without merging**
