### PR TITLE
Fix wait loop and void cast

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by patacongo** [comment]
Removing the (void) cast actually violates the coding standard.  Look at:

http://nuttx.org/Documentation/NuttXCCodingStandard.html#retvalues

**Checking Return Values**. Callers of internal OS functions should always check return values for an error. At a minimum, a debug statement should indicate that an error has occurred. **_The calling logic intentionally ignores the returned value, then the function return value should be explicitly cast to (void) to indicate that the return value is intentionally ignored._** An exception of for standard functions for which people have historically ignored the returned values, such as printf() or close. All calls to malloc or realloc must be checked for failures to allocate memory.

**Comment by juniskane** [comment]
This PR completely breaks usrsock networking for one of our projects. Underlying cause is not clear but creating a revert for commit 6a3c2aded683e8284e fixed it. I suggest reverting this in any case as merging insanely big PRs like this that confuse several unrelated concepts into single commit make root cause analysis extra hard.

**Comment by xiaoxiang781216** [comment]
@juniskane could you point out which patch break your networking? or which socket function break?

**Comment by xiaoxiang781216** [comment]
Please help me identify which patch generate the regression like this:
1.git revert  6a3c2ad
2.download https://github.com/apache/incubator-nuttx/commit/a5aac1fd5515e2447785025da4102c5b04fc6389.patch
3.git am download-file.patch
And run your test case.

**Comment by xiaoxiang781216** [comment]
Does the error like this:
proxy> ping 127.0.0.1
ERROR: socket() failed: 106
proxy>

**Comment by jkivilin** [comment]
Bug appears to be reproducable with 'usrsocktest' testing application (CONFIG_EXAMPLES_USRSOCKTEST=y). 

The config I used for quick test is at https://gist.github.com/jkivilin/7d7558b54a85fd70c8a439d6d8feba5e

With offending commit **reverted**, I get output:
```
$ ./nuttx 

NuttShell (NSH) NuttX-8.2
MOTD: username=admin password=Administrator
nsh> usrsocktest
Starting unit-tests...
Testing group "CharDev" =>
        Group "CharDev": [OK]
Testing group "NoDaemon" =>
        Group "NoDaemon": [OK]
Testing group "BasicDaemon" =>
        Group "BasicDaemon": [OK]
Testing group "BasicConnect" =>
        Group "BasicConnect": [OK]
Testing group "BasicConnectDelay" =>
        Group "BasicConnectDelay": [OK]
Testing group "NoBlockConnect" =>
        Group "NoBlockConnect": [OK]
Testing group "BasicSend" =>
        Group "BasicSend": [OK]
Testing group "NoBlockSend" =>
        Group "NoBlockSend": [OK]
Testing group "BlockSend" =>
        Group "BlockSend": [OK]
Testing group "NoBlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "Receive":
                line 200: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
        Group "NoBlockRecv": [FAILED]
Testing group "BlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "NoBlockConnect":
                line 268: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
        Group "BlockRecv": [FAILED]
Testing group "RemoteDisconnect" =>
        Group "RemoteDisconnect": [OK]
Testing group "BasicSetSockOpt" =>
        Group "BasicSetSockOpt": [OK]
Testing group "BasicGetSockOpt" =>
        Group "BasicGetSockOpt": [OK]
Testing group "BasicGetSockName" =>
Segmentation fault (core dumped)
```

There is some other issue that causes test-cases to fail, but when 6a3c2ad is **not reverted**, the output changes.  Now I get different errors, first being at 'Testing group "BasicSend"':

```
$ ./nuttx 

NuttShell (NSH) NuttX-8.2
MOTD: username=admin password=Administrator
nsh> 
nsh> usrsocktest
Starting unit-tests...
Testing group "CharDev" =>
        Group "CharDev": [OK]
Testing group "NoDaemon" =>
        Group "NoDaemon": [OK]
Testing group "BasicDaemon" =>
        Group "BasicDaemon": [OK]
Testing group "BasicConnect" =>
        Group "BasicConnect": [OK]
Testing group "BasicConnectDelay" =>
        Group "BasicConnectDelay": [OK]
Testing group "NoBlockConnect" =>
        Group "NoBlockConnect": [OK]
Testing group "BasicSend" =>
        [TEST ASSERT FAILED!]
                In function "ConnectSend":
                line 244: Assertion `(ssize_t)((ret)) == (ssize_t)((datalen))' failed.
                        got value: -1
                        should be: 4
        Group "BasicSend": [FAILED]
Testing group "NoBlockSend" =>
        [TEST ASSERT FAILED!]
                In function "Send":
                line 111: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "NoBlockSend": [FAILED]
Testing group "BlockSend" =>
        [TEST ASSERT FAILED!]
                In function "ConnectSend":
                line 112: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "BlockSend": [FAILED]
Testing group "NoBlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "Receive":
                line 115: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "NoBlockRecv": [FAILED]
Testing group "BlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "ConnectReceive":
                line 114: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "BlockRecv": [FAILED]
Testing group "RemoteDisconnect" =>
        [TEST ASSERT FAILED!]
                In function "Unreachable":
                line 115: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "RemoteDisconnect": [FAILED]
Testing group "BasicSetSockOpt" =>
        [TEST ASSERT FAILED!]
                In function "Open":
                line 105: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "BasicSetSockOpt": [FAILED]
Testing group "BasicGetSockOpt" =>
        [TEST ASSERT FAILED!]
                In function "Open":
                line 105: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "BasicGetSockOpt": [FAILED]
Testing group "BasicGetSockName" =>
        [TEST ASSERT FAILED!]
                In function "Open":
                line 110: Assertion `(ssize_t)((usrsocktest_daemon_start(dconf))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "BasicGetSockName": [FAILED]
Testing group "WakeWithSignal" =>
        [TEST ASSERT FAILED!]
                In function "do_wake_test":
                line 487: Assertion `(ssize_t)((usrsocktest_daemon_start(&usrsocktest_daemon_config))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "WakeWithSignal": [FAILED]
Testing group "MultiThread" =>
        [TEST ASSERT FAILED!]
                In function "usrsocktest_test_MultiThread_OpenClose":
                line 221: Assertion `(ssize_t)((usrsocktest_daemon_start(&usrsocktest_daemon_config))) == (ssize_t)((0))' failed.
                        got value: -120
                        should be: 0
        Group "MultiThread": [FAILED]
Unit-test groups done... OK:6, FAILED:11, TOTAL:17
 -- number of checks made: 786
HEAP BEFORE TESTS:
             total       used       free    largest
Mem:       4194304    1597616    2596688    2596432
HEAP AFTER TESTS:
             total       used       free    largest
Mem:       4194304    1607440    2586864    2586800
nsh>
```

Maybe above can be used to locate the issue?

**Comment by jkivilin** [comment]
With 6a3c2ad reverted and https://github.com/apache/incubator-nuttx/commit/a5aac1fd5515e2447785025da4102c5b04fc6389.patch applied, usrsocktest output is the same (so problem is not with in a5aac1fd55):
```
$ ./nuttx 

NuttShell (NSH) NuttX-8.2
MOTD: username=admin password=Administrator
nsh> usrsocktest
Starting unit-tests...
Testing group "CharDev" =>
        Group "CharDev": [OK]
Testing group "NoDaemon" =>
        Group "NoDaemon": [OK]
Testing group "BasicDaemon" =>
        Group "BasicDaemon": [OK]
Testing group "BasicConnect" =>
        Group "BasicConnect": [OK]
Testing group "BasicConnectDelay" =>
        Group "BasicConnectDelay": [OK]
Testing group "NoBlockConnect" =>
        Group "NoBlockConnect": [OK]
Testing group "BasicSend" =>
        Group "BasicSend": [OK]
Testing group "NoBlockSend" =>
        Group "NoBlockSend": [OK]
Testing group "BlockSend" =>
        Group "BlockSend": [OK]
Testing group "NoBlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "Receive":
                line 200: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
        Group "NoBlockRecv": [FAILED]
Testing group "BlockRecv" =>
        [TEST ASSERT FAILED!]
                In function "NoBlockConnect":
                line 268: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
        Group "BlockRecv": [FAILED]
Testing group "RemoteDisconnect" =>
        Group "RemoteDisconnect": [OK]
Testing group "BasicSetSockOpt" =>
        Group "BasicSetSockOpt": [OK]
Testing group "BasicGetSockOpt" =>
        Group "BasicGetSockOpt": [OK]
Testing group "BasicGetSockName" =>
Segmentation fault (core dumped)
```

**Comment by xiaoxiang781216** [comment]
Ok, let me repro on simulator with your config

**Comment by juniskane** [comment]
I agree with Jussi, problem is caused by a9ff3e1, not the other commit. I cannot spot the problem by code reading unfortunately.

This is usrsocktest with old upstream merge from December (some of the SHAs here are from our internal repository) running on proprietary STM32L4 board. Something is broken, but not as much as with a9ff3e1:

[usrsocktest_Dec16_master_9e3bf44870.txt](https://github.com/apache/incubator-nuttx/files/4039587/usrsocktest_Dec16_master_9e3bf44870.txt)

Broken master:

[usrsocktest_Jan08_devel_5ff90c1aa27.txt](https://github.com/apache/incubator-nuttx/files/4039591/usrsocktest_Jan08_devel_5ff90c1aa27.txt)

Broken master + this PR reverted (identical with Dec 16 output):

[usrsocktest_Jan08_devel_revert_5864cf8e038.txt](https://github.com/apache/incubator-nuttx/files/4039589/usrsocktest_Jan08_devel_revert_5864cf8e038.txt)

Broken master + this PR reverted + add a9ff3e1 (identical with broken master)

[usrsocktest_Jan08_devel_revert_and_add_a9ff3e1778d950f7d7.txt](https://github.com/apache/incubator-nuttx/files/4039590/usrsocktest_Jan08_devel_revert_and_add_a9ff3e1778d950f7d7.txt)

**Comment by juniskane** [comment]
This is unrelated, but why is priv->tx_result ignored here (different than priv->rx_result handling)?

@@ -645,23 +637,7 @@ static void spi_dmarxwait(FAR struct stm32l4_spidev_s *priv)
 #ifdef CONFIG_STM32L4_SPI_DMA
 static void spi_dmatxwait(FAR struct stm32l4_spidev_s *priv)
 {
-  int ret;
-
-  /* Take the semaphore (perhaps waiting).  If the result is zero, then the DMA
-   * must not really have completed???
-   */
-
-  do
-    {
-      ret = nxsem_wait(&priv->txsem);
-
-      /* The only case that an error should occur here is if the wait was
-       * awakened by a signal.
-       */
-
-      DEBUGASSERT(ret == OK || ret == -EINTR);
-    }
-  while (ret == -EINTR || priv->txresult == 0);
+  nxsem_wait_uninterruptible(&priv->txsem);
 }
 #endif

**Comment by xiaoxiang781216** [comment]
My intention is to remove all result check since only interrupt handler will post semaphore, the check is redundant.

**Comment by xiaoxiang781216** [comment]
> This is unrelated, but why is priv->tx_result ignored here (different than priv->rx_result handling)?
> 
> ```
> @@ -645,23 +637,7 @@ static void spi_dmarxwait(FAR struct stm32l4_spidev_s *priv)
>  #ifdef CONFIG_STM32L4_SPI_DMA
>  static void spi_dmatxwait(FAR struct stm32l4_spidev_s *priv)
>  {
> -  int ret;
> -
> -  /* Take the semaphore (perhaps waiting).  If the result is zero, then the DMA
> -   * must not really have completed???
> -   */
> -
> -  do
> -    {
> -      ret = nxsem_wait(&priv->txsem);
> -
> -      /* The only case that an error should occur here is if the wait was
> -       * awakened by a signal.
> -       */
> -
> -      DEBUGASSERT(ret == OK || ret == -EINTR);
> -    }
> -  while (ret == -EINTR || priv->txresult == 0);
> +  nxsem_wait_uninterruptible(&priv->txsem);
>  }
>  #endif
> ```

My intention is to remove all result check since only interrupt handler will post semaphore, the check is redundant.

**Comment by xiaoxiang781216** [comment]
> With [6a3c2ad](https://github.com/apache/incubator-nuttx/commit/6a3c2aded683e8284e793eb3ee8793d2960ae000) reverted and https://github.com/apache/incubator-nuttx/commit/a5aac1fd5515e2447785025da4102c5b04fc6389.patch applied, usrsocktest output is the same (so problem is not with in [a5aac1f](https://github.com/apache/incubator-nuttx/commit/a5aac1fd5515e2447785025da4102c5b04fc6389)):
> 
> ```
> $ ./nuttx 
> 
> NuttShell (NSH) NuttX-8.2
> MOTD: username=admin password=Administrator
> nsh> usrsocktest
> Starting unit-tests...
> Testing group "CharDev" =>
>         Group "CharDev": [OK]
> Testing group "NoDaemon" =>
>         Group "NoDaemon": [OK]
> Testing group "BasicDaemon" =>
>         Group "BasicDaemon": [OK]
> Testing group "BasicConnect" =>
>         Group "BasicConnect": [OK]
> Testing group "BasicConnectDelay" =>
>         Group "BasicConnectDelay": [OK]
> Testing group "NoBlockConnect" =>
>         Group "NoBlockConnect": [OK]
> Testing group "BasicSend" =>
>         Group "BasicSend": [OK]
> Testing group "NoBlockSend" =>
>         Group "NoBlockSend": [OK]
> Testing group "BlockSend" =>
>         Group "BlockSend": [OK]
> Testing group "NoBlockRecv" =>
>         [TEST ASSERT FAILED!]
>                 In function "Receive":
>                 line 200: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
>         Group "NoBlockRecv": [FAILED]
> Testing group "BlockRecv" =>
>         [TEST ASSERT FAILED!]
>                 In function "NoBlockConnect":
>                 line 268: Assertion `memcmp((&remoteaddr), (&addr), (addrlen)) == 0' failed.
>         Group "BlockRecv": [FAILED]
> Testing group "RemoteDisconnect" =>
>         Group "RemoteDisconnect": [OK]
> Testing group "BasicSetSockOpt" =>
>         Group "BasicSetSockOpt": [OK]
> Testing group "BasicGetSockOpt" =>
>         Group "BasicGetSockOpt": [OK]
> Testing group "BasicGetSockName" =>
> Segmentation fault (core dumped)
> ```

I test your config on my simulator, the result isn't stable: BasicSend can pass sometime, but will hit segmentation fault at the later time. The old release can pass BaiscSend stably, but also will hit segmentation fault.

**Comment by juniskane** [comment]
This could be it:
```
diff --git a/net/usrsock/usrsock_dev.c b/net/usrsock/usrsock_dev.c
index 9359fd0..2bca669 100644
--- a/net/usrsock/usrsock_dev.c
+++ b/net/usrsock/usrsock_dev.c
@@ -1166,7 +1166,7 @@ int usrsockdev_do_request(FAR struct usrsock_conn_s *conn,
 {
   FAR struct usrsockdev_s *dev = conn->dev;
   FAR struct usrsock_request_common_s *req_head = iov[0].iov_base;
-  int ret;
+  int ret = OK;
 
   if (!dev)
     {
```
still looking at the patch if there more instances....

**Comment by jkivilin** [comment]
Ok. So, before adding `net_lockedwait_uninterruptible`, `ret` was being initialized by
 ```
      while ((ret = net_lockedwait(&dev->req.acksem)) < 0)
        {
          DEBUGASSERT(ret == -EINTR || ret == -ECANCELED);
        }
```
and return value from net_lockedwait was returned for `usrsockdev_do_request` but that's no longer the case.

**Comment by juniskane** [comment]
There is still something wrong. After this PR and above fix I still get error when doing netcat over cellular connection. DNS is resolved correctly but there is "polling error 12" that was not there before:

```
nsh> nc echo.u-blox.com 13
[1578570098.316560]event_state_change(): old state: 0 => new state: 11
[1578570098.316560]event_data_to_modem():     to modem: [AT+USOCR=17\x0D]
[1578570098.856560]event_data_from_modem(): from modem: [\x0D]
[1578570098.856560]event_data_from_modem(): from modem: [\x0A+USOCR: ]
[1578570098.856560]event_data_from_modem(): from modem: [0\x0D\x0A\x0D\x0AOK\x0D\x0A]
[1578570098.856560]event_state_change(): old state: 11 => new state: 0
[1578570098.886560]event_state_change(): old state: 0 => new state: 11
[1578570098.886560]event_data_to_modem():     to modem: [AT+USOST=0,"130.244.127.161",53,33\x0D]
[1578570098.906560]event_data_from_modem(): from modem: [\x0D]
[1578570098.906560]event_data_from_modem(): from modem: [\x0A@]
[1578570098.966560]event_data_to_modem():     to modem: [\xB9"\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x04echo\x06u-blox\x03com\x00\x00\x01\x00\x01]
[1578570099.096560]event_data_from_modem(): from modem: [\x0D]
[1578570099.096560]event_data_from_modem(): from modem: [\x0A+USOST: ]
[1578570099.096560]event_data_from_modem(): from modem: [0,33\x0D\x0A\x0D\x0AOK\x0D]
[1578570099.096560]event_state_change(): old state: 11 => new state: 0
[1578570099.096560]event_data_from_modem(): from modem: [\x0A]
[1578570099.126560]event_data_from_modem(): from modem: [\x0D]
[1578570099.126560]event_data_from_modem(): from modem: [\x0A+UUSORD:]
[1578570099.126560]event_data_from_modem(): from modem: [ 0,117\x0D\x0A]
[1578570099.146560]event_state_change(): old state: 0 => new state: 11
[1578570099.146560]event_data_to_modem():     to modem: [AT+USORF=0,117\x0D]
[1578570099.146560]event_data_from_modem(): from modem: [\x0D]
[1578570099.146560]event_data_from_modem(): from modem: [\x0A+USORF: ]
[1578570099.146560]event_data_from_modem(): from modem: [0,"130.244.]
[1578570099.146560]event_data_from_modem(): from modem: [127.161",53,]
[1578570099.146560]event_data_from_modem(): from modem: [117,"\xB9"\x81\x80\x00\x01]
[1578570099.156560]event_data_from_modem(): from modem: [\x00\x01\x00\x02\x00\x02\x04echo\x06u-]
[1578570099.156560]event_data_from_modem(): from modem: [blox\x03com\x00\x00\x01\x00\x01\xC0\x0C]
[1578570099.156560]event_data_from_modem(): from modem: [\x00\x01\x00\x01\x00\x00\x00\xF3\x00\x04\xC3"Y\xF1\xC0\x11]
[1578570099.156560]event_data_from_modem(): from modem: [\x00\x02\x00\x01\x00\x01zL\x00\x06\x03ns3\xC0\x11\xC0\x11\x00]
[1578570099.156560]event_data_from_modem(): from modem: [\x02\x00\x01\x00\x01zL\x00\x06\x03ns4\xC0\x11\xC0=\x00\x01\x00]
[1578570099.156560]event_data_from_modem(): from modem: [\x01\x00\x01zL\x00\x04\xC3"Y\xF1\xC0O\x00\x01\x00\x01\x00\x01z]
[1578570099.166560]event_data_from_modem(): from modem: [L\x00\x04\xB9\xD7\xC3r"\x0D\x0A\x0D\x0AOK\x0D\x0A]
[1578570099.166560]event_state_change(): old state: 11 => new state: 0
[1578570099.186560]event_state_change(): old state: 0 => new state: 11
[1578570099.186560]event_data_to_modem():     to modem: [AT+USOCL=0\x0D]
[1578570099.206560]event_data_from_modem(): from modem: [\x0D]
[1578570099.206560]event_data_from_modem(): from modem: [\x0AOK\x0D\x0A]
[1578570099.206560]event_state_change(): old state: 11 => new state: 0
[1578570099.216560]event_state_change(): old state: 0 => new state: 11
[1578570099.216560]event_state_change(): old state: 11 => new state: 0
[1578570099.236560]event_state_change(): old state: 0 => new state: 11
[1578570099.236560]event_data_to_modem():     to modem: [AT+USOCR=6\x0D]
[1578570099.236560]event_data_from_modem(): from modem: [\x0D]
[1578570099.236560]event_data_from_modem(): from modem: [\x0A+USOCR: ]
[1578570099.236560]event_data_from_modem(): from modem: [0\x0D\x0A\x0D\x0AOK\x0D\x0A]
[1578570099.236560]event_state_change(): old state: 11 => new state: 0
[1578570099.256560]event_state_change(): old state: 0 => new state: 11
[1578570099.256560]event_data_to_modem():     to modem: [AT+USOCO=0,"195.34.89.241",13\x0D]
[1578570099.336560]event_data_from_modem(): from modem: [\x0D]
[1578570099.336560]event_data_from_modem(): from modem: [\x0AOK\x0D\x0A]
[1578570099.336560]event_state_change(): old state: 11 => new state: 0
[1578570099.356560]event_state_change(): old state: 0 => new state: 11
[1578570099.356560]event_data_to_modem():     to modem: [AT+USOCL=0\x0D]
[1578570099.376560]event_data_from_modem(): from modem: [\x0D]
[1578570099.376560]event_data_from_modem(): from modem: [\x0AOK\x0D\x0A]
[1578570099.376560]event_state_change(): old state: 11 => new state: 0
polling error error=12,"Unknown error"
nsh> [1578570099.406560]event_state_change(): old state: 0 => new state: 11
[1578570099.406560]event_state_change(): old state: 11 => new state: 0

nsh> [1578570108.836560]event_data_from_modem(): from modem: [\x0D]
nsh>
```

usrsocktest application does not reveal this. usersocktest output is now same as the Dec16 baseline.

**Comment by xiaoxiang781216** [comment]
> There is still something wrong. After this PR and above fix I still get error when doing netcat over cellular connection. DNS is resolved correctly but there is "polling error 12" that was not there before:
> 
> [EDITED: archive trace to comment history]
> 
> Nevermind, fixed this by increasing CONFIG_NET_USRSOCK_NPOLLWAITERS from 1 to 2.

Thanks for finding the tough bug, could you send the patch fix both issues?

**Comment by xiaoxiang781216** [comment]
> This could be it:
> 
> ```
> diff --git a/net/usrsock/usrsock_dev.c b/net/usrsock/usrsock_dev.c
> index 9359fd0..2bca669 100644
> --- a/net/usrsock/usrsock_dev.c
> +++ b/net/usrsock/usrsock_dev.c
> @@ -1166,7 +1166,7 @@ int usrsockdev_do_request(FAR struct usrsock_conn_s *conn,
>  {
>    FAR struct usrsockdev_s *dev = conn->dev;
>    FAR struct usrsock_request_common_s *req_head = iov[0].iov_base;
> -  int ret;
> +  int ret = OK;
>  
>    if (!dev)
>      {
> ```
> 
> still looking at the patch if there more instances....

Good finding, it explain why sometime the test case can pass, but sometime not.

**Comment by juniskane** [comment]
I have not reviewed CONFIG_NET_USRSOCK_NPOLLWAITERS in upstream configs. I'd expect that to be 1 most of time (only one waiting for a given socket) so no patch for that. Users of usersock have to review their projects for this value. We also found similar issues with 'ret' in:

wireless/bluetooth/bt_hcicore.c
drivers/sensors/hc_sr04.c

Details forthcoming...

**Comment by juniskane** [comment]
Likely caused by this PR:

Issue #1: In bt_hci_cmd_send_sync():

bt_hcicore

Issue #2: (also found by Jussi Kivilinna) In hcsr04_ioctl() with SNIOC_READ_RAW_DATA, uninitialized 'ret' is returned. This ioctl command also looks useless as no read data is returned to caller. Driver author @acassis to comment/fix this?

No patch for these, just want to report bugs.

**Comment by xiaoxiang781216** [comment]
@acassis here is the fix:
https://github.com/apache/incubator-nuttx/pull/67
Thanks very much, @juniskane.

**Comment by acassis** [comment]
Done! Thank you Xiao Xiang!

**Comment by juniskane** [comment]
> > ```
> > @@ -645,23 +637,7 @@ static void spi_dmarxwait(FAR struct stm32l4_spidev_s *priv)
> >  #ifdef CONFIG_STM32L4_SPI_DMA
> >  static void spi_dmatxwait(FAR struct stm32l4_spidev_s *priv)
> >  {
> > -  int ret;
> > -
> > -  /* Take the semaphore (perhaps waiting).  If the result is zero, then the DMA
> > -   * must not really have completed???
> > -   */
> > -
> > -  do
> > -    {
> > -      ret = nxsem_wait(&priv->txsem);
> > -
> > -      /* The only case that an error should occur here is if the wait was
> > -       * awakened by a signal.
> > -       */
> > -
> > -      DEBUGASSERT(ret == OK || ret == -EINTR);
> > -    }
> > -  while (ret == -EINTR || priv->txresult == 0);
> > +  nxsem_wait_uninterruptible(&priv->txsem);
> >  }
> >  #endif
> > ```
> 
> My intention is to remove all result check since only interrupt handler will post semaphore, the check is redundant.

Any reason why this bit of code is now done differently for stm32f7 and stm32f0l0g0 than for other STM32?

**Comment by xiaoxiang781216** [comment]
> > > ```
> > > @@ -645,23 +637,7 @@ static void spi_dmarxwait(FAR struct stm32l4_spidev_s *priv)
> > >  #ifdef CONFIG_STM32L4_SPI_DMA
> > >  static void spi_dmatxwait(FAR struct stm32l4_spidev_s *priv)
> > >  {
> > > -  int ret;
> > > -
> > > -  /* Take the semaphore (perhaps waiting).  If the result is zero, then the DMA
> > > -   * must not really have completed???
> > > -   */
> > > -
> > > -  do
> > > -    {
> > > -      ret = nxsem_wait(&priv->txsem);
> > > -
> > > -      /* The only case that an error should occur here is if the wait was
> > > -       * awakened by a signal.
> > > -       */
> > > -
> > > -      DEBUGASSERT(ret == OK || ret == -EINTR);
> > > -    }
> > > -  while (ret == -EINTR || priv->txresult == 0);
> > > +  nxsem_wait_uninterruptible(&priv->txsem);
> > >  }
> > >  #endif
> > > ```
> > 
> > 
> > My intention is to remove all result check since only interrupt handler will post semaphore, the check is redundant.
> 
> Any reason why this bit of code is now done differently for stm32f7 and stm32f0l0g0 than for other STM32?

I will provide a patch to bring back "do {} while (priv->XXresult == 0);".

**Comment by xiaoxiang781216** [comment]
@juniskane here is the patch:
https://github.com/apache/incubator-nuttx/pull/77

**Comment by lukegluke** [comment]
Hi @xiaoxiang781216, @jkivilin!

I have some problems running usrsocktest, few of them looks similar to those mentioned in this issue.
изображение

I've described my issues in dev@nuttx.apache.org mailing list - topic: "Usrsocktest app example fails"
I think it is not really related to this issue, but I wonder if usrsocktest now runs correctly for you in latest NuttX, without any errors?
Thanks for feedback.

**Comment by xiaoxiang781216** [comment]
> Hi @xiaoxiang781216, @jkivilin!
> 
> I have some problems running usrsocktest, few of them looks similar to those mentioned in this issue.
> 
> I've described my issues in [dev@nuttx.apache.org](mailto:dev@nuttx.apache.org) mailing list - topic: "Usrsocktest app example fails"
> I think it is not really related to this issue, but I wonder if usrsocktest now runs correctly for you in latest NuttX, without any errors?
> Thanks for feedback.

As I remember there are two test case fail even after this fix, I will look at these two fail today or tomorrow.

**Comment by xiaoxiang781216** [comment]
@lukegluke , @masayuki2009 create a fix here, please try it:
https://github.com/apache/incubator-nuttx-apps/pull/85

**Comment by lukegluke** [comment]
> @lukegluke , @masayuki2009 create a fix here, please try it:
> [apache/incubator-nuttx-apps#85](https://github.com/apache/incubator-nuttx-apps/pull/85)
> #345

Thanks, it fix fails in NoBlockRecv and BlockRecv indeed, but there are more complicated errors that (as I think) involve net stack.
Here more detail output with CONFIG_DEBUG_NET_ERROR and CONFIG_DEBUG_NET_WARN.

```
nsh> Starting unit-tests...
Testing group "CharDev" =>
usrsockdev_open: failed to open
        Group "CharDev": [OK]
Testing group "NoDaemon" =>
usrsock_sockif_setup: WARNING: usrsock daemon is not running
psock_socket: ERROR: socket address family unsupported: 2
socket: ERROR: psock_socket() failed: -106
        Group "NoDaemon": [OK]
Testing group "BasicDaemon" =>
socket: ERROR: psock_socket() failed: -123
socket: ERROR: psock_socket() failed: -123
socket: ERROR: psock_socket() failed: -123
socket: ERROR: psock_socket() failed: -123
socket: ERROR: psock_socket() failed: -24
socket: ERROR: psock_socket() failed: -24
        Group "BasicDaemon": [OK]
Testing group "BasicConnect" =>
        Group "BasicConnect": [OK]
Testing group "BasicConnectDelay" =>
        Group "BasicConnectDelay": [OK]
Testing group "NoBlockConnect" =>
        Group "NoBlockConnect": [OK]
Testing group "BasicSend" =>
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -128
psock_sendto: ERROR:  Family-specific send failed: -128
psock_sendto: ERROR:  Family-specific send failed: -127
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -128
psock_sendto: ERROR:  Family-specific send failed: -128
psock_sendto: ERROR:  Family-specific send failed: -127
        Group "BasicSend": [OK]
Testing group "NoBlockSend" =>
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
        Group "NoBlockSend": [OK]
Testing group "BlockSend" =>
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -11
        Group "BlockSend": [OK]
Testing group "NoBlockRecv" =>
        Group "NoBlockRecv": [OK]
Testing group "BlockRecv" =>
        Group "BlockRecv": [OK]
Testing group "RemoteDisconnect" =>
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
psock_send: ERROR: socket si_send() (or usrsock_sendto()) failed: -32
        Group "RemoteDisconnect": [OK]
Testing group "BasicSetSockOpt" =>
        Group "BasicSetSockOpt": [OK]
Testing group "BasicGetSockOpt" =>
        Group "BasicGetSockOpt": [OK]
Testing group "BasicGetSockName" =>
        [TEST ASSERT FAILED!]
                In function "Open":
                line 176: Assertion `(ssize_t)((ret)) == (ssize_t)((-1))' failed.
                        got value: 0
                        should be: -1
        Group "BasicGetSockName": [FAILED]
Testing group "WakeWithSignal" =>
up_assert: Assertion failed at file:semaphore/sem_holder.c line: 128 task: usrsocktest
```

**Pull request merged**
