### PR TITLE
usbdev: add Android Debug Bridge driver

### PR DESCRIPTION
**Pull request by spiriou**
## Summary

Add USB device driver for Android Debug Bridge.
https://developer.android.com/studio/command-line/adb

## Impact

None

## Testing

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@spiriou nice contrition! Have you ported adb command tool?

**Comment by spiriou** [comment]
> @spiriou nice contribution! Have you ported adb command tool?

It works with the "adb" command tool from Android platform tools. You can download it from https://developer.android.com/studio/releases/platform-tools

Tested with "adb shell/push/pull/forward/reverse/logcat".

**Comment by xiaoxiang781216** [comment]
But I suppose that we need a tool on device side to handle the command from host, like adbd on Android device.

**Comment by spiriou** [comment]
Exactly, I'll submit it after this pull request

**Comment by v01d** [comment]
@spiriou do you have some reference to understand the ADB protocol? I would like to know if it is possible for it to be used over BLE. If it works over a serial connection maybe it could be made to work over BLE UART but it is possibly not a good solution

**Comment by acassis** [comment]
> @spiriou do you have some reference to understand the ADB protocol? I would like to know if it is possible for it to be used over BLE. If it works over a serial connection maybe it could be made to work over BLE UART but it is possibly not a good solution

Hi @v01d I think it could help you: https://github.com/cstyan/adbDocumentation

**Comment by spiriou** [comment]
> > @spiriou do you have some reference to understand the ADB protocol? I would like to know if it is possible for it to be used over BLE. If it works over a serial connection maybe it could be made to work over BLE UART but it is possibly not a good solution
> 
> Hi @v01d I think it could help you: https://github.com/cstyan/adbDocumentation

@v01d ADB is basically a TLV communication over a serial link (binary). If you can provide a serial channel over BLE, then it may be possible. One other issue is that the adb client from android platform tools only support USB or TCP connection. Hence you would also have to provide on host side a TCP <-> BLE serial application.

**Comment by v01d** [comment]
Thanks for the info. I don't think adb will be the right protocol to use over BLE then.

**Pull request merged**
