### PR TITLE
[BACKPORT #2264/#2272/#2279] Fix nxtask_exit() and pthread_join() for SMP

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Backport SMP fixes #2264 #2272 #2279

## Testing
Running sim:smp and ostest on a 10 loop soak where it previously would lock

### CODE REVIEW

**Comment by btashton** [comment]
@masayuki2009 Sorry it took me a bit to get to these.  I think this covers the backport of your SMP fixes.

**Comment by masayuki2009** [comment]
> @masayuki2009 Sorry it took me a bit to get to these. I think this covers the backport of your SMP fixes.

@btashton 
Thanks! 
But I think https://github.com/apache/incubator-nuttx/pull/2272 is not included.

**Comment by btashton** [comment]
My apologies. I had missed it originally and forgot to force push, it should be there now.

**Comment by masayuki2009** [comment]
> My apologies. I had missed it originally and forgot to force push, it should be there now.

@btashton 
Thanks, all the commits are now included in this PR.

**Review by masayuki2009 — APPROVED** [review]
LGTM

**Pull request merged**
