### PR TITLE
documentation: switch to m2r2 for Markdown support; update requirements.txt

### PR DESCRIPTION
**Pull request by v01d**
# Summary

This change allows including Markdown files outside of the Documentation directory. To do so they can be included in the toc or inline with: `mdinclude` directive. 

# Impact

Documentation

# Testing

Tested including a Markdown file and displayed correctly

### CODE REVIEW

**Comment by btashton** [comment]
Can you update the pipenv file as well.

**Comment by v01d** [comment]
I was about to ask how to do that

**Comment by btashton** [comment]
`pipenv install <package name>` should add it.
Otherwise recreate it from the requirements.txt `pipenv install -r requirements.txt`

**Comment by v01d** [comment]
Ok, I just force pushed the Pipfile change.
What about the `.python-version` file? Should this be pulled in or added to .gitignore?

**Comment by btashton** [comment]
> What about the `.python-version` file? Should this be pulled in or added to .gitignore?
We should drop that.  The rest looks good though.

**Comment by v01d** [comment]
Ok, just added to gitignore.

**Pull request merged**
