### PR TITLE
Add interrupt stack for SMP

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR adds interrupt stack to spresense:smp and esp32-devkitc:smp

## Impact

- None

## Testing

- Tested with ostest

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hmm, something is wrong with the CI.

```
Run docker pull docker.pkg.github.com/apache/incubator-nuttx/apache-nuttx-ci-linux
Using default tag: latest
Error response from daemon: Get https://docker.pkg.github.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error: Process completed with exit code 1.
```

**Comment by xiaoxiang781216** [comment]
Let's restart the CI.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@masayuki2009 since this PR always time out, I move the change to https://github.com/apache/incubator-nuttx/pull/4020. Let's see what happen.

**Comment by masayuki2009** [comment]
> @masayuki2009 since this PR always time out, I move the change to #4020. Let's see what happen.

@xiaoxiang781216 
Hmm, other PRs are also timed out...

**Comment by xiaoxiang781216** [comment]
Look like #4020 more stable than this one. Let's move the rest patch to that PR.

**Pull request closed without merging**
