### PR TITLE
update license on files with Author: Gregory Nutt

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
license update to Apache 

## Impact
None

## Testing
None

### CODE REVIEW

**Comment by acassis** [comment]
Hi @jerpelea I think the first two Author license update could be squashed, otherwise LGTM

**Comment by jerpelea** [comment]
@acassis they are coming from 2 authors and in my opinion this kind of squashing is not ok 
Are you sure that you want them squashed?

**Comment by jerpelea** [comment]
@acassis done

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by acassis** [comment]
Ok, sorry my fault.

**Comment by jerpelea** [comment]
can we merge it ?

**Pull request merged**
