### PR TITLE
stm32_pwm: improvements for PULSECOUNT support

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
- drivers/timers/pwm.c: fix compilation warnings
- stm32_pwm.c: fix compilation warnings
- stm32_pwm: fixes for PULSECOUNT support:
    1. generate an indefinite number of pulses when info->count = 0
    2. timers that don't support pulse-count shouldn't use pulse-count logic

## Testing
PWM example on nucleo-f446re with TIM1 PWM and TIM2 PWM enabled.

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by davids5** [comment]
@raiden00pl Was @DisruptiveNL going to test this?

**Review by jerpelea — APPROVED** [review]
LGTM

**Comment by davids5** [comment]
Thanks @acassis

**Pull request merged**
