### PR TITLE
sigact: get free sigact from freelist always successful

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
sigact: get free sigact from freelist always successful

Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>

## Testing
Ci test

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@Donny9 

I noticed that my automatic test failed because the smp application with esp32-devkitc:smp (QEMU)  runs too slow.

**Comment by Donny9** [comment]
> 

too slow ? busy loop because this pr ?

**Comment by masayuki2009** [comment]
>too slow ? busy loop because this pr ?

@Donny9 
Yes.

**Comment by Donny9** [comment]
> > too slow ? busy loop because this pr ?
> 
> @Donny9 Yes.

It looks very unlikely, nxsig_alloc_actionblock will alloc four new sigactq_t  every time.

**Comment by masayuki2009** [comment]
> I noticed that my automatic test failed because the smp application with esp32-devkitc:smp (QEMU) runs too slow.

@Ouss4 
Can you try the latest master and confirm if the above issue happens on esp32-qemu?

**Comment by Ouss4** [comment]
@masayuki2009 I just looked at our pipelines, all the ESP32 configs are passing.

(in somewhat unrelated note, ESP32-C3 is failing, all the new RISC-V changes must have broken something. We are getting `up_assert: Assertion failed at file:common/riscv_exception.c line: 8`)

**Comment by masayuki2009** [comment]
>@masayuki2009 I just looked at our pipelines, all the ESP32 configs are passing.

How about the performance of the smp application with esp32-devkitc:smp on QEMU?

**Comment by Ouss4** [comment]
I just tried locally as well.  I didn't notice any performance issues.  Is it timing out for your test?

**Comment by masayuki2009** [comment]
>I just tried locally as well. I didn't notice any performance issues. Is it timing out for your test?

@Ouss4 
Thanks for your comments.
It seems that something is wrong with my environment.

**Pull request merged**
