### PR TITLE
build qemu in docker

### PR DESCRIPTION
**Pull request by ttnie**
Signed-off-by: nietingting <nietingting@xiaomi.com>

## Summary
build qemu in docker
## Impact
no
## Testing
test on local host

### CODE REVIEW

**Comment by pkarashchenko** [comment]
Why do we need to build qemu is docker?

**Comment by ttnie** [comment]
> Why do we need to build qemu is docker?

I want to run some basic test on qemu(imx6 and riscv 32bit && 64bit), but qemu-system-arm, qemu-system-riscv32 and qemu-system-riscv64 not included on docker. So build from the source...

**Comment by btashton** [comment]
Can't we use the qemu-system-misc and qemu-system-arm packages

**Comment by ttnie** [comment]
> 

qemu-system-arm be installed before, but still not work on https://github.com/apache/incubator-nuttx/pull/7266
so I try to build from the source

**Comment by acassis** [comment]
Maybe we should put the final binaries in some server and download it, compiling from source code all the time will slow down the CI machine

**Comment by btashton** [comment]
The push job that actually uploaded the image with your changes in master failed which is why it was missing. I  restarted that job https://github.com/apache/incubator-nuttx/actions/runs/3273853972

**Pull request closed without merging**
