### PR TITLE
[EXPERIMENT/DISCUSS] sim/zblue: zephyr bluetooth stack support

### PR DESCRIPTION
**Pull request by anchao**
## Summary

The current implementation of Xiaomi’s Bluetooth stack is different with the current architecture.
HCI transport layer communication will be based on /dev/ttyS* devices instead of sockets,
The stack module prefers like bluedroid instead of bluez, host/l2cap will run on userspace,

The reasons for this are as follows:

```
1. Low coupling and more flexible: 

             The stack implementation is completely decoupled from the operating system, 
             which will completely decouple the nuttx from the stack with different implementation characteristics, 
             Developers will have more ways to choose the stack which they need (btstack/zephyr/nimble/bluedroid ?)

2. Easier to porting: 

             Implement and maintain the OSI layer is enough to porting the open source stack.

3. Sustainability/low maintenance cost:

             Keep in sync with the main line of the 3-party stack, regularly updated with the common code.
             (For the stack common code is not modified at all or some minor possible modification,)

4. Code contribution:

             Since the common code is exactly the same as the main line, the stack issues will be solved in the corresponding community.
             This is also the contribution of nuttx developers to other open source projects.
```

At present, Xiaomi has completed the porting of the zephyr stack(including ble, mesh, shell，etc),
and preparing to apply it to the internal module products,

`https://github.com/anchao/zblue`

1. Shell:

```
https://github.com/anchao/zblue/tree/master/port/subsys/bluetooth/shell
https://github.com/anchao/zblue/tree/master/subsys/bluetooth/shell
```

2. Stack:

`https://github.com/anchao/zblue/tree/master/subsys/bluetooth`

3. OSI porting:

`https://github.com/anchao/zblue/tree/master/port`

4. HCI and Chip:

```
Realtek AmebaZ rtl8720c:
https://github.com/anchao/zblue/tree/master/port/chip/amebaz

XRadio tech:
https://github.com/anchao/zblue/tree/master/port/chip/xr829

libusb H2 for NuttX simulation(refer to sim/zblue):
https://github.com/anchao/zblue/tree/master/port/drivers/bluetooth/hci/libusb.c

```

and also we have nuttx sim demo for the zephyr stack,
If anyone is interested, you can try the following steps to run the stack on sim:

1. USB Dongle: (Recommend CSR8510 (BT+BLE+MESH 5.0))

```
$ lsusb
...
Bus 001 Device 073: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
...
```

2. Setup Environment:

```
sudo apt-get install libusb-1.0-0-dev:i386
sudo apt-get install libusb-1.0-0-dev
```

3. Download the source code:  

```
git clone git@github.com:apache/incubator-nuttx.git
git clone git@github.com:apache/incubator-nuttx-apps.git
git clone git@github.com:anchao/external.git
git clone git@github.com:anchao/tinycrypt.git external/tinycrypt
git clone git@github.com:anchao/zblue.git external/zblue

mv incubator-nuttx-apps apps
ln -s ../external apps/external
```

Apply the patch list of this PR to incubator-nuttx:

`https://github.com/apache/incubator-nuttx/pull/1651`

Directory structure:

```
$ tree

├── apps
│   ├── external -> ../external
├── external
│   ├── tinycrypt
│    ── zblue
 ── incubator-nuttx

```

5. Compile sim/zblue

```
cd incubator-nuttx

./tools/configure.sh sim/zblue
make
```

6. Startup the stack:

```
archer@c:~/code/nuttx/incubator-nuttx$ sudo ./nuttx 

NuttShell (NSH) NuttX-9.1.0
nsh> 
nsh> bt init
[    2.285300] 0a12:0001 (bus 1, device 105) - class e0 subclass 1 protocol 1
[    2.285300] -> using 0x81 for HCI Events
[    2.285300] -> using 0x02 for ACL Data Out
[    2.285300] -> using 0x82 for ACL Data In
[    2.285300] -> using 0x03 for SCO Data Out
[    2.285300] -> using 0x83 for SCO Data In
[    2.640300] Controller doesn't seem to support Zephyr vendor HCI
[    2.640300] No ID address. App must call settings_load()
[    2.640300] Bluetooth initialized
[    2.643300] Identity: 00:1A:7D:DA:71:13 (public)
[    2.643300] HCI: version 4.0 (0x06) revision 0x22bb, manufacturer 0x000a
[    2.643300] LMP: version 4.0 (0x06) subver 0x22bb
nsh> 
nsh> ps
  PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0 FIFO     Kthread N-- Ready              00000000 002048 001296  63.2%  Idle Task
    1     1 224 FIFO     Kthread --- Waiting  Signal    00000000 008208 001980  24.1%  hpwork
    2     1 100 FIFO     Task    --- Running            00000000 030736 002432   7.9%  init
    4     4 102 FIFO     Kthread --- Waiting  Semaphore 00000000 008176 000692   8.4%  BT TX  0xf7945040
    5     4 103 FIFO     Kthread --- Waiting  Semaphore 00000000 008176 000820  10.0%  BT RX  0xf7945040
    6     4 105 FIFO     Kthread --- Waiting  Semaphore 00000000 008176 000692   8.4%  BT ECC  0xf7945040
    7     4 103 FIFO     Kthread --- Waiting  Signal    00000000 008176 001020  12.4%  BT Driver  0xf7945040
nsh> 
```

7. BLE Peripheral:

```
archer@c:~/code/nuttx/incubator-nuttx$ sudo ./nuttx 

NuttShell (NSH) NuttX-9.1.0
nsh> peripheral
[    1.938300] 0a12:0001 (bus 1, device 105) - class e0 subclass 1 protocol 1
[    1.938300] -> using 0x81 for HCI Events
[    1.938300] -> using 0x02 for ACL Data Out
[    1.938300] -> using 0x82 for ACL Data In
[    1.938300] -> using 0x03 for SCO Data Out
[    1.938300] -> using 0x83 for SCO Data In
[    2.286500] Controller doesn't seem to support Zephyr vendor HCI
[    2.286500] No ID address. App must call settings_load()
Bluetooth initialized
[    2.288500] Identity: 00:1A:7D:DA:71:13 (public)
[    2.288500] HCI: version 4.0 (0x06) revision 0x22bb, manufacturer 0x000a
[    2.288500] LMP: version 4.0 (0x06) subver 0x22bb
Advertising successfully started
```

8. BLE Central:

```
archer@c:~/code/nuttx/incubator-nuttx$ sudo ./nuttx 

NuttShell (NSH) NuttX-9.1.0
nsh> central
[    4.013700] 0a12:0001 (bus 1, device 105) - class e0 subclass 1 protocol 1
[    4.013700] -> using 0x81 for HCI Events
[    4.013700] -> using 0x02 for ACL Data Out
[    4.013700] -> using 0x82 for ACL Data In
[    4.013700] -> using 0x03 for SCO Data Out
[    4.013700] -> using 0x83 for SCO Data In
[    4.365500] Controller doesn't seem to support Zephyr vendor HCI
[    4.365500] No ID address. App must call settings_load()
[    4.367500] Identity: 00:1A:7D:DA:71:13 (public)
[    4.367500] HCI: version 4.0 (0x06) revision 0x22bb, manufacturer 0x000a
[    4.367500] LMP: version 4.0 (0x06) subver 0x22bb
Bluetooth initialized
Scanning successfully started
nsh> Device found: 78:20:CC:53:FB:E4 (random) (RSSI -79)
Device found: 78:11:DC:92:42:42 (public) (RSSI -65)
Connected: 78:11:DC:92:42:42 (public)
Disconnected: 78:11:DC:92:42:42 (public) (reason 0x08)
Scanning successfully started
Device found: 73:4F:31:AC:17:CB (random) (RSSI -69)
Connected: 73:4F:31:AC:17:CB (random)
Disconnected: 73:4F:31:AC:17:CB (random) (reason 0x16)
Scanning successfully started
Device found: 58:77:EF:3D:A0:6D (random) (RSSI -62)
Connected: 58:77:EF:3D:A0:6D (random)
Disconnected: 58:77:EF:3D:A0:6D (random) (reason 0x16)
Scanning successfully started
Device found: 6A:E7:51:C7:66:F3 (random) (RSSI -62)
Connected: 6A:E7:51:C7:66:F3 (random)
Disconnected: 6A:E7:51:C7:66:F3 (random) (reason 0x3e)
Scanning successfully started
Device found: 55:D6:73:66:9F:3C (random) (RSSI -66)
Connected: 55:D6:73:66:9F:3C (random)
Disconnected: 55:D6:73:66:9F:3C (random) (reason 0x3e)
Scanning successfully started
Device found: 7A:4A:23:31:82:93 (random) (RSSI -72)
Device found: 47:F9:5A:17:6A:CE (random) (RSSI -59)
Connected: 47:F9:5A:17:6A:CE (random)
```

9. BLE Mesh node:

```

archer@c:~/code/nuttx/incubator-nuttx$ sudo ./nuttx 

NuttShell (NSH) NuttX-9.1.0
nsh> btmesh
Initializing...
[    5.340600] 0a12:0001 (bus 1, device 107) - class e0 subclass 1 protocol 1
[    5.340600] -> using 0x81 for HCI Events
[    5.340600] -> using 0x02 for ACL Data Out
[    5.340600] -> using 0x82 for ACL Data In
[    5.340600] -> using 0x03 for SCO Data Out
[    5.340600] -> using 0x83 for SCO Data In
nsh> [    5.700400] Controller doesn't seem to support Zephyr vendor HCI
[    5.700400] No ID address. App must call settings_load()
Bluetooth initialized
[    5.732400] Identity: 00:1A:7D:DA:71:13 (public)
[    5.732400] HCI: version 4.0 (0x06) revision 0x22bb, manufacturer 0x000a
[    5.732400] LMP: version 4.0 (0x06) subver 0x22bb
[    5.732400] Device UUID: 00000000-0000-0000-0000-00000000dddd
Mesh initialized
OOB Number: 1993
[   28.035000] Primary Element: 0x0002
[   37.035000] No matching TX context for ack
```

10. Shell:

```
nsh> bt
[    1.766000] Bluetooth shell commands :
[    1.766000] [00]: bt init : [none]
[    1.766000] [01]: bt hci-cmd : <ogf> <ocf> [data]
[    1.766000] [02]: bt id-create : [addr]
[    1.766000] [03]: bt id-reset : <id> [addr]
[    1.766000] [04]: bt id-delete : <id>
[    1.766000] [05]: bt id-show : [none]
[    1.766000] [06]: bt id-select : <id>
[    1.766000] [07]: bt name : [name]
[    1.766000] [08]: bt scan : <value: on, passive, off> [filter: dups, nodups] [wl] [coded] [no-1m]
[    1.766000] [09]: bt advertise : <type: off, on, scan, nconn> [mode: discov, non_discov] [whitelist: wl, wl-scan, wl-conn] [identity] [no-name] [one-time]
[    1.766000] [10]: bt directed-adv : <address: XX:XX:XX:XX:XX:XX> <type: (public|random)> [mode: low] [identity] [dir-rpa]
[    1.766000] [11]: bt adv-create : <type: conn-scan conn-nscan, nconn-scan nconn-nscan> [ext-adv] [no-2m] [coded] [whitelist: wl, wl-scan, wl-conn] [identity] [name] [directed <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>] [mode: low]
[    1.766000] [12]: bt adv-param : <type: conn-scan conn-nscan, nconn-scan nconn-nscan> [ext-adv] [no-2m] [coded] [whitelist: wl, wl-scan, wl-conn] [identity] [name] [directed <address: XX:XX:XX:XX:XX:XX> <type: (public|random)>] [mode: low]
[    1.766000] [13]: bt adv-data : <data> [scan-response <data>] <type: discov, name, hex>
....

nsh> gatt
[    3.717700] Bluetooth GATT shell commands :
[    3.717700] [00]: gatt discover : [UUID] [start handle] [end handle]
[    3.717700] [01]: gatt discover-characteristic : [UUID] [start handle] [end handle]
[    3.717700] [02]: gatt discover-descriptor : [UUID] [start handle] [end handle]
[    3.717700] [03]: gatt discover-include : [UUID] [start handle] [end handle]
[    3.717700] [04]: gatt discover-primary : [UUID] [start handle] [end handle]
[    3.717700] [05]: gatt discover-secondary : [UUID] [start handle] [end handle]

....

nsh> l2cap
[   18.302000] Bluetooth L2CAP shell commands :
[   18.302000] [00]: l2cap connect : <psm>
[   18.302000] [01]: l2cap disconnect : [none]
[   18.302000] [02]: l2cap metrics : <value on, off>

....

nsh> mesh
[   24.813900] Bluetooth Mesh shell commands :
[   24.813900] [00]: mesh init : (null)
[   24.813900] [01]: mesh reset : (null)
[   24.813900] [02]: mesh ident : (null)
[   24.813900] [03]: mesh dst : [destination address]
[   24.813900] [04]: mesh netidx : [NetIdx]
[   24.813900] [05]: mesh appidx : [AppIdx]
[   24.813900] [06]: mesh net-send : <hex string>
[   24.813900] [07]: mesh rpl-clear : (null)
[   24.813900] [08]: mesh pb-gatt : <val: off, on>
[   24.813900] [09]: mesh pb-adv : <val: off, on>
[   24.813900] [10]: mesh uuid : <UUID: 1-16 hex values>
[   24.813900] [11]: mesh input-num : <number>
[   24.813900] [12]: mesh input-str : <string>
[   24.813900] [13]: mesh static-oob : [val: 1-16 hex values]
[   24.813900] [14]: mesh provision : <NetKeyIndex> <addr> [IVIndex]
....

```

### CODE REVIEW

**Comment by patacongo** [comment]
@btashton said this in the dev list:

> While I appreciate the need to have a more complete Bluetooth stack working, I am very opposed to this being brought into mainline. It fully bypasses the OS. This would be as if we implemented the full network stack in user space. 
> 
> Doing this also ties us to a critical bit of software that we do not maintain which is also not something I could support.
> 
> The Bluedroid comparison is a good one, it exists to explicitly work around the Linux stack and further sperate Android from the kernel. This split also let Qualcomm ship there entirely own stack also out of the Kernel. 
> 
> 
> What I will say is that once I implement the HCI socket interface, using the user channel you could easily have zblue run on top of that with no changes to NuttX. Drivers do not have to implement a special tty interface since it can just use the socket interface.  This is the whole point of the user channel and how several years ago I added mesh support outside of the Linux kernel. 

I am in 100% agreement.  I am very opposed to this change because it violates all of the architectural principles that have been established for the NuttX wireless subsystem over the course of about a 2 year discussion in the old Google group.  That architecture and roadmap are documented here:  https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=139629397

Specifically, the interface to the all complex wireless devices MUST be through the network layer.  Use of character devices in anything other than the most trivial of radios is strictly forbidden.

Xiaomi cannot contribute this crappy implementation only because they are too lazy to follow the established architectural principles as required in the INVIOLABLES.md.  This is wrong and cannot be permitted to happen.

I also believe the underlying approach is unethical.  It takes some of the Zephyr code, downloads it at build time, and builds the unauthorized third party code into the binaries.  The purpose of this is to avoid the NuttX coding standard and to circumvent the ASF's policies for including third party code.  While this approach may meet the legal definitions, it is inherently corrupt at its core.  This approach is not only lazy, inconsistent with the NuttX roadmap, but lacks integrity.

This code must NEVER come into the NuttX master branch.  This is not in the spirit of NuttX, it is not consistent with the NuttX roadmap, custs corners to reduce effort, and lacks integrity.  This is all in contradiction to most of the statements.

I have marked this as a Draft so that it is not accidently merged.  It would have to be reverted if it were merged.

**Comment by patacongo** [comment]
I think that this PR was created with a dirty repository.  There are 5 commits in the PR and only one seems to deal with the title subject.  The rest appear to unrelated.

**Comment by anchao** [comment]
As mentioned in the title, this is just an experimental project that needs to discuss further the implementation of the bluetooth stack.
The implementation of bt stack in userspace does not conflict with the current architecture, this is just a choice.
On the contrary, the complete BLE+MESH solution will help for some developers to announce their products more quickly, 
which is very helpful for NuttX promotion.

I fully agree with @btashton @v01d, According to the current implementation of nuttx, 
the socket model will be a perfect solution to solve the compatibility issue between userspace and kernelspace.
I am not exclusive, and hope that PMC can enhance further the current bt stack implementation.

However, from 2018 to 2020, after Greg completed the stack initial version, until now, the NuttX stack does not have any enhancements, In userspace, btsak lacks a lot of important functions and features,  such as MESH, A2DP have not yet been implemented.

We discovered during the evaluation at the beginning of the project that if we have an urgent product launch cycle, 
then we will invest a lot of HC and resources to maintain this stack, the investment here is uncertain, seriously, this is not a sane approach.
So now there is a practical problem in front of us，If we have a large number of product lines that need to use MESH and A2DP on nuttx, what should we do? 
how about SIG certification? I think it's a problem that many developers will faced, and it's also an important metrics to choose OS.

What can NuttX bring to us? In addition to a stable OS, I think a complete and highly integrated net stack will be a great place.
Zephyr ble+mesh stack will only be one of the BLE solutions. In the future, Xiaomi will complete the bluedroid porting of NuttX to bring support for the A2DP part.

As I said at the beginning, this is just a solution to let NuttX developers know that the current OS has a reliable stack support.
Of course, Roadmap of NuttX has not changed, and the socket model is still under development,

**Comment by patacongo** [comment]
> Of course, Roadmap of NuttX has not changed, and the socket model is still under development,

In the mean time, no other user-space or character-driver implementation will be permitted into the repositories.

**Comment by xiaoxiang781216** [comment]
> Was this PR was created with a dirty repository? There are 5 commits in the PR and from the commit comments, only one seems to deal with the title subject. The rest appear to be unrelated.
> 
> Hmmm...
> 
> Looking at the code I see only sim-related changes. I don't see any bluetooth. I am not sure what I am looking at. I see a call to 

Yes, most of changes are the common fix for sim, which isn't related to bluetooth stack at all. The pure userspace solution don't need make any change to NuttX kernel. 

>STDLIBS += -lusb-1.0 and libusb_bt_stack_initialize() in sim_appinit.c, but that is all.
> 

libusb-1.0.so is used to talk with USB Bluetooth Dongle and make BT stack could access it like tty peripheral.

> These changes still should not come into master. It is not the correct architectural approach to support Bluetooth under the NuttX wireless roadmap.

**Comment by anchao** [comment]
This is not a dirty repository，let me clarify these commits:

1. sim/rcS: mount the current directory if hostfs is enabled
Bluetooth settings require file system access to save the related bt hash and smp key.

2. arch/sim: Initialize idle thread stack information
Thread TLS bug, rtc driver will access errno in idle, which will cause crash, this improvement is pending on https://github.com/apache/incubator-nuttx/pull/1369, 
this is just a workaround.

3. sim/link: enable garbage collection by default
The internal symbols of zephyr stack need complete link garbage collection

4. sim/Make.defs: add -fvisibility=hidden to CFLAGS
hide nuttx symbol to avoid host dynamic library invaild link to nuttx

5. sim/zblue: enable zephyr bluetooth stack
enable stack

**Comment by xiaoxiang781216** [comment]
@anchao all patch except the last one are common fix not relate to bluetooth at all, it's better to put into another PR.

**Comment by anchao** [comment]
> @anchao all patch except the last one are common fix not relate to bluetooth at all, it's better to put into another PR.

Got, I will separate them to another PR

**Pull request closed without merging**
