### PR TITLE
Improve releasecheck.sh

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Build and run asan instead:

- boards/sim: Automatically run ostest for asan and kasan config
- tools/release.sh: Build sim:asan instead of sim:nsh 
- tools/checkrelease.sh: Launch nuttx after build

## Impact
./tools/checkrelease.sh

## Testing
./tools/checkrelease.sh --release 10.2.0-RC0
with the following output:
```
Downloading release files from https://dist.apache.org/repos/dist/dev/incubator/nuttx/10.2.0-RC0/
gpg: directory '/tmp/nuttx-checkrelease/.gnupg' created
gpg: keybox '/tmp/nuttx-checkrelease/.gnupg/pubring.kbx' created
gpg: /tmp/nuttx-checkrelease/.gnupg/trustdb.gpg: trustdb created
gpg: key E1B6E30DB05D6280: public key "Brennan Ashton <btashton@apache.org>" imported
gpg: key 2B8C7F0EAB22000E: public key "Abdelatif Guettouche (CODE SIGNING KEY) <aguettouche@apache.org>" imported
gpg: key A57CE1279F1E7328: public key "Alin Jerpelea (CODE SIGNING KEY) <jerpelea@apache.org>" imported
gpg: Total number processed: 3
gpg:               imported: 3
 OK: https://dist.apache.org/repos/dist/dev/incubator/nuttx/KEYS is imported.
Checking apache-nuttx-10.2.0-incubating.tar.gz sha512...
 OK: apache-nuttx-10.2.0-incubating.tar.gz sha512 hash matches.

Checking apache-nuttx-10.2.0-incubating.tar.gz GPG signature:
gpg: Signature made Mon Nov  1 16:28:10 2021 CST
gpg:                using RSA key FAFEEA08ABE09A8F060D984CA57CE1279F1E7328
gpg: Good signature from "Alin Jerpelea (CODE SIGNING KEY) <jerpelea@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FAFE EA08 ABE0 9A8F 060D  984C A57C E127 9F1E 7328
 OK: apache-nuttx-10.2.0-incubating.tar.gz gpg signature matches.

Checking apache-nuttx-10.2.0-incubating.tar.gz for required files:
 OK: all required files exist in nuttx.

Checking apache-nuttx-apps-10.2.0-incubating.tar.gz sha512...
 OK: apache-nuttx-apps-10.2.0-incubating.tar.gz sha512 hash matches.

Checking apache-nuttx-apps-10.2.0-incubating.tar.gz GPG signature:
gpg: Signature made Mon Nov  1 16:28:11 2021 CST
gpg:                using RSA key FAFEEA08ABE09A8F060D984CA57CE1279F1E7328
gpg: Good signature from "Alin Jerpelea (CODE SIGNING KEY) <jerpelea@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FAFE EA08 ABE0 9A8F 060D  984C A57C E127 9F1E 7328
 OK: apache-nuttx-apps-10.2.0-incubating.tar.gz gpg signature matches.

Checking apache-nuttx-apps-10.2.0-incubating.tar.gz for required files:
 OK: all required files exist in apps.

Trying to build nuttx sim:asan...
 OK: we were able to build sim:asan.

Trying to run nuttx sim:asan...
==737==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7ffe4e7f6000; bottom 0x631000023000; size: 0x1cee4e7d3000 (31809844621312)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
 OK: ostest with ASAN pass.
```

### CODE REVIEW

**Review by Ouss4 — COMMENTED** [review]
@xiaoxiang781216 is it possible to also run `sim:ostest`?  the ASAN is a good option however it also bypasses our memory allocator.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 is it possible to also run `sim:ostest`? the ASAN is a good option however it also bypasses our memory allocator.

But, asan can catch the potential memory corruption. Since the built-in heap is seldom modified, it's more important to expose the memory issue as much as possible with ASAN.

**Comment by Ouss4** [comment]
What a simple `sim:ostest` can do is to just confirm that 1. The build of the allocator is good and 2. If we run with `DEBUGASERTION` enabled we can also catch a bunch of issues.  
The thing here is that we will have to enable 2 or more options before building.

In any case, I was just asking if you had the idea of running that as well, it's not a requirement for this PR.

**Review by Ouss4 — APPROVED** [review]
LGTM!

**Pull request merged**
