### PR TITLE
Remove boilerplate from the PR template.

### PR DESCRIPTION
**Pull request by patacongo**
So far, the use of the new pull request template has been disastrous.  People are ignoring the writing instructions the template is polluting the PR history.  This change just removes the boilerplate and writing instructions fromt he template.  We don't need to see this unmodified serveral times per day.

# Pull Request Template

## Title guidelines

Following the guidelines for writting good commit messages (https://chris.beams.io/posts/git-commit/) and creating a meaningful title is key in effective team communication.

**do's**
- stm32h7:  Add SDMMC Support
- nsh:  Separate `source` and `sh` for POSIX compliance
- nxstyle:  Fixed Camel case detection
- drivers/serial:  Fixed style violation

**dont's**
- fixed bug
- nxstyle
- PR #12

## Description

**Describe problem solved by the PR**
A clear and concise description of the problem, if any, this PR will solve. Please also include relevant motivation and context: E.g. The current nsh sh command violates the POSIX ...

List any dependencies that are required for this change.

**Describe your solution**
A clear and concise description of what you have implemented.

**Describe possible alternatives**
A clear and concise description of alternative solutions  you've considered.

**Additional context**
Add any other context or screenshots for the pr.

Fixes # (issue)

## Type of change

Delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

* Nuttx board/config:
* Hardware:
* Toolchain:

## Checklist:

- [ ] My code follows the style guidelines of this project (NEED link to how to run checkpatch)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings (NEED link to how to run checkpatch spelling)

### CODE REVIEW

**Comment by jerpelea** [comment]
+1

**Comment by patacongo** [comment]
I think additional simplifications are also needed.  Feel free to suggest changes or even to push commits to the branch on my fork.  A template is good, but this is not usable in its current form.

**Comment by btashton** [comment]
You can also use comments to keep the commentary out of the rendered body if there a places we want to keep some of it to guide people in writing a good PR. 

```
# a section heading
<!--
This is a description of what might go here. Don't worry about deleting this. l will not render in the PR.
-->
```

**Comment by patacongo** [comment]
> 
> 
> You can also use comments to keep the commentary out of the rendered body if there a places we want to keep some of it to guide people in writing a good PR.
> 
> ```
> # a section heading
> 
> ```

Writing instructions that people cannot see is not useful.  Instructions should probably go in the Confluence workflow description.

**Comment by patacongo** [comment]
Closed due to lack of interest.

**Comment by btashton** [comment]
No one is using it so SGTM.  Maybe in the future we can revisit with something less intimidating, it would be nice if some of the PRs had a little more description in them.

**Comment by patacongo** [comment]
> No one is using it so SGTM. Maybe in the future we can revisit with something less intimidating, it would be nice if some of the PRs had a little more description in them.

We are looking for a short, to-the-point template that won't intimidate people and will encourage them to provide the information that they have.  We just updated this again so now we are adopting the very sweet and short template used by Sony.  I think this will help us a lot.  Contributors won't be so offending and should feel comfortable in giving us the information that they have.  That is all we should expect.

**Pull request merged**
