### PR TITLE
STM32L4: Improvements on ADC driver

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**
## Summary

  * Add option to start adc at setup
  * Add option to cofigure ADC resolution
  * Add option to cofigure ADC sample time
  * Add option to cofigure ADC DMA
  * Add suport for low level operations.

This improvements was based on STM32 ADC driver.

## Testing

Tested with board nucleo-l432kc and ADC example application.
It's necessary to test  low level operations.

### CODE REVIEW

**Comment by acassis** [comment]
Hi @daniel-p-carvalho please update your defconfig, it is reporting error

**Comment by daniel-p-carvalho** [comment]
@acassis I don't know what is the problem with defconfig file. It was generated by menuconfig.

**Comment by acassis** [comment]
Hi @daniel-p-carvalho it still with BSD license.

**Comment by davids5** [comment]
@daniel-p-carvalho - there are new CI failures. Please fix them and force push.

**Comment by acassis** [comment]
It passed now! LGTM

**Pull request merged**
