### PR TITLE
mm: Implement malloc_usable_size

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
defined here:
https://man7.org/linux/man-pages/man3/malloc_usable_size.3.html

## Impact
New API.

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 is the an opengroup reference for this?

**Comment by xiaoxiang781216** [comment]
No, it is glibc extension, but very useful.

**Comment by xiaoxiang781216** [comment]
@davids5 I just found the link is wrong, please see the new link.

**Comment by davids5** [comment]
@xiaoxiang781216 - Obviusly you have a use case for it, I do not have a problem with it, @patacongo any opinion?

**Comment by davids5** [comment]
> @davids5 I just found the link is wrong, please see the new link.

Yes Thanks for updating the link, I saw that and found the correct one, when I asked the OG question.

**Comment by hartmannathan** [comment]
The change looks good to me. Is there any reason it hasn't been merged yet?

**Comment by jerpelea** [comment]
LGTM

**Comment by jerpelea** [comment]
LGTM

**Pull request merged**
