### PR TITLE
gs2200m: Add a comment to mention the referred document

### PR DESCRIPTION
**Pull request by yamt**
Many of existing comments in this file refer to the document.
Like "NOTE: See 3.2.2.3 Annexure - HI Frame Format (From Host)"

### CODE REVIEW

**Comment by jerpelea** [comment]
it would be better to reference the document name and title because the documents can be moved during the website lifetime

**Comment by yamt** [comment]
@jerpelea the document name is in the comment

**Comment by jerpelea** [comment]
instead of the long URL!

**Comment by yamt** [comment]
@jerpelea i changed it to a shorter url which i guess will less likely changed.

**Comment by jerpelea** [comment]
you still have a url and this one will need maintenance but should be fine for now

**Pull request merged**
