### PR TITLE
sama5d3x-ek/ov2640: Enable CONFIG_ALLOW_GPL_COMPONENT

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Fix the build break by: https://github.com/apache/incubator-nuttx/pull/4352

## Testing
Pass CI

### CODE REVIEW

**Review by Ouss4 — APPROVED** [review]
LGTM

**Comment by Ouss4** [comment]
BTW, I see in the ov2640.c file the following comment:

> ```C
>  * WARNING:  Some of the information in the data tables below came from other
>  * projects with conflicting licenses:  Linux and ArduCAM.  Those both have
>  * GPL licenses.  I am not sure if it is proper or not to lift the content
>  * of those tables and still retain this BSD license.  I am guessing so, but
>  * I am not copyright attorney so you should use this driver in products at
>  * your own risk.
> ```

Can we seek some information about this? It looks huge to call it "GPL code" while it only gets few values in a lookup table.

**Comment by xiaoxiang781216** [comment]
> BTW, I see in the ov2640.c file the following comment:
> 
> > ```c
> >  * WARNING:  Some of the information in the data tables below came from other
> >  * projects with conflicting licenses:  Linux and ArduCAM.  Those both have
> >  * GPL licenses.  I am not sure if it is proper or not to lift the content
> >  * of those tables and still retain this BSD license.  I am guessing so, but
> >  * I am not copyright attorney so you should use this driver in products at
> >  * your own risk.
> > ```
> 
> Can we seek some information about this? It looks huge to call it "GPL code" while it only gets few values in a lookup table.

We can refine the code later.

**Comment by xiaoxiang781216** [comment]
CI fail to download uClibc++-0.2.5.tar.gz, since the change is small and fix the mainline build break, @Ouss4 could you merge this patch directly?

**Pull request merged**
