### PR TITLE
Reduce the preserved memory to save the space

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
The memory consumption is reduced by 2KB with the default Kconfig.

### CODE REVIEW

**Comment by jerpelea** [comment]
LGTM

**Comment by yamt** [comment]
what kind of system the numbers in the commit message are measured for?
eg. arch/board
eg. number of tasks

**Comment by xiaoxiang781216** [comment]
minimal config with nsh:
CONFIG_ARCH="sim"
CONFIG_ARCH_BOARD="sim"
CONFIG_ARCH_BOARD_SIM=y
CONFIG_ARCH_CHIP="sim"
CONFIG_ARCH_SIM=y
CONFIG_DEBUG_SYMBOLS=y
CONFIG_SIM_M32=y
CONFIG_SYSTEM_NSH=y
CONFIG_USER_ENTRYPOINT="nsh_main"
I used 32bit sim, but the number should be similar for other arch since the optimiation focus on the preserved global memory.

**Comment by xiaoxiang781216** [comment]
@jerpelea could you merge this patch?

**Pull request merged**
