### PR TITLE
mm: add heap policy and asan logic to support mm debug on sim platform

### PR DESCRIPTION
**Pull request by mage0811**
## Summary
We can detect more bug with asan tool.

## Impact
No, disabled by default.

## Testing
CONFIG_SIM_SANITIZE=y and run nuttx to ensure no ASAN error report

### CODE REVIEW

**Comment by mage0811** [comment]
depend on the patch "improve the memory manager modularity and reduce the inforamtion explosion #3086 "

**Comment by mage0811** [comment]
this is one customize mm policy defined for sim platform, depend on "improve the memory manager modularity and reduce the inforamtion explosion #3086"

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
@Ouss4 here is the demo how to implement the custom heap manager to enable the advanced sanitizer on SIM.

**Comment by Ouss4** [comment]
Thanks @xiaoxiang781216 
You also mentioned that you tried or are using tlsf, is it a per arch implementation like this one or you have it somewhere else?

**Comment by xiaoxiang781216** [comment]
> Thanks @xiaoxiang781216
> You also mentioned that you tried or are using tlsf, is it a per arch implementation like this one or you have it somewhere else?

No, tlsf is a general implementation, so the code is put inside mm/tlsf and a new choice option is added.

**Review by Ouss4 — APPROVED** [review]
Thanks @mage0811 @xiaoxiang781216
LGTM

**Pull request merged**
