### PR TITLE
drivers: audio: Fix cxd56_stop in cxd56.c

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- In the previous implementation, cxd56_stop() checked the internal
state before sending AUDIO_MSG_STOP to the message queue. However,
if the worker thread took time to turn on AMP, cxd560_stop() was
not able to send the message and caused a deadlock.

- This commit fixes this issue by always sending AUDIO_MSG_STOP
regardless of the internal state.

## Impact

- This PR affects cxd56.c audio driver.

## Testing

- I tested this PR with nxrecorder and nxplayer with spresense.

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hi @jerpelea @tobias2johansson,

This is another fix that I found during testing nxrecorder.
Could you please review this PR?

**Comment by masayuki2009** [comment]
@btashton 

Hmm, all Build / macOS were canceled...

**Comment by masayuki2009** [comment]
> @btashton
> 
> Hmm, all Build / macOS were canceled...

I've updated the commit date and pushed with -f to kick the CI again.

**Comment by btashton** [comment]
@masayuki2009 you can also wait for the runs to finish or cancel them and then click the re-run all button. Not ideal but that's all I got :/ the macOS runners just seem to be less reliable.

**Pull request merged**
