### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by v01d**
## Summary

Mostly in quickstart section, removing some redundant information, improving organization and readability. I also left some TODOs guiding remaining areas of improvement.

## Impact

Documentation

## Testing

Documentation build

### CODE REVIEW

**Comment by btashton** [comment]
Thanks @v01d 
I'm also planning on getting back to adding some more docs on how to use some of the subsystems, just need to find the time...

**Comment by v01d** [comment]
> Thanks @v01d
> I'm also planning on getting back to adding some more docs on how to use some of the subsystems, just need to find the time...

That'd be great

**Comment by diegoherranz** [comment]
Is it, then, no longer required to `make clean` after modifying the config?
Thanks!

**Comment by v01d** [comment]
Not under normal circumstances. I would say that if something breaks when reconfiguring and not cleaning it should be a bug since a configuration change will trigger a dependency regeneration and the rebuild anything that actually depends on the config.

There's a corner case when changing build flags (turning on/off optimization) though: if a file does not depend on the config in any way it will not be rebuild, in that case it will use the old flags (not sure if we have such a case still). This is something that we need to address and is tracked in #1768

**Comment by diegoherranz** [comment]
Many thanks for your reply.

**Pull request merged**
