### PR TITLE
stm32f7:serial Bug Fix: Ensure next buffer is processed

### PR DESCRIPTION
**Pull request by davids5**
## Summary

   When the Head to Tail relationship was H < T, then
   only the tail to end of buffer was sent.

   The fix is: In the txdma completion to do a second
   the DMA operation using nbuffer if the nlength is
   non zero.

stm32f7:serial UART5 use actual size

   UART5 was using the CONFIG_UART5_TXBUFSIZE
   not the UART5_TXBUFSIZE_ADJUSTED.
   Since the buffer size was adjusted up, this
   has no dcache implications.
   If the UART5_TXBUFSIZE_ADJUSTED is larger
   then CONFIG_UART5_TXBUFSIZE it will present
   a larger usable buffer to the system's
   serial driver.

## Impact
master has critical data loss with TX DMA, this PR fixes that. 

## Testing

PX4FMUv5X - serial test.

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 

Can you have a look and merge this?

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM. let's wait other reviewer feedback.

**Review by Ouss4 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by davids5** [comment]
@acassis or @Ouss4  - Would one of you please merge this.

**Comment by davids5** [comment]
Thank you!  @Ouss4

**Pull request merged**
