### PR TITLE
sched/clock: Remove CLOCK_MONOTONIC option from Kconfig

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Split from https://github.com/apache/incubator-nuttx/pull/5503

## Impact
See the discussion in the original thread

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
before this PR:
```
   text    data     bss     dec     hex filename
  30730     168    1552   32450    7ec2 nuttx
```
after this PR:
```
   text    data     bss     dec     hex filename
  30746     168    1552   32466    7ed2 nuttx
```
The change increase 16 bytes.

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
> before this PR:
> ```
>    text    data     bss     dec     hex filename
>   30730     168    1552   32450    7ec2 nuttx
> ```
> after this PR:
> ```
>    text    data     bss     dec     hex filename
>   30746     168    1552   32466    7ed2 nuttx
> ```
> The change increase 16 bytes.
> BTW, test with ./boards/arm/stm32/olimexino-stm32/configs/tiny

Thank you!

**Comment by pkarashchenko** [comment]
> @pkarashchenko the patch can't pass CI because it need work with patch(https://github.com/apache/incubator-nuttx-apps/pull/1005) in apps side.

I will review that patch as well.

**Comment by acassis** [comment]
@xiaoxiang781216 many drivers are using it, I think you only fixed some, please take a look:
$ git grep CONFIG_CLOCK_MONOTONIC

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 many drivers are using it, I think you only fixed some, please take a look: $ git grep CONFIG_CLOCK_MONOTONIC
> 
> ```
> drivers/sensors/bmp280.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/sensors/ds18b20.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/sensors/hyt271.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/sensors/lis2dh.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/sensors/lis2dh.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/sensors/ms5611.c:#ifdef CONFIG_CLOCK_MONOTONIC
> drivers/syslog/vsyslog.c:#elif defined(CONFIG_CLOCK_MONOTONIC)
> fs/vfs/fs_epoll.c:#ifdef CONFIG_CLOCK_MONOTONIC
> fs/vfs/fs_epoll.c:#ifdef CONFIG_CLOCK_MONOTONIC
> fs/vfs/fs_timerfd.c:#ifdef CONFIG_CLOCK_MONOTONIC
> fs/vfs/fs_timerfd.c:#endif /* CONFIG_CLOCK_MONOTONIC */
> include/nuttx/clock.h:    defined(CONFIG_CLOCK_MONOTONIC) && !defined(CONFIG_SCHED_TICKLESS)
> include/nuttx/input/touchscreen.h:#ifdef CONFIG_CLOCK_MONOTONIC
> include/nuttx/rc/lirc_dev.h:#ifdef CONFIG_CLOCK_MONOTONIC
> include/nuttx/sensors/sensor.h:#ifdef CONFIG_CLOCK_MONOTONIC
> include/time.h:#ifdef CONFIG_CLOCK_MONOTONIC
> include/time.h:#ifdef CONFIG_CLOCK_MONOTONIC
> libs/libc/netdb/lib_dnscache.c:#ifdef CONFIG_CLOCK_MONOTONIC
> libs/libc/pthread/pthread_condattr_setclock.c:#ifdef CONFIG_CLOCK_MONOTONIC
> libs/libc/time/lib_gethrtime.c:#ifdef CONFIG_CLOCK_MONOTONIC
> libs/libc/unistd/lib_sysconf.c:#ifdef CONFIG_CLOCK_MONOTONIC
> sched/clock/clock_getres.c:#ifdef CONFIG_CLOCK_MONOTONIC
> sched/clock/clock_gettime.c:#ifdef CONFIG_CLOCK_MONOTONIC
> sched/timer/timer_create.c:#ifdef CONFIG_CLOCK_MONOTONIC
> sched/timer/timer_create.c:#endif /* CONFIG_CLOCK_MONOTONIC */
> ```

They are in a separated path:
https://github.com/apache/incubator-nuttx/pull/5503/commits/4a101f21f74b394eacf95c97294b74ff09c8c9be
Anyway, I move the related change to this PR. Please review again.

**Comment by xiaoxiang781216** [comment]
ping @acassis

**Review by acassis — APPROVED** [review]

**Pull request merged**
