### PR TITLE
Initial support for the Infineon XMC4700 Relax board

### PR DESCRIPTION
**Pull request by raiden00pl**

### CODE REVIEW

**Comment by patacongo** [comment]
There are some failing coding standard checks.  These are probably not your fault but were probably already in the files.  But it would be helpful if you could get the modified files to pass the check of tools/nxstyle.

**Comment by raiden00pl** [comment]
The problem is in the arch/arm/include/xmc4/irq.h file where we include files with chip specific irq definitions in the pre-procesor section. 
Is there any other way to do this without breaking the CS ? One option is to keep irq definitions in a single file, but it's a terrible solution for arch with many chips supported (eg. stm32)

**Comment by Ouss4** [comment]
nxstyle is only complaining about the location of the included files.
Moving them under the Included Files section will eliminate the error.

**Comment by raiden00pl** [comment]
Yes, but these included files "extend" definitions which are present in /arch/<arch>/include/irq.h and depends on it (eg. we need the last common processor exception to define the first chip-specific interrupt).
If we include irq.h in sources then there is no problem. But there can be some problems if we put preprocesor logic in the chip-specific irq header because of missing definitions from top irq.h

**Comment by patacongo** [comment]
This has been the case with many architectures.  I have been ignoring this error in the past, but it is harder to ignore with this automated style checker.

And in this case, the #include cannot be moved because it depends on a #define that must precede it.  And you cannot more the #define or your will get a similar error.  I think that there is no alternative but you use good engineering judgement and accept the change as is.

I will be happy to merge the change if anyone concurs.

**Comment by patacongo** [comment]
This kind of logic is very common in architecure specific code:

- Set up some definitions, then
- include some architecture specific code

You will see this a lot in arch/xyz/include and arch/src/xyz/hardware directories.

I added the check to nxstyle that is causing the problem.  My intention was to assure that people provide the "Included Files" section header.  So the error would file if that section is not present.

Ideally, then all #included should be in that "Included Files" section.  But there are exceptions where it makes sense to relax this requirement.  So as this one and, I suspect, several others.

I don't know of any way to programmatically "relax" the requirement other than inspecting the nxstyle complaint and then making a good, informed engineering decision.

**Comment by patacongo** [comment]
@Ouss4 Okay.. I will continue with the merge after I do one final review.

**Pull request merged**
