### PR TITLE
arm64: add Cortex-A57 and Cortex-A72 configurations

### PR DESCRIPTION
**Pull request by HidenoriMatsubayashi**
## Summary
This change adds the followings:
- Rename the board configuration name from `qemu-a53` to `qemu-v8a`.
- Add the configurations for Cortex-A57 and Cortex-A72.

Basically, there should be no difference we must address by software between `cortex-a53`, `cortex-a57`, and `cortex-a72`.

スクリーンショット 2022-10-13 22 51 06

Reference:
[Arm Cortex-A Processor Comparison Table](https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Cortex-A%20R%20M%20datasheets/Arm%20Cortex-A%20Comparison%20Table_v4.ashx)

## Impact
None

## Testing
Confirmed that OS boots with the following commands/configuration:

```shell
qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 \
  -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx
```

```shell
qemu-system-aarch64 -cpu cortex-a57 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 \
  -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx
```

```shell
qemu-system-aarch64 -cpu cortex-a72 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 \
  -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx
```

Signed-off-by: Hidenori Matsubayashi <hidenori.matsubayashi@gmail.com>

### CODE REVIEW

**Comment by HidenoriMatsubayashi** [comment]
@xiaoxiang781216 @masayuki2009 

Can you please review this change?

**Comment by xiaoxiang781216** [comment]
@HidenoriMatsubayashi should we drop this patch: https://github.com/apache/incubator-nuttx/pull/7303

**Comment by HidenoriMatsubayashi** [comment]
@xiaoxiang781216 

Oh, sorry. It looks like my mistake. You mean should I merge it into this patch?

**Comment by HidenoriMatsubayashi** [comment]
I merged https://github.com/apache/incubator-nuttx/pull/7303 into this change.

**Comment by xiaoxiang781216** [comment]
Need reorder config in defconfig:
image
This can be done by:
./tools/refresh.sh --silent armv8a:nsh

**Comment by pkarashchenko** [comment]
Please rebase

**Comment by masayuki2009** [comment]
@HidenoriMatsubayashi 
Please rebase this PR to the latest master to fix the conflicts.

**Comment by HidenoriMatsubayashi** [comment]
> This can be done by:
> ./tools/refresh.sh --silent armv8a:nsh

Thanks for the information.

I rebased the PR.

**Review by masayuki2009 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
