### PR TITLE
make/expression: improving up asm/C/C++ compile times(make with multi-jobs only)

### PR DESCRIPTION
**Pull request by anchao**
## Summary

make/expression: improving up asm/C/C++ compile times 

In the current compilation environment, the recursive assignment(=) for compile
flags will be delayed until every file is actually need to be compile.

For example:
--------------------------------------------------------------------------------
```
arch/arm/src/Makefile:

INCLUDES += ${shell $(INCDIR) "$(CC)" $(ARCH_SRCDIR)$(DELIM)chip}
INCLUDES += ${shell $(INCDIR) "$(CC)" $(ARCH_SRCDIR)$(DELIM)common}
INCLUDES += ${shell $(INCDIR) "$(CC)" $(ARCH_SRCDIR)$(DELIM)$(ARCH_SUBDIR)}
INCLUDES += ${shell $(INCDIR) "$(CC)" $(TOPDIR)$(DELIM)sched}

CPPFLAGS += $(INCLUDES) $(EXTRAFLAGS)
CFLAGS += $(INCLUDES) $(EXTRAFLAGS)
CXXFLAGS += $(INCLUDES) $(EXTRAFLAGS)
AFLAGS += $(INCLUDES) $(EXTRAFLAGS)
```
--------------------------------------------------------------------------------

All compilation options will be included recursively,
which will be delayed until the compilation options are actually used:

tools/Config.mk:

--------------------------------------------------------------------------------
```
define COMPILE
  @echo "CC: $1"
  $(Q) $(CC) -c $(CFLAGS) $($(strip $1)_CFLAGS) $1 -o $2
endef
```
--------------------------------------------------------------------------------

All compile flags to be reexecuted $(INCDIR) as long as one file needs to be compiled,
but in fact, the compilation options have not changed in the current directory.

So the we recommand to change the syntax of assignment
From
    Recursive (=)
To
    Simple    (:=)

In this way, we can ensure that all compilation options are expanded only once and reducing repeated works.

Signed-off-by: chao.an <anchao@xiaomi.com>

## Impact

Compile times

## Testing

make

### CODE REVIEW

**Comment by davids5** [comment]
@anchao - what is the time difference?

**Comment by anchao** [comment]
Hi @davids5 

Seems the improvement is not obvious if run the build on CI server, 
But when I compile a C + + project locally, the improvement is very obvious,
In this case I think compilation with muljobs (-j) are very necessary.

Before patch:

```
$ time make -j8

real	7m9.702s
user	17m11.087s
sys	2m37.242s
```

After patch:

```
$ time make -j8

real	2m16.006s
user	14m47.700s
sys	1m0.800s
```

**Comment by Ouss4** [comment]
> In this case I think compilation with muljobs (-j) are very necessary.

Just for the comparison sake, I think we see better results if -j is not used.

**Comment by anchao** [comment]
Hi @Ouss4 

OK, I think I found out why the improvement is very obvious in my test,
In my local C++ project I used a lot of $(INCDIR) to include different header dir:

```
CXXFLAGS += ${shell $(INCDIR) $(INCDIROPT) "$(CC)" dir1}
CXXFLAGS += ${shell $(INCDIR) $(INCDIROPT) "$(CC)" dir2}
CXXFLAGS += ${shell $(INCDIR) $(INCDIROPT) "$(CC)" dir3}
CXXFLAGS += ${shell $(INCDIR) $(INCDIROPT) "$(CC)" dir4}
...
```

If recursive assignment(=) is used, each of $(INCDIR) will occupy a make job thread due to the delayed expanded mechanism.

make -j8:

```
job 1: incdir dir1
job 2: incdir dir2
job 3: incdir dir3
job 4: incdir dir4
....
job 8: c++ file

```
This will lead to the waste of time slice of make job in the case of compiling with multithreading


After changing to simple assignment (:=), the situation will be significantly improved,
and $(INCDIR) will only be expanded once when makefile is included,

At compile time, the thread status is:

make -j8:

```
job 1: c++ file1
job 2: c++ file2
job 3: c++ file3
job 4: c++ file4
....
job 8: c++ file8
```


Seems the improvement is obvious. Is there anyone who has got the similar issues with me?

**Comment by Ouss4** [comment]
> After changing to simple assignment (:=), the situation will be significantly improved

Yes, it should be.  Not too long ago @xiaoxiang781216 submitted a similar change and we followed up with others that improved the config/build time.
To be honest I didn't carefully look at all of the 241 files, but the idea of the change looks good to me.

**Comment by davids5** [comment]
I did a little testing with PX4.

`make clean;time make px4_fmu-v5x`
It is two builds of nuttx on for FMU F7 one for the IO F1

This PR:

```
make clean;time make px4_fmu-v5x
real	0m23.396s
user	0m42.845s
sys	0m11.689s
```

master:
```
make clean;time make px4_fmu-v5x
real	0m22.699s
user	0m42.993s
sys	0m11.840s
```
So I do not see the improvement. But I am glad you do!

**Comment by v01d** [comment]
Reducing build time is appreciated. I'm surprised though that it takes 7 minutes with 8 jobs. Maybe the difference is only obvious under certain circumstances. I usually get very reasonable build times with -j8.

This change makes me wonder why we cannot have these CXXFLAGS, CFLAGS definitions in the arch Makefile itself. The board could add any extra defines later. @xiaoxiang781216 has been doing this for a few variables at a time, maybe he knows about that. It would help future changes like this to not have to alter around ~200 files every time.

I think the change looks safe. There are a few cases where we really need the `=` (the evaluation depends on the Makefile including the Make.defs) but I think this is not one of those.

**Comment by davids5** [comment]
Ahh I added a ccache -C, but still not as big of a delta. It might be cmake and nijabuld. 

this PR:
```
real	1m25.752s
user	4m40.563s
sys	1m2.958s
```
Master:
```
real	1m21.247s
user	4m42.481s
sys	1m3.266s
```

**Comment by anchao** [comment]
> Ahh I added a ccache -C, but still not as big of a delta. It might be cmake and nijabuld.
> 
> this PR:
> 
> ```
> real	1m25.752s
> user	4m40.563s
> sys	1m2.958s
> ```
> 
> Master:
> 
> ```
> real	1m21.247s
> user	4m42.481s
> sys	1m3.266s
> ```

Hi  @davids5 

Thanks a lot for your verification, Could you please try to build with multi-jobs ? emm... I can not gurantee whether there will be an improvement, but which is really helpful for my local project.

how about this?
make clean;time make px4_fmu-v5x -j8

**Comment by davids5** [comment]
@anchao 

happy to test it for you.

> how about this?
> make clean;time make px4_fmu-v5x -j8

`ccache -C`
`make clean;time make px4_fmu-v5x -j8`

We get lot's of warning:
```
[337/1387] Generating nuttx/sched/libsched.a
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[338/1387] Generating nuttx/libs/libc/libc.a
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[568/1387] Generating ../gencromfs
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

This PR
```
real	1m21.979s
user	4m43.264s
sys	1m4.305s
```

Master
```
real	1m20.792s
user	4m42.621s
sys	1m3.808s
```

**Comment by xiaoxiang781216** [comment]
> Reducing build time is appreciated. I'm surprised though that it takes 7 minutes with 8 jobs. Maybe the difference is only obvious under certain circumstances. I usually get very reasonable build times with -j8.
> 
> This change makes me wonder why we cannot have these CXXFLAGS, CFLAGS definitions in the arch Makefile itself. The board could add any extra defines later. @xiaoxiang781216 has been doing this for a few variables at a time, maybe he knows about that. It would help future changes like this to not have to alter around ~200 files every time.
> 

Yes, I plan to move more common setting(especially for C++ options) to Toolchains.defs in Chinese National Day.

> I think the change looks safe. There are a few cases where we really need the `=` (the evaluation depends on the Makefile including the Make.defs) but I think this is not one of those.

**Comment by xiaoxiang781216** [comment]
> @anchao
> 
> happy to test it for you.
> 
> > how about this?
> > make clean;time make px4_fmu-v5x -j8
> 
> `ccache -C`
> `make clean;time make px4_fmu-v5x -j8`
> 
> We get lot's of warning:
> 
> ```
> [337/1387] Generating nuttx/sched/libsched.a
> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> [338/1387] Generating nuttx/libs/libc/libc.a
> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> [568/1387] Generating ../gencromfs
> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> ```
> 
> This PR
> 
> ```
> real	1m21.979s
> user	4m43.264s
> sys	1m4.305s
> ```
> 
> Master
> 
> ```
> real	1m20.792s
> user	4m42.621s
> sys	1m3.808s
> ```

@davids5 the speed boost depends on how much complex in your c++ code:

1. Meta programming(https://en.wikipedia.org/wiki/Template_metaprogramming)
2. Functional programming(https://en.wikipedia.org/wiki/Functional_(C%2B%2B))
3. The complex library, e.g.:
    STL: https://en.wikipedia.org/wiki/Standard_Template_Library
    Boost: https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)

Since C++ usage in PX4 is the classic(or old) programming style(C with class), the speed boost isn't remarkable.

**Comment by davids5** [comment]
> Since C++ usage in PX4 is the classic(or old) programming style(C with class), the speed boost isn't remarkable.

What is you SLOC count in code your coverage?

We are using CRTP, C11, templates and I built PX4 (alomost 6 Million lines of code) and nuttx twice. 

I think it is the build system.

**Comment by xiaoxiang781216** [comment]
@davids5 as @anchao mentioned the key point is wether you use "${shell $(INCDIR) $(INCDIROPT) "$(CC)" dir1}" to add the search path. Could you change all your search path and try again? Anyway, the change boost the build speed in some case and don't make any regression, why not merge it?

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
