### PR TITLE
armv7-a/r:cp15_invalidate_dcache_all: fix Sets mask error.

### PR DESCRIPTION
**Pull request by zhuyanlinzyl**
As NumSets field is bits 13-27, use 0x7fff instead.
And add way to get from CCSIDR.

## Impact

No, bug fix

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@zhuyanlinzyl @xiaoxiang781216 
Humm, sabre-6quad:smp with QEMU does not boot now.

If I revert this PR it works again.
Could you confirm what is happening with QEMU?

**Comment by zhuyanlinzyl** [comment]
hi, @masayuki2009.

I build sabre-6quad:smp and try in QEMU, but it still crash without this patch.

Did I use the wrong command?

  
zyl@zyl:~/nuttx$ qemu-system-arm -net nic,model=stellaris -net user,hostfwd=tcp:127.0.0.1:10023-10.0.2.15:23,hostfwd=tcp:127.0.0.1:10021-10.0.2.15:21 -M lm3s6965evb -kernel nuttx -nographic
qemu: fatal: Lockup: can't escalate 3 to HardFault (current priority -1)

R00=00000000 R01=00000000 R02=00000000 R03=00000000
R04=00000000 R05=00000000 R06=00000000 R07=00000000
R08=00000000 R09=00000000 R10=00000000 R11=00000000
R12=00000000 R13=ffffffe0 R14=fffffff9 R15=00000000
XPSR=40000003 -Z-- A handler
FPSCR: 00000000
已放弃 (核心已转储)

**Comment by masayuki2009** [comment]
@zhuyanlinzyl 

>Did I use the wrong command, Can you share the shell command with me?

Please rever the following llink
https://github.com/apache/incubator-nuttx/blob/b0d24f53c4be391f2e0081ef4bba4f5058e54f9e/boards/arm/imx6/sabre-6quad/README.txt#L643

NOTE: If you just start the qemu without GDB, you can remove -s -S options.

**Comment by zhuyanlinzyl** [comment]
hi， @masayuki2009  

It's my mistake, a4 register not save in cp15_invalidate_dcache_all.

I fixed it in PR https://github.com/apache/incubator-nuttx/pull/5367

 I verify in sabre-6quad:smp build. You can have a try.

**Pull request merged**
