### PR TITLE
ez80: fix several bugs in emac driver

### PR DESCRIPTION
**Pull request by codebje**
## Summary

IRQs cannot be individually disabled on the eZ80, so using
`up_disable_irq()` had no effect. This left the IRQ handler being
constantly triggered without the lower half handler running.

The macro for EMAC stats was incompatible with Clang. The simplified
form gives identical results under ZDS-II.

The MII clock speed must be set before trying to read MII registers.
It's now done before resetting the PHY using the Mode Control Register.

MII initialization waited on the auto-neogotiate restart bit being set
but PHY hardware is frequently fast enough to have cleared the bit
before the first read of it. It now instead just waits on auto-negotiate
completing. The MII poll loop now uses `up_mdelay` because it was far
too fast at 50MHz using a busy loop, giving time for a link to be
established.

Bad packets are now processed enough to release their buffers back to
the EMAC hardware.

A few typos, unused variables, and other miscellaneous issues were also
fixed.

## Impact

These changes permit building the eZ80 EMAC driver and enable basic Ethernet functionality.

## Testing

Successful ICMP echo receive and response:

```
ez80emac_receive: rxnext=0xffdd00 {ffdd80, 102, 8020} rrp=0xffdd00 rwp=0xffdd80 blkslft=003e
ez80emac_receive: rxnext=0xffdd80 {653734, 14128, 3166} rrp=0xffdd80 rwp=0xffdd80 blkslft=0040
ez80emac_receive: IPv4 frame
icmp_input: Outgoing ICMP packet length: 84 (84)
ez80emac_transmit: txnext=0xffc6c0 {000000, 0, 0000} trp=06c0
ez80emac_transmit: txdesc=0xffc6c0 {ffc740, 98, 8000}
ez80emac_transmit: txnext=0xffc740 {000000, 0, 0000} trp=0740
ez80emac_txinterrupt_work: txhead=0xffc6c0 {ffc740, 98, 0000} trp=0740 istat=01
ez80emac_txinterrupt_work: txhead=0xffc740 {000000, 0, 0000} trp=0740
ez80emac_txinterrupt_work: No pending Tx.. Stopping XMIT function.
```

### CODE REVIEW

**Comment by codebje** [comment]
There are further issues with networking on the eZ80 to resolve:

  - Large frames put the EMAC driver into an endless loop failing to process the invalid message
  - A DHCP lease cannot be obtained, but I don't yet know why - it may not be related to the EMAC driver
  - Auto-negotiation is successful on the DP83848C but not correctly detected as begun or complete

I can continue to update this PR if it's preferable to merge any further changes into one.

**Comment by xiaoxiang781216** [comment]
@codebje is this patch ready for merge?

**Comment by codebje** [comment]
I think so - I've traced the DHCP issue far enough to know that it reaches `udp_input` with the right data, so whatever's causing the DCHP offer to be lost is probably not in the EMAC.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Ok, let's merge it.

**Pull request merged**
