### PR TITLE
Add Apache 2.0 License headers to SAMA5 C files — no code changes

### PR DESCRIPTION
**Pull request by adamfeuer**
### Summary

* Adds Apache 2.0 License headers to SAMA5 C files — no code changes.
* Some non-UTF-characters were removed or changed in comments.

### Impact

* None if you are not using the SAMA5 chips
* Should be none for SAMA5 users, but code files were touched.

### Detail

* Non-UTF-8 characters in comments were replaced or removed. All files are now UTF-8 encoded.

### Testing

* SAMA5D27-XULT compiles

### CODE REVIEW

**Comment by Ouss4** [comment]
@adamfeuer  Thanks. I made a small modification in header's file names to change "./arch/" to just "arch/", this is how it's done of all the files.

**Comment by adamfeuer** [comment]
Thanks @Ouss4. I updated my tool to create the paths correctly for next time.

**Comment by patacongo** [comment]
This change must be reverted.  It damages the files.

**Comment by davids5** [comment]
Why the (p)PMC not voting on changes of this magnitude **before** they are merged?

**Pull request merged**
