### PR TITLE
sched/task: Remove stack argument from nxtask_init

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
since nobody really pass the non-null stack pointer

## Impact
Minor

## Testing
Pass CI

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 - This precludes a statically defined system. It should not brought in.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 - This precludes a statically defined system. It should not brought in.

Here is my thought:

1. All public API task_create/kthread_create/posix_spawn doesn't accept stack pointer as argument
2. nxtask_init still do the dynamical allocation internally(e.g. task_group...)

If the statical allocation is the target, the public API should accept the stack pointer at least. Do you think it's better to add stackaddr field in posix_a like this:
```
struct posix_spawnattr_s
{
  FAR void *stackaddr;           
  size_t        stacksize;
};
```

**Comment by xiaoxiang781216** [comment]
@davids5 I create a new PR https://github.com/apache/incubator-nuttx/pull/3703 to utilize the stack pointer fully. One of these two PR need to merge to avoid the partial solution.

**Comment by davids5** [comment]
@xiaoxiang781216 

I thought the AP supported it. (living in the past I guess) 

This type of a change should be discussed, I see the value but, this is just my opinion. Let's get some more feedback....
@antmerlino @btashton @patacongo, @v01d ?

**Comment by xiaoxiang781216** [comment]
I will close this PR, and focus on to support the customize the stack pointer.

**Pull request closed without merging**
