### PR TITLE
New Documentation

### PR DESCRIPTION
**Pull request by v01d**
## Summary

This PR converts the existing HTML based documentation to ReStructuredText (RST) format. Is is based on Sphinx,
which renders the RST into HTML. All documents have been converted (first using pandoc to get an initial base and then
manually to fix problems of the automated conversion).
As part of this conversion, the big HTML files have been split into individual thematic RST files. Also, they have been grouped in a way that works better when they are part of an cohesive documentation instead of isolated HTML documents.
I have created a structure I believe helps to find things in the expected place.

Since documentation changes to original HTML files have ocurred while this PR was worked on, I have backported those changes in individual commits here, so this is up to date w.r.t. HTML documentation on master.

You can see this PR rendered in the GitHub pages of my fork here: https://v01d.github.io/incubator-nuttx/docs/index.html

This PR also includes a CI change which:
  - Adds a build job to render RST files into HTML and store this to an artifact. This is mostly to get build warnings/errors.
  This does not deploy documentation to anywhere (this will be taken care of in a subsequent PR)
  - Disabled the processing of old HTML documentation which was designed to publish to the wiki (manually)
  - NuttX build workflow will not trigger when a push contains only changes inside Documentation/
  - Docs will always be built, even when only code changes (this step is quite fast anyway)

This PR also removes the old HTML documents so that RST documentation is in the same `Documentation` directory.

In order to test this locally please follow the instructions on Contributing -> Documentation.

Finally, a series of follow up PRs will be done separately (to avoid overgrowing this one more focused on the migration itself):
- [ ] devise the CI workflows necessary to have this published on nuttx website. documentation should be deployed for master and for every tagged release. The documentation itself allows to choose which version to read (see mockup dropdown just above search field in documentation)
- [ ] fill supported boards section using content from current README files
- [ ] autogenerate the list of supported platforms based on all boards existing on the repo
- [ ] allow the docs to pickup information from the application repo so that applications are also documented (or at least initially, listed)
- [ ] look into defining a workflow which would build documntation for each PR somewhere (github pages for the nuttx repo?) so that previewing a PR is simple.

(I will move the above items to a separate issue to track this tasks)

**NOTE** this PR fails check step but this is due to nxstyle attempting to run on .rst files and getting confused by the renames

## Impact

All changes are to documentation and CI system.

## Testing

The result has been visually verified comparing the previous documentation HTML files to each of the converted RST files.

### CODE REVIEW

**Comment by v01d** [comment]
FYI: I will be working on NSH and User API parts next
Maybe we can continue colaborating on this using PRs on my fork?

**Comment by v01d** [comment]
I've worked a while on the User API (from the UserGuide HTML). I split the document into one for each subsection and started converting the shorter ones. You can see how it goes here:

- list: https://v01d.github.io/incubator-nuttx/docs/reference/user/index.html
- migration finished example: https://v01d.github.io/incubator-nuttx/docs/reference/user/interfaces/12_shared_memory.html

**Comment by Ouss4** [comment]
Hi,
Just a quick one, probably not related to this PR and should have been suggested with the README PR, but can we add Nightly build status to the REAMDE?  Can we also add it somewhere in the documentation?
Here is the link: https://builds.apache.org/view/Incubator%20Projects/job/NuttX-Nightly-Build/badge/

**Comment by btashton** [comment]
> Hi,
> Just a quick one, probably not related to this PR and should have been suggested with the README PR, but can we add Nightly build status to the REAMDE?  Can we also add it somewhere in the documentation?
> Here is the link: https://builds.apache.org/view/Incubator%20Projects/job/NuttX-Nightly-Build/badge/

There are also build badges for GitHub Actions which also includes the macOS builds.

**Comment by xiaoxiang781216** [comment]
@v01d could you convert the document one by one? I am afraid that it will lock the document folder too long if you do all conversion in one patch.

**Comment by v01d** [comment]
I was expecting to finish conversion in about a week. Is that reasonable?
Splitting the PR would be a bit difficult, if I can avoid it that would be ideal.
Also, if it becomes a blocker on /Documentation changes I can apply any changes
from that folder before final merge. Just let me know when you do (mentioning the PR
is enough).

**Comment by xiaoxiang781216** [comment]
I have a patch which remove wd_create/wd_delete, will upload in this week.

**Comment by patacongo** [comment]
> 
> 
> I have a patch which remove wd_create/wd_delete, will upload in this week. I will point that patch to you once it's ready.

Changes to basic, documented APIs should not be permitted by any single person or organization.  Please do NOT submit a PR without first having some [DISCUSS] phase in the dev list.  You must have everyone's input on this before any change can be considered.

**Comment by xiaoxiang781216** [comment]
> > I have a patch which remove wd_create/wd_delete, will upload in this week. I will point that patch to you once it's ready.
> 
> Changes to basic, documented APIs should not be permitted by any single person or organization. Please do NOT submit a PR without first having some [DISCUSS] phase in the dev list. You must have everyone's input on this before any change can be considered.
> 
> You will get much better reception and support if you behave as a team player.

It's better to prepare a concrete change before dissussing. The PR doesn't conflict with discussion but help people understand the problem.

**Comment by patacongo** [comment]
> It's better to prepare a concrete change before dissussing. The PR doesn't conflict with discussion but help people understand the problem.

You should at least first understand the reason why the OS uses all pre-allocated memory resources.  This is required by certain safety standards:  After the booting, these standards prohibit any dynamic allocation of memory.  We need to conform to this standard.  This is currently implemented for most structures.

Messages are a little different, there is a fixed pool there too, but additional messages can be allocated dynamically if necessary.  But, in general, the no dynamic-allocation-after-initialization must be supported.

**Comment by xiaoxiang781216** [comment]
> > It's better to prepare a concrete change before discussing. The PR doesn't conflict with discussion but help people understand the problem.
> 
> You should at least first understand the reason why the OS uses all pre-allocated memory resources. This is required by certain safety standards: After the booting, these standards prohibit any dynamic allocation of memory. We need to conform to this standard. This is currently implemented for most OS structures.
> 
> Messages are a little different, there is a fixed pool there too, but additional messages can be allocated dynamically if necessary. But, in general, the no dynamic-allocation-after-initialization requirement must be supported.


Of course, I understand the pool usage: no body can forecast how fast message/signal will generate/consume at runtime, the dynamic allocation is required for message/signal and the preallocated pool can avoid the memory fragment, allow interrrupt send message/signal and improve the performance.
But wdog is different from message/signal which usage is fixed: we can directly embed wdog_s into the parent struct and bypass the allocation at all:
```
struct posix_timer_s
{
  FAR struct posix_timer_s *flink;

  uint8_t          pt_flags;       /* See PT_FLAGS_* definitions */
  uint8_t          pt_crefs;       /* Reference count */
  pid_t            pt_owner;       /* Creator of timer */
  int              pt_delay;       /* If non-zero, used to reset repetitive timers */
  int              pt_last;        /* Last value used to set watchdog */
  struct wdog_s    pt_wdog;        /* The watchdog that provides the timing */
  struct sigevent  pt_event;       /* Notification information */
  struct sigwork_s pt_work;
};
```
It's much better than the current implementation: less memory and fast speed. So please don't assume your design is always best.

**Comment by v01d** [comment]
Completed migration of BinFmt and added PM and SYSLOG sections from PortinGuide:
* https://v01d.github.io/incubator-nuttx/docs/components/power.html
* https://v01d.github.io/incubator-nuttx/docs/components/syslog.html
* https://v01d.github.io/incubator-nuttx/docs/components/binfmt.html

**Comment by xiaoxiang781216** [comment]
Anyway, I could keep wd_create/wd_delete if @patacongo, you have any concern. But the code in the master will swtich to embed wdog_s directly.

**Comment by xiaoxiang781216** [comment]
https://github.com/apache/incubator-nuttx/pull/1545

**Comment by v01d** [comment]
Today I managed to finish the "reference" and "components" section, which is mostly the contents of the user and porting guide. There are two big ones that require considerable work: NSH and NxWidgets. I also improved the overall structure which I believe is friendlier to navigate. You can have a look if you like: https://v01d.github.io/incubator-nuttx/docs/index.html

For NSH it is mostly about the very long list of commands. I've been looking at the `apps/nshlib/README.txt` and it seems there a lot of commands documented there as well. I'm wondering what would be the reasonable approach, to finish migrating the NSH HTML as-is and consolidate documentation later (which might be a lot of wasted effort) or look into getting that into the docs directly. 

For NxWidgets it is simply a ver long document so there's no way around that.

I'm hoping that with these two complete, this could be much closer to being mergeable. There might be a lot of things that could be improved but I would prefer to do that in separate PRs to avoid continuing to grow this one. Also, I'd really like if the remaining effort could be distributed with others that are willing to give a hand with this. The effort will mostly be about looking at the generated documentation side-by-side with the HTML and look for things that are missing or look off. I've also found many typos/glitches in the original docs, but as I was focused on the migration they might still exist in the migrated ones. Of course, there's also a lot of undocumented functions and even whole parts of NuttX. That will the much longer to complete, but hopefully can be managed over time with help from others. I can eventually create an issue to track all of these.

I'm thinking that one way to wrap this PR would be to: 1) finalize the CI changes in this PR, 2) squash, 3) backport doc changes introducing recently 4) remove HTMLs from /Documentation
As I understand, there's a separate copy of the HTML docs on the wiki right? If so, removing HTMLs should not harm the availability of current docs. I would keep those for some time until we feel confident they can be archived.   

@btashton do you already have an idea about how CI should work for this to be published on the site? We can leave that for a separate PR and only leave the sphinx build here as a check to catch errors/warnings. But for deploying to the website I'm not sure how it would work.

**Comment by adamfeuer** [comment]
@v01d This looks great! I owe the remaining changes for supported platforms– formatting and hyperlinks. I'll try to get that done by Sunday.

As for removing the HTMLs from the tree– I think we need to come up with a way for people to see the docs for each release. If we did that, the HTMLs from 9.1 would still be there. I'll see if I can come up with a way to do that. If you have ideas I'd love to know them.

**Comment by v01d** [comment]
> @v01d This looks great! I owe the remaining changes for supported platforms– formatting and hyperlinks. I'll try to get that done by Sunday.

Thanks! I was unsure if I should work on that section since I suspect it would be replaced by the individual board documentation eventually. But if you're willing to do it I would be something good to have until then.

> As for removing the HTMLs from the tree– I think we need to come up with a way for people to see the docs for each release. If we did that, the HTMLs from 9.1 would still be there. I'll see if I can come up with a way to do that. If you have ideas I'd love to know them.

Sorry, I did not understand what you meant. Versioned documentation is something that is also yet missing but it shouldn't be hard to implement. In that scenario, releases after the new docs are there would each get its version of the docs and be available on the site (like Zephyr does on their doc site).

**Comment by btashton** [comment]
@v01d I am happy to wire up the CI as we had previously discussed, but yes I think that is for another PR.  I wanted to wait for this to settle before hooking it into the website CI.

My thought was to support what ever tagged releases we have via the new doc system +  master, and optionally the previous pure HTML ones.  The later is I think a lower priority since they are in the release bundles already and we have never hosted anything beyond the last release.

**Comment by adamfeuer** [comment]
@v01d @btashton Re: versioned releases going forward only, at least for now, I'm ok with that.

Re: the supported boards, yeah, I think the new boards structure would be better, but I want something that works for now to help people feel better about accepting this new doc system. 🙂 We can get to the new structure in steps.

**Comment by v01d** [comment]
PS: something to consider in the future is to write a parser for NuttX formatted comments used to document functions. This could then be used to automatically generate the documentation for a given function. This is what they are doing on Linux: https://static.lwn.net/kerneldoc/kernel-documentation.html#including-kernel-doc-comments

**Comment by patacongo** [comment]
> 
> 
> PS: something to consider in the future is to write a parser for NuttX formatted comments used to document functions. This could then be used to automatically generate the documentation for a given function. This is what they are doing on Linux: https://static.lwn.net/kerneldoc/kernel-documentation.html#including-kernel-doc-comments

Doxygen tags and similar are explicitly forbidden the by the coding standard.

**Comment by v01d** [comment]
> > PS: something to consider in the future is to write a parser for NuttX formatted comments used to document functions. This could then be used to automatically generate the documentation for a given function. This is what they are doing on Linux: https://static.lwn.net/kerneldoc/kernel-documentation.html#including-kernel-doc-comments
> 
> Doxygen tags and similar are explicitly forbidden the by the coding standard. The coding standard of major style changes should only be made after a vote of the project and is subject to some constraints in INVIOLABLES.txt.

I never mentioned Doxygen, I explicitly mentioned NuttX formatted comments. I was suggesting that these could be parsed since they are standardized by NuttX coding standard.

**Comment by v01d** [comment]
I completed migration of NuttShell document and will now continue with NXGraphics, the last one.
I will then go over through all documents to see I'm not missing something obvious. I will then disable the CI steps which use GitHub pages. Finally, I will backport documentation changes made in previous days.

After all this, I hope we can merge as is, even while there will most likely be many small things to fix that will take longer, but would be better to do as smaller separate PRs, ideally with help from others.

I will also try to improve the "contributing documentation" with some guidelines so that others can easily contribute changes. Hopefully once these new docs get published on the website, they get more attention from non-maintainers and we receive also fixes/improvements from them.

Will let you know once I get the remaining steps done. I will undraft the PR then. In the meantime you can start looking at everything but NXGraphics, if you'd like. But please, have an mind that if you find things to improve (in contrast to very big errors or missing content), I'd rather do that in a separate PR.

**Comment by v01d** [comment]
I have finally completed migration of all documents. Only one not completely migrated is the detailed list of supported platforms. @adamfeuer as you mentioned you could take care of this, you can create a PR to my fork against the docs branch as before.

I wanted to check with you (maybe @btashton ?): I understand that the latest version of HTML docs is always on the Wiki, built from the repo, right? If so, I would include the deletion of all HTMLs and renaming of doc/ to Documentation/ in this PR. The wiki would then host the archived version of latest HTML docs. Does that sound correct? Or should we go about this another way? My intention is that with this PR, the new docs become the official docs and any other change which impacts documentation will already be done over these (and not HTMLs), thus the idea of removing them.

**Comment by btashton** [comment]
> I wanted to check with you (maybe @btashton ?): I understand that the latest version of HTML docs is always on the Wiki, built from the repo, right? If so, I would include the deletion of all HTMLs and renaming of doc/ to Documentation/ in this PR. The wiki would then host the archived version of latest HTML docs. Does that sound correct? Or should we go about this another way? My intention is that with this PR, the new docs become the official docs and any other change which impacts documentation will already be done over these (and not HTMLs), thus the idea of removing them.

The docs on the wiki are for the latest release and it is a manual process to update them.  The CI creates a minified inlined HTML file so that the wiki can render it, but it does not update anything.  So short of it is that we can drop the doc CI step that already existed and add the one that exists in this PR that generates the HTML files as Artifacts.   As I said earlier I will be happy to do the CI bit that connects this all to the website release.

**Comment by v01d** [comment]
> > I wanted to check with you (maybe @btashton ?): I understand that the latest version of HTML docs is always on the Wiki, built from the repo, right? If so, I would include the deletion of all HTMLs and renaming of doc/ to Documentation/ in this PR. The wiki would then host the archived version of latest HTML docs. Does that sound correct? Or should we go about this another way? My intention is that with this PR, the new docs become the official docs and any other change which impacts documentation will already be done over these (and not HTMLs), thus the idea of removing them.
> 
> The docs on the wiki are for the latest release and it is a manual process to update them. The CI creates a minified inlined HTML file so that the wiki can render it, but it does not update anything. So short of it is that we can drop the doc CI step that already existed and add the one that exists in this PR that generates the HTML files as Artifacts. As I said earlier I will be happy to do the CI bit that connects this all to the website release.

I see. But then if I drop the doc workflow, there will be no more artifacts generated for old docs (only for new ones) once this is merged. If the latest version is not on the wiki, maybe we should grab latest artifact from master for old docs y use that to update the wiki (or maybe as in the website itself, so that we can link to the archived version of the docs there). If that's what you had in mind, I will then remove the doc workflow, and leave the sphinx-docs (only building and creating the artifiact, removing the GH pages part).

**Comment by btashton** [comment]
> I see. But then if I drop the doc workflow, there will be no more artifacts generated for old docs (only for new ones) once this is merged. If the latest version is not on the wiki, maybe we should grab latest artifact from master for old docs y use that to update the wiki (or maybe as in the website itself, so that we can link to the archived version of the docs there). If that's what you had in mind, I will then remove the doc workflow, and leave the sphinx-docs (only building and creating the artifiact, removing the GH pages part).

There is no need.  Only the docs for from the latest __released__ version are there (currently the 9.1.0 tag).  Master is never represented in the official docs.  For the next release we can just point at these docs.

**Comment by adamfeuer** [comment]
@v01d I will do a PR to this branch Saturday or Sunday with the hyperlinked list of supported boards.

**Comment by v01d** [comment]
It appears checkpatch is confused by the rename, it attempts to get files from the path before the rename. Also, it appears to be checking .rst files using nxstyle.

**Comment by adamfeuer** [comment]
@v01d You can feed checkpatch a list of files to check explicitly. Something like this (filtering for the files you want):

```
git diff --name-only master | egrep "\.c|\.h" | xargs echo | xargs ./tools/checkpatch.sh -f | less
```

**Comment by v01d** [comment]
> @v01d You can feed checkpatch a list of files to check explicitly. Something like this (filtering for the files you want):
> 
> ```
> git diff --name-only master | egrep "\.c|\.h" | xargs echo | xargs ./tools/checkpatch.sh -f | less
> ```

I meant the CI is failing due to this

**Comment by adamfeuer** [comment]
@v01d Re: CI failing, I guess we have to ignore for now, in the future we can improve the way checkpatch gets its list of files...

**Comment by adamfeuer** [comment]
@v01d I got hyperlinks working for Supported Boards by CPU core. I'll be able to get the links for boards by manufacturer tomorrow. Code is here: https://github.com/starcat-io/incubator-nuttx/tree/feature/docs-supported-boards-hyperlinks

Will do a PR when I get it done.

**Comment by v01d** [comment]
> @v01d I got hyperlinks working for Supported Boards by CPU core. I'll be able to get the links for boards by manufacturer tomorrow. Code is here: https://github.com/starcat-io/incubator-nuttx/tree/feature/docs-supported-boards-hyperlinks
> 
> Will do a PR when I get it done.

Great, I've been adding some finishing touches to prepare this PR, so with your change this should be ready.

**Comment by adamfeuer** [comment]
@v01d Got the hyperlinks and most of the table formatting done– I just need to clean up a few things, and will do a PR later today.

**Comment by adamfeuer** [comment]
@v01d Hey, it looks like the [sphinx build passed](https://github.com/apache/incubator-nuttx/pull/1501/checks?check_run_id=991820110), but the [supported platforms page](https://v01d.github.io/incubator-nuttx/docs/introduction/supported_platforms.html) is still showing the old nonworking links in the table... am I missing something? Does the html get pushed some other way?

**Comment by v01d** [comment]
> @v01d Hey, it looks like the [sphinx build passed](https://github.com/apache/incubator-nuttx/pull/1501/checks?check_run_id=991820110), but the [supported platforms page](https://v01d.github.io/incubator-nuttx/docs/introduction/supported_platforms.html) is still showing the old nonworking links in the table... am I missing something? Does the html get pushed some other way?

I disabled the publishing to GH pages a few commits ago in preparation for the merge. I will make one more (manual) update of GH pages before requesting the merge so that others can see the updated result.

In the future we should consider previewing doc PRs in someway.

**Comment by adamfeuer** [comment]
@v01d Great, thank you. Yes, it would be great to have PRs create a doc build that can be looked at before publishing to the main site.

**Comment by btashton** [comment]
You can see the result. The generated HTML is attached to the build as an artifact.

**Comment by v01d** [comment]
> You can see the result. The generated HTML is attached to the build as an artifact.

I think it is a bit cumbersome to have to go find the artifact link, download the complete tar, extract somewhere and open the index. If we could later enable GH pages here we could try to setup a per-PR deployment. The tricky part is deleting the result after the merge. Also GH pages is based around modifying a branch in the repo which makes me cringe a bit. 

Anyway, documentation changes should be readable enough by looking at the RST, so I think we can live without it for now.

**Comment by davids5** [comment]
> You can see the result. The generated HTML is attached to the build as an artifact.

I am trying to catch-up on the changes here.  I did not see any HTML files in the artifacts, Just .rst files

image

Where would I preview the new docs?

**Comment by adamfeuer** [comment]
@davids5 You can see an old build of the new docs here: https://v01d.github.io/incubator-nuttx/docs/index.html

@v01d will do a manual update with the latest changes soon. This was being updated by CI, but it was disabled in preparation for a merge (if this is accepted). If accepted, we'll then do another PR to add CI to the Apache incubator-nuttx so we can have CI-built docs.

**Comment by v01d** [comment]
I will take care of a few tiny things and the undraft this. I will also update the PR description to reflect the current status and what remains to be done in follow up PRs

**Comment by v01d** [comment]
@davids5 The artifacts are the result of the "Build Documentation" job. You should click on "details" next to it and you will see an "artifacts" link for that job which contains the HTML docs.

**Comment by davids5** [comment]
@v01d @adamfeuer  - Thank you, i was looking in the wrong flow. On first blush this looks very nice. I will dig into in detail later.

**Comment by v01d** [comment]
Ok, I have edited the PR description and I'm now undrafting.

**Comment by adamfeuer** [comment]
@v01d @btashton If this PR is accepted, if it's wanted, I would like to contribute the docs I wrote (with @btashton's contributions) in the [NuttX Companion](https://nuttx-companion.readthedocs.io/en/latest/). This includes a Quickstart guide, detailed instructions for installing and running, and some information on writing drivers. I will then deprecate and remove that Guide.

I think the Quickstart and Detailed Instructions are a start on @w8jcik's request for opinionated documentation to help beginners, and I think we can expand the instructions to include several flavors of popular boards (STM32, i.MX RT, Arduino, etc.).

**Comment by v01d** [comment]
Definitely, that is a very important part of the documentation since new users will expect a quick way to get into NuttX.
I think that eventually we could define a "signature board" (or maybe a couple) which has enough features to demonstrate various NuttX abilities and also have this maintained well so that this quickstart revolves around a easy to use and working use case.

**Comment by Ouss4** [comment]
Looking good! Thank you for your work guys!

I've seen that there is an entry for the workflow.  I was waiting to wrap up the N.O.W to try and revive the topic.
Just a simple question: should we migrate what we have on confluence to the new documentation or a small TL;DR; version is more appropriate?

**Comment by v01d** [comment]
Regarding the workflow section, sorry, I meant to comment about it. Please don't take it as if I'm defining the workflow implicitly by myself. I merely described what already happens without stating that this is the definite workflow.
Better to have that in place until the definitive workflow is finalized.

**Comment by adamfeuer** [comment]
@Ouss4 @v01d Re: workflow, [this page](https://nuttx-companion.readthedocs.io/en/latest/user/making-changes.html) is also not meant to be definitive, but has some concrete tips for one way to contribute to NuttX, if this PR is accepted, I will contribute it next. We could link to the wiki for people who want to go deeper.

**Comment by Ouss4** [comment]
We already have this one: https://cwiki.apache.org/confluence/display/NUTTX/Code+Contribution+Workflow
It's still not 100% finished but the Github/Git part of contributing is pretty much done.
There have been talks about extracting just that part to make a quick reference document.

I was just asking if it's planned to include that in the new documentation.

**Comment by v01d** [comment]
> There have been talks about extracting just that part to make a quick reference document.

That was mostly my intention with this preliminary workflow document: give potential contributors quick and easy to read instructions. In some projects there's a distinction between user and dev docs. With the same spirit we could move most of the content of the final workflow document intended for maintainers to a separate section and leave one with a more friendly one.
 
> I was just asking if it's planned to include that in the new documentation.

Yes, as I mentioned, I wrote something considering a new contributor reading the docs so that we have that until the internal workflow document is finalized. I would then put this document on the docs site.

**Comment by adamfeuer** [comment]
@Ouss4 There's also clearly a lot of improvements we can make to the docs– I think we want to also work to keep this PR as small as possible, while addressing any needed issues. We will be doing follow-up PRs to keep improving the docs, but ideally in smaller chunks.

**Comment by Ouss4** [comment]
@adamfeuer @v01d 
I don't object.  Please do not let this discussion block merging.  I took a tour, it looks good to me.

**Comment by btashton** [comment]
One thing I noticed is the code files are missing Apache headers.

**Comment by v01d** [comment]
> One thing I noticed is the code files are missing Apache headers.

Which files you mean? `conf.py`?

**Comment by btashton** [comment]
> > One thing I noticed is the code files are missing Apache headers.
> 
> Which files you mean? `conf.py`?
> 
> 

Yes that as well as the CSS and the possibility the HTML template.

**Comment by v01d** [comment]
> > > One thing I noticed is the code files are missing Apache headers.
> > 
> > 
> > Which files you mean? `conf.py`?
> 
> Yes that as well as the Makefile, CSS and the possibility the HTML template.

I will add the header to those then

**Comment by hartmannathan** [comment]
> I've seen that there is an entry for the workflow. I was waiting to wrap up the N.O.W to try and revive the topic.
> Just a simple question: should we migrate what we have on confluence to the new documentation or a small TL;DR; version is more appropriate?

I think a user friendly simple doc is good for newcomers who just need an introduction.

The workflow doc in our Wiki is more geared to the project's maintainers. The user friendly one can link to the wiki for those who want all the details.

**Comment by davids5** [comment]
Small typo https://v01d.github.io/incubator-nuttx/docs/contributing/workflow.html checkpath ->checkpacth (I hate the name, They are PRs! not patches but it should be correct)

**Comment by v01d** [comment]
> Small typo https://v01d.github.io/incubator-nuttx/docs/contributing/workflow.html checkpath ->checkpacth (I hate the name, They are PRs! not patches but it should be correct)

Thanks, fixed. I think "patch" is due to git nomenclature.

I will backport the linked PR when it gets merged.

**Comment by btashton** [comment]
> > You can see the result. The generated HTML is attached to the build as an artifact.
> 
> I am trying to catch-up on the changes here. I did not see any HTML files in the artifacts, Just .rst files
> 
> Where would I preview the new docs?

@davids5  Not sure how you got the files, but you can download the bundle from the "Artifacts" link here
Screenshot from 2020-08-24 10-19-43

and then you should see the rendered HTML files where you can just select index.html or in my case I run a simple webserver against the folder `python3 -m http.server --directory /tmp/`
Screenshot from 2020-08-24 10-20-48

**Comment by btashton** [comment]
This has been idle for a few days and there were no objections so I am going to merge this in and then create  PR this week to propose how we render the docs alongside the website.

Thanks for all the hard work making these changes.

**Comment by v01d** [comment]
Thanks brennan!
I will create an issue soon to outline the next tasks I have in mind to continue work on documentation.
Let me know if you need any help with the CI. I left some foundations for handling multiple versions.

**Comment by adamfeuer** [comment]
@btashton Thank you. This is great.
@v01d Thanks for leading the charge! 🙂

**Pull request merged**
