### PR TITLE
Revert "macOS support for sim"

### PR DESCRIPTION
**Pull request by jerpelea**
Reverts apache/incubator-nuttx#179

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
How about let @yamt provide the new PR instead reverting the whole patchset?

**Comment by patacongo** [comment]
This should be closed, right?  It was merged prematurely.  For complex changes.. ESPECIALLY changes involving the build system, we must wait for comments.  Committing build system change blindly is almost always fatal.

We are waiting for the updates from the author now, right?  So this should be closed.

**Comment by jerpelea** [comment]
I am sorry for accidentally merging this one

**Comment by jerpelea** [comment]
we can revert it and wait to get the fixes or we can merge my revert and wait to a new PR

**Comment by patacongo** [comment]
Don't worry about it.  We appreciate all of your help.  We all sometimes make the decision that we would later do differently.  I think I have done many like that and I usually hear about it too.

I think it would be simpler to just add the fixes rather than reverting and reapplying the whole thing, But we need make sure that everyone understands how we are going to proceed and make sure that fixes will actually happen.

**Comment by patacongo** [comment]
"we can revert it and wait to get the fixes or we can merge my revert and wait to a new PR"--  less turmoil if we can wait.  I propose that if nothing happens in 24 hours, we go ahead and revert.  I can do the merge for you then.

**Comment by Ouss4** [comment]
@jerpelea Should the `revert-179-osx-sim` branch be deleted as well?

**Comment by jerpelea** [comment]
done !
thanks for reminding me

**Comment by TA1DB** [comment]
[I have an issue explained here ](https://github.com/apache/incubator-nuttx/pull/1817#issuecomment-716140269)

**Pull request closed without merging**
