### PR TITLE
libs:machine:rv64:add missing logic for elf rel-type R_RISCV_LO12_S

### PR DESCRIPTION
**Pull request by hotislandn**
Signed-off-by: hotislandn <hotislandn@hotmail.com>

This is a patch for RV64 elf relcateadd handler which is copied from RV32.

.

### CODE REVIEW

**Comment by hotislandn** [comment]
BTW，this file is almost the same for rv32 and rv64, how about merging them into one, and put into a common folder under risc-v?

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
> BTW，this file is almost the same for rv32 and rv64, how about merging them into one, and put into a common folder under risc-v?

Yes, it is in the plan, please see: https://github.com/apache/incubator-nuttx/issues/2593, https://github.com/apache/incubator-nuttx/issues/2594 and https://github.com/apache/incubator-nuttx/pull/2822.
Could you provide a PR to merge llibs/libc/machine/risc-v?

**Comment by hotislandn** [comment]
Sure. I would like to give it a try.

**Pull request merged**
