### PR TITLE
Lint Python code for syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
```
./tools/discover.py:73:11: E999 SyntaxError: invalid syntax
    print 'Sending discover...'
          ^
./tools/xmlrpc_test.py:27:15: E999 SyntaxError: invalid syntax
        print 'Usage: %s <ip address>' % sys.argv[0]
              ^
2     E999 SyntaxError: invalid syntax
2
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ is raised which will halt/crash the script on the user.

### CODE REVIEW

**Comment by btashton** [comment]
The GitHub super linter already can support this which we have enabled. You just update the config for that.

It supports flake8 although to be honest I would be fine just having it use Black and then we have.  Easy code style for python that can be auto formated. 
https://github.com/github/super-linter

**Comment by cclauss** [comment]
That linter might be super but it is also super slow.  In its 5 minute runtime it should be able to lint all programming languages known to man.

The test I added takes 5 second and actually finds code that would crash on the user.  `black` if properly configured should should be unable to parse these two files.

**Comment by btashton** [comment]
It already includes flake8 black etc... We already have it for yaml linting why not just enable it for python as well?

**Comment by xiaoxiang781216** [comment]
@cclauss could you squach your patches into one?

**Comment by cclauss** [comment]
I do not usually squash commits of PRs that have failing tests.

**Comment by xiaoxiang781216** [comment]
But your second patch revert the first patch, and the third patch revert the partial second patch. It doesn't make sense to left your intermediate in the public git history.

**Comment by xiaoxiang781216** [comment]
And since you enable the additional check, please fix the error reported by Lint.

**Pull request closed without merging**
