### PR TITLE
Rename CONFIG_LIB_BOARDCTL to CONFIG_BOARDCTL

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
since boardctl isn't a libc feature. Need mrege with https://github.com/apache/incubator-nuttx-apps/pull/820

## Impact
No real function change

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@gustavonihei this patch can't pass CI because it depends on apache/incubator-nuttx-apps#820. We have to merge both together after you finish review and fix the potential issue after that.

**Comment by gustavonihei** [comment]
I agree with the change. As mentioned by @Ouss4 in https://github.com/apache/incubator-nuttx/pull/4267, we need to document these breaking changes for the next release.

**Comment by xiaoxiang781216** [comment]
@gustavonihei the release note update here:
https://cwiki.apache.org/confluence/display/NUTTX/NuttX+10.2#changes-to-kconfig

**Review by gustavonihei — APPROVED** [review]
LGTM

**Comment by Ouss4** [comment]
@xiaoxiang781216 with #4267 merged, there are more conflicts here.  Please take a look.

**Comment by xiaoxiang781216** [comment]
Done.

**Comment by Ouss4** [comment]
@xiaoxiang781216 apache/incubator-nuttx-apps#820 is merged, can you take a look at the failures here?  It looks like some defconfigs need to be refreshed.

**Comment by xiaoxiang781216** [comment]
Yes, I am working on this PR.

**Pull request merged**
