### PR TITLE
[BACKPORT #2265/#2267/#2281] sim: Remove cxxtest specifial Make.defs

### LINKED ISSUE #2086: sim:cxxtest Build Broken
The build is broken for `sim:cxxtest`

```
make[2]: Leaving directory '/home/bashton/nuttx/apache/incubator-nuttx/boards/sim/sim/sim/src'
CPP:  nuttx-names.in-> nuttx-names.dat
cc: warning: nuttx-names.in: linker input file unused because linking not done
LD:  nuttx
ld: cannot open linker script file nuttx.ld: No such file or directory
make[1]: *** [Makefile:295: nuttx] Error 1
make[1]: Leaving directory '/home/bashton/nuttx/apache/incubator-nuttx/arch/sim/src'
make: *** [tools/Makefile.unix:415: nuttx] Error 2
```

Also the NOTES section in readme is no long accurate for this target and should be updated to correctly represent the requirements of this.

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Backports #2265 #2267 #2281 

## Impact
Fixes #2086 sim:cxxtest build failure

## Testing
sim:cxxtesting

### CODE REVIEW

**Comment by btashton** [comment]
@xiaoxiang781216 I think there is something else necessary for this backport besides what was in the PR:

```
cxxtest_main.cxx: In function ‘void test_rtti()’:
cxxtest_main.cxx:193:15: error: ‘dynamic_cast’ not permitted with ‘-fno-rtti’
  193 |   Extend *t = dynamic_cast<Extend *>(a);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
cxxtest_main.cxx:196:7: error: ‘dynamic_cast’ not permitted with ‘-fno-rtti’
  196 |   t = dynamic_cast<Extend *>(b);
```

**Comment by xiaoxiang781216** [comment]
@btashton please cherry-pick these patches: https://github.com/apache/incubator-nuttx/pull/2267, https://github.com/apache/incubator-nuttx/pull/2265.

**Comment by btashton** [comment]
> @btashton please cherry-pick these patches: https://github.com/apache/incubator-nuttx/pull/2267, https://github.com/apache/incubator-nuttx/pull/2265.

Thanks I'll update it in a bit.

**Comment by btashton** [comment]
@xiaoxiang781216 I have added all three patches and tested it locally. Thank you.

**Review by xiaoxiang781216 — COMMENTED** [review]
LGTM.

**Pull request merged**
