### PR TITLE
boards: sabre-6quad: Add CONFIG_DEBUG_FULLOPT=y to knsh/defconfig

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- I noticed that undefined instruction happens with getprime and gcc-10.3.1
- Actually, the issue does not happen with gcc-9.3.1
- This is a tentative solution to avoid the issue

## Impact

- sabre-6quad:knsh only

## Testing

- Tested with hello/getprime

### CODE REVIEW

**Comment by masayuki2009** [comment]
See https://github.com/apache/incubator-nuttx/pull/5645 as well.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
I confirmed that https://github.com/apache/incubator-nuttx/pull/5734 fixes the sabref-6quad:knsh + gcc-10.3 issue.

**Comment by pkarashchenko** [comment]
Should we revert this change?

**Comment by masayuki2009** [comment]
> Should we revert this change?

@pkarashchenko 
It's OK to keep the current configuration because `CONFIG_DEBUG_FULLOPT=y` is set in most of defconfigs.

**Pull request merged**
