### PR TITLE
MPFS emmcsd

### PR DESCRIPTION
**Pull request by jrosberg**
## Summary
mpfs: add emmcsd driver

## Impact
This adds the emmcsd driver for the Polarfire Icicle kit.

## Testing
The driver has been tested with several SD-cards, such as:

- Kingston 32 GB SDS2 Canvas Select Plus
- Kingston MicroSD Canvas Select Plus
- Sandisk Extreme PRO 32 GB
- Transcend 8 GB MicroSD

The internal eMMC hasn't been tested comprehensively.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by acassis** [comment]
@jrosberg it is failing because this warning:
```
Building NuttX...
In file included from mmcsd/mmcsd_spi.c:39:
mmcsd/mmcsd_spi.c: In function 'mmcsd_read':
Error: mmcsd/mmcsd_spi.c:1300:9: error: format '%d' expects argument of type 'int', but argument 3 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
   finfo("Read %d bytes:\n", nbytes);
         ^~~~~~~~~~~~~~~~~~  ~~~~~~
```

**Comment by jrosberg** [comment]
@acassis Do you want me to add fix for that on this PR: %d -> %zu
Is it better to do own PR for that?

**Comment by acassis** [comment]
> @acassis Do you want me to add fix for that on this PR: %d -> %zu
> Is it better to do own PR for that?

Yes, please fix it.

**Comment by jrosberg** [comment]
@acassis  done. note that the problematic file was not part or original patch.

**Pull request merged**
