### PR TITLE
sem:remove sem default protocl

### PR DESCRIPTION
**Pull request by anjiahao1**
## Summary
[step 1](https://github.com/apache/incubator-nuttx/pull/5070)
[step 2](https://github.com/apache/incubator-nuttx/pull/6965)
 this is step 3, remove all defult `nxsem_set_protocol` with `SEM_PRIO_NONE`,and then add it in `nxsem_init` & `nxmutex_init`

## Impact
nothing
## Testing
ostest

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anjiahao1** [comment]
> @anjiahao1 A deadlock happened with `qemu-intel64:ostest `
> 
> ```
> + /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-x86_64 -cpu host -enable-kvm -m 256M -cdrom boot.iso -nographic -serial mon:stdio
> SeaBIOS (version rel-1.16.0-0-gd239552ce722-prebuilt.qemu.org)
> 
> 
> iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+0FF91160+0FEF1160 CA00
> 
> 
> 
> Booting from Hard Disk...
> Boot failed: could not read the boot disk
> 
> Booting from Floppy...
> Boot failed: could not read the boot disk
> 
> Booting from DVD/CD...
> stdio_test: write fd=1
> stdio_test: Standard I/O Check: printf
> stdio_test: write fd=2
> ...
> priority_inheritance: Waiting...
> lowpri_thread-1: Started
> lowpri_thread-1: initial priority: 1
> lowpri_thread-1: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> lowpri_thread-2: Started
> lowpri_thread-2: initial priority: 1
> lowpri_thread-2: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> lowpri_thread-3: Started
> lowpri_thread-3: initial priority: 1
> lowpri_thread-3: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> lowpri_thread-1: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> lowpri_thread-2: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> lowpri_thread-3: Waiting for the midle pri task to run
>     g_middlestate:  0
>     g_highstate[0]: 0
>     I still have a count on the semaphore
> priority_inheritance: Starting medpri_thread at 99
> priority_inheritance: Set medpri_thread priority to 99
> priority_inheritance: Waiting...
> medpri_thread: Started ... I won't let go of the CPU!
> priority_inheritance: Starting highpri_thread-1 (of 1) at 255
> priority_inheritance: Set highpri_thread-1 priority to 255
> highpri_thread-1: Started
> priority_inheritance: Waiting for highpri_thread-1 to complete
> highpri_thread-1: Calling sem_wait()
> Traceback (most recent call last):
> ```

ok,i check it now

**Comment by anjiahao1** [comment]
@masayuki2009 https://github.com/apache/incubator-nuttx-apps/pull/1358 this is fix patch

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 sorry, but where the sem default behaviour is changed?

**Comment by masayuki2009** [comment]
>@masayuki2009 https://github.com/apache/incubator-nuttx-apps/pull/1358 this is fix patch

@anjiahao1 
Please update the impact in the summary.

**Comment by xiaoxiang781216** [comment]
let move this patch to the pr#5070

**Comment by davids5** [comment]
@anjiahao1 Is there documentation added to the docs for this change documenting the new mutex and sem symantics and usage?

**Comment by anjiahao1** [comment]
use https://github.com/apache/incubator-nuttx/pull/5070 to submit  patch,so close current PR

**Pull request closed without merging**
