### PR TITLE
Don't use __attribute__ in source code directly

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

- Replace all __attribute__((aligned(x)) with aligned_data(x)
- Replace all __attribute__((section(x)) with locate_data(x)

## Impact

Same as before after macro expansion

## Testing

Pass the CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Please the nxstyle warning due the heavy maco used in include/nuttx/tree.h:
````
include/nuttx/tree.h:317:23: error: Multiple data definitions
include/nuttx/tree.h:330:14: error: Garbage follows right bracket
include/nuttx/tree.h:338:18: error: Garbage follows right bracket
include/nuttx/tree.h:339:12: error: Garbage follows right bracket
include/nuttx/tree.h:342:10: error: Garbage follows right bracket
include/nuttx/tree.h:349:14: error: Garbage follows right bracket
include/nuttx/tree.h:357:18: error: Garbage follows right bracket
include/nuttx/tree.h:358:14: error: Garbage follows right bracket
include/nuttx/tree.h:361:10: error: Garbage follows right bracket
include/nuttx/tree.h:362:6: error: Garbage follows right bracket
```

**Review by davids5 — COMMENTED** [review]
@xiaoxiang781216 - The best way to verify this is 100% correct it to compare the builds. I did see 2-lines of assignments deleted.  Did you intend to mix that in with this PR?

**Comment by xiaoxiang781216** [comment]
The change is intentional, you can review it separately here:
https://github.com/apache/incubator-nuttx/pull/4238/commits/14582e1fc4afb08039e248a0ea0cfb8e1751d70d

**Comment by xiaoxiang781216** [comment]
Rebase to fix the conflict, no really change.

**Comment by gustavonihei** [comment]
> The change is intentional, you can review it separately here:
> [14582e1](https://github.com/apache/incubator-nuttx/commit/14582e1fc4afb08039e248a0ea0cfb8e1751d70d)

The change is not related to this PR, so I think it should be left out.
This function is probably not built by any CI configuration, because this `USB_DmaDesc` symbol seems to come from the vendor's BSP. Another evidence is the `epph` on the below line, which contains a typo and should be `epphy`.

If we simply remove that single line it will probably make someone's life more difficult to track an eventual bug on this driver.

**Comment by xiaoxiang781216** [comment]
Ok, I drop that patch from PR.

**Review by gustavonihei — APPROVED** [review]
LGTM. Let's ignore those nxstyle errors.

**Pull request merged**
