### PR TITLE
boards: Remove the duplicated prototype of CONFIG_INIT_ENTRYPOINT

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Remove the duplication

## Impact
code refactor only

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
```
Error: nor_main.c:78:5: error: conflicting types for 'nor_main'
   78 | int nor_main(int argc, char *argv)
      |     ^~~~~~~~
In file included from nor_main.c:25:
/github/workspace/sources/nuttx/include/sys/types.h:318:5: note: previous declaration of 'nor_main' was here
  318 | int CONFIG_INIT_ENTRYPOINT(int argc, FAR char *argv[]);
```

**Comment by xiaoxiang781216** [comment]
> ```
> Error: nor_main.c:78:5: error: conflicting types for 'nor_main'
>    78 | int nor_main(int argc, char *argv)
>       |     ^~~~~~~~
> In file included from nor_main.c:25:
> /github/workspace/sources/nuttx/include/sys/types.h:318:5: note: previous declaration of 'nor_main' was here
>   318 | int CONFIG_INIT_ENTRYPOINT(int argc, FAR char *argv[]);
> ```

Fixed.

**Review by pkarashchenko — APPROVED** [review]
LGTM!

**Comment by pkarashchenko** [comment]
Same with `dram_main.c:76:5: error: conflicting types for 'dram_main'`

**Comment by xiaoxiang781216** [comment]
Fix all.

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
