### PR TITLE
arch/arm/stm32f7: fix cache invalidation issue in Ethernet RX

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
Fix cache invalidation issue in Ethernet RX for stm32f7

## Impact
Reception of Ethernet packets should be improved

## Testing
Pass CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by davids5 — APPROVED** [review]
@pkarashchenko Yikes! Good Catch!

**Comment by lukegluke** [comment]
@pkarashchenko Nice, thanks!

**Comment by slorquet** [comment]
Just in case, could a similar issue apply to stm32h7?

**Comment by slorquet** [comment]
like, here:
https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/stm32h7/stm32_ethernet.c#L1826

Can you apply a patch since you are "owning" the issue? thanks. I have a stm32h7 board, if you have a regression test I can try, I will do it.

**Comment by lukegluke** [comment]
> Just in case, could a similar issue apply to stm32h7?

No, it is ok in stm32h7, there is already full address (start pointer + offset) is correctly used in function, while for stm32f7 only the offset was passed wrongly before.

**Comment by slorquet** [comment]
Thank you for checking!

**Pull request merged**
