### PR TITLE
Makefile: move INCDIROPT to common place

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by patacongo** [comment]
This change effects systems using Cygwin under windows with Windos native toolchain.  In that case WINTOOLS will be defined and the -2 option must be used.  Has that been verified.  This change should not be merged if that test case has not been verified.

It appears to me that the -w was only removed, breaking all such builds.  This is the build configuration that I use Windows Cygwin plus Windows native toolchan and this looks to me like it would break my build.

I think it should not be merged.

**Comment by xiaoxiang781216** [comment]
> This change effects systems using Cygwin under windows with Windos native toolchain. In that case WINTOOLS will be defined and the -2 option must be used. Has that been verified. This change should not be merged if that test case has not been verified.
>

Yes, we need improve github/apache to verify the patch for windows cygwin/native/msys2.
 
> It appears to me that the -w was only removed, breaking all such builds. This is the build configuration that I use Windows Cygwin plus Windows native toolchan and this looks to me like it would break my build.
> 

-w doesn't lose, I set the -w in tools/Config.mk 

https://github.com/apache/incubator-nuttx/pull/625/files#diff-043fcc977f97645d33de793ab09bd262R99

> I think it should not be merged.

**Comment by patacongo** [comment]
Should there be a companion change to incubator-nuttx-apps?

**Comment by patacongo** [comment]
No, it does not appear to work.  My system no longer builds.  Looking into it.

**Comment by xiaoxiang781216** [comment]
> Should there be a companion change to incubator-nuttx-apps?

Yes, here: https://github.com/apache/incubator-nuttx-apps/pull/141

**Comment by patacongo** [comment]
The same error occurs during compilation:

    CC:  binfmt_execmodule.c
    binfmt_execmodule.c:54:10: fatal error: sched/sched.h: No such file or directory
     #include "sched/sched.h"
              ^~~~~~~~~~~~~~~
    compilation terminated.

**Comment by xiaoxiang781216** [comment]
> > Should there be a companion change to incubator-nuttx-apps?
> 
> Yes, here: [apache/incubator-nuttx-apps#141](https://github.com/apache/incubator-nuttx-apps/pull/141)



> No, it does not appear to work. My system no longer builds. Looking into it.

It's time to create wndows VM to very all PR for cygwin/native/msys.
@liuguo09 could you work with @patacongo to setup Windows CI environment?

**Comment by patacongo** [comment]
Whatever binfmt_execmodule.c needs it should not include sched/sched.h directly.  the necessary things need to be moved into include/nuttx and binfmt must not include "sched/sched.h".

It looks like I did this in commit d798dd37a75 .  that should be fixed.

**Comment by patacongo** [comment]
> It looks like I did this in commit [d798dd3](https://github.com/apache/incubator-nuttx/commit/d798dd37a75c3dd89b66aef2be27e130d574bbf5) . that should be fixed. Wow... that was back in 2014.

So that change is not the direct, root cause of the problem.  Rather some change in the include path has broken that build.  Let me check.  yes.  I think this change broke the build.

    make -C binfmt TOPDIR="/cygdrive/d/Spuda/Documents/projects/nuttx/master/incubator_nuttx" libbinfmt.a KERNEL=y EXTRADEFINES=-D__KERNEL__
    make[1]: Entering directory '/cygdrive/d/Spuda/Documents/projects/nuttx/master/incubator_nuttx/binfmt'
    CC:  binfmt_execmodule.c
    arm-none-eabi-gcc -c -fno-builtin -funwind-tables -Wall -Wstrict-prototypes -Wshadow -Wundef -Os -fno-strict-aliasing -fomit-frame-pointer -fno-strength-reduce -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -I. -isystem "D:\Spuda\Documents\projects\nuttx\master\incubator_nuttx\include"  -D__KERNEL__ -pipe -I "/cygdrive/d/Spuda/Documents/projects/nuttx/master/incubator_nuttx/sched"   binfmt_execmodule.c -o  binfmt_execmodule.o
    binfmt_execmodule.c:54:10: fatal error: sched/sched.h: No such file or directory
     #include "sched/sched.h"
              ^~~~~~~~~~~~~~~
    compilation terminated.


This is the argumentthat caused the problem:

    -I "/cygdrive/d/Spuda/Documents/projects/nuttx/master/incubator_nuttx/sched"

That is a Cygwin path, not a Windows path.  The tool requires a Windows path (i.e., with the -w option).

**Comment by patacongo** [comment]
I think that the problem is in binfmt/Makefile.

     40 CFLAGS += ${shell $(INCDIR) "$(CC)" "$(TOPDIR)$(DELIM)sched"}

**Comment by patacongo** [comment]
Should I revert the change?  Or can you recommend a fix?

**Comment by patacongo** [comment]
[I know the problem.  WINTOOL is not available to Config.mk.  It is included by Make.defs BEFORE WINTOOL is defined.  This must be reverted.

**Comment by xiaoxiang781216** [comment]
> Config

Ok, I will find a method ensure WINTOOL get define before include Config.mk

**Comment by patacongo** [comment]
I fixed the issues with binfmt/binfmt_execmodule.c with PR #632 and I cannot find any other location with this exact failure setup,  This does not fix the logical, ordering problem in general so I don't think recommends the PR.

The best fix would be to make WINTOOL into a configuration option CONFIG_BUILD_WINTOOL that is set automatically if a Windows native toolcahin is selected and if the platform is Cygwin.  Thent he definition with exist prior to the first inclusion of Config.mk.

Currently WINTOOL is set in the Toolchain.defs file.  It would affect several Kconfig files to make it a pre-existing configuration setting.

**Pull request merged**
