### PR TITLE
vpnkit: Make this less verbose on connection errors

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by yamt** [comment]
check failure looks unrelated to this change.

> /bin/sh: 1: /__w/incubator-nuttx/incubator-nuttx/nuttx/tools/mkdeps: not found

**Comment by xiaoxiang781216** [comment]
> check failure looks unrelated to this change.
> 
> > /bin/sh: 1: /__w/incubator-nuttx/incubator-nuttx/nuttx/tools/mkdeps: not found

@liuguo09 and me is looking this issue now, please wait a moment.

**Comment by yamt** [comment]
@xiaoxiang781216 @liuguo09 thank you!

**Comment by xiaoxiang781216** [comment]
@yamt please rebase PR

**Comment by yamt** [comment]
now failing for other reasons.

> arm-none-eabi-ld: chardev.o: file not recognized: file truncated

@xiaoxiang781216 i guess it's related to your recent changes in apps.

**Comment by xiaoxiang781216** [comment]
> now failing for other reasons.
> 
> > arm-none-eabi-ld: chardev.o: file not recognized: file truncated
> 
> @xiaoxiang781216 i guess it's related to your recent changes in apps.

The parallel build issue exist for a long time(maybe never work before).
This PR should fix the major parallel build issue:
https://github.com/apache/incubator-nuttx-apps/pull/138
apps/Makefile still has one place with the similar problem, I will provide a patch before the end of week.

**Pull request merged**
