### PR TITLE
spresense elf support 

### PR DESCRIPTION
**Pull request by masayuki2009**
### Summary

- Added elf configuration for Sony Spresense board

### Impact

- This PR does not affects other configurations

### Testing

- To test this configuration, you need to apply another PR to apps to avoid crash in task test due to stack corruption.

### CODE REVIEW

**Comment by yamt** [comment]
can you consider to add a brief explanation of the purpose of the new config, maybe in boards/arm/cxd56xx/spresense/README.txt?

**Comment by masayuki2009** [comment]
> can you consider to add a brief explanation of the purpose of the new config, 
>maybe in boards/arm/cxd56xx/spresense/README.txt?

I'll add comments to the above file and push in this PR later.

**Comment by masayuki2009** [comment]
@yamt I've just updated README.txt

**Comment by yamt** [comment]
@masayuki2009 thank you

**Pull request merged**
