### PR TITLE
RX65N Ethernet pre-check warnings resolved

### PR DESCRIPTION
**Pull request by Bhindhiya**
Resolved RX65N pre-check warnings in rx65n_eth.c

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@Bhindhiya why rx65n_eth don't support ICMPv6?

**Comment by Bhindhiya** [comment]
@xiaoxiang781216,
ICMPv6 is an integral part of IPv6 and RX65N supports IPv6 whereas hashtable indexing is not supported. So, only the hashtable indexing related code is being removed.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216,
> ICMPv6 is an integral part of IPv6 and RX65N supports IPv6 whereas hashtable indexing is not supported. So, only the hashtable indexing related code is being removed.

So you don't want to support IPv6 multicast?

**Comment by Bhindhiya** [comment]
@xiaoxiang781216 ,
The multicast packet can be filtered at Ethernet level or at IP layer. 
RX65N supports IPv6 multicast filtering only in the IP layer, not at the Ethernet level (mac layer) since RX65N hardware does not have hash mac register.
All received multicast frames are passed to IP layer and IP layer detects whether the received packet belongs to the defined multicast group.
IPv6 multicast has been tested on RX65N by configuring CONFIG_NET_MLD=y and working fine.

**Comment by xiaoxiang781216** [comment]
@Bhindhiya thanks for explanation. Let's merge it.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
