### PR TITLE
esp32: module related fixes

### PR DESCRIPTION
**Pull request by yamt**
## Summary
Fix a few issues I noticed when testing today's master.

## Impact
esp32 CONFIG_MODULE

## Testing
tested on a devkit-c board.

### CODE REVIEW

**Comment by yamt** [comment]
i guess i need to drop CONFIG_ESP32_QEMU_IMAGE from configs to pass the gate.

**Comment by Ouss4** [comment]
> i guess i need to drop CONFIG_ESP32_QEMU_IMAGE from configs to pass the gate.

Where the checks failing with CONFIG_ESP32_QEMU_IMAGE?

**Comment by yamt** [comment]
> > i guess i need to drop CONFIG_ESP32_QEMU_IMAGE from configs to pass the gate.
> 
> Were the checks failing with CONFIG_ESP32_QEMU_IMAGE?

configs with CONFIG_ESP32_QEMU_IMAGE was failing to build.
i just assumed that the CI was not providing ESPTOOL_BINDIR and haven't investigated further.

**Comment by Ouss4** [comment]
> i just assumed that the CI was not providing ESPTOOL_BINDIR and haven't investigated further.

Ah, yes, that should be the issue.

**Review by Ouss4 — APPROVED** [review]

**Pull request merged**
