### PR TITLE
Revert "Optimize syslog_write performance"

### PR DESCRIPTION
**Pull request by fjpanag**
Reverts apache/incubator-nuttx#6618

PR #6618 broke syslog, and it must be reverted (at least temporarily).

The buffer passed to `syslog_default_write()` is **NOT** NULL-terminated.  
Printing depends on the value of `buflen`.

On the other hand, `up_puts()` **needs** the string to be NULL-terminated.

As a result, syslog over-runs the buffer and prints garbage.

*The offending commit is specifically 8254ad9159d19db024ce401fa2b0f8fd1ad5bee3.*

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@fjpanag the new approach call up_nputs not up_puts, so it isn't a problem that the buffer isn't terminated by null pointer.

**Comment by fjpanag** [comment]
@xiaoxiang781216 in file `syslog_channel.c` in function `syslog_default_write()` there is a call to `up_puts()`.

**Comment by xiaoxiang781216** [comment]
@pkarashchenko @fjpanag please review patch https://github.com/apache/incubator-nuttx/pull/6661

**Comment by fjpanag** [comment]
Closing in favor of #6661.

**Pull request closed without merging**
