### PR TITLE
xtensa/esp32: Add Partition and OTA device

### PR DESCRIPTION
**Pull request by donghengqaz**
## Summary

Add Partition and OTA device.

## Impact

Add new features about ESP32's partition and OTA management.

### CODE REVIEW

**Comment by acassis** [comment]
LGTM?

**Comment by Ouss4** [comment]
@donghengqaz please fix the conflict.  Thanks.

**Comment by donghengqaz** [comment]
> @donghengqaz please fix the conflict. Thanks.

The conflict is fixed.

**Comment by acassis** [comment]
LGTM ?

**Review by Ouss4 — APPROVED** [review]

**Pull request merged**
