### PR TITLE
Re-arranged syslog fields.

### PR DESCRIPTION
**Pull request by fjpanag**
## Summary
Re-arranged fields in syslog, as discoussed in #2698.

## Impact
None.

## Testing
N/A.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Look good, but do you want to move the coloration to the first?

**Review by jerpelea — APPROVED** [review]

**Comment by fjpanag** [comment]
@xiaoxiang781216 Well... that's mostly a personal preference.  
It looks to me much nicer like this, coloring only what is relevant to priority.

But, either way, it makes no difference.  
If you insist, I can change this now.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Well... that's mostly a personal preference.
> It looks to me much nicer like this, coloring only what is relevant to priority.
> 
> But, either way, it makes no difference.
> If you insist, I can change this now.

I am fine with either.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by fjpanag** [comment]
Wow... Almost 3 hours for the MacOS build....

**Comment by btashton** [comment]
> Wow... Almost 3 hours for the MacOS build....

Yeah unfortunately we are limited by the number of runners across all the active builds so some times there is a bit of a queue. One thing that makes this worse is if you push and then pushed again shortly after both builds will still run, I have a ticket open to cancel the old run, but it's not been implemented yet.

**Comment by fjpanag** [comment]
@btashton Can we donate CPU time anyhow?

**Comment by btashton** [comment]
> @btashton Can we donate CPU time anyhow?

Unfortunately not at this time. It's something that is being actively discussed between Apache and GitHub since it a problem that other Apache projects are facing that use the service.

**Pull request merged**
