### PR TITLE
Improve proxy/stub parameter passing for variadic OS interfaces.

### PR DESCRIPTION
**Pull request by patacongo**
## Summary

In the past a very low effort interface was used:

- All parmeters were treated as though they were type uinptr_t, and
- The maximum number of parmeters (6) was passed in all cases.

The first is potentially wrong and the second is very inefficient.  This commit improves this by:

- Making tools/mksyscall.c more intelligent, and
- Extending the syntax for variadic functions.

For example, in syscall.cvs, the open() API was represened like this:

    "open","fcntl.h","","int","const char*","int","..."

In reality, open may take only a single optional argument of type mode_t which is not the same size as uintptr_t.  And there is not reason to pass 6 parameters in that case.

And this has been extended to:

    "open","fcntl.h","","int","const char*","int","...","mode_t"

The existence of the "mode_t" tells tools/mksyscall that there is at most one optional parameter and, if present, it is of type mode_t.

## Impact

This change has no effect in the FLAT build but could effect PROTECTED and KERNEL mode builds.  Those are the only build modes that require stubs and proxies.

## Testing

Verififed witih stm32f4disovery:kostest

### CODE REVIEW

**Comment by patacongo** [comment]
One nxstyle complaint is normal and expected:

    syscall/syscall_stublookup.c:425:3: warning: #include outside of 'Included Files' section

That ocurs because that is dynamically generated data in a header file at is included in order to initialize a data structure.  That data structure must like in the "Private Data" section.  So this cannot be changed.

Please ignore this particular nxstyle complaint in your decision to merge.

**Comment by Ouss4** [comment]
@xiaoxiang781216 I merged this but I figured that maybe you'd want to take a look since you and Greg had some conversation about this in an earlier PR.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I merged this but I figured that maybe you'd want to take a look since you and Greg had some conversation about this in an earlier PR.

I found several issues, will provide PR later.

**Comment by patacongo** [comment]
> I found several issues, will provide PR later.

I have plenty of free time today.  If you want to give me the list of issues, I will do the PR.

**Comment by xiaoxiang781216** [comment]
I am preparing the patch, will submit soon.

**Pull request merged**
