### PR TITLE
board/sim: Don't ignore any files under src/etc/ folder

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Since init.d is normally used to hold the initial shell scripts

## Summary
See the disussion here: https://github.com/apache/incubator-nuttx/issues/1363

### CODE REVIEW

**Comment by btashton** [comment]
Wouldn't it be better to disable all the gitignore rules in the folder that we are packing up in the binary?  Otherwise we are going to be calling out random files in the top level gitignore.

**Comment by xiaoxiang781216** [comment]
But init.d is the standard POSIX folder, do you want each board directory add "!.init.d" individually?

**Comment by btashton** [comment]
No.  we have `etc/init.d/rcS`  I am suggesting that maybe we should be doing something like `!*` in the `etc` folder.  This is a filesystem for the device I am not sure why we would apply the code base artifact rules to them.

**Comment by xiaoxiang781216** [comment]
> No. we have `etc/init.d/rcS` I am suggesting that maybe we should be doing something like `!*` in the `etc` folder. This is a filesystem for the device I am not sure why we would apply the code base artifact rules to them.

But this will package .gitignore into the generated file system image.

**Comment by xiaoxiang781216** [comment]
I move the pattern to the parent folder.

**Comment by btashton** [comment]
@xiaoxiang781216 I'll merge this in, but I am thinking of only backporting #1376 if we merge that since it will resolve the issue directly for this release while this will fix future issues.  Does that sound reasonable?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I'll merge this in, but I am thinking of only backporting #1376 if we merge that since it will resolve the issue directly for this release while this will fix future issues. Does that sound reasonable?

Yes, this patch isn't critcial as before with #1376.

**Pull request merged**
