### PR TITLE
boards/xtensa/esp32: Move the WLAN initialisation to the common directory.

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
Move the WLAN initialisation to the common directory.  Since the initialisation part is the same for all the boards.
## Impact
Shouldn't have any impact.  The same code was just refactored.
## Testing
esp32-devkitc:wapi
esp32-wrover-kit:wapi

### CODE REVIEW

**Review by v01d — APPROVED** [review]

**Comment by Ouss4** [comment]
@v01d it looks like the macOS(other) build timed out.  However, the interesting configs (wapi) were built error free.

**Comment by v01d** [comment]
Yes, it seems network error: `curl: (6) Could not resolve host: github.com`

**Comment by Ouss4** [comment]
I don't feel like we need to restart it again, I think the important configs passed.  So if you don't have any concerns let's merge it please.

**Comment by xiaoxiang781216** [comment]
The error isn't related to this patch, let's merge it to avoid the waste of build resource.

**Pull request merged**
