### PR TITLE
arch/arm/src/imxrt/imxrt_usbdev.c: Add OUT interrupt endpoint support

### PR DESCRIPTION
**Pull request by thomasactia**

### CODE REVIEW

**Comment by davids5** [comment]
@thomasactia 

There is a CI failure from the style check.  It wants the comments to be in the same column. 
 Note : Inserting a blank line resets the col position

Would you  please rebase on master (to get the latest nxstyle)  or use the following to update it locally to today's nxstyle


```
#/bin/bash
pushd tools
mv nxstyle.c last_nxstyle.c
wget https://raw.githubusercontent.com/apache/incubator-nuttx/master/tools/nxstyle.c
make -f Makefile.host
rm nxstyle.c
mv last_nxstyle.c nxstyle.c
cp nxstyle /usr/local/bin/nxstyle
popd
```

then run tools/checkpatch.sh -f <path to file> and resolve the issues,

**Comment by thomasactia** [comment]
@davids5 Do you prefer to right-shift all comments when there is one block of code for one register, or insert newlines within that block?

Original:
```
#define USBDEV_ENDPTCTRL_RXE                 (1 << 7)  /* Bit 7:  Rx endpoint enable */
#define USBDEV_ENDPTCTRL_RXR                 (1 << 6)  /* Bit 6:  Rx data toggle reset */
#define USBDEV_ENDPTCTRL_RXI                 (1 << 5)  /* Bit 5:  Rx data toggle inhibit */
#define USBDEV_ENDPTCTRL_RXT_SHIFT           (2)       /* Bits 2-3: Endpoint type */
#define USBDEV_ENDPTCTRL_RXT_MASK            (3 << USBDEV_ENDPTCTRL_RXT_SHIFT)
#  define USBDEV_ENDPTCTRL_RXT_CTRL          (0 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Control */
#  define USBDEV_ENDPTCTRL_RXT_ISOC          (1 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Isochronous */
#  define USBDEV_ENDPTCTRL_RXT_BULK          (2 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Bulk */
```

Insert spaces:
```
#define USBDEV_ENDPTCTRL_RXE                 (1 << 7)                          /* Bit 7:  Rx endpoint enable */
#define USBDEV_ENDPTCTRL_RXR                 (1 << 6)                          /* Bit 6:  Rx data toggle reset */
#define USBDEV_ENDPTCTRL_RXI                 (1 << 5)                          /* Bit 5:  Rx data toggle inhibit */
#define USBDEV_ENDPTCTRL_RXT_SHIFT           (2)                               /* Bits 2-3: Endpoint type */
#define USBDEV_ENDPTCTRL_RXT_MASK            (3 << USBDEV_ENDPTCTRL_RXT_SHIFT)
#  define USBDEV_ENDPTCTRL_RXT_CTRL          (0 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Control */
#  define USBDEV_ENDPTCTRL_RXT_ISOC          (1 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Isochronous */
#  define USBDEV_ENDPTCTRL_RXT_BULK          (2 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Bulk */
```

Or split the block:
```#define USBDEV_ENDPTCTRL_RXE                 (1 << 7)  /* Bit 7:  Rx endpoint enable */
#define USBDEV_ENDPTCTRL_RXR                 (1 << 6)  /* Bit 6:  Rx data toggle reset */
#define USBDEV_ENDPTCTRL_RXI                 (1 << 5)  /* Bit 5:  Rx data toggle inhibit */
#define USBDEV_ENDPTCTRL_RXT_SHIFT           (2)       /* Bits 2-3: Endpoint type */

#define USBDEV_ENDPTCTRL_RXT_MASK            (3 << USBDEV_ENDPTCTRL_RXT_SHIFT)
#  define USBDEV_ENDPTCTRL_RXT_CTRL          (0 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Control */
#  define USBDEV_ENDPTCTRL_RXT_ISOC          (1 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Isochronous */
#  define USBDEV_ENDPTCTRL_RXT_BULK          (2 << USBDEV_ENDPTCTRL_RXT_SHIFT) /* Bulk */
```

**Comment by davids5** [comment]
> @davids5 Do you prefer to right-shift all comments when there is one block of code for one register, or insert newlines within that block?

Personally I think the original is fine. The tool is the problem here. 

@johannes-nivus Do you see a simple way to fix the tool?

**Comment by johannes-nivus** [comment]
@davids5 please see #591
But I think @patacongo should review that change.

**Pull request merged**
