### PR TITLE
arch: arm: z16: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by jerpelea** [comment]
@xiaoxiang781216 comments?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 comments?

LGTM.

**Comment by jerpelea** [comment]
this one finished

**Comment by davids5** [comment]
@jerpelea - Shall we ignore the Tabs and mix case?

**Comment by jerpelea** [comment]
please ignore 
they will be fixed on the cleanup phase for the whole nuttx

**Pull request merged**
