### PR TITLE
nxstyle: Added assembly header detection.

### PR DESCRIPTION
**Pull request by johannes-nivus**
Should fix problems like the ones arised with PR #548 .

### CODE REVIEW

**Comment by johannes-nivus** [comment]
On a sidenote:
I'm not sure if continue fixing nxstyle issues makes sense during the undergoing efforts to switch to clang-format or comparable.

**Comment by patacongo** [comment]
I see you are still force pushing changes.  Is the ready to be reviewed?  Actually I have already looked at the changes and as far as I can tell from the online UI, this looks reasonable.  I plan to merge when the checkes complete (assuming success).

**Comment by johannes-nivus** [comment]
As always, I thought everything's fine and testing went well, but I had another look and "n" of a strncmp had been a liitle bit too small.
Please review and merge.

**Comment by patacongo** [comment]
> I'm not sure if continue fixing nxstyle issues makes sense during the undergoing efforts to switch to clang-format or comparable.

It will be weeks or perhaps even months before we know the answer to that.  I don't know that is a good idea to run all files wholesale through a pretty printer.  I would have to have extreme confidence in the tool to be really enthusiatic about that.  Such a tool will need some significant mileage before we can be certain.

But such a tool could potencially simplify a lot if it were truy trustworthy.  So let's wait and see.  You have experience some of the complex cornercases in the code, the tool has not yet.

**Comment by johannes-nivus** [comment]
Again slightly off topic:
The problem of a pretty printer is the missing control loop.
A "simple" style checker forces the commiter to fix the issues by hand in a reasonable way.
But what I see now: Each addressed "cornercase" adds to the complexity of the tool's sourcecode, reduces maintainability and increases risk of unwanted side effects.

**Comment by patacongo** [comment]
I don't have a problem with contributors fixing their own code.  In some ways, that seems more proper than automatically modifying it.  But I have also seen a lot of strange ways to fix nxstyle complaints. For example, someone recently simply increased the with of block comments to 180 to avoid long line complaints.  One some files (particularly header files), small increases in the block comment width is completely reasonable.  A pretty printer tool would, at least, assure that the issues are fixed in a common way.

But what would pretty printer do in the case as in many register definition files where the lines are just inherently very long.  I don't think we would be happy with the result and the pretty printer would not be smart enough to increase the block comment width which is often the correct solution (but should not be done as a general quick, low-effor fix).

**Comment by patacongo** [comment]
I don't have any fixed opinion at this time .. other than a pretty printer needs more work, more thought, and a lot of testing.

**Pull request merged**
