### PR TITLE
fix modem/altair semaphore related compiler warning

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Change-Id: Icfb7af6f1e31397dcadf3e652590cd2a55dc96a7
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by patacongo** [comment]
I think your fork is corrupted.  It says there are 13 commits and 1,647 files changed.  I think you need a new fork.

**Comment by patacongo** [comment]
Or perhaps just rebase your fork from upstream?

**Comment by xiaoxiang781216** [comment]
Done, do you see any change?

**Comment by patacongo** [comment]
Yes, now it says one commit, two files changed.  Thanks!

**Comment by patacongo** [comment]
But when I changed the base branch, it went back to 13 commits and 1,647 files.  let me recreate the branch.

**Comment by patacongo** [comment]
Yes, sorry.  The problem was my branch.

**Pull request merged**
