### PR TITLE
Imx6 adb

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR contains the following commits
- commit1: libs: spawn: Add forkaround for posix_spawn_file_actions_adddup2()
   - I noticed that adb shell failed when sh is spawned.
   - Finally, I found that an error happened when executing dup2() action
      if the file descriptor has the O_CLOEXEC option.
   - This commit fixes this issue by dropping the option in the API.
- commit2: boards: sabre-6quad: Add adbd to netnsh/defconfig

## Impact

- posix_spawn_file_actions_adddup2() only

## Testing

- Tested with qemu-6.2

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
> ## Summary
> * This PR contains the following commits
> * commit1: libs: spawn: Add forkaround for posix_spawn_file_actions_adddup2()
>   
>   * I noticed that adb shell failed when sh is spawned.
>   * Finally, I found that an error happened when executing dup2() action
>     if the file descriptor has the O_CLOEXEC option.

@masayuki2009 we also notice this problem and remove O_CLOEXEC from adb temporarily. But both workaround isn't good. The better fix is removed the spawn proxy thread.

**Comment by masayuki2009** [comment]
>@masayuki2009 we also notice this problem and remove O_CLOEXEC from adb temporarily. But both workaround isn't good, the better fix is removed the spawn proxy thread.

@xiaoxiang781216 
Hmm, but removing the spawn proxy thread would be a big change.

**Comment by xiaoxiang781216** [comment]
> > @masayuki2009 we also notice this problem and remove O_CLOEXEC from adb temporarily. But both workaround isn't good, the better fix is removed the spawn proxy thread.
> 
> @xiaoxiang781216 Hmm, but removing the spawn proxy thread would be a big change.

Yes, @Donny9 is preparing the patch to fix this, but the change isn't small, he need time to prepare the patch.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Let's merge this PR first. @Donny9 please revert the first patch after spawn proxy thread is removed.

**Pull request merged**
