### PR TITLE
trace: and sched note dump

### PR DESCRIPTION
**Pull request by OctopusHu0105**
trace: and sched note dump

note_type NOTE_DUMP_STRING API:
```
sched_note_string
sched_note_vprintf
sched_note_printf
```
note_type NOTE_DUMP_BINARY API:
```
sched_note_dump
sched_note_vbprintf
sched_note_bprintf
```

Pair with https://github.com/apache/incubator-nuttx-apps/pull/916

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@YuuichiNakamura could you take a look?

**Comment by davids5** [comment]
@OctopusHu0105 - what it the use case and motivation for these?

**Comment by xiaoxiang781216** [comment]
> @OctopusHu0105 - what it the use case and motivation for these?

Let's user add the custom info to the note stream, much like what Linux kernel do:
https://lwn.net/Articles/365835/
https://manpages.debian.org/jessie-backports/linux-manual-4.8/trace_printk.9.en.html

**Comment by xiaoxiang781216** [comment]
> @OctopusHu0105 - what it the use case and motivation for these?

Let's user add the custom info to the note stream, much like what Linux kernel do:
https://lwn.net/Articles/365835/
https://manpages.debian.org/jessie-backports/linux-manual-4.8/trace_printk.9.en.html

**Comment by xiaoxiang781216** [comment]
Here is the usage: https://github.com/apache/incubator-nuttx-apps/pull/916

**Comment by xiaoxiang781216** [comment]
@davids5 do you think the new API acceptable?

**Review by davids5 — COMMENTED** [review]
I am fine with the changes. Should we ask @YuuichiNakamura for a review?

**Comment by xiaoxiang781216** [comment]
Yes, I have at YuuichiNakamura but no response yet.

**Comment by YuuichiNakamura** [comment]
Oh, sorry. I didn't have time to review.
Both #4963 and https://github.com/apache/incubator-nuttx-apps/pull/916 are ok for me.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
