### PR TITLE
Kconfig:  Fix unmet dependencies on ARCH_PHY_INTERRUPT

### PR DESCRIPTION
**Pull request by patacongo**
Fix new warnings in the build test output.  The warnings were were of the form "... selects ARCH_PHY_INTERRUPT which has unmet dependencies (NETDEVICES && ARCH_HAVE_PHY)".  This was observed on the s32k148evb:nsh configuration.

I assume that this is because of the NETDEVICES dependency.  In most cases, the 'select ARCH_PHY_INTERRUPT' depended on NETDEVICES, but that was not the case for i.MX RT, S32K1xx, and Tiva.  This commit adds that dependency to the select like:

	select ARCH_PHY_INTERRUPT if NETDEVICES

as it is done in all other Kconfig files that select ARCH_PHY_INTERRUPT.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Should we follow the same princple mention below:
https://github.com/apache/incubator-nuttx/pull/228
https://github.com/apache/incubator-nuttx/pull/217
It's better to move ARCH_PHY_INTERRUPT to net/Kconfig just after config "ARCH_HAVE_PHY" and remove if NETDEVICES from all other Kconfig.

**Comment by patacongo** [comment]
Okay, I will update the PR.

**Comment by patacongo** [comment]
This, however, is not an ARCH_HAVE_* configuration.  This actually enables functionality, it does not just indicate feature support.  However, I see one case (Tiva) where the device has an internal PHY and so does not select ARCH_HAVE_PHY but does select ARCH_HAVE_PHY_INTERRUPT.

**Comment by patacongo** [comment]
It took me three commits to get this right.  Please squash into one if/when you merge.  Thanks!

**Pull request merged**
