### PR TITLE
boardctl: added BOARDIOC_PM_CHECKSTATE to BOARDIOC_PM_CONTROL

### PR DESCRIPTION
**Pull request by cisvanmierlo**
## Summary
Added boardctl BOARDIOC_PM_CHECKSTATE used in BOARDIOC_PM_CONTROL to check the recommended pm state (pm_checkstate()). 
## Impact
Minimal, added a new boardctl to excisting interface.
## Testing
Tested boardctl call on RDDRONE-BMS772, it worked.

### CODE REVIEW

**Comment by cisvanmierlo** [comment]
@v01d @davids5 @xiaoxiang781216 Here is the other function, pm_checkstate(), as well.

**Review by davids5 — APPROVED** [review]
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM, @v01d please take a look.

**Comment by cisvanmierlo** [comment]
check test failed, removed whitespace and updated code

**Comment by acassis** [comment]
I think it is good, but let give @v01d the chance to take a look

**Comment by v01d** [comment]
I was waiting for CI to finish. LGTM.

**Pull request merged**
