### PR TITLE
boards: esp32: Set CONFIG_NET_ETH_PKTSIZE to 1514

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- Recently I noticed that ESP32-DevKitC-32D suddenly stops
  receiving ping packets from PC after 10-20mins
- Also, during receiving ping packets, sometimes memory leak
  happened. (perhaps, some device sent a big broadcast
  packet periodically on the network)
- This commit fixes this issue by setting CONFIG_NET_ETH_PKTSIZE
  to 1514

## Impact

- All network use-cases for esp32 boards

## Testing

- Tested with esp32-devkitc:wapi only
- The commit should work for ethernet as well

### CODE REVIEW

**Comment by yamt** [comment]
>     * Also, during receiving ping packets, sometimes memory leak
>       happened. (perhaps, some device sent a big broadcast
>       packet periodically on the network)

do you mean that some of size checks in esp32_wlan.c are broken?

isn't this check enough?
https://github.com/apache/incubator-nuttx/blob/6e08c4dca3314d5df7da3c4ad582fa2169d2c48c/arch/xtensa/src/esp32/esp32_wlan.c#L492

**Comment by masayuki2009** [comment]
> > ```
> > * Also, during receiving ping packets, sometimes memory leak
> >   happened. (perhaps, some device sent a big broadcast
> >   packet periodically on the network)
> > ```
> 
> do you mean that some of size checks in esp32_wlan.c are broken?
> 
> isn't this check enough?
> 
> https://github.com/apache/incubator-nuttx/blob/6e08c4dca3314d5df7da3c4ad582fa2169d2c48c/arch/xtensa/src/esp32/esp32_wlan.c#L492

@yamt 
I'm not sure. Let me check if the condition happens with the default CONFIG_NET_ETH_PKTSIZE.

**Comment by xiaoxiang781216** [comment]
Should we change NET_ETH_PKTSIZE default to 1514? Most people who hasn't the deep knowledge about NuttX network stack don't know the existence of NET_ETH_PKTSIZE config. The default value should work out of box in the most case to help the normal user.

**Comment by masayuki2009** [comment]
@yamt 

>I'm not sure. Let me check if the condition happens with the default CONFIG_NET_ETH_PKTSIZE.

```
sh> free
                     total       used       free    largest
        Umem:       283296      50032     233264     156032
nsh> free
                     total       used       free    largest
        Umem:       283296      50032     233264     156032
nsh> [  179.660000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  179.910000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  180.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  181.420000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  183.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  185.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  187.420000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590

nsh> free
                     total       used       free    largest
        Umem:       283296      62016     221280     156032
nsh> free
                     total       used       free    largest
        Umem:       283296      62016     221280     156032
nsh> free
                     total       used       free    largest
        Umem:       283296      62016     221280     156032
nsh> 
nsh> free
                     total       used       free    largest
        Umem:       283296      62016     221280     156032
nsh> [  588.300000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  588.430000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  588.680000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  589.180000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  590.170000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  592.130000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[  594.140000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590

nsh> free
                     total       used       free    largest
        Umem:       283296      74000     209296     156032
```

**Comment by yamt** [comment]
> @yamt
> 
> > I'm not sure. Let me check if the condition happens with the default CONFIG_NET_ETH_PKTSIZE.
> 
> ```
> sh> free
>                      total       used       free    largest
>         Umem:       283296      50032     233264     156032
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      50032     233264     156032
> nsh> [  179.660000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  179.910000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  180.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  181.420000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  183.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  185.410000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  187.420000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> 
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      62016     221280     156032
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      62016     221280     156032
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      62016     221280     156032
> nsh> 
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      62016     221280     156032
> nsh> [  588.300000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  588.430000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  588.680000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  589.180000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  590.170000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  592.130000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> [  594.140000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
> 
> nsh> free
>                      total       used       free    largest
>         Umem:       283296      74000     209296     156032
> ```

i suspect the real fix might be to call `esp_wifi_free_eb` in that case.

**Comment by masayuki2009** [comment]
> Should we change NET_ETH_PKTSIZE default to 1514? Most people who hasn't the deep knowledge about NuttX network stack don't know the existence of NET_ETH_PKTSIZE config. The default value should work out of box in the most case to help the normal user.

@xiaoxiang781216 

I agree with you.
Should we close this issue and create a new PR for it?

**Comment by patacongo** [comment]
This would probably break some minimal configurations.Sent from my Galaxy
-------- Original message --------From: Masayuki Ishikawa <notifications@github.com> Date: 2/15/21  11:03 PM  (GMT-06:00) To: apache/incubator-nuttx <incubator-nuttx@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [apache/incubator-nuttx] boards: esp32: Set CONFIG_NET_ETH_PKTSIZE to 1514 (#2857) 

Should we change NET_ETH_PKTSIZE default to 1514? Most people who hasn't the deep knowledge about NuttX network stack don't know the existence of NET_ETH_PKTSIZE config. The default value should work out of box in the most case to help the normal user.

@xiaoxiang781216
I agree with you.
Should we close this issue and create a new PR for it?

**Comment by patacongo** [comment]
This would probablySent from my Galaxy
-------- Original message --------From: Masayuki Ishikawa <notifications@github.com> Date: 2/15/21  11:03 PM  (GMT-06:00) To: apache/incubator-nuttx <incubator-nuttx@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [apache/incubator-nuttx] boards: esp32: Set CONFIG_NET_ETH_PKTSIZE to 1514 (#2857) 

Should we change NET_ETH_PKTSIZE default to 1514? Most people who hasn't the deep knowledge about NuttX network stack don't know the existence of NET_ETH_PKTSIZE config. The default value should work out of box in the most case to help the normal user.

@xiaoxiang781216
I agree with you.
Should we close this issue and create a new PR for it?

**Comment by masayuki2009** [comment]
>This would probably break some minimal configurations.

@patacongo 

Thanks for the comment.

**Comment by masayuki2009** [comment]
@yamt 

>i suspect the real fix might be to call esp_wifi_free_eb in that case.

Thanks for the comment. Let me try your idea.

**Comment by xiaoxiang781216** [comment]
> This would probably break some minimal configurations.

How about we guard 1514 with !DEFAULT_SMALL?

**Comment by masayuki2009** [comment]
@yamt 

>Thanks for the comment. Let me try your idea.

So far, so good.
I will push the commit later.

```
nsh> [ 1244.170000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1244.420000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1244.920000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1245.920000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1247.900000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1249.910000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1251.910000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590

nsh> free
                     total       used       free    largest
        Umem:       283296      50032     233264     156032
nsh> ps
  PID PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK COMMAND
    0   0 FIFO     Kthread N-- Ready              00000000 003072 Idle Task
    1 100 RR       Kthread --- Waiting  Signal    00000000 002128 lpwork
    2 100 RR       Task    --- Running            00000000 002128 init
    3 223 RR       Kthread --- Waiting  Semaphore 00000000 002112 rt_timer
    4 253 RR       Kthread --- Waiting  MQ empty  00000000 003664 wifi
nsh> [ 1515.590000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1515.760000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1516.110000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1516.810000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1518.200000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1520.210000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590
[ 1522.220000] wlan_rx_done: ERROR: Wlan receive 698 larger than 590

nsh> free
                     total       used       free    largest
        Umem:       283296      50032     233264     156032
nsh> ps
  PID PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK COMMAND
    0   0 FIFO     Kthread N-- Ready              00000000 003072 Idle Task
    1 100 RR       Kthread --- Waiting  Signal    00000000 002128 lpwork
    2 100 RR       Task    --- Running            00000000 002128 init
    3 223 RR       Kthread --- Waiting  Semaphore 00000000 002112 rt_timer
    4 253 RR       Kthread --- Waiting  MQ empty  00000000 003664 wifi
```

**Comment by masayuki2009** [comment]
I close this issue.
Please see https://github.com/apache/incubator-nuttx/pull/2858 for the esp32 wifi fix.

**Comment by patacongo** [comment]
Sounds good to me.  Or MM_SMALL?Sent from my Galaxy
-------- Original message --------From: Xiang Xiao <notifications@github.com> Date: 2/15/21  11:43 PM  (GMT-06:00) To: apache/incubator-nuttx <incubator-nuttx@noreply.github.com> Cc: patacongo <spudarnia@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [apache/incubator-nuttx] boards: esp32: Set
  CONFIG_NET_ETH_PKTSIZE to 1514 (#2857) 

This would probably break some minimal configurations.

How about we guard 1514 with !DEFAULT_SMALL?

**Pull request closed without merging**
