### PR TITLE
Add low level operations to STM32L4 PWM driver.

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**

### CODE REVIEW

**Comment by jerpelea** [comment]
you should rebase your commits to avoid this kind of master merge!

Merge remote-tracking branch 'upstream/master'

**Comment by acassis** [comment]
Hi Alin, normally I do: git pull --rebase, but I did it after the pr98 creating and then merged pr98 with master to keep it in sync. It generated an avalanche of previous patches, but the final commit was fine. I just spent more time fixing the message. I should love to have some trigger that force me to do a rebase before creating a branch

**Comment by jerpelea** [comment]
@acassis now I saw that you did it manually 

Thanks !

**Comment by acassis** [comment]
You are welcome! I need a "pre-branch" hook, but AFAIK it doesn't exist: https://stackoverflow.com/questions/26745194/git-pre-branch-hook-possible

**Comment by acassis** [comment]
Mmm, I can create my own "git branch" command, very interesting: https://coderwall.com/p/bt93ia/extend-git-with-custom-commands

**Comment by acassis** [comment]
Worked like a charm! Now I just need to run: "git newpr pr98" and everything is done:

$ cat /usr/bin/git-newpr 
#!/bin/bash

source "$(git --exec-path)/git-sh-setup"

function _newpr() {
    git pull --rebase
    git branch $1
    git checkout $1
}

_newpr $1

**Pull request merged**
