### PR TITLE
sched: Consolidate the cancellation notification logic

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
no real funcitonality change.

### CODE REVIEW

**Comment by patacongo** [comment]
Cannot be merged due to conflict

**Comment by xiaoxiang781216** [comment]
> Cannot be merged due to conflict

Rebase to the mainline, please try again.

**Comment by xiaoxiang781216** [comment]
Need PR merge first: https://github.com/apache/incubator-nuttx/pull/1240

**Comment by Ouss4** [comment]
@xiaoxiang781216 Could you please rebase again, this will also need #1242 to pass.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 Could you please rebase again, this will also need #1242 to pass.

Done.

**Comment by Ouss4** [comment]
The failing build is due to a missing prototype, #1243 fixes that.

**Pull request merged**
