### PR TITLE
Fix video driver

### PR DESCRIPTION
**Pull request by SPRESENSE**
## Summary

- Add features on CXD5602 image processing driver
- Fix bugs ISX012 image sensor

## Testing

Tested by Spresense board

### CODE REVIEW

**Comment by jerpelea** [comment]
please add commit messages

**Comment by SPRESENSE** [comment]
@jerpelea 

This commits have whole description in the title, so if you want, I write the same content in the message. Is it okay?
However, other commits have only title, just Signed-off-by lines, how about this?

**Comment by jerpelea** [comment]
Please add the commit messages so that they are stored together with the commit and easy to read

**Comment by jerpelea** [comment]
please add the description for the commits

**Comment by jerpelea** [comment]
we have to show a good example how the commits should look 
please add commit messages

**Comment by SPRESENSE** [comment]
@jerpelea I updated commit messages. Please check them again.

**Comment by jerpelea** [comment]
@SPRESENSE thanks for the update

**Pull request merged**
