### PR TITLE
boards: arm: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses
 to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by jerpelea** [comment]
@xiaoxiang781216 
I am out of ideas except refactoring for 
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> I am out of ideas except refactoring for
> boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c

let's merge this hube PR first. I will try to create a new PR address this issue.

**Comment by jerpelea** [comment]
@xiaoxiang781216 I was hoping to have time to clear the mixed case issues but now I have no idea which files were affected

**Comment by jerpelea** [comment]
@xiaoxiang781216  I will look into the mixed case errors

**Comment by xiaoxiang781216** [comment]
You can try this command:
```
./tools/checkpatch.sh -g commit-id~...commit-id
```

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> I am out of ideas except refactoring for
> boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c

@jerpelea here is the fix: https://github.com/apache/incubator-nuttx/pull/3120

**Pull request merged**
