### PR TITLE
fs/nfs/nfs_proto.h: Use of uint64_t in the data types breaks NFS func…

### PR DESCRIPTION
**Pull request by meerd**
## Summary
The use of uint64_t primitive type in NFS structures forces the compiler to align data on an 8-byte boundary. 

## Impact
As a result of this, unwanted gaps being created, which causes NFS to fail. (e.g.,nfs_read/initialize the request)

## Testing
I noticed this issue while I was trying to 'cat' a file. The NFS implementation was always failing with 10001. After digging into the problem and sniffing the packages with Wireshark, I saw some garbage data in the read requests. After making this change, the problem disappeared, and everything has started to work as expected.

### CODE REVIEW

**Comment by meerd** [comment]
I see that the CI creates so many warnings for the existing code. I haven't touched any of them for clarity. @patacongo

**Comment by yamt** [comment]
lgtm.

**Comment by patacongo** [comment]
We have made exceptions for the "error: Mixed case identifier found" errors if there is no reasonable option.  But otherwise, all modified files must pass the style check before they can be merged.

**Comment by meerd** [comment]
I've made the necessary changes. The only remaining type of error is the "Mixed case identifier found."

In the TO-DO file, under "MISSING FILE SYSTEM FEATURES" title, I see that NFS is one of the filesystems that need review. I want to be of help to implement those features. And as part of this work, I could update existing type definitions that don't conform to the coding standard. @patacongo

**Pull request merged**
