### PR TITLE
board: Enable CONFIG_BOARDCTL_ROMDISK

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
to fix build break by commit 3156aa7532c5097c9

### CODE REVIEW

**Comment by btashton** [comment]
Still failing 
```
elf_main.c: In function 'elf_main':
Error: elf_main.c:209:29: error: unused variable 'desc' [-Werror=unused-variable]
  209 |   struct boardioc_romdisk_s desc;
      |                             ^~~~

```

**Comment by xiaoxiang781216** [comment]
Fix here: https://github.com/apache/incubator-nuttx-apps/pull/712

**Review by btashton — APPROVED** [review]
Thanks for fixing this up @xiaoxiang781216

**Comment by davids5** [comment]
Restarted and it is still failing - CI is current failures.

**Comment by btashton** [comment]
sim:posix_spawn needs to be in the sim02.dat exclude list instead of sim01.dat

**Comment by xiaoxiang781216** [comment]
Since my PR fix the build break, I will merge it directly.

**Pull request merged**
