### PR TITLE
boards/sim: Add adb config for test

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
help develop and test adb on sim. Depends on https://github.com/apache/incubator-nuttx/pull/5545 and https://github.com/apache/incubator-nuttx/pull/5498

## Impact
New config for sim

## Testing
Pass CI

### CODE REVIEW

**Review by yamt — APPROVED** [review]
mention it in boards/sim/sim/sim/README.txt?
otherwise lgtm

**Comment by xiaoxiang781216** [comment]
> mention it in boards/sim/sim/sim/README.txt? otherwise lgtm

Done.

**Review by yamt — COMMENTED** [review]
lgtm

**Review by pkarashchenko — APPROVED** [review]
LGTM!

**Comment by pkarashchenko** [comment]
Seems that this change depends on https://github.com/apache/incubator-nuttx/pull/5503

**Comment by xiaoxiang781216** [comment]
Yes, you are right.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 

```
====================================================================================
Configuration/Tool: sim/adb
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   127  100   127    0     0    920      0 --:--:-- --:--:-- --:--:--   920
From https://github.com/spiriou/microADB
 * branch            b7025c67b866925d1e64c016a844a6a3392557a4 -> FETCH_HEAD

100  711k    0  711k    0     0   797k      0 --:--:-- --:--:-- --:--:--  797k
100 1571k    0 1571k    0     0  1633k      0 --:--:-- --:--:-- --:--:-- 12.0M
/usr/bin/ld: nuttx.rel: in function `adb_uv_on_data_available':
/github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_packet.c:141: undefined reference to `uv_read_stop'
/usr/bin/ld: nuttx.rel: in function `tcp_uv_write':
/github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:68: undefined reference to `uv_write'
/usr/bin/ld: nuttx.rel: in function `tcp_uv_kick':
/github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:84: undefined reference to `uv_read_start'
/usr/bin/ld: nuttx.rel: in function `tcp_on_connection':
/github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:132: undefined reference to `uv_tcp_init'
/usr/bin/ld: /github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:139: undefined reference to `uv_accept'
/usr/bin/ld: /github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:143: undefined reference to `uv_read_start'
/usr/bin/ld: nuttx.rel: in function `adb_uv_tcp_setup':
/github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:161: undefined reference to `uv_tcp_init'
/usr/bin/ld: /github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:172: undefined reference to `uv_tcp_bind'
/usr/bin/ld: /github/workspace/sources/apps/system/adb/microADB/hal/hal_uv_client_tcp.c:178: undefined reference to `uv_listen'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:298: nuttx] Error 1
make: *** [tools/Unix.mk:509: nuttx] Error 2
make: Target 'all' not remade because of errors.
```

**Comment by xiaoxiang781216** [comment]
@masayuki2009 we need new libuv to pass the build. @no1wudi will provide the patch soon.

**Comment by no1wudi** [comment]
Yes, I'll update https://github.com/apache/incubator-nuttx-apps/pull/854 tomorrow.

**Review by jerpelea — APPROVED** [review]

**Comment by pkarashchenko** [comment]
Please rebase on top of the latest master

**Review by pkarashchenko — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@pkarashchenko it's finally pass the build.

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
