### PR TITLE
arch:risc-v:bl602: enable FPU for this target.

### PR DESCRIPTION
**Pull request by hotislandn**
## Summary
This patch enables the FPU support for arch:risc-v:bl602 SoC.

## Impact
RV32IM targets.

## Testing
The FPU tests within ostest passed.

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
@hotislandn please run to fix the CI error:
./tools/refresh.sh --silent bl602evb:fpu

**Comment by hotislandn** [comment]
> tools/refresh.sh --silent bl602evb:fpu

Thanks for your advice, xiaoxiang781216. And here comes the updated version.

**Comment by btashton** [comment]
@xiaoxiang781216 I would like to give this a look this weekend before merging so I can test if that's alright.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I would like to give this a look this weekend before merging so I can test if that's alright.

Sure, let's wait your test.

**Comment by btashton** [comment]
There was a small style issue that I fixed, but tested and looks good.

@xiaoxiang781216 did want to get your thought on this.  Seems like we should just move this section to be common per arch as a general cleanup?
https://github.com/apache/incubator-nuttx/pull/2809/files#diff-4901235976e131b4b1ba0507040dc1d33d669366a5973196d4cab6c43626078bR73-R95

**Review by btashton — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Yes, I think it's better to part of rv32/rv64 to avoid the duplication in each chip. We can refine it with new PR.

**Comment by btashton** [comment]
> Yes, I think it's better to part of rv32/rv64 to avoid the duplication in each chip. We can refine it with new PR.

Sounds good, I can put one together for all the arch this week.

**Comment by hotislandn** [comment]
> > Yes, I think it's better to part of rv32/rv64 to avoid the duplication in each chip. We can refine it with new PR.
> 
> Sounds good, I can put one together for all the arch this week.

Thanks and have a nice day!

**Pull request merged**
