### PR TITLE
Updated Rx65n rtc for non CONFIG_RTC_HIRES

### PR DESCRIPTION
**Pull request by RB-tel**
Added support for non CONFIG_RTC_HIRES

### CODE REVIEW

**Comment by Ouss4** [comment]
Could you please rebase and fix the conflicts.
And also please squash the commits.

**Comment by patacongo** [comment]
@RB-tel This cannot be merged until the conflicts are fixed.

**Comment by patacongo** [comment]
@RB-tel You need to rebase this against the current master branch to eliminate the conflicts.

**Comment by RB-tel** [comment]
> @RB-tel You need to rebase this against the current master branch to eliminate the conflicts.

Yes, I am trying to rebase. Facing issues. Will resolve them ASAP.

**Comment by patacongo** [comment]
I did the rebase.  I had to resolve conflicts in 3 files.  I tried to push the changes to your branch, but apparently I did not have permission to do that.

These are the kinds of things that we can help you with if you do not uncheck the box that allows maintainers to have access to your branch.

**Comment by RB-tel** [comment]
> I did the rebase. I had to resolve conflicts in 3 files. I tried to push the changes to your branch, but apparently I did not have permission to do that.
> 
> These are the kinds of things that we can help you with if you do not uncheck the box that allows maintainers to have access to your branch.

I understand. The check box was unintentionally kept unchecked.
I did rebase and remove the conflicts for the 3 files. But got status as branch diverged. Tried few things. Still facing issue. Any suggestion on what can be done.

**Comment by patacongo** [comment]
You probably have to force the push upstream.  That should ignore that fact that the branches has divurged and simply overwrite the old branch with the new one.

Sometimes I just have to re-create a clean version of the branch.  If force pushing does not work, then you can try tyat.  There might be some better solution but I would probably do a brute force change like:

- rebase the master branch
- rename the old branch
- re-create the branch, applying the changes from the old branch cleanly
- force push the new clean branch.  It would certainly be necessary to force in this case.

**Comment by patacongo** [comment]
I think I can merge this onto a branch, fix the conflicts, then merge it to main.  That is not the preferred way of doing things, but might allow us to make some progress on this.

**Comment by patacongo** [comment]
I pulled the changes, resolved the conflicts, and merged to master.  I will now have to close this PR.  Please verify that the changes are in place correctly.

This is not the correct way to do things.  We will need to be more careful in the future.  For one thing, please always allow maintainer access to the branch to we can help you out of such difficulties without resorting to these kind of steps.

**Comment by RB-tel** [comment]
> I pulled the changes, resolved the conflicts, and merged to master. I will now have to close this PR. Please verify that the changes are in place correctly.
> 
> This is not the correct way to do things. We will need to be more careful in the future. For one thing, please always allow maintainer access to the branch to we can help you out of such difficulties without resorting to these kind of steps.

Thanks a lot. The changes are placed correctly. Thank you.

**Pull request closed without merging**
