### PR TITLE
include: nuttx: update license headers

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt sumited the SGA and we can replace the headers with Apache 2.0 license

## Impact
None

## Testing
None

### CODE REVIEW

**Comment by acassis** [comment]
Thank you @jerpelea ! Please squash the commits

**Comment by btashton** [comment]
Some of these files have changes from others besides Greg, Did you make sure those are ones we have a ICLAs from if they are not minor changes.

**Comment by jerpelea** [comment]
@btashton In my understanding Greg holds the copyright of the file which means that the other contributors contributed to the copyright holder. 
Am I wrong?

**Comment by jerpelea** [comment]
@acassis I would prefer to have them separate commits to allow us to better track the changes but if you need I can squash them

**Comment by acassis** [comment]
> @acassis I would prefer to have them separate commits to allow us to better track the changes but if you need I can squash them

Yes, modification doing the same thing should be squashed in a single commit to avoid polluting the log history

**Comment by jerpelea** [comment]
@acassis done

**Comment by btashton** [comment]
> @btashton In my understanding Greg holds the copyright of the file which means that the other contributors contributed to the copyright holder.
> Am I wrong?

I guess this would indicate that you are correct, https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/#the-copyright-holder so long as Greg is the one that actually holds the copyright. We do need to be careful in cases where the original work was not actually assigned to Greg as his SGA may not fully cover that work.   A starting filter would be any work that has more than one person listed, in that case we will likely need to dig more into the history.

**Comment by jerpelea** [comment]
@btashton I will separate the work in 2 parts so that we can merged parts of this commit

**Comment by jerpelea** [comment]
@acassis can we merged this PR so that I can continue

**Comment by acassis** [comment]
Hi @jerpelea ok I will merge it. I was worried about the points raised by @btashton but since the Copyright were all from Greg I think there is not big issue here

**Comment by jerpelea** [comment]
perfect. I will continue to clean his files and then yours :)

**Pull request merged**
