### PR TITLE
net/local: Remove local_send.c since nobody use it now

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
 Forget to remove in:
    commit e223f60c091dea6937b58c73861adca57e500b82
    Author: Peter Bee <bijunda1@xiaomi.com>
    Date:   Tue Dec 1 14:55:16 2020 +0800
    
        net/socket: move si_send/recv into sendmsg/recvmsg
    
        Implement si_send/sendto/recvfrom with si_sendmsg/recvmsg, instead of
        the other way round.

## Impact
Should no

## Testing
Pass the build

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by acassis** [comment]
Hi @xiaoxiang781216 please describe the commit better. Why we don't need it anymore? Please cite other commit or issue. Is it because local_sendmsg.c can be a replacement?

**Comment by acassis** [comment]
Please supply more information [here](https://github.com/apache/incubator-nuttx/pull/3043#issue-591464860)

**Comment by davids5** [comment]
@acassis - I grepped the code base all the resent changes orphaned it. There has been a lot of really good work done on networking. 

@xiaoxiang781216 What is needed is a concise med/high level description of all the resent networking changes and the **motivation / benefits.**.  

It will be needed for the release notes and is scattered at the moment. Answer question like why sndmsg was added etc would be super helpful

**Comment by davids5** [comment]
@acassis - when you satisfied please mereg

**Comment by acassis** [comment]
> @acassis - when you satisfied please merge

Thank you @davids5 I just will wait for @xiaoxiang781216 reply/fix and merge it.

**Comment by xiaoxiang781216** [comment]
@acassis the commit message is updated

**Pull request merged**
