### PR TITLE
Add more symbols to libc.csv

### PR DESCRIPTION
**Pull request by yamt**
## Summary
Add more symbols to libc.csv
## Testing
tested with my local app.
this changes made it loadable at least.

### CODE REVIEW

**Comment by anchao** [comment]
How about merging the c interface changes into one commit? these does not have new implementations

**Comment by yamt** [comment]
> How about merging the c interface changes into one commit? these does not have new implementations

for me, it's easier to deal with this way.

**Comment by anchao** [comment]
> for me, it's easier to deal with this way.

Seriously, I do not quite agree with this way ... this will make the git commit history become garbage, if everyone split the commit line by line, there are a lot of commits in NuttX, but the code implementation is not really meaningful.

**Comment by yamt** [comment]
> > for me, it's easier to deal with this way.
> 
> Seriously, I do not quite agree with this way ... this will make the git commit history become garbage, if everyone split the commit line by line, there are a lot of commits in NuttX, but the code implementation is not really meaningful.

it's about logical separation. not about line by line separation.
i actually had to fix/replace/drop a few of these commits. it would have been more cumbersome if it was a single commit.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by anchao** [comment]
Do you think the commit logs like this is make sense to other developers? this can definitely be solved with a single commit !
I bet that if the similar changes are commit to other active communities, they will certainly vote against it .

```
commit 794df92fc98a0d54be5203c1f9681c18328eaba5 (HEAD, origin/master, origin/HEAD)
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 19:41:21 2022 +0900

    libs/libc/libc.csv: Add feof

commit 82fdba525896df7c30e59014fa396e6bcbefdbec
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 19:17:29 2022 +0900

    libs/libc/libc.csv: Add truncate

commit 182575d24086260e7b9a608341301e1cfe990421
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 19:07:27 2022 +0900

    libs/libc/libc.csv: Add localtime and ctime

commit 0db6ac28d81da1e9c19891cec48d202e0212f240
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 18:54:29 2022 +0900

    libs/libc/libc.csv: Add atoi and friends

commit 4b183b93cf45537f5903d54ef89f46d36b7bdfbb
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 17:39:28 2022 +0900

    libs/libc/libc.csv: Add mktemp and its friends

commit 113992c0377520676a4179f6c6d8a4a9f11d5fae
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 17:27:44 2022 +0900

    libs/libc/libc.csv: Add gettimeofday

commit 5ebfb70427c5466fc4ccfa04ec379f8e278e9804
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 17:19:27 2022 +0900

    libs/libc/libc.csv: Add pthread_cond_timedwait

commit 741a1d21490529726604a0a1bff09c3e84a4dcbe
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 17:10:02 2022 +0900

    libs/libc/libc.csv: Add pthread_create

commit bbfd0667fcbc055cd0959c38fb07811e31d098a3
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 16:54:25 2022 +0900

    libs/libc/libc.csv: Add uname

commit ebbfa034c798a31396c8d21459befcc83bd4fcec
Author: YAMAMOTO Takashi <yamamoto@midokura.com>
Date:   Thu Jan 27 16:24:40 2022 +0900

    libs/libc/libc.csv: Add shutdown


```

**Comment by davids5** [comment]
Hmmm, Isn't this why Squash should be enabled on our repos?

**Comment by yamt** [comment]
> Do you think the commit logs like this is make sense to other developers?

yes.

> this can definitely be solved with a single commit !

why? i explained why i did this way.

> I bet that if the similar changes are commit to other active communities, they will certainly vote against it .

i bet differently.

**Pull request merged**
