### PR TITLE
Change shes related headers

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This commit replaces SHES related headers with Apache License 2.0

## Impact

- No impact

## Testing

- Build check only

### CODE REVIEW

**Comment by justinmclean** [comment]
HI,

Why are these headers being replaced without a software grant? 

Thanks,
Justin

**Comment by masayuki2009** [comment]
> HI, Why are these headers being replaced without a software grant? Thanks, Justin

Hi, @justinmclean,

I am currently an SHES employee and I already submitted ICLA and I contributed the code.
so I thought it's OK to replace the headers.

**Comment by justinmclean** [comment]
Hi,
> I am currently an SHES employee and I already submitted ICLA and I contributed the code.
> so I thought it's OK to replace the headers.
> 

It is never OK to replace 3rd party headers without permission of the copyright owner. Sony is most likely the copyright owner here. Do we have documented permission on this mailing list to change the license or headers of those files? About the only case I could think of were it would be OK is if the wrong headers were accidentally put on the files in the first place, but I don’t think that’s the case here.

Thanks,
justin

**Comment by masayuki2009** [comment]
> Hi,
> I am currently an SHES employee and I already submitted ICLA and I contributed the code. so I thought it's OK to replace the headers.
> It is never OK to replace 3rd party headers without permission of the copyright owner. Sony is most likely the copyright owner here. Do we have documented permission on this mailing list to change the license or headers of those files? About the only case I could think of were it would be OK is if the wrong headers were accidentally put on the files in the first place, but I don’t think that’s the case here. Thanks, justin

Hi @justinmclean,

Thanks for the comment.

I'm still confused regarding the right process to change the license headers.
I think I need to send email to dev@nuttx.apache.org to change requests which refer to this PR.

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you ask the lawyer to sign SGA? like we do here:
https://lists.apache.org/thread.html/re120dc1cd10822ad5d7d4af594961cd4e80c48d9c32285a2254e3c56%40%3Cdev.nuttx.apache.org%3E

**Comment by masayuki2009** [comment]
> @masayuki2009 could you ask the lawyer to sign SGA? like we do here:
> https://lists.apache.org/thread.html/re120dc1cd10822ad5d7d4af594961cd4e80c48d9c32285a2254e3c56%40%3Cdev.nuttx.apache.org%3E

@xiaoxiang781216 

Thanks for the comments.
We will discuss SGA internally.

**Comment by v01d** [comment]
@masayuki2009 any updates on this?

**Comment by masayuki2009** [comment]
> @masayuki2009 any updates on this?

@v01d 

Legal group in our company is still reviewing SGA.
So please wait for a while.

**Review by jerpelea — APPROVED** [review]

**Comment by jerpelea** [comment]
The SGA has been submitted

**Comment by xiaoxiang781216** [comment]
@masayuki2009 and @jerpelea there still has many files with "Sony Semiconductor" or "Sony Home Entertainment" in nuttx and apps folder, should we change their copyright too?

**Comment by masayuki2009** [comment]
> @masayuki2009 and @jerpelea there still has many files with "Sony Semiconductor" or "Sony Home Entertainment" in nuttx and apps folder, should we change their copyright too?

@xiaoxiang781216 
Yes, we will create new PRs later.

**Pull request merged**
