### PR TITLE
tools/zipme.sh: Let major.minor.patch argument optional

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Simplify the version handling.

### CODE REVIEW

**Comment by Ouss4** [comment]
@xiaoxiang781216  this will relay on the latest tag, which may or may not correspond to the release version.
With this, a manual tagging before calling the script will be necessary.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 this will relay on the latest tag, which may or may not correspond to the release version.
> With this, a manual tagging before calling the script will be necessary.

It is possible to find the right tag for a particular release, https://github.com/apache/incubator-nuttx/pull/757 has the detailed discussion.

**Comment by Ouss4** [comment]
> It is possible to find the right tag for a particular release, #757 has the detailed discussion.

Yes, but only if the tag exists.

What I am saying is without supplying the version string to the script we relay solely on the tags.  The latest tag needs to match the version we are trying to create the tarballs for.
This may not be an issue on its own, I just wanted to make sure that we all agree that a manual tag will be needed.

**Comment by xiaoxiang781216** [comment]
> > It is possible to find the right tag for a particular release, #757 has the detailed discussion.
> 
> Yes, but only if the tag exists.
> 

gitver.sh also assume the tag is created before execution. There isn't difference between gitver.sh and version.sh from this point of view.

> What I am saying is without supplying the version string to the script we relay solely on the tags. The latest tag needs to match the version we are trying to create the tarballs for.

Yes, I agree. My suggestion is that it's better to put the algorithm to find the right tag in one place instead two(version.sh and gitver.sh).

> This may not be an issue on its own, I just wanted to make sure that we all agree that a manual tag will be needed.

Yes, here are two issues:
1.How to find the right tag? My proprose is that merging gitver.sh logic into version.sh.
2.How to create the tag?
   Created by the release manager manually, then the release process become:
   a.The release manager merge the PR with critical patch into the release branch
   b.The release manager create the right tag
   c.The release manager run zipme.sh to generate the package
   Or create(increase patch number) in package.yaml, then the most action can run automatically:
   a.The release manager merge the PR with critical patch into the release branch
   b.package.yaml(or call some script) create a new tag which point to the header of release branch
   c.package.yaml run zipme.sh to generate the package

     
 The simplify one is the release manager

**Comment by xiaoxiang781216** [comment]
For the final step, we may even make it automatically:
1.Generate the release candidate email from PR description automatically without signing, I think the signing isn't so important in the public review phase.
After the end of publish review, the release manager could sign the candidate package and upload to the Apache server. Of course, this step has to be done manually.

**Comment by Ouss4** [comment]
> Yes, I agree. My suggestion is that it's better to put the algorithm to find the right tag in one place instead two(version.sh and gitver.sh).

I agree.  I also had this concern about some of the logic duplication in both version.sh and gitver.sh.
I guess the issue was that the `packagerelease.yml` couldn't call `zipme.sh` without a version, so it needed to generate one.

**Comment by btashton** [comment]
> > > It is possible to find the right tag for a particular release, #757 has the detailed discussion.
> > 
> > Yes, but only if the tag exists.
> > 
> 
> gitver.sh also assume the tag is created before execution. There isn't difference between gitver.sh and version.sh from this point of view.
>

This is _not_ true. This is exactly why gitver.sh is different. I want to be able to create a version string _before_ the tag may exist.

**Comment by btashton** [comment]
> For the final step, we may even make it automatically:
> 1.Generate the release candidate email from PR description automatically without signing, I think the signing isn't so important in the public review phase.
> After the end of publish review, the release manager could sign the candidate package and upload to the Apache server. Of course, this step has to be done manually.

As I said before we cannot do this. The candidate package needs to be uploaded to Apache and _that_ link needs to be in the email, they explicitly require that.

**Comment by xiaoxiang781216** [comment]
> > For the final step, we may even make it automatically:
> > 1.Generate the release candidate email from PR description automatically without signing, I think the signing isn't so important in the public review phase.
> > After the end of publish review, the release manager could sign the candidate package and upload to the Apache server. Of course, this step has to be done manually.
> 
> As I said before we cannot do this. The candidate package needs to be uploaded to Apache and _that_ link needs to be in the email, they explicitly require that.

If so, this step need finish manually.

**Comment by xiaoxiang781216** [comment]
> > > > It is possible to find the right tag for a particular release, #757 has the detailed discussion.
> > > 
> > > 
> > > Yes, but only if the tag exists.
> > 
> > 
> > gitver.sh also assume the tag is created before execution. There isn't difference between gitver.sh and version.sh from this point of view.
> 
> This is _not_ true. This is exactly why gitver.sh is different. I want to be able to create a version string _before_ the tag may exist.

You mean the follow code?
```
# Closest Tag of this Version
VER_TAG=`git describe --abbrev=0 --match "nuttx-$NUTTX_VERSION" --match "nuttx-$NUTTX_VERSION-*" --match "nuttx-$NUTTX_VERSION.[0-9]*"  2>/dev/null`
if [ $? -ne 0 ]
then
    VER_TAG=nuttx-$NUTTX_VERSION
fi
```
This can be done in version.h too once we get the current branch with "git branch --show-current". Of course, we should only go through the above code when the branch name like release/^[0-9]+\.[0-9]+$.

**Comment by Ouss4** [comment]
I think regardless, this change is harmless and we can merge it.
We can carry on the discussion of whether to include the gitver.sh into version.sh or not in the other PR.
If @btashton has no concerns, we'll merge this.

**Comment by btashton** [comment]
If version is not supplied should we have a default like 0.0.0 or something. Otherwise the filenames will look funny. Or did I miss something.

**Comment by Ouss4** [comment]
Oops, it looks like I missed something.  They will indeed not look the way we want them to.

**Comment by xiaoxiang781216** [comment]
> If version is not supplied should we have a default like 0.0.0 or something. Otherwise the filenames will look funny. Or did I miss something.

you are right, I forget to update VERSION. I will update the patch to fix this issue.

**Comment by xiaoxiang781216** [comment]
@btashton @Ouss4 with the new zipme.sh, I think that we can migrate  the algo from gitver.sh to version.sh.

**Comment by xiaoxiang781216** [comment]
@yamt macOS build always fail to download espressif tools:
```
+ add_path /Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/xtensa-esp32-elf/bin
+ PATH=/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/xtensa-esp32-elf/bin:/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/riscv64-unknown-elf-gcc/bin:/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/gcc-arm-none-eabi/bin:/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/kconfig-frontends/bin:/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/genromfs/usr/bin:/Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/pylocal/bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools
+ '[' '!' -f /Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc ']'
+ cd /Users/runner/runners/2.169.0/work/incubator-nuttx/incubator-nuttx/testing/../prebuilt
+ case $os in
+ wget https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp-2019r2-macos.tar.gz
--2020-04-22 04:18:02--  https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp-2019r2-macos.tar.gz
Resolving dl.espressif.com (dl.espressif.com)... 119.9.91.16
Connecting to dl.espressif.com (dl.espressif.com)|119.9.91.16|:443... connected.
ERROR: cannot verify dl.espressif.com's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to dl.espressif.com insecurely, use `--no-check-certificate'.
##[error]Process completed with exit code 5.
```
It seem that the certification is expired, should we add `--no-check-certificate' like the suggestion?

**Comment by xiaoxiang781216** [comment]
@btashton do you think this patch is good to merge?

**Comment by xiaoxiang781216** [comment]
Since the below patch remove .version when user issue "make distclean":
https://github.com/apache/incubator-nuttx/pull/842
We need merge this patch to move "make distclean" before "tools/version.sh"

**Comment by btashton** [comment]
> Since the below patch remove .version when user issue "make distclean":
> https://github.com/apache/incubator-nuttx/pull/842

Won't that be bad for users of a release tarballs?

**Comment by xiaoxiang781216** [comment]
> > Since the below patch remove .version when user issue "make distclean":
> > #842
> 
> Won't that be bad for users of a release tarballs?

The old flow in zipme.sh is:
1.tools/version.sh
2.make distclean
It isn't an issue to invoke distclean after .version is generated since disclean don't remove .version before.
But with PR #842, distclean remove .version too, so this PR change the order as:
1.make distclean
2.tools/version.sh
If both PR merge, .version file is still zipped into tarball, the final result is same.

**Comment by Ouss4** [comment]
@xiaoxiang781216 If we remove `.version` with each `make distclean` then the version will 0.0.0 after a distclean with a tarball because there is no .git directory to fall back to.

**Comment by patacongo** [comment]
> If we remove `.version` with each `make distclean` then the version will be 0.0.0 after a distclean with a tarball because there is no .git directory to fall back to.

True.  We must retain the .version file.  We have to handle the use cases where (1) there is no GIT information available, and (2) end-users have a custom, hand-editted version of the .version file which they use to identify specific product releases which may be unrelated to NuttX releases.

We can only achieve backward compatibility and we can only accomplish the end-user usage cases be retaining the .version file.  It must never be deleted.

We have gone through this discussion numerous times, but it keeps coming back.  The .version file contains information which may or may not be related to the NuttX release.  A default version is created in the release, but there must be no assumption made about the content of the .version file, and it must survive all command line operations (with the exeption only of 'rm .version')

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 If we remove `.version` with each `make distclean` then the version will be 0.0.0 after the first distclean when we are using a tarball, because there is no .git directory to fall back to.

Yes, you are right, I will modify #842 to move rm .version from Makefile.* to cibuild.sh.

**Comment by xiaoxiang781216** [comment]
@Ouss4 @patacongo #842 remove .version inside testbuild.sh now.

**Comment by Ouss4** [comment]
@xiaoxiang781216 why do you need to remove the `.version` file?

PS. Does anyone have any issue with this PR? If not we can merge it and move the discussion to #842.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 why do you need to remove the `.version` file?
> 

Because we need checkthe whole code base restore to the original state after 'make distclean'  with "git status --ignored".

**Comment by patacongo** [comment]
> Because we need checkthe whole code base restore to the original state after 'make distclean' with "git status --ignored".

These are the kinds of odd situations you get in because .version must persist like part of the repository, but must not actually be in the the repository.  That is why I suggested a .release file in the dev mailing list a few days ago to break the odd situation.  The .release file would be a fixed version file in the repository created when the release it made.  It could then be used to create the customizable .version file which is not in the repository.

I am not saying it is an ideal proposal, but would (1) help to resolve issues like this and (2) would provide a valid, meaningul version number for all NuttX installations (0.0.0 is not meaningful).

**Pull request merged**
