### PR TITLE
CI: adapt to testlist changes

### PR DESCRIPTION
**Pull request by v01d**
## Summary

Adapt to testlist changes from https://github.com/apache/incubator-nuttx-testing/pull/92

## Impact

CI

## Testing

CI

### CODE REVIEW

**Comment by Ouss4** [comment]
18 minutes macOS, nice to see that!

**Comment by v01d** [comment]
> 18 minutes macOS, nice to see that!

Well, macos.dat is quite minimalistic now. If we made macos sim faster that could be quite a shorter total time.

**Comment by v01d** [comment]
I suggest we merge this as soon as possible, otherwise new PRs will not test against the test cases I moved out of other.dat.

**Comment by v01d** [comment]
Thanks!

**Pull request merged**
