### PR TITLE
libc: Move crc8.h, crc16.h and crc32.h from include to include/nuttx

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
to avoid the conflict with the 3rd party library.
note: all major libc provider doesn't put crc8.h, crc16.h and crc32.h directly under include folder.
depends on https://github.com/apache/incubator-nuttx-apps/pull/1260

## Testing
Pass CI

### CODE REVIEW

**Comment by davids5** [comment]
@xiaoxiang781216 - are you getting a clean build locally with apps?

**Comment by xiaoxiang781216** [comment]
Yes, I build with sim:spiffs

**Comment by davids5** [comment]
> Yes, I build with sim:spiffs

Do you get a local CI clean build with the apps PR and this one? I.E Do we have to ignore the CI fails or should the PR be a draft until it is ready?

**Comment by xiaoxiang781216** [comment]
> > Yes, I build with sim:spiffs
> 
> Do you get a local CI clean build with the apps PR and this one? I.E Do we have to ignore the CI fails or should the PR be a draft until it is ready?

Yes, it's ready for merge: sim:spiffs cover the change in libc and apps/fstest. If there is any break, I will monitor the CI in the next couple hours to fix the potential break quickly.

**Review by davids5 — APPROVED** [review]

**Comment by pkarashchenko** [comment]
I will take a look EOD. Anyway CI is failing, so I still have some time

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
