### PR TITLE
Fix timeout

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Fix the issue reported by:
https://groups.google.com/forum/#!topic/nuttx/AaNkS7oU6R0
https://groups.google.com/forum/#!topic/nuttx/nF0pfDkd3hA
https://lists.apache.org/thread.html/r9877de4a9c25890912d920cc15ca418368a9154212a5bf8e0c36a883%40<dev.nuttx.apache.org>

### CODE REVIEW

**Comment by fenconsultants** [comment]
Tested d403167 and 3c0d68f against my reproducible cases and both appear resolved.

**Comment by fenconsultants** [comment]
Minor issue: Enable CONFIG_NET_TCP_KEEPALIVE and then several references to struct timeval fail where sys/time.h is no longer included.

**Comment by patacongo** [comment]
I have some concerns that this combines unrelated changes into the same PR.  The result is that it is too large to review properly.  It will take some time.

**Comment by xiaoxiang781216** [comment]
> I have some concerns that this combines unrelated changes into the same PR. The result is that it is too large to review properly. It will take some time.

Yes, the change is huge but related each other unfortunately. That is why is better to "Rebase and merge" instead of "Squash", so we can keep each change separate and revertable.

**Pull request merged**
