### PR TITLE
Porting arch/armv8-m support

### PR DESCRIPTION
**Pull request by pangqiao**
1. Add dsp extension; float point based on hardware and software.
2. Delete folder "iar"
3. Add tool chain for cortex-M23 and cortex-M35p

Signed-off-by: qiaowei <qiaowei@xiaomi.com>
Change-Id: I5bfc78abb025adb0ad4fae37e2b444915f477fe7

# Pull Request Template

## Title guidelines

Following the guidelines for writting good commit messages (https://chris.beams.io/posts/git-commit/) and creating a meaningful title is key in effective team communication.

**do's**
- stm32h7:  Add SDMMC Support
- nsh:  Separate `source` and `sh` for POSIX compliance
- nxstyle:  Fixed Camel case detection
- drivers/serial:  Fixed style violation

**dont's**
- fixed bug
- nxstyle
- PR #12

## Description

**Describe problem solved by the PR**
A clear and concise description of the problem, if any, this PR will solve. Please also include relevant motivation and context: E.g. The current nsh sh command violates the POSIX ...

List any dependencies that are required for this change.

**Describe your solution**
A clear and concise description of what you have implemented.

**Describe possible alternatives**
A clear and concise description of alternative solutions  you've considered.

**Additional context**
Add any other context or screenshots for the pr.

Fixes # (issue)

## Type of change

Delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

* Nuttx board/config:
* Hardware:
* Toolchain:

## Checklist:

- [ ] My code follows the style guidelines of this project (NEED link to how to run checkpatch)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings (NEED link to how to run checkpatch spelling)

### CODE REVIEW

**Comment by patacongo** [comment]
Good job!  Great contribution!  I will be happy to merge this as soon as it passes all of the nxstyle checks.  That appears to be the only hold up.

**Comment by xiaoxiang781216** [comment]
> Good job! Great contribution! I will be happy to merge this as soon as it passes all of the nxstyle checks. That appears to be the only hold up.

@patacongo , @pangqiao will fix nxstyle issue in tomorrow. Please wait a moment.

**Comment by patacongo** [comment]
I will merge this despite the fact that it does not pass the nxstyle checks.  We agreed early on that cosmetic changes will no be held to the same review standard.

**Comment by xiaoxiang781216** [comment]
> I will merge this despite the fact that it does not pass the nxstyle checks. We agreed early on that cosmetic changes will no be held to the same review standard.

Ok, anyway @pangqiao will provide a follow up patch fix the remain nxstyle issue.

**Comment by patacongo** [comment]
> 
> 
> > I will merge this despite the fact that it does not pass the nxstyle checks. We agreed early on that cosmetic changes will no be held to the same review standard.
> 
> Ok, anyway @pangqiao will provide a follow up patch fix the remain nxstyle issue.

Oh.. I made a mistake.  I meant to merge #878 and keep this one open.  My mistake.  Well, know I can to the nxstyle fixed on your behalf if you like.  Sorry, I can repay you in that way.

I am getting too old and making too many mistakes.  It is past time for me to retire.

**Comment by patacongo** [comment]
PR #880 makes amends for my mistake and, hopefully, saves you a little effort.

**Comment by patacongo** [comment]
One other thing that we should consider is the naming of the files.  I tried to establish some consistent naming standards here:  https://cwiki.apache.org/confluence/display/NUTTX/Naming+FAQ

But I did not go to the effort to change all of the older architectures to follow this convention.  These newer architectures do follow this convetion.  See, for example, arch/arm/src/armv7-a.

Would like to follow this naming convention.  This would involve change the file names that begin with up_ to arm_.  it would also involve change armv8-m internal function names that begin with up_ to arm_.

What do you think?  Or should we just throw the naming convention away since it was never implemented?

**Comment by patacongo** [comment]
I could also make the renaming changes within the armv8-m/ directory is you agree to that.  I am not doing anything else of value today.

**Comment by xiaoxiang781216** [comment]
That's fine for us, but is it may better that we do the change for all arch to keep the consistent?

**Comment by patacongo** [comment]
I made the changes with PR882.

**Comment by patacongo** [comment]
I never changed the other architectures because the job is large and I am very cautious about do things that I cannot test may break other people's code.  Stability is important, but so it controlled change.

arm/, armv6-m, and armv7-m do not follow the convention.  armv8-m, armv7-a, and armv7-r do follow the convention.

**Comment by patacongo** [comment]
Changing the arch/arm/src/* file names is pretty easy.  Fixing the function names is more difficult since the effect functions could be called from board logic too.

If the are only called from arm/ and board/  then they should be arm_.  If they are also called from, say, sched/ then they should be up_ meaning that the interface must be common across all architectures.  arm_ means that the interface only applies to the specific arm architecture.

**Comment by xiaoxiang781216** [comment]
But with the daily build system, I think the risk is low but the work load is huge.

**Comment by patacongo** [comment]
yes, we can wait.  Or we can do it like I did that huge change to nxsem_wait_uninterruptible.  That was huge and took a week to do, but was not too painful because we created a small sub-team to divide the work up.  Most of the work is very simple, it is just a repetitive change but you still have to be very careful.  Staying aleart and careful is the hard part.

**Comment by patacongo** [comment]
Because of the time zone differences, Alan, Adelatif, and I work a lot together.  Abdelatif is a lot further west be he is a night time person.  I am further to the east but I am a morning person, so our work hours overlap.

it is more difficult for us to work together since you don't usually even start work until I am asleep.

**Comment by patacongo** [comment]
> arm/, armv6-m, and armv7-m do not follow the convention. armv8-m, armv7-a, and armv7-r do follow the convention.

But that ignores the non-ARM architectures.  Think this convention has been completely ignored in MIPs, RISC-V, and others.  So yes, the job would be quite large.

It is only easy when you start with a new architecture.

**Comment by patacongo** [comment]
@xiaoxiang781216 I notice a TizenRT PR to add TrustZone support: https://github.com/Samsung/TizenRT/pull/4262/files

**Comment by xiaoxiang781216** [comment]
@pangqiao please take a look

**Pull request merged**
