### PR TITLE
Rename clock_systime[r|spec] to clock_systime_[ticks|timespec]

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Follow the consistent naming patter of https://cwiki.apache.org/confluence/display/NUTTX/Naming+of+OS+Internal+Functions

## Impact
Name change only. No impact is expected

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
nxstyle error can be ignored:
arch/arm/src/lc823450/lc823450_sddrv_dep.c:98:35: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:147:29: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:178:29: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:212:29: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:229:29: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:271:33: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:286:28: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:303:28: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:312:26: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:326:35: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:360:32: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:391:25: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:479:26: error: Mixed case identifier found
drivers/wireless/nrf24l01.c:1905:11: error: Mixed case identifier found
drivers/wireless/nrf24l01.c:1908:11: error: Mixed case identifier found
drivers/wireless/nrf24l01.c:1912:11: error: Mixed case identifier found

**Comment by patacongo** [comment]
I wonder if internal clock interfaces should be nxclock_ vs. clock_?  The are several other internal clock interfaces, we don't need to change this PR for that.

**Comment by patacongo** [comment]
This is failing and holding up the merge:

    libmetal/lib/system/nuttx/time.c:21:6: error: implicit declaration of function 'clock_systimespec'; did you mean 'clock_systime_timespec'? [-Werror=implicit-function-declaration]
      r = clock_systimespec(&tp);
          ^~~~~~~~~~~~~~~~~
          clock_systime_timespec

**Comment by patacongo** [comment]
Now it looks like it is failing with in lc823450_sddrv_dep.c:

    chip/lc823450_sddrv_dep.c: In function 'sddep_read':
    chip/lc823450_sddrv_dep.c:402:32: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      402 |                           type == SDDR_RW_INC_WORD ? LC823450_DMA_DSTINC : 0,
    chip/lc823450_sddrv_dep.c:411:31: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      411 |                          type == SDDR_RW_INC_HWORD ? LC823450_DMA_DSTINC : 0,
    chip/lc823450_sddrv_dep.c:420:32: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      420 |                           type == SDDR_RW_INC_BYTE ? LC823450_DMA_DSTINC : 0,
    chip/lc823450_sddrv_dep.c: In function 'sddep_write':
    chip/lc823450_sddrv_dep.c:490:32: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      490 |                           type == SDDR_RW_INC_WORD ? LC823450_DMA_SRCINC : 0,
    chip/lc823450_sddrv_dep.c:499:31: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      499 |                          type == SDDR_RW_INC_HWORD ? LC823450_DMA_SRCINC : 0,
    chip/lc823450_sddrv_dep.c:508:32: error: suggest parentheses around comparison in operand of '|' [-Werror=parentheses]
      508 |                           type == SDDR_RW_INC_BYTE ? LC823450_DMA_SRCINC : 0,
    cc1: all warnings being treated as errors

I don't see how that is related to your change.

**Comment by patacongo** [comment]
You did not modify c823450_sddrv_dep.c and it appears to me that master does have the missing parentheses.  For example at lone 409 on master (NOT line 402), I see the first:

     (type == SDDR_RW_INC_HWORD ? LC823450_DMA_DSTINC : 0),

Do you need to rebase your branch?

**Comment by patacongo** [comment]
No, I was mistaken.  You did modify the tests.  Your PR removes the parentheses and introduces the errors.  You need to back out all of the changes like:

    @@ -485,7 +487,7 @@ SINT_T sddep_write(void *src, void *dst, UI_32 size, SINT_T type,
            lc823450_dmasetup(_hwdma[ch],
            lc823450_dmasetup(_hwdma[ch],
                              LC823450_DMA_SRCWIDTH_WORD |
                              LC823450_DMA_SRCWIDTH_WORD |
                              LC823450_DMA_DSTWIDTH_WORD |
                              LC823450_DMA_DSTWIDTH_WORD |
        -                     (type == SDDR_RW_INC_WORD ? LC823450_DMA_SRCINC : 0),
        +                     type == SDDR_RW_INC_WORD ? LC823450_DMA_SRCINC : 0,
                              (uint32_t)src, (uint32_t)dst, size / 4);
                              (uint32_t)src, (uint32_t)dst, size / 4);
            break;

**Comment by patacongo** [comment]
> You modified the tests in this PR. Your PR removes the parentheses and introduces the errors. You need to back out all of the changes like:

I fixed them with a forced push to your branch

**Pull request merged**
