### PR TITLE
Improve 64bit elf support

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by patacongo** [comment]
@xiaoxiang781216 I don't know what is going on here.  I don't understand why it failed.  There is something odd with stm32f4discovery:module, but the output is not interpretable and does not seem to be an error.  I have restart the checks several time but they only do the Docs/doc then stop with no further messages.

**Comment by btashton** [comment]
@patacongo I believe it is triggered by this in `testbuild.sh`
```
  # Ensure nuttx and apps directory in clean state

  if [ -d $nuttx/.git ] || [ -d $APPSDIR/.git ]; then
    if [[ -n $(git -C $nuttx status -s) ]]; then
      git -C $nuttx status
      fail=1
    fi
``` 

If normalize changes a defconfig file all the remaining tests will fail.  We see this here
```
2020-05-31T19:11:30.8945191Z ====================================================================================
2020-05-31T19:11:30.8968015Z Configuration/Tool: stm32f4discovery/module,CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
2020-05-31T19:11:30.9059881Z ------------------------------------------------------------------------------------
2020-05-31T19:11:30.9060022Z   Cleaning...
2020-05-31T19:11:36.8669871Z   Configuring...
2020-05-31T19:11:36.8817755Z   Copy files
2020-05-31T19:11:36.8971116Z   Select CONFIG_HOST_LINUX=y
2020-05-31T19:11:36.9096081Z   Refreshing...
2020-05-31T19:11:39.7550237Z   Disabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
2020-05-31T19:11:39.7573155Z   Enabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
2020-05-31T19:11:40.0977181Z   Building NuttX...
2020-05-31T19:12:04.9881712Z   Normalize stm32f4discovery/module
2020-05-31T19:12:05.5552111Z 51d50
2020-05-31T19:12:05.5552403Z < CONFIG_STM32_CCMEXCLUDE=y
2020-05-31T19:12:05.5555891Z Saving the new configuration file
2020-05-31T19:12:06.0344867Z HEAD detached at pull/1157/merge
2020-05-31T19:12:06.0345077Z Changes not staged for commit:
2020-05-31T19:12:06.0345223Z   (use "git add <file>..." to update what will be committed)
2020-05-31T19:12:06.0346145Z   (use "git checkout -- <file>..." to discard changes in working directory)
2020-05-31T19:12:06.0346233Z 
2020-05-31T19:12:06.0346373Z 	modified:   boards/arm/stm32/stm32f4discovery/configs/module/defconfig
2020-05-31T19:12:06.0346469Z 
2020-05-31T19:12:06.0346845Z no changes added to commit (use "git add" and/or "git commit -a")
2020-05-31T19:12:06.0506069Z ====================================================================================
```

**Comment by btashton** [comment]
@patacongo @xiaoxiang781216 Would you be open to a patch that causes `testbuild.sh` to echo out the error stats in a github actions format that allows for annotating the build with the actual errors instead of having to dig for them in the logs (especially with parallel runs)?  I know we want to keep the CI stuff out of this as much as possible, but this would be just some extra a little syntax around the message that github is able to pick up.
We can also define our out syntax and have github understand that, but I dont think it gains us much.
See this https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

**Comment by patacongo** [comment]
> 
> 
> @patacongo @xiaoxiang781216 Would you be open to a patch that causes `testbuild.sh` to echo out the error stats in a github actions format that allows for annotating the build with the actual errors instead of having to dig for them in the logs (especially with parallel runs)? I know we want to keep the CI stuff out of this as much as possible, but this would be just some extra a little syntax around the message that github is able to pick up.
> We can also define our out syntax and have github understand that, but I dont think it gains us much.
> See this https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

This is probably the wrong place to be having this discussion.  I am pretty open to changes to testbuild.sh.  There are only two "brick walls" that we must not cross:

1. testbuild.sh is a stand-alone program used by many people in their own test environments.  It is not inherently a part of the CI build tools; it is only used by the CI build tools.  No changes to testbuild.sh must effect the usability for people who use testbuild.sh in their own non-github, non-CI environment for testing.

2. I can't include in unconditional logic that depends on GIT.  It must be usable by the many NuttX users (the majority I think), who use their own CM which may or many not be GIT.  We must not break that.

Having said that, any of the above may be circumvented by simply adding command line parameters that are used only in the NuttX CI build.  If those parameters are not present, the legacy behavior is retained and no NuttX user is impacted.  There should be no change in the experience for those users who have build their own test harnesses around testbuild.sh.

There are already such specialized command line settings.  This one:

      -G Use "git clean -xfdq" instead of "make distclean" to clean the tree.
         This option may speed up the builds. However, note that:
           * This assumes that your trees are git based.
           * This assumes that only nuttx and apps repos need to be cleaned.
           * If the tree has files not managed by git, they will be removed
             as well.

If the changes that you want to make to testbuild.sh for CI usage diverge too much from the end-user expectation, we should consider an alternative version, perhaps in incubator-nuttx-testing that does not have these necessary restrictions.

Re-using code is a good thing.  But this is not such complex code that the sharing argument justifies an overly complex tool or a tool that cannot meet both needs.

**Comment by btashton** [comment]
@xiaoxiang781216 I think that refreshing the  `stm32f4discovery:module` config to remove that config flag makes sense.  Before it depended on `CONFIG_ELF` but that was not set but the config had LIBC_MODLIB enabled so it the CCM needed to be disabled.  Now this dependency is handled correctly.

**Comment by xiaoxiang781216** [comment]
I will took at this problem when I come to office.

**Pull request merged**
