### PR TITLE
Fix LCD pins to work correctly

### PR DESCRIPTION
**Pull request by acassis**
## Summary
Fix LCD pins to work correctly
## Impact
None
## Testing
With LVGL demo

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@acassis the check failure is fixed here: https://github.com/apache/incubator-nuttx/pull/1389

**Comment by masayuki2009** [comment]
> @acassis the check failure is fixed here: #1389

@xiaoxiang781216 
I merged the #1389 and reran the CI but it still fails...

**Comment by xiaoxiang781216** [comment]
> > @acassis the check failure is fixed here: #1389
> 
> @xiaoxiang781216
> I merged the #1389 and reran the CI but it still fails...

This PR need rebase to the latest mainline.

**Comment by masayuki2009** [comment]
> This PR need rebase to the latest mainline.

@xiaoxiang781216 
Thanks.

@acassis 
Please rebase this PR to the latest master.

**Comment by acassis** [comment]
Thank you @xiaoxiang781216 and @masayuki2009

**Pull request merged**
