### PR TITLE
Change license for lc823450

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This commit replaces license header under lc823450

## Impact

- No impact

## Testing

- Build check only

### CODE REVIEW

**Comment by justinmclean** [comment]
Hi,
> This commit replaces license header under lc823450
> NOTE: I got approval to remove 'ON Semiconductor' copyright info

Approval from who? And what was the approval to do? This approval need to be recorded on the mailing list.

Also you can’t really remove copyright ownership, ON Semiconductor would still have copyright of those files but the license terms allow it to be refused by others.

Normally the process is to submit a software grant and have the donated code undergo IP clearance, this alls means getting ICLAs from all committers. Even if you have permission to change the headers it may be better from an ASF perspective to leave them as they are unless On Semiconductor wants to submit a software grant and we get ICLAs from all contributors.

Thanks,
Justin

**Comment by masayuki2009** [comment]
> Hi,
> This commit replaces license header under lc823450 NOTE: I got approval to remove 'ON Semiconductor' copyright info
> Approval from who? And what was the approval to do? This approval need to be recorded on the mailing list. Also you can’t really remove copyright ownership, ON Semiconductor would still have copyright of those files but the license terms allow it to be refused by others. Normally the process is to submit a software grant and have the donated code undergo IP clearance, this alls means getting ICLAs from all committers. Even if you have permission to change the headers it may be better from an ASF perspective to leave them as they are unless On Semiconductor wants to submit a software grant and we get ICLAs from all contributors. Thanks, Justin

Hi, @justinmclean,

Thanks for the comments.

I will leave 'ON Semiconductor' copyright info and change the license headers to Apache 2.0.
Is this approach acceptable?

**Comment by masayuki2009** [comment]
> > Hi,
> > This commit replaces license header under lc823450 NOTE: I got approval to remove 'ON Semiconductor' copyright info
> > Approval from who? And what was the approval to do? This approval need to be recorded on the mailing list. Also you can’t really remove copyright ownership, ON Semiconductor would still have copyright of those files but the license terms allow it to be refused by others. Normally the process is to submit a software grant and have the donated code undergo IP clearance, this alls means getting ICLAs from all committers. Even if you have permission to change the headers it may be better from an ASF perspective to leave them as they are unless On Semiconductor wants to submit a software grant and we get ICLAs from all contributors. Thanks, Justin
> 
> Hi, @justinmclean,
> 
> Thanks for the comments.
> 
> I will leave 'ON Semiconductor' copyright info and change the license headers to Apache 2.0.
> Is this approach acceptable?

Hi @justinmclean,

I've just modified the commits so that they keep copyright info on 'ON Semiconductor'.

**Comment by justinmclean** [comment]
Hi,
> I will leave 'ON Semiconductor' copyright info and change the license headers to Apache 2.0.
> Is this approach acceptable?
> 

As I don’t know what you got permission to do or who it was from I can’t really give any advice on the approach. 

If they said you can change the license and that was from a CEO or companies legal representative then that would be OK but we need that recorded on the mailing list. We need something that we can provide a link to show that the company has officially allowed this. The mailing list is archived and searchable so provides a good place to do this.

If we what to change the header to ASF ones then we would need a software grant from the company for this code.

Thanks,
Justin

**Comment by masayuki2009** [comment]
@justinmclean 

Thanks for the comments.

I will not change the headers which include 'ON Semiconductor' copyright until I receive an official message from their legal representative.

**Comment by masayuki2009** [comment]
> @justinmclean
> 
> Thanks for the comments.
> 
> I will not change the headers which include 'ON Semiconductor' copyright until I receive an official message from their legal representative.

I've just pushed with -f.

**Pull request merged**
