### PR TITLE
idle: remove heap & stack check in idle thread

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary
idle: remove heap & stack check in idle thread. See the discussion here: https://github.com/apache/incubator-nuttx/pull/5266

## Impact
idle
heap & stack check

## Testing
VELA

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Review by jerpelea — APPROVED** [review]
LGTM

**Comment by xiaoxiang781216** [comment]
@a-lunev please try this patch.

**Review by pkarashchenko — APPROVED** [review]
LGTM!

**Comment by a-lunev** [comment]
> @a-lunev please try this patch.

Do you mean on some particular config?

**Comment by a-lunev** [comment]
> @a-lunev please try this patch.

I have tested it now using default sim:tcpblaster config. The TCP throughput of RX and TX is not reduced (if you were concerned about the performance).

**Review by a-lunev — APPROVED** [review]

**Pull request merged**
