### PR TITLE
libs/libc: add interface to support output stream as buffer style

### PR DESCRIPTION
**Pull request by anchao**
## Summary

libs/libc: add interface to support output stream as buffer style

## Impact

Interface extension for  struct lib_outstream_s

## Testing

run lib_outstream_s on stream mode

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@xiaoxiang781216 @anchao 

Hmm, something strange with spresense:smp

```
NuttShell (NSH) NuttX-10.2.0
nsh> uname -a
NuttX 10.2.0 e228434cea Nov 24 2021 14:46:22 arm spresense
nsh> hello
nsh> 
```

**Comment by masayuki2009** [comment]
>@xiaoxiang781216 @anchao
>
>Hmm, something strange with spresense:smp

The same problem happens with sim:smp.
Could you please confirm what is happening?

```
nsh> uname -a
NuttX 10.2.0 e228434cea Nov 24 2021 14:52:54 sim sim
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 065488 002344   3.5%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 065488 007048  10.7%  CPU1 IDLE
    2     2   2   0 FIFO     Kthread N-- Running            00000000 065488 004736   7.2%  CPU2 IDLE
    3     3   3   0 FIFO     Kthread N-- Running            00000000 065488 004704   7.1%  CPU3 IDLE
    4     4   0 100 FIFO     Task    --- Running            00000000 065504 003128   4.7%  init
nsh> hello
```

**Comment by xiaoxiang781216** [comment]
Yes, we found the same issue in the daily test too.
Here is fixed: https://github.com/apache/incubator-nuttx/pull/4874
Please try it, sorry for inconvenience.

**Comment by masayuki2009** [comment]
>Yes, we found the same issue in the daily test too.
>Here is fixed: #4874
>Please try it, sorry for inconvenience.

@xiaoxiang781216 
Thanks for your comments.
I confirmed that #4874 fixes the issue.

**Pull request merged**
