### PR TITLE
armv7-a/r: refact cp15_cache functions

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

mmu: mmu enable should after enable SMP
armv7-a/r: only primary can do invalidate_dcache_all() at startting
armv7a/r: refact cp15_cache functions

## Impact

cache & mmu

## Testing

VELA

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Let's ignore the CI false alarm on macOS.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@GUIDINGLI 
sabre-6quad:smp (real board, not QEMU) can not boot with this PR.

**Comment by GUIDINGLI** [comment]
@masayuki2009 
I have tried sabre-6quad:smp, both QEMU & real board, and can't reproduce your problem.

real board, step:
./tools/configure.sh sabre-6quad:smp -j8
make -j8

sudo systemctl restart tftpd-hpa
sudo cp nuttx.bin /srv/tftp/

board:
setenv ipaddr 192.168.31.56
setenv serverip 192.168.31.57
tftp 0x10800000 nuttx.bin
go 0x10800000



Here is the log:


U-Boot 2016.03 (Dec 25 2017 - 22:47:32 +0800)

CPU:   Freescale i.MX6Q rev1.2 996 MHz (running at 792 MHz)
CPU:   Automotive temperature grade (-40C to 125C) at 40C
Reset cause: POR
Board: MX6-SabreSD
I2C:   ready
DRAM:  1 GiB
PMIC:  PFUZE100 ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
*** Warning - bad CRC, using default environment

No panel detected: default to Hannstar-XGA
Display: Hannstar-XGA (1024x768)
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc1 is current device
Net:   FEC [PRIME]
Normal Boot
Hit any key to stop autoboot:  0 
=> 
=> 
=> 
=> setenv ipaddr 192.168.31.56
=> setenv serverip 192.168.31.57
=> tftp 0x10800000 nuttx.bin
Using FEC device
TFTP from server 192.168.31.57; our IP address is 192.168.31.56
Filename 'nuttx.bin'.
Load address: 0x10800000

         6.2 MiB/s
done
Bytes transferred = 130108 (1fc3c hex)
=> 
Using FEC device
TFTP from server 192.168.31.57; our IP address is 192.168.31.56
Filename 'nuttx.bin'.
Load address: 0x10800000

         5.2 MiB/s
done
Bytes transferred = 130108 (1fc3c hex)
=> go 0x10800000
## Starting application at 0x10800000 ...

NuttShell (NSH) NuttX-10.4.0
nsh> 
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 001000 000432  43.2%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 001000 000664  66.4%  CPU1 IDLE
    2     2   2   0 FIFO     Kthread N-- Running            00000000 001000 000664  66.4%  CPU2 IDLE
    3     3   3   0 FIFO     Kthread N-- Running            00000000 001000 000664  66.4%  CPU3 IDLE
    4     4 --- 192 RR       Kthread --- Waiting  Semaphore 00000000 001992 000416  20.8%  hpwork 0x108227d4
    5     5   0 100 RR       Task    --- Running            00000000 002000 001240  62.0%  nsh_main
nsh> 
nsh> hello
Hello, World!!

**Comment by masayuki2009** [comment]
>I have tried sabre-6quad:smp, both QEMU & real board, and can't reproduce your problem.

Hmm, it's strange.
Could you tell me the compiler version?

I've been using the following gcc.

```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by GUIDINGLI** [comment]
ligd@Opt:~/platform/mainline/nuttx$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by GUIDINGLI** [comment]
Just update cp15.h in new version

**Comment by masayuki2009** [comment]
>Just update cp15.h in new version

@GUIDINGLI 
The issue still happens with the latest PR.
I think the issue might depend on how to reset the board and what kind of the nuttx.bin was running before resetting the board.

I've been doing the board reset with openocd after deploying nuttx.bin to the tftp server.

```
./src/openocd -s ./tcl -f ./tcl/interface/jlink.cfg -f ./tcl/board/fsl_imx6q_sabresd.cfg -c init -c "reset" -c "exit"
```

And before testing `sabre-6quad:smp`, I did testing `sabre-6quad:elf`.

**Comment by GUIDINGLI** [comment]
Maybe your resets cmd is not a "cold reset", there is still something remaining ?

**Comment by GUIDINGLI** [comment]
@masayuki2009 
I will separate the PR to check the error, here is the first:
https://github.com/apache/incubator-nuttx/pull/7141

**Comment by GUIDINGLI** [comment]
@masayuki2009
Can you help to check, which caused error ?
https://github.com/apache/incubator-nuttx/pull/7141
https://github.com/apache/incubator-nuttx/pull/7144
https://github.com/apache/incubator-nuttx/pull/7113

**Comment by masayuki2009** [comment]
@GUIDINGLI 
The latest PR works with the sabre-6quad board.

**Comment by xiaoxiang781216** [comment]
@GUIDINGLI please rebase the patch to fix the conflict.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
