### PR TITLE
Apps Issue #246: Replace romdisk_register() with boardctl(BOARDIOC_ROMDISK)

### PR DESCRIPTION
**Pull request by tanushreebaindur**
## Summary

C file changes in the apps project:
examples/bastest/bastest_main.c, examples/elf/elf_main.c,
examples/module/module_main.c, examples/posix_spawn/spawn_main.c,
examples/romfs/romfs_main.c, examples/sotest/sotest_main.c,
examples/unionfs/unionfs_main.c

Corresponding defconfig files added/modified to test above changes:
       new file:   boards/sim/sim/sim/configs/bastest/defconfig
       new file:   boards/sim/sim/sim/configs/elf/defconfig
       modified:   boards/sim/sim/sim/configs/module/defconfig
       new file:   boards/sim/sim/sim/configs/posix_spawn/defconfig
       new file:   boards/sim/sim/sim/configs/romfs/defconfig
       modified:   boards/sim/sim/sim/configs/sotest/defconfig
       modified:   boards/sim/sim/sim/configs/unionfs/defconfig
       modified:   boards/sim/sim/sim/configs/module32/defconfig
       modified:   boards/sim/sim/sim/configs/sotest32/defconfig

## Impact
None

## Testing
Tested on local simulator

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by tanushreebaindur** [comment]
@xiaoxiang781216 . I have edited and committed   boards/sim/sim/sim/configs/sotest32/defconfig to this review to correct the build break: https://github.com/apache/incubator-nuttx-apps/pull/709/checks?check_run_id=2558161975.

I have also edited and added boards/sim/sim/sim/configs/module32/defconfig to this review in order to successfully run examples/module  in 32 bit configuration

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by btashton** [comment]
This PR seemed to have broken master can someone please take a look.

**Comment by tanushreebaindur** [comment]
I have seen that build error when CONFIG_BOARDCTL_ROMDISK is not enabled in the defconfig. 

CONFIG_BOARDCTL_ROMDISK can be enabled by doing the following in menuconfig: BOARD  SELECTION -> Enable application space creation of ROM disks.

I have used a simulator only to test the code changes. Could the  build break in  docker: add ninja-build #3705 be happening because a similar change must be made to the defconfig in spresense/elf, spresense/posix_spawn and spresense/module?

**Comment by xiaoxiang781216** [comment]
I am taking a look, @btashton .

**Pull request merged**
