### PR TITLE
Add support for STM32G43XX comparator

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**
## Summary

Up to this moment
  - Added register definition file
  - Added config options on menuconfig
  - Change logic on stm32_comp.c to support STM32G43XX (In progress). 

The Analog Comparator peripheral on STMF33XX different from STM32G4 family so big changes in stm32_comp.c are expected.

Help and suggestions are welcome.

## Impact

The Analog Comparator Driver (implemented for STM32_STM32F33XX) may break due to this change. 

## Testing

The only test performed was compile the configuration stm32f334-disco enabling COMP2 and Analog Comparator Driver.

### CODE REVIEW

**Comment by hartmannathan** [comment]
> The Analog Comparator peripheral on STMF33XX different from STM32G4 family so big changes in stm32_comp.c are expected.
> 
> Help and suggestions are welcome.


I recommend stm32_comp_v1.c and stm32_comp_v2.c, like we are doing for, e.g., DMA.

**Comment by daniel-p-carvalho** [comment]
> I recommend stm32_comp_v1.c and stm32_comp_v2.c, like we are doing for, e.g., DMA.

No problems for me. I will do this in another branch first, without any modification relative to STM32G4 Analog Comparator.

Thanks

 I will rename stm32_comp.c to stm32_comp_v1.c and create the new file for STM32G4.

**Comment by acassis** [comment]
@daniel-p-carvalho when this PR is done, please remove the Draft flag

**Comment by daniel-p-carvalho** [comment]
Hi Alan,

This PR is not finished yet. I am very busy this week.

Daniel Pereira de Carvalho


Em qui., 24 de jun. de 2021 às 08:52, Alan Carvalho de Assis <
***@***.***> escreveu:

**Comment by acassis** [comment]
no hurry up @daniel-p-carvalho ;-)

**Pull request closed without merging**
