### PR TITLE
Fix make target dependencies

### PR DESCRIPTION
**Pull request by yamt**
"all" and "depend" targets should not be made concurrently.
I occasionally see APPDIR build failures because of this.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Does this patch can fix this issue:
install: cannot stat 'hello': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [hello_install] Error 2
install: cannot stat 'struct': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [struct_install] Error 2
install: cannot stat 'errno': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [errno_install] Error 2
install: cannot stat 'signal': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [signal_install] Error 2
install: cannot stat 'mutex': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [mutex_install] Error 2
install: cannot stat 'pthread': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [pthread_install] Error 2
install: cannot stat 'task': No such file or directory
make[4]: *** [install] Error 1
make[3]: *** [task_install] Error 2
nm: 'a.out': No such file
make[3]: Target 'all' not remade because of errors.
make[2]: *** [tests/symtab.c] Error 2
make[2]: Target 'depend' not remade because of errors.
make[1]: *** [/home/jenkins/jenkins-slave/workspace/NuttX-Nightly-Build/apps/examples/elf_depend] Error 2

**Comment by yamt** [comment]
i don't know. i haven't seen that symptom.
my symptom was often with .xx_builtin_list.h.

**Comment by xiaoxiang781216** [comment]
> i don't know. i haven't seen that symptom.
> my symptom was often with .xx_builtin_list.h.

Ok, thanks for explanation which case this patch can fix.

**Comment by yamt** [comment]
@xiaoxiang781216 
is your symptom with examples/elf?
if it's caused by running "all" and "depend" target simultaneously (from your log it seems to be) this patch can fix it.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> is your symptom with examples/elf?
> if it's caused by running "all" and "depend" target simultaneously (from your log it seems to be) this patch can fix it.

Ok, let's try it, this is one of block issue to release the nightly build.

**Comment by liuguo09** [comment]
@yamt I just sync the change, then make -j8, and error happen as below: 
Seems example/elf/tests enter and built twice with make depend and all which result in object file truncated.

make[1]: Entering directory '/home/haitao/code/apache/apps'
CXX:  libxx_delete.cxx
CC:  dirent/lib_telldir.c
make[2]: Entering directory '/home/haitao/code/apache/apps/examples/elf'
**make -C tests TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" CROSSDEV=arm-none-eabi-**
make[2]: Entering directory '/home/haitao/code/apache/apps/builtin'
make[2]: Entering directory '/home/haitao/code/apache/apps/netutils/codecs'
CC:  dirent/lib_alphasort.c
CC:  mm_heap/mm_addfreechunk.c
make[3]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests'
make -C errno all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/errno'
CXX:  libxx_delete_sized.cxx
CC: errno.c
CC:  dirent/lib_scandir.c
make[3]: Entering directory '/home/haitao/code/apache/apps/builtin/registry'
make[3]: Nothing to be done for 'context'.
make[3]: Leaving directory '/home/haitao/code/apache/apps/builtin/registry'
make[2]: Leaving directory '/home/haitao/code/apache/apps/builtin'
make[2]: Entering directory '/home/haitao/code/apache/apps/platform'
make[2]: Entering directory '/home/haitao/code/apache/apps/examples/elf'
**make -C tests TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" CROSSDEV=arm-none-eabi-**
CC:  mm_heap/mm_size2ndx.c
CXX:  libxx_deletea.cxx
make[2]: Entering directory '/home/haitao/code/apache/apps'
CC:  urldecode.c
make[3]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests'
make -C errno all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
LD: errno.o
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/errno'
make -C hello all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
CC:  mm_heap/mm_shrinkchunk.c
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/errno'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/errno'
make -C hello all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/hello'
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/hello'
CC: hello.c
CC: hello.c
make[3]: Entering directory '/home/haitao/code/apache/apps/examples/elf'
make[3]: Nothing to be done for 'context'.
make[3]: Leaving directory '/home/haitao/code/apache/apps/examples/elf'
CXX:  libxx_deletea_sized.cxx
CC:  endian/lib_swap16.c
CC:  board/dummy.c
make[3]: Entering directory '/home/haitao/code/apache/apps/netutils/codecs'
make[3]: Nothing to be done for 'context'.
make[3]: Leaving directory '/home/haitao/code/apache/apps/netutils/codecs'
CC:  mm_heap/mm_brkaddr.c
CXX:  libxx_new.cxx
CC:  base64.c
CC:  endian/lib_swap32.c
make[2]: Leaving directory '/home/haitao/code/apache/apps/platform'
CC:  mm_heap/mm_calloc.c
make[3]: Entering directory '/home/haitao/code/apache/apps/platform'
LN: platform/board to /home/haitao/code/apache/apps/platform/dummy
LD: hello.o
LD: hello.o
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/hello'
make -C struct all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/hello'
make -C struct all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
make[3]: Leaving directory '/home/haitao/code/apache/apps/platform'
make[2]: Leaving directory '/home/haitao/code/apache/apps'
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/struct'
make -C signal all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
CC: struct_main.c
CC: struct_dummy.c
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/struct'
CC: struct_main.c
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/signal'
CC: signal.c
CC:  endian/lib_swap64.c
CXX:  libxx_newa.cxx
CC:  mm_heap/mm_extend.c
CC:  md5.c
CC:  mm_heap/mm_free.c
CC:  fixedmath/lib_fixedmath.c
CXX:  libxx_stdthrow.cxx
make -C signal all TOPDIR="/home/haitao/code/apache/nuttx" APPDIR="/home/haitao/code/apache/apps" FSIMG_DIR="/home/haitao/code/apache/apps/examples/elf/tests/romfs" CROSSDEV=arm-none-eabi-
LD: struct_main.o
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/struct'
make[4]: Entering directory '/home/haitao/code/apache/apps/examples/elf/tests/signal'
CC:  mm_heap/mm_mallinfo.c
LD: signal.o
CC:  fixedmath/lib_b16sin.c
**arm-none-eabi-ld: signal.o: file not recognized: file truncated**
Makefile:82: recipe for target 'signal' failed
make[4]: *** [signal] Error 1
make[4]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests/signal'
Makefile:86: recipe for target 'signal_build' failed
make[3]: *** [signal_build] Error 2
make[3]: Leaving directory '/home/haitao/code/apache/apps/examples/elf/tests'
Makefile:64: recipe for target 'tests/symtab.c' failed
make[2]: *** [tests/symtab.c] Error 2
make[2]: Leaving directory '/home/haitao/code/apache/apps/examples/elf'
Makefile:75: recipe for target '/home/haitao/code/apache/apps/examples/elf_all' failed
make[1]: *** [/home/haitao/code/apache/apps/examples/elf_all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by xiaoxiang781216** [comment]
> i don't know. i haven't seen that symptom.
> my symptom was often with .xx_builtin_list.h.

Suppose this patch could fix your problem:
https://github.com/apache/incubator-nuttx-apps/commit/8c8c48138162921f669127965a4e837ba2b0f535

This patch create a regression in the parallel build, we have to revert this patch until you find the root cause and correct it.

**Comment by yamt** [comment]
@xiaoxiang781216 which regression?

**Pull request merged**
