### PR TITLE
remove nested irq_save/restore code

### PR DESCRIPTION
**Pull request by klmchp**
Hi ,
Fix nested irq save/restore operation in sam_eefc.c.

BR
Kevin Liu

### CODE REVIEW

**Comment by patacongo** [comment]
This is a problem with this PR.  In includes the same commit as PR328 related EEFC and UUID.  I will merge to a branch and pick out the single commit that you intended.

**Comment by patacongo** [comment]
No, it won't let me do that.  You will have to fix the PR.  I see conflict:

    Conflicting files
    arch/arm/src/samv7/sam_eefc.c
    arch/arm/src/samv7/sam_eefc.h
    arch/arm/src/samv7/sam_uid.c

**Comment by patacongo** [comment]
Ooops hit the wrong button again.  I did not mean to close this.  Bad habit.
Hmm.. now it won't let me re-open it???

**Comment by patacongo** [comment]
I would let me re-open it because I removed branch pr336

**Comment by klmchp** [comment]
Thanks to Greg's work, modification merged to master.

**Pull request closed without merging**
