### PR TITLE
Revert "stm32h7 sdmmc: set SDMMC_CK pin to high speed (50 MHz) mode."

### PR DESCRIPTION
**Pull request by davids5**
Reverts apache/incubator-nuttx#5010

This is a board level decision based on the routing. We can not change a this globally or it will effect certifications. The mechanism is in place to set the slew rate. See:

```

/* Alternate Pin Functions.
 * All members of the STM32H76|7xxx family share the same pin multiplexing
 *(although they may differ in the pins physically available).
 *
 * Alternative pin selections are provided with a numeric suffix like _1, _2,
 * etc. Drivers, however, will use the pin selection without the numeric
 * suffix.
 * Additional definitions are required in the board.h file.  For example,
 * if CAN1_RX connects vis PA11 on some board, then the following definitions
 * should appear in the board.h header file for that board:
 *
 * #define GPIO_CAN1_RX GPIO_CAN1_RX_1
 *
 * The driver will then automatically configure PA11 as the CAN1 RX pin.
 */

/* WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
 * Additional effort is required to select specific GPIO options such as
 * frequency, open-drain/push-pull, and pull-up/down!  Just the basics are
 * defined for most pins in this file.
 */
```
The changes should be to adorn GPIO_SDMMC1_CK with the  _\<number\> (ie GPIO_SDMMC1_CK _5) and then in board.h file 

```#define (GPIO_SDMMC1_CK  GPIO_SDMMC1_CK_5|GPIO_SPEED_50MHz)```

### CODE REVIEW

**Comment by a-lunev** [comment]
@davids5, then we are removing GPIO_SPEED_50MHz,GPIO_PUSHPULL,GPIO_PULLUP from all SDIO lines (not only GPIO_SDMMC*_CK) in stm32h7x3xx_pinmap.h, and renaming all the constants (adding _< number >), correct?
It was:
```
#define GPIO_SDMMC2_CK_1          (GPIO_ALT|GPIO_AF11|GPIO_SPEED_50MHz|GPIO_PORTD|GPIO_PIN6)
#define GPIO_SDMMC2_CK_2          (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PORTC|GPIO_PIN1)
#define GPIO_SDMMC2_CMD_1         (GPIO_ALT|GPIO_AF11|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PULLUP|GPIO_PORTD|GPIO_PIN7)
#define GPIO_SDMMC2_CMD_2         (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
#define GPIO_SDMMC2_D0            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN14)
#define GPIO_SDMMC2_D1            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN15)
#define GPIO_SDMMC2_D2_1          (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTG|GPIO_PIN11)
#define GPIO_SDMMC2_D2_2          (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN3)
#define GPIO_SDMMC2_D3            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN4)
#define GPIO_SDMMC2_D4            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN8)
#define GPIO_SDMMC2_D5            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN9)
#define GPIO_SDMMC2_D6            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN6)
#define GPIO_SDMMC2_D7            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN7)

```
It will be:
```
#define GPIO_SDMMC2_CK_1          (GPIO_ALT|GPIO_AF11|GPIO_PORTD|GPIO_PIN6)
#define GPIO_SDMMC2_CK_2          (GPIO_ALT|GPIO_AF9|GPIO_PORTC|GPIO_PIN1)
#define GPIO_SDMMC2_CMD_1         (GPIO_ALT|GPIO_AF11|GPIO_PORTD|GPIO_PIN7)
#define GPIO_SDMMC2_CMD_2         (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)
#define GPIO_SDMMC2_D0            (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN14)
#define GPIO_SDMMC2_D1            (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN15)
#define GPIO_SDMMC2_D2_1          (GPIO_ALT|GPIO_AF10|GPIO_PORTG|GPIO_PIN11)
#define GPIO_SDMMC2_D2_2          (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN3)
#define GPIO_SDMMC2_D3            (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN4)
#define GPIO_SDMMC2_D4            (GPIO_ALT|GPIO_AF10|GPIO_PORTB|GPIO_PIN8)
#define GPIO_SDMMC2_D5            (GPIO_ALT|GPIO_AF10|GPIO_PORTB|GPIO_PIN9)
#define GPIO_SDMMC2_D6            (GPIO_ALT|GPIO_AF10|GPIO_PORTC|GPIO_PIN6)
#define GPIO_SDMMC2_D7            (GPIO_ALT|GPIO_AF10|GPIO_PORTC|GPIO_PIN7)
```

And similar changes are for all the other interfaces (CAN, I2C etc.).

**Comment by davids5** [comment]
> @davids5, then we are removing GPIO_SPEED_50MHz,GPIO_PUSHPULL,GPIO_PULLUP from all SDIO lines (not only GPIO_SDMMC*_CK) in stm32h7x3xx_pinmap.h, and renaming all the constants (adding _< number >), correct? It was:
> 
> ```
> #define GPIO_SDMMC2_CK_1          (GPIO_ALT|GPIO_AF11|GPIO_SPEED_50MHz|GPIO_PORTD|GPIO_PIN6)
> #define GPIO_SDMMC2_CK_2          (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PORTC|GPIO_PIN1)
> #define GPIO_SDMMC2_CMD_1         (GPIO_ALT|GPIO_AF11|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PULLUP|GPIO_PORTD|GPIO_PIN7)
> #define GPIO_SDMMC2_CMD_2         (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
> #define GPIO_SDMMC2_D0            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN14)
> #define GPIO_SDMMC2_D1            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN15)
> #define GPIO_SDMMC2_D2_1          (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTG|GPIO_PIN11)
> #define GPIO_SDMMC2_D2_2          (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN3)
> #define GPIO_SDMMC2_D3            (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN4)
> #define GPIO_SDMMC2_D4            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN8)
> #define GPIO_SDMMC2_D5            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTB|GPIO_PIN9)
> #define GPIO_SDMMC2_D6            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN6)
> #define GPIO_SDMMC2_D7            (GPIO_ALT|GPIO_AF10|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN7)
> ```
> 
> It will be:
> 
> ```
> #define GPIO_SDMMC2_CK_1          (GPIO_ALT|GPIO_AF11|GPIO_PORTD|GPIO_PIN6)
> #define GPIO_SDMMC2_CK_2          (GPIO_ALT|GPIO_AF9|GPIO_PORTC|GPIO_PIN1)
> #define GPIO_SDMMC2_CMD_1         (GPIO_ALT|GPIO_AF11|GPIO_PORTD|GPIO_PIN7)
> #define GPIO_SDMMC2_CMD_2         (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)
> #define GPIO_SDMMC2_D0_1            (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN14)
> #define GPIO_SDMMC2_D1_1           (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN15)
> #define GPIO_SDMMC2_D2_1          (GPIO_ALT|GPIO_AF10|GPIO_PORTG|GPIO_PIN11)
> #define GPIO_SDMMC2_D2_2          (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN3)
> #define GPIO_SDMMC2_D3_1            (GPIO_ALT|GPIO_AF9|GPIO_PORTB|GPIO_PIN4)
> #define GPIO_SDMMC2_D4_1           (GPIO_ALT|GPIO_AF10|GPIO_PORTB|GPIO_PIN8)
> #define GPIO_SDMMC2_D5_1            (GPIO_ALT|GPIO_AF10|GPIO_PORTB|GPIO_PIN9)
> #define GPIO_SDMMC2_D6_1            (GPIO_ALT|GPIO_AF10|GPIO_PORTC|GPIO_PIN6)
> #define GPIO_SDMMC2_D7_1            (GPIO_ALT|GPIO_AF10|GPIO_PORTC|GPIO_PIN7)
> ```
> 
> And similar changes are for all the other interfaces (CAN, I2C etc.).

Yes that is the idea. It is a breaking change and has to be documented very well. So that people can get back to working and know what slew rates they had.

**Comment by a-lunev** [comment]
> Yes that is the idea. It is a breaking change and has to be documented very well. So that people can get back to working and know what slew rates they had.

I'm thinking about two more possible approaches:

**Approach N2**: get rid of stm32h7x3xx_pinmap.h (and all similar files for all families) at all.
Let's consider one of the following potential change in stm32h7x3xx_pinmap.h:
before:
`#define GPIO_SDMMC2_CMD         (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
`
after:
`#define GPIO_SDMMC2_CMD_2         (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`

And the following line is going to be added to board.h:
`#define GPIO_SDMMC2_CMD         (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`

Currently there are about 1,500 defines in stm32h7x3xx_pinmap.h and all or part of 1,500 defines (depending on a particular board) are going to migrate to board.h files.

Then if we look into board.h, "GPIO_SDMMC2_CMD_2" and all the other referred constants may be confusing (because of "_ < number >" endings).
Possibly it would be better to have the whole (not split) define in board.h, namely:
`#define GPIO_SDMMC2_CMD         (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
`
In this case it would be more clear how a pin is configured for given board.

**Approach N3**: the same as Approach N1 (the one you have suggested), however use a port label instead of "_ < number > ".
The potential change in stm32h7x3xx_pinmap.h:
before:
`#define GPIO_SDMMC2_CMD         (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
`
after:
`#define GPIO_SDMMC2_CMD_PA0         (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`

And the following line is going to be added to board.h:
`#define GPIO_SDMMC2_CMD         (GPIO_SDMMC2_CMD_PA0|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`

What do you think?

**Comment by davids5** [comment]
> > Yes that is the idea. It is a breaking change and has to be documented very well. So that people can get back to working and know what slew rates they had.
> 
> I'm thinking about two more possible approaches:
> 
> **Approach N2**: get rid of stm32h7x3xx_pinmap.h (and all similar files for all families) at all. 

Did you mean get rid of the slew, drive type or the files themselves?

I would be opposed to getting rid of the files. There is too much info that is valid and tested.  I think the drive type is known by context of the pin and is usually defined by the IP block. I.E. I2C is open drain - so there is no reason to removes everything. Just board (layout) specified components of the pin definitions I.E.  Slew Rate, PU/PD etc.

>Let's consider one of the following potential change in stm32h7x3xx_pinmap.h: before: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` after: `#define GPIO_SDMMC2_CMD_2 (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`
> 
> And the following line is going to be added to board.h: `#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`
> 
> Currently there are about 1,500 defines in stm32h7x3xx_pinmap.h and all or part of 1,500 defines (depending on a particular board) are going to migrate to board.h files.
> 
> Then if we look into board.h, "GPIO_SDMMC2_CMD_2" and all the other referred constants may be confusing (because of "_ < number >" endings). Possibly it would be better to have the whole (not split) define in board.h, namely: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` In this case it would be more clear how a pin is configured for given board.
> 
> **Approach N3**: the same as Approach N1 (the one you have suggested), however use a port label instead of "_ < number > ". The potential change in stm32h7x3xx_pinmap.h: before: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` after: `#define GPIO_SDMMC2_CMD_PA0 (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`
> 
> And the following line is going to be added to board.h: `#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_PA0|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`
> 
> What do you think?

N3 - is just encoding the information in the define in the name. I am not a fan. 

once all the defines have a _n all of this is a moot point.

The NuttX drivers use the root name: GPIO_SDMMC2_CMD, I can role my own in board.h. 

I can ignore the _n
```
#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
```

 I can use the _n and ADD 
```
#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)
```

Or change it, See https://github.com/PX4/PX4-Autopilot/pull/15024/commits/de7aa78518fe77a04789f4f8ab06fa420c74542e

The simple fix is to remove all root names from the pin maps files by adding the `_n`  In the past @mubes and I had this discussion and I had suggested using `_0` to - un-root the root names. 

It should only effect the  root name defines in the pinmaps files, and that will be much less then all of defines in the pin map.

**Comment by a-lunev** [comment]
> > > Yes that is the idea. It is a breaking change and has to be documented very well. So that people can get back to working and know what slew rates they had.
> > 
> > 
> > I'm thinking about two more possible approaches:
> > **Approach N2**: get rid of stm32h7x3xx_pinmap.h (and all similar files for all families) at all.
> 
> Did you mean get rid of the slew, drive type or the files themselves?

For approach N2 I meant getting rid of the files themselves.

> 
> I would be opposed to getting rid of the files. There is too much info that is valid and tested. I think the drive type is known by context of the pin and is usually defined by the IP block. I.E. I2C is open drain - so there is no reason to removes everything. Just board (layout) specified components of the pin definitions I.E. Slew Rate, PU/PD etc.

(Not approach N2 then) Existing files like stm32h7x3xx_pinmap.h could be announced deprecated and retained (say for 5 years) for compatibility purposes with the boards that are out of NuttX tree. New pinmap files could be introduced (that do not contain Slew Rate, PU/PD etc.) and recommended for use.
 
> > Let's consider one of the following potential change in stm32h7x3xx_pinmap.h: before: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` after: `#define GPIO_SDMMC2_CMD_2 (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`
> > And the following line is going to be added to board.h: `#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`
> > Currently there are about 1,500 defines in stm32h7x3xx_pinmap.h and all or part of 1,500 defines (depending on a particular board) are going to migrate to board.h files.
> > Then if we look into board.h, "GPIO_SDMMC2_CMD_2" and all the other referred constants may be confusing (because of "_ < number >" endings). Possibly it would be better to have the whole (not split) define in board.h, namely: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` In this case it would be more clear how a pin is configured for given board.
> > **Approach N3**: the same as Approach N1 (the one you have suggested), however use a port label instead of "_ < number > ". The potential change in stm32h7x3xx_pinmap.h: before: `#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0) ` after: `#define GPIO_SDMMC2_CMD_PA0 (GPIO_ALT|GPIO_AF9|GPIO_PORTA|GPIO_PIN0)`
> > And the following line is going to be added to board.h: `#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_PA0|GPIO_SPEED_50MHz|GPIO_PUSHPULL)`
> > What do you think?
> 
> N3 - is just encoding the information in the define in the name. I am not a fan.
> 
> once all the defines have a _n all of this is a moot point.

Yes, there would be a huge rework. However, I think having port name+number in the define name is much less error-prone compared to just _n.

> The NuttX drivers use the root name: GPIO_SDMMC2_CMD, I can role my own in board.h.
> 
> I can ignore the _n
> 
> ```
> #define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
> ```
> 
(as in Approach N2)

> I can use the _n and ADD
> 
> ```
> #define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)
> ```
> 
> Or change it, See [PX4/PX4-Autopilot@de7aa78](https://github.com/PX4/PX4-Autopilot/commit/de7aa78518fe77a04789f4f8ab06fa420c74542e)

Yes, there are comments with port name+number clarification for each define. That is one of the points why I think it'd better to use port name+number in the define name instead of _n. It would be self-documented and then it would be almost unlikely to misuse the constants.

> 
> The simple fix is to remove all root names from the pin maps files by adding the `_n` In the past @mubes and I had this discussion and I had suggested using `_0` to - un-root the root names.
> 
> It should only effect the root name defines in the pinmaps files, and that will be much less then all of defines in the pin map.

Yes, I think it would be also a signal (compile errors) for out-of-tree board maintainer to migrate to the new pinmap way.

**Comment by davids5** [comment]
If you change ALL the _n to a value Pnn you cause massive churn that IMO added very little value as it only duplicates information in from the define into the name.  - Hence I said I am not a Fan of that change.

I would add _0 to the non numbered root names and stop there. The compiler will catch it. The user can then deal will it. Were is is less apparent is the removal Slew rates (and others). That will have to be added to every board file. We should script that to give a was: is: Change list.

**Comment by davids5** [comment]
Please lets get this reverted - then fix the big picture.

**Comment by xiaoxiang781216** [comment]
@a-lunev let's revert this patch now, and wait your new better fix?

**Comment by a-lunev** [comment]
Good. Let's revert so far.

**Comment by a-lunev** [comment]
> If you change ALL the _n to a value Pnn you cause massive churn that IMO added very little value as it only duplicates information in from the define into the name. - Hence I said I am not a Fan of that change.

As we are going to remove at least GPIO_SPEED_50MHz, GPIO_PUSHPULL, GPIO_PULLUP from all existing pinmap files, it will be a massive churn any case. If we start doing this, I think it is reasonable to do it with the most effective strategy. I think we should avoid a half-hearted massive code refactoring in this case. 
The highest value of using port name+number in the define names (vs _n naming) is in board.h files.
GPIO_SDMMC2_CMD_PA0 define name is much better compared to GPIO_SDMMC2_CMD_1 in board.h.
GPIO_SDMMC2_CMD_PA0 gives you a total picture what the pin is.
GPIO_SDMMC2_CMD_1 is just confusing and error-prune.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by davids5** [comment]
> as we are going to remove at least GPIO_SPEED_50MHz, GPIO_PUSHPULL, GPIO_PULLUP 

I would only remove GPIO_SPEED_xxMHz, not GPIO_PUSHPULL nor GPIO_PULLUP if the setting make make sense for the pin.   Most are correct. 

The port encoding is one more place for an error to happen in is not FNF. It is not generically usable:
What are you going to do on processors have pad names like GPIO_AD_B1_15 call it GPIO_SDMMC2_CMD_GPIO_AD_B0_10.

I would appose the pad encoding in the name change 100%.

**Comment by a-lunev** [comment]
> > as we are going to remove at least GPIO_SPEED_50MHz, GPIO_PUSHPULL, GPIO_PULLUP
> 
> I would only remove GPIO_SPEED_xxMHz, not GPIO_PUSHPULL nor GPIO_PULLUP if the setting make make sense for the pin. Most are correct.

GPIO_PUSHPULL / GPIO_OPENDRAIN possibly should be retained (right now I can not figure out where it could vary along different boards for a particular type of interface).
GPIO_PULLUP depends on PCB circuit design. One of the examples is SDIO. Some boards have external pull-up resistors, some do not. If a board does not have external pull-up resistors, SDIO host of the board should enable its internal pull-up resistors. Otherwise, SDIO host should disable its internal pull-up resistors.
Thus at least GPIO_SPEED and GPIO_PULLUP should be definitely removed from pinmap files.

> The port encoding is one more place for an error to happen in is not FNF. It is not generically usable: What are you going to do on processors have pad names like GPIO_AD_B1_15 call it GPIO_SDMMC2_CMD_GPIO_AD_B0_10.

I would shorten it to GPIO_SDMMC2_CMD_AD_B0_10.

**Comment by davids5** [comment]
> I would shorten it to GPIO_SDMMC2_CMD_AD_B0_10.

No - please no!

The key point that keeps getting missed here is: Once there are no ROOT names in the pin map files.  The perfectly reasonable default of a GPIO_PULLUP on a UART RX can be removed in the board file. If you need to. That is enough.  That is all we need.

**Comment by a-lunev** [comment]
> > I would shorten it to GPIO_SDMMC2_CMD_AD_B0_10.
> 
> No - please no!
> 
> The key point that keeps getting missed here is: Once there are no ROOT names in the pin map files.

As I can see there are not root names in some pin map files for some interfaces. What is the issue with that?

> The perfectly reasonable default of a GPIO_PULLUP on a UART RX can be removed in the board file. If you need to. That is enough. That is all we need.

Do you mean to retain some of reasonable default GPIO_PULLUPs in pin map files and remove the others?

**Comment by davids5** [comment]
> > > I would shorten it to GPIO_SDMMC2_CMD_AD_B0_10.
> > 
> > 
> > No - please no!
> > The key point that keeps getting missed here is: Once there are no ROOT names in the pin map files.
> 
> As I can see there are not root names in some pin map files for some interfaces. What is the issue with that?

None - if there are no root names in the pinmap file than the board file **has** to map it and can use any of the 3 methods discussed above. 

1. Fully re define it.
```
#define GPIO_SDMMC2_CMD (GPIO_ALT|GPIO_AF9|GPIO_SPEED_50MHz|GPIO_PUSHPULL|GPIO_PORTA|GPIO_PIN0)
```
2. Use the NON root name (xxxx_n) and ADD to it.
```
#define GPIO_SDMMC2_CMD (GPIO_SDMMC2_CMD_2|GPIO_SPEED_50MHz|GPIO_PUSHPULL)
```
3. Use the NON root name (xxxx_n) and change it
```
#define ADJ_SLEW_RATE(p) (((p) & ~GPIO_SPEED_MASK) | (GPIO_SPEED_2MHz))
#define GPIO_SPI3_SCK ADJ_SLEW_RATE(GPIO_SPI3_SCK_2) /* PC10 */
```

> 
> > The perfectly reasonable default of a GPIO_PULLUP on a UART RX can be removed in the board file. If you need to. That is enough. That is all we need.
> 
> Do you mean to retain some of the reasonable default GPIO_PULLUPs in pin map files and remove the others (from pin map files)?

Yes.  I think most the PU and Driver type are reasonable.  But we should do an audit.

**Pull request merged**
