### PR TITLE
mm: Move the real implementation of mm_sbrk to sbrk

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
and remove mm_sbrk and kmm_sbrk since it's wrong to expose
sbrk to other heaps except the default userspace heap.

## Impact
No, code refactor

### CODE REVIEW

**Review by masayuki2009 — APPROVED** [review]
LGTM

**Comment by masayuki2009** [comment]
@xiaoxiang781216 

BTW, can you add sabre-6quad:knsh to test CONFIG_BUILD_KERNEL with QEMU?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> 
> BTW, can you add sabre-6quad:knsh to test CONFIG_BUILD_KERNEL with QEMU?

But, sabre-6quad doesn't have any config enable CONFIG_BUILD_KERNEL. Did you boot sabre-6quad with kernel mode sucessfully before?

**Comment by masayuki2009** [comment]
> > @xiaoxiang781216
> > BTW, can you add sabre-6quad:knsh to test CONFIG_BUILD_KERNEL with QEMU?
> 
> But, sabre-6quad doesn't have any config enable CONFIG_BUILD_KERNEL. Did you boot sabre-6quad with kernel mode sucessfully before? It will be great to have a kernel config run with QEMU, so we can verify many kernel only feature without any real hardware.

@xiaoxiang781216 
No, I've never tried CONFIG_BUILD_KERNEL before.
I think you are using dual Cortex-A7 in KERNEL mode as well, so I thought it would be easy to apply the feature to sabre-6quad.

**Comment by xiaoxiang781216** [comment]
No, we use dual Cortex-A7 in FLAT mode.

**Pull request merged**
