### PR TITLE
boards/tm4c129e-launchpad: Expand README.txt

### PR DESCRIPTION
**Pull request by hartmannathan**
## Summary

Expand the README.txt for `tm4c129e-launchpad`.

(The main motivation was to add the elusive `openocd` incantation to flash program this board. However, I also added useful documentation about toolchains, debugging, clocking, and the ICDI virtual serial interface.)

## Impact

Improve documentation.

## Testing

The openocd incantation works. :-)

### CODE REVIEW

**Comment by btashton** [comment]
You might find this PR of interest where I updated the docs for these and then it got stuck 
https://github.com/apache/incubator-nuttx/pull/3604

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Let's ignore the false ci alarm.

**Comment by xiaoxiang781216** [comment]
> You might find this PR of interest where I updated the docs for these and then it got stuck #3604

@hartmannathan could you continue @btashton 's work?

**Comment by hartmannathan** [comment]
> > You might find this PR of interest where I updated the docs for these and then it got stuck #3604
> 
> @hartmannathan could you continue @btashton 's work?

@btashton @xiaoxiang781216 Yes. I am traveling but will be back in a few days and I'll look at it then.

**Pull request merged**
