### PR TITLE
stm32f7:sdmmc defer invalidate until after DMA completion

### PR DESCRIPTION
**Pull request by davids5**
## Summary

   The FAT was not coherent. Resulting in a write failed
   with errno:28 No space left on device.

   It is unclear how the memory is acesses prior to the DMA
   completion. But this restructuring ensures the data
   is coherent.

   This issue was not detected on the stm32h7
## Impact

Random files system failures have been resolved.

## Testing

px4_fmu-v5

### CODE REVIEW

**Review by xiaoxiang781216 — COMMENTED** [review]
@davids5 could you try this PR: https://github.com/apache/incubator-nuttx/pull/4878? I guess it may fix your problem

**Comment by davids5** [comment]
@xiaoxiang781216 - I will test it in a few hrs.....

**Comment by hartmannathan** [comment]
I haven't grokked exactly what the problem is in this particular instance, but one possible issue may occur if buffers are not aligned *and* padded to exact D-Cache line boundaries. From my hazy memory on H7 that's 32 bytes; don't know on F7. I have been bitten by this one in the past:

Why an issue may occur: The "invalidate D-cache" operation basically means "delete the contents of those cache lines." If any other data besides the DMA buffers falls within those cache lines, e.g., variables, newer values of those variables which are in the cache and not yet written to RAM will be lost, leaving older stale values in RAM.

**Comment by xiaoxiang781216** [comment]
Yes, this is what this patch want to fix, @hartmannathan .

**Comment by davids5** [comment]
@xiaoxiang781216 I am trying to wrap my head around how the cache change would make any difference for a 32 byte aligned 512 buffer.

**Comment by davids5** [comment]
@xiaoxiang781216 

I tested  #4878 . It did not fix the issues here in. Moreover it looks incorrect see: https://github.com/apache/incubator-nuttx/pull/4878#pullrequestreview-815194027  it is over reaching and will corrupt adjacent data in a WB usage.

 

```
commit ebc84faaba8973672d870eea2f18be727a84cb01 (HEAD -> px4_firmware_nuttx-10.1.0+-test-cac)
Author: zhuyanlin <zhuyanlin1@xiaomi.com>
Date:   Tue Nov 23 20:27:32 2021 +0800

    arch:cache_invalidate: fix unalign cacheline invalidate
    
    Only invalidate may corrupt data in unalign start and end.
    Use writeback and invalidate instead.
    
    Signed-off-by: zhuyanlin <zhuyanlin1@xiaomi.com>
```

```
nsh> ver all
HW arch: PX4_FMU_V5
HW type: V500
HW version: 0x00000000
HW revision: 0x00000000
FW git-hash: 8e3ee9f6cd9a912222fa187b496d0c033e150eec
FW version: 1.13.0 0 (17629184)
FW git-branch: master
OS: NuttX
OS version: 0.0.0 0 (0)
OS git-hash: ebc84faaba8973672d870eea2f18be727a84cb01
Build datetime: Nov 24 2021 09:31:19
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 000200000000363539373137510100340032
MCU: STM32F76xxx, rev. Z
nsh> ERROR [logger] write failed errno:28 (No space left on device), retrying
ERROR [logger] write failed errno:28 (No space left on device), retrying
```

**Comment by davids5** [comment]
@xiaoxiang781216 - Please merge this.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
