### PR TITLE
arch: xtensa: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by Ouss4** [comment]
@jerpelea under the Xtensa directory there are a few files copyrighted to Espressif.  If you want to change them, Espressif has already signed an SGA.

**Comment by jerpelea** [comment]
@Ouss4 all copyrights are handled locally and will be pushed based on authors

**Review by Ouss4 — APPROVED** [review]

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by jerpelea** [comment]
please ignore tabs and mixed cases for now

**Pull request merged**
