### PR TITLE
drivers/syslog: Prepend Process ID to syslog message 

### PR DESCRIPTION
**Pull request by anchao**
## Summary

drivers/syslog: Prepend Process ID to syslog message 

Signed-off-by: chao.an <anchao@xiaomi.com>

## Impact

syslog

## Testing

```
[   14.618783] Test Initializing...
[   14.618872] Test initialized
->
[   14.618783] [7] Test Initializing...
[   14.618872] [7] Test initialized
```

### CODE REVIEW

**Comment by btashton** [comment]
@anchao I am on board with these changes, but it might be work prefixing the pid and priority number somehow so you know what the field is.  Right now if only one is enabled you cannot tell what is in the log, maybe something like this?

```
[   14.618783] [pid-7] [pri-100] Test Initializing...
[   14.618872] [pid-7] [pri-100] Test initialized
```

**Comment by fjpanag** [comment]
@btashton The priority is logged as string, i.e. `[INFO]`, so I believe it is unambiguous.

Only pid is logged as a plain number. So everything can be clear as to what it refers to, regardless of the configuration.

I have no objection to prefixing pid of course... Just saying that it does not seem necessary to do so.

**Comment by btashton** [comment]
Ah you are right, I was mixing up process priority with debug priority....

**Comment by xiaoxiang781216** [comment]
@anchao please rebase your patch to resolve the conflict.

**Pull request merged**
