### PR TITLE
nuttx/wamr: WAMR configuration based on NSH added

### PR DESCRIPTION
**Pull request by DS-LK**
nuttx/wamr: WAMR configuration based on NSH added

### CODE REVIEW

**Comment by davids5** [comment]
@DS-LK - Please stare the purpose and usage for this config [here](https://github.com/apache/incubator-nuttx/pull/3108#issue-596308899).  
 I only know WAMR as 
image

**Comment by DS-LK** [comment]
> @DS-LK - Please state the purpose and usage for this config [here](https://github.com/apache/incubator-nuttx/pull/3108#issue-596308899).
> I only know WAMR as
> image

**Comment by DS-LK** [comment]
> @DS-LK - Please state the purpose and usage for this config [here](https://github.com/apache/incubator-nuttx/pull/3108#issue-596308899).
> I only know WAMR as
> image

Hi, WAMR (WASM-Micro-Runtime) is a standalone WebAssembly (WASM) Runtime. It supports multiple platforms, including NuttX, and WAMR is already in the incubator -NuttX-apps /interpreters directory. Because WAMR's support for NuttX will continue to improve, I think NuttX needs a simple configuration for WAMR.

**Comment by davids5** [comment]
@DS-LK - Thank you. Please forgive my ignorance. It really helps to have a definition of the TLA and FLA (Three and Four Letter acronym). Please reopen if you want it in.

**Comment by DS-LK** [comment]
> @DS-LK - Thank you. Please forgive my ignorance. It really helps to have a definition of the TLA and FLA (Three and Four Letter acronym). Please reopen if you want it in.

Thank you. Many of the abbreviations have double names, and we don't understand all of them.

**Review by davids5 — APPROVED** [review]
@DS-LK - Thank you!

**Comment by xiaoxiang781216** [comment]
@DS-LK please fetch the latest, rebase and push again to fix the ci failure.

**Comment by DS-LK** [comment]
> @DS-LK please fetch the latest, rebase and push again to fix the ci failure.

ok，Thanks.

**Comment by DS-LK** [comment]
WAMR's Struct Timeval had a type conflict with NuttX, the WAMR community has fixed this. I will temporarily close this PR until the next release of the WAMR community.

**Pull request closed without merging**
