### PR TITLE
Port nuttx to sparc-v8

### PR DESCRIPTION
**Pull request by zouboan**
## Summary
I have modified all the coding style problem
I finished porting NuttX to SPARC V8 last year, Include architecture support code and board support code, I also verified the Tickless OS mode and ELF file separate load on SPARC V8 architecture
## Impact
Someone can run NuttX on AT697F(based on LEON 2)
## Testing
I have verified compile with apps and ELF file separate load.All this work has been tested on real hardware

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@zouboan could you squash all patch into one?

**Comment by zouboan** [comment]
I'm not sure how to operate,but i have delete old branch before i push local code

**Comment by xiaoxiang781216** [comment]
> I'm not sure how to operate,but i have delete old branch before i push local code

try this:
```
git rebase --interactive HEAD~5
and check pick to squash
refine the comment
git push -f origin fft
```

**Comment by zouboan** [comment]
> 

there are
pick dfc0d2f new commit
pick 4749b52 sparc
pick f06c035 new commit
pick a27fe14 new commit
pick 88aba2a sparc-v8
when i do  git rebase --interactive HEAD~5
i't means i need replace them with  "pick to squash" ?

**Comment by zouboan** [comment]
ok,I finally done, now there is only one commit!

**Comment by xiaoxiang781216** [comment]
> ok,I finally done, now there is only one commit!

It's better to update the commit message to reflect the patch by:
```
git commit --amend
```

**Comment by acassis** [comment]
Congratulations @zouboan you did it! Please just change commit message using "git commit --amend" as Mr Xiang suggest, because "new commit" is not a good name for a commit important like this! Hehehe

**Comment by zouboan** [comment]
ok, the commit message has been updated

**Comment by acassis** [comment]
"habemus spark v8" kudos @zouboan

**Comment by zouboan** [comment]
> "habemus spark v8" kudos @zouboan

I will try to support the SMP of leon 5 in future

**Comment by xiaoxiang781216** [comment]
@zouboan could you add sparc-v8 to the daily ci?
You can add the tool installation here:
https://github.com/apache/incubator-nuttx/blob/master/tools/ci/cibuild.sh#L49
and enable build here:
https://github.com/apache/incubator-nuttx/blob/master/tools/ci/testlist/other.dat
https://github.com/apache/incubator-nuttx/blob/master/tools/ci/testlist/all.dat

**Comment by zouboan** [comment]
@xiaoxiang781216 ok, i will try it

**Pull request merged**
