### PR TITLE
.github/workflows: Add nuttx/source to the safe directory

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Report here: https://github.com/apache/incubator-nuttx/pull/6460

## Impact
Fix the CI error

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by qinwei2004** [comment]
fail again
https://github.com/apache/incubator-nuttx/runs/7041873476?check_suite_focus=true
from the fail log, maybe we need to add another directory:
git config --global --add safe.directory /github/workspace/sources/apps

@xiaoxiang781216 @pkarashchenko @btashton

**Comment by btashton** [comment]
Yeah I had suggested we do  this which I think would cover all the repos.
```
git config --global --add safe.directory /github/workspace/sources
```

**Comment by btashton** [comment]
Let's make sure we bring this change over to the apps repo as well.

**Comment by xiaoxiang781216** [comment]
It's here: https://github.com/apache/incubator-nuttx-apps/pull/1210

**Pull request merged**
