### PR TITLE
Use driver-specific spinlock for ESP32 serial driver.

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
This PR replaces the critical sections in ESP32 serial driver by a device specific spin lock.
- See https://github.com/apache/incubator-nuttx/issues/2213
## Impact
ESP32's serial driver in SMP mode.
## Testing
esp32-devkitc:ostest
esp32-devkitc:smp
esp32-devkitc:wapi_smp

### CODE REVIEW

**Comment by Ouss4** [comment]
@xiaoxiang781216 @masayuki2009 please look at: https://github.com/Ouss4/incubator-nuttx/commit/8b8975ea9caaa6538717044ba1b3d977955498f0 if I'm reading the code correctly, there is an `#else` missing there for the case where serial interrupts are suppressed.  

Without that `#else` calls to `esp32_txint` would be called recursively from the same CPU with the spin-lock locked which leads to deadlocks.  @masayuki2009 did you face such deadlocks when you did https://github.com/apache/incubator-nuttx/pull/2830?  I see `cxd56_serial.c` still uses `enter_critical_setction` in `up_txint`.

**Comment by Ouss4** [comment]
I'm still seeing some sporadic deadlocks, like this:

```gdb
#0  up_cpu_pausereq (cpu=1) at common/xtensa_cpupause.c:67
#1  0x400d37e0 in irq_waitlock (cpu=1) at irq/irq_csection.c:127
#2  0x400d3941 in enter_critical_section () at irq/irq_csection.c:350
#3  0x400d89f6 in modifyreg32 (addr=1072955404, clearbits=0, setbits=16386) at common/xtensa_modifyreg32.c:52
#4  0x400d95bb in esp32_txint (dev=<optimized out>, enable=<optimized out>) at chip/esp32_serial.c:1760
#5  0x400f144c in uart_write (filep=<optimized out>, buffer=<optimized out>, buflen=0) at serial/serial.c:1225
#6  0x4014673e in file_write (filep=<optimized out>, buf=0x3ffe0f70, nbytes=1) at vfs/fs_write.c:89
#7  0x400e4430 in nx_write (fd=1, buf=0x3ffe0f70, nbytes=1) at vfs/fs_write.c:138
#8  0x400e4443 in write (fd=1, buf=0x3ffe0f70, nbytes=1) at vfs/fs_write.c:202
#9  0x400deeaf in readline_putc (vtbl=0x3ffe0fd0, ch=<optimized out>) at readline.c:145
#10 0x400df195 in readline_common (vtbl=0x3ffe0fd0, buf=0x3ffcb01c "iperf -c 192.168.1.12 -p 124444", buflen=<optimized out>)
    at readline_common.c:734
#11 0x400def40 in readline (buf=0x3ffcb01c "iperf -c 192.168.1.12 -p 124444", buflen=300, instream=<optimized out>,
    outstream=0x3ffaf854) at readline.c:227
#12 0x400ddb97 in nsh_session (pstate=0x3ffcadb0, login=<optimized out>, argc=<optimized out>, argv=0x3ffe0480) at nsh_session.c:159
#13 0x400da274 in nsh_consolemain (argc=1, argv=0x3ffe0480) at nsh_consolemain.c:100
#14 0x400da224 in nsh_main (argc=1, argv=0x3ffe0480) at nsh_main.c:153
#15 0x400d5fdf in nxtask_startup (entrypt=0x400da1e0 <nsh_main>, argc=1, argv=0x3ffe0480) at sched/task_startup.c:151
#16 0x400d41cb in nxtask_start () at task/task_start.c:130
```
I'll have to debug this a little more.

**Comment by masayuki2009** [comment]
@Ouss4 
In your case, modifyreg32() uses the critical section  API which would cause a deadlock if the driver-specific API took a spinlock. Furthermore, in cxd56_serial.c case, I remember that up_txint() is called recursively. In this case, if we apply the driver-specific spinlock it would also cause a deadlock. (Currently, driver-specific spinlock does not permit recursive lock).

```
gdb) where 
#0 0x0d009aa6 in up_testset2 (lock=lock@entry=0x2d05b0a8 <g_uart1priv+28> "\001") at chip/cxd56_testset.c:53 
#1 0x0d009ab2 in up_testset (lock=lock@entry=0x2d05b0a8 <g_uart1priv+28> "\001") at chip/cxd56_testset.c:120 
#2 0x0d004de8 in spin_lock (lock=0x2d05b0a8 <g_uart1priv+28> "\001") at semaphore/spinlock.c:77 
#3 0x0d00411e in spin_lock_irqsave (lock=lock@entry=0x2d05b0a8 <g_uart1priv+28> "\001") at irq/irq_spinlock.c:103 
#4 0x0d0003e2 in up_txint (dev=0x2d05b050 <g_uart1port>, enable=<optimized out>) at chip/cxd56_serial.c:995 
#5 0x0d007710 in uart_xmitchars (dev=dev@entry=0x2d05b050 <g_uart1port>) at serial/serial_io.c:91 
#6 0x0d0003fa in up_txint (dev=0x2d05b050 <g_uart1port>, enable=<optimized out>) at chip/cxd56_serial.c:1006 
#7 0x0d0074d8 in uart_write (filep=<optimized out>, buffer=0x2d06bba5 "", buflen=0) at serial/serial.c:1225 
#8 0x0d00cc12 in nx_write (fd=<optimized out>, buf=buf@entry=0x2d06bba4, nbytes=nbytes@entry=1) at vfs/fs_write.c:138
#9 0x0d00cc22 in write (fd=<optimized out>, buf=buf@entry=0x2d06bba4, nbytes=nbytes@entry=1) at vfs/fs_write.c:202 
#10 0x0d00886c in lib_fflush (stream=stream@entry=0x2d06bb84, bforce=bforce@entry=1 '\001') at stdio/lib_libfflush.c:117 
#11 0x0d02ea10 in fputs (s=0xd04cc46 <g_nshgreeting> "\nNuttShell (NSH) NuttX-10.1.0\n", stream=0x2d06bb84) at stdio/lib_fputs.c:130 
#12 0x0d01ceb2 in nsh_session (pstate=0x2d06ca60, login=<optimized out>, argc=1, argv=0x2d06bdc8) at nsh_session.c:91 
#13 0x0d01cbd8 in nsh_consolemain (argc=argc@entry=1, argv=argv@entry=0x2d06bdc8) at nsh_consolemain.c:100 
#14 0x0d01cb82 in nsh_main (argc=1, argv=0x2d06bdc8) at nsh_main.c:153 
#15 0x0d007ac2 in nxtask_startup (entrypt=0xd0104ed <spresense_main>, argc=1, argv=<optimized out>) at sched/task_startup.c:151 
#16 0x0d005698 in nxtask_start () at task/task_start.c:130 
```

**Comment by Ouss4** [comment]
@masayuki2009  Thanks for your comment, regarding:

> Furthermore, in cxd56_serial.c case, I remember that up_txint() is called recursively. In this case, if we apply the driver-specific spinlock it would also cause a deadlock.

I think this recursion is only there because of the SUPPRESS_SERIAL_INTS part, where I believe an else is missing.  In normal cases (where we don't suppress serial interrupts) we should just enable interrupts and leave.  This shouldn't recurse.

**Comment by davids5** [comment]
Hi @Ouss4 - I responded in the stm32 PR, that it is my belief that the call has to occur to handle the HW flow control.

**Comment by Ouss4** [comment]
@masayuki2009 could you please check this PR again.  It should be ready.

**Review by masayuki2009 — APPROVED** [review]

**Pull request merged**
