### PR TITLE
Don't generate .depend anymore

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by patacongo** [comment]
We have a problem.  All chackes are failing because the sim tests are not building.  I have the same issue on the PRs that I just submitted.  And on Miguel Herranz PR.  I merged Miguel's anyway because his ESP32 changes have absolutely nothing to do with sim.

By the way, I requested you review of my changes.  That is the removal of CONFIG_FS_WRITABLE that we discussed last week.

**Comment by Ouss4** [comment]
@xiaoxiang781216 we might want to get the quiet part back for this: https://github.com/apache/incubator-nuttx/blob/master/tools/sethost.sh#L214
The checks output is unreadable.

**Comment by Ouss4** [comment]
@xiaoxiang781216 I pulled both this change and the PR from apps to verify that the issue is not similar to the one described in [PR602](https://github.com/apache/incubator-nuttx/pull/602#issuecomment-602104471)
However the problem persisted. I can build other configs (even custom boards) but the boards failing the checks don't build.
In another note, when one of the failing boards is configured, running distclean results in an infinite loop of : 

```
make[2]: Entering directory '/home/ouss4/NuttX/nuttx/graphics/nxglib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ouss4/NuttX/nuttx/graphics/nxglib'
```

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I pulled both this change and the PR from apps to verify that the issue is not similar to the one described in [PR602](https://github.com/apache/incubator-nuttx/pull/602#issuecomment-602104471)
> However the problem persisted. I can build other configs (even custom boards) but the boards failing the checks don't build.
> In another note, when one of the failing boards is configured, running distclean results in an infinite loop of :
> 
> ```
> make[2]: Entering directory '/home/ouss4/NuttX/nuttx/graphics/nxglib'
> make[2]: Nothing to be done for 'all'.
> make[2]: Leaving directory '/home/ouss4/NuttX/nuttx/graphics/nxglib'
> ```

My PR make the fail at graphics/nxglib, I will take time to look at the root cause.

**Comment by patacongo** [comment]
This kind of logic is very common in architecture specific files:

The including file has to some #define setup
Then it includes and architecture specific header file

You will see this a LOT under arch/xyz/include and under arch/src/xyz/hardware.

**Comment by patacongo** [comment]
This is a companion to apps/ PR132.  Both should be merged together when this one passes its PR checks.

**Comment by btashton** [comment]
@xiaoxiang781216 @patacongo This seems to have done something to break a builds.  I see the CI is passing here but I am not quite clear why.  I see lots of these in the logs
`/bin/sh: 1: /__w/incubator-nuttx/incubator-nuttx/nuttx/tools/mkdeps: not found` and I also see some issues locally where it wont build because of issues running kconf tools in a totally clean environment.  When I revert the .depend patch everything goes back to normal.

**Comment by Ouss4** [comment]
@btashton I'm having issues with this as well. By pulling all the changes from apps/ and also the yet to be merged [PR136](https://github.com/apache/incubator-nuttx-apps/pull/136) a lot of the have been resolved.
As for mkdeps, building it manually removes those "not found" messages.
@xiaoxiang781216 one weird issue is that make distclean runs cleanly the first time but generates alot of errors the second time (when everything is clean and no config)
The errors are related to this line https://github.com/apache/incubator-nuttx/blob/master/crypto/Makefile#L96 in all folders with similar Makefile

**Comment by yamt** [comment]
let's see if a revert fixes the CI breakage. https://github.com/apache/incubator-nuttx/pull/610

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 @patacongo This seems to have done something to break a builds. I see the CI is passing here but I am not quite clear why. I see lots of these in the logs
> `/bin/sh: 1: /__w/incubator-nuttx/incubator-nuttx/nuttx/tools/mkdeps: not found` and I also see some issues locally where it wont build because of issues running kconf tools in a totally clean environment. When I revert the .depend patch everything goes back to normal.

I am wondering why this patch can pass ci?

**Comment by xiaoxiang781216** [comment]
> let's see if a revert fixes the CI breakage. #610

@yamt the real PR make the break is this one:
https://github.com/apache/incubator-nuttx-apps/pull/132
But it's also pass the ci test:(

**Comment by Ouss4** [comment]
Now, with reverting, the build is broken.
Other PRs (in apps mostly) were merged after this PR (and its companion in apps).

**Pull request merged**
