### PR TITLE
Sabre6quad netknsh

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR consists of the following 2 commits
  - commit 1: syscall: Fix task_tls_alloc in syscall.csv
  - commit 2: boards: sabre-6quad: Add netknsh/defconfig

## Impact

- None

## Testing

- Tested with qemu-6.2

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
Hmm, it seems that the build failed.

**Comment by xiaoxiang781216** [comment]
> Hmm, it seems that the build failed.

Is it the first ci try to build tcpblaster/udpblaster? look like both examples forget to clean up the temp files.

**Comment by masayuki2009** [comment]
>Is it the first ci try to build tcpblaster/udpblaster? look like both examples forget to clean up the temp files.

Yes for CONFIG_BUILD_KERNEL=y but no for CONFIG_BUILD_FLAT=y (i.e. sabre-6quad:netnsh)

**Comment by masayuki2009** [comment]
Let me try to remove tcpblaster and udpblaster from sabre-6quad:netknsh.

**Comment by xiaoxiang781216** [comment]
How about we fix the problem instead?

**Comment by masayuki2009** [comment]
>How about we fix the problem instead?

@xiaoxiang781216 
I noticed that cibuild.sh -G works but you removed the option in .github/workflows/build.yml

**Comment by xiaoxiang781216** [comment]
> .github/workflows/build.yml

Yes, because I want CI verify that "make distclean" can remove all temporary files.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
I've just sent  https://github.com/apache/incubator-nuttx-apps/pull/1216

**Comment by masayuki2009** [comment]
Let me disable the iperf app until the build system for apps is fixed.

**Pull request merged**
