### PR TITLE
fs/littlefs: set `LFS_NAME_MAX` to `CONFIG_NAME_MAX`

### PR DESCRIPTION
**Pull request by casaroli**
## Summary

In NuttX 7.29, we set `LFS_NAME_MAX` to `NAME_MAX`, however later, when we removed littlefs tree from NuttX tree, this option was not set, leaving the defaults of `255`.

This sets `LFS_NAME_MAX` to `CONFIG_NAME_MAX`.
 
## Impact

Reduces the nonvolatile memory consumption of LFS and probably breaks compatibility with old filesystems that use `LFS_NAME_MAX` = `255`

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by yamt — COMMENTED** [review]
how about introducing a separate config, CONFIG_LFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?

in any case, i suppose this change warrants a warning in release notes.

**Comment by casaroli** [comment]
> how about introducing a separate config, CONFIG_FS_LITTLEFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?
> 
> in any case, i suppose this change warrants a warning in release notes.

Just for reference, from NuttX 7.29 release notes:

>         - LittleFS:  Fix a minor issue found in code review:  (1) Replace
>         printf to finfo/fwarn/ferr, (2) Replace malloc/free to
>         kmm_malloc/kmm_free, (3) define LFS_NAME_MAX to NAME_MAX, (4) Check
>         the big endian using CONFIG_ENDIAN_BIG.  From Xiang Xiao.

**Comment by xiaoxiang781216** [comment]
> how about introducing a separate config, CONFIG_FS_LITTLEFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?
> 
> in any case, i suppose this change warrants a warning in release notes.

It isn't good idea to add new config since if it's different from NAME_MAX, either the buffer will overflow or the name will be truncate.

**Comment by yamt** [comment]
> > how about introducing a separate config, CONFIG_FS_LITTLEFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?
> > in any case, i suppose this change warrants a warning in release notes.
> 
> It isn't good idea to add new config since if it's different from NAME_MAX, either the buffer will overflow or the name will be truncate. So why we add new config which has to be same as NAME_MAX in the first place?

because you might still want to mount old filesystems?

**Comment by xiaoxiang781216** [comment]
> > > how about introducing a separate config, CONFIG_FS_LITTLEFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?
> > > in any case, i suppose this change warrants a warning in release notes.
> > 
> > 
> > It isn't good idea to add new config since if it's different from NAME_MAX, either the buffer will overflow or the name will be truncate. So why we add new config which has to be same as NAME_MAX in the first place?
> 
> because you might still want to mount old filesystems?

This is one reason, another case is mount the different file system and copy from each other. one shared config(NAME_MAX) could avoid the potential issue. Last, it also avoid confuse people.

**Comment by yamt** [comment]
> > > > how about introducing a separate config, CONFIG_FS_LITTLEFS_NAME_MAX, which defaults to 255 or CONFIG_NAME_MAX?
> > > > in any case, i suppose this change warrants a warning in release notes.
> > > 
> > > 
> > > It isn't good idea to add new config since if it's different from NAME_MAX, either the buffer will overflow or the name will be truncate. So why we add new config which has to be same as NAME_MAX in the first place?
> > 
> > 
> > because you might still want to mount old filesystems?
> 
> This is one reason, another case is mount the different file system and copy from each other. one shared config(NAME_MAX) could avoid the potential issue. Last, it also avoid confuse people.

i meant, because you might still want to mount old filesystems, it's better to have a separate config for on-disk structure.

also, i guess it's common to use an external tool to generate filesystem images. such a tool likely has it default to 255.

**Comment by xiaoxiang781216** [comment]
@yamt @casaroli OK, i am fine with either. Do you want to change this patch or merge it as it.

**Pull request merged**
