### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by fjpanag**
## Summary
Just a minor typo fix in mkdeps.

## Impact
N/A

## Testing
N/A

### CODE REVIEW

**Comment by acassis** [comment]
Hi @fjpanag this is not just a Typo, this patch is removing the "stm32_pwr_enableoverdrive()". If stm32_pwr_enableoverdrive() is not working, then we need to fix it, instead of removing it. Maybe someone at ST could help us.

**Comment by fjpanag** [comment]
@acassis 
??? I don't understand... The stm32_pwr_enableoverdrive is already removed in #1841... And nevertheless this is not what Github showed me when I created the PR...

Can we fix that? Or should I make a new PR?

**Comment by fjpanag** [comment]
Hmmm... Indeed it shows 3 commits, but only one file changed...

image

**Comment by acassis** [comment]
> @acassis
> ??? I don't understand... The stm32_pwr_enableoverdrive is already removed in #1841... And nevertheless this is not what Github showed me when I created the PR...
> 
> Can we fix that? Or should I make a new PR?

I think forgot to sync your branck with mainline before submitting this PR.

Normally I do this way: https://acassis.wordpress.com/2020/03/31/syncing-my-github-fork/

After submitting your PR and it was incorporated on upstream, you need to pull our upstream branch and sync your master with it. Case your master will with your original patch you can "git reset --hard" your master to the last upstream commit and give a git push -f to rewind your master (since only you use your master it is not an issue)

**Comment by fjpanag** [comment]
I actually synced my repo to upstream, but maybe I did something wrong... Nevertheless, I think it is fixed now.

(Thank you for your advice on how to fix this!)

**Comment by acassis** [comment]
Thank you Fotis, it is fine now!

**Pull request merged**
