### PR TITLE
Update licenses to Apache 2.0

### PR DESCRIPTION
**Pull request by Palmitoxico**
Update the license of all files that I own do the Apache License 2.0.

I also give permission to change the license of `drivers/analog/dac7554.c` and `drivers/rf/Make.defs` to the Apache License 2.0 (copyright shared with other contributors).

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@Palmitoxico could you fix the follow nxstyle warning:
```
Warning: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/include/nuttx/rf/ioctl.h:23:1: warning: #include outside of 'Included Files' section
Warning: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/include/nuttx/rf/ioctl.h:24:1: warning: #include outside of 'Included Files' section
```

**Comment by Palmitoxico** [comment]
done

**Comment by acassis** [comment]
Hi @Palmitoxico please don't include your copyright in the header, all files should include only the license without user copyright name. I need to create a Copyright file to include the name of all contributors

**Comment by Palmitoxico** [comment]
Hi Alan,

That is a little unusual, I haven't followed the mailing list closely lately but is this a requirement for Apache projects or just nuttx? With no user name / email on source files it makes getting in contact with its respective maintainers not so straightforward.

**Comment by acassis** [comment]
> Hi Alan,
> 
> That is a little unusual, I haven't followed the mailing list closely lately but is this a requirement for Apache projects or just nuttx? With no user name / email on source files it makes getting in contact with its respective maintainers not so straightforward.

yes, according with @justinmclean the projects on Apache Software Foundation (ASF) only have apache license on each file without the contributors names. It is because ASF needs to have control over it in case some legal action.

**Comment by xiaoxiang781216** [comment]
maybe we can add something like this:
https://github.com/torvalds/linux/blob/master/MAINTAINERS

**Comment by justinmclean** [comment]
Hi,
> yes, according with @justinmclean <https://github.com/justinmclean> the projects on Apache Software Foundation (ASF) only have apache license on each file without the contributors names. It is because ASF needs to have control over it in case some legal action.
> 
It more that the file belongs to the project and not one individual person, over time people can come and go on a project. Contributors names are recorded in version control.

Thanks,
Justin

**Comment by Palmitoxico** [comment]
Ok, copyright header removed.

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Pull request merged**
