### PR TITLE
crypto: fix compile error.

### PR DESCRIPTION
**Pull request by CV-Bowen**
## Summary
Compile error when enable CONFIG_CRYPTO_AES

In file included from drivers_initialize.c:25:0:
/home/wangbowen/project/community/wbw_nuttx/nuttx/include/nuttx/crypto/crypto.h:74:20: error: expected ')' before 'void'

## Testing
local test with tlsr8278adk80d:nsh

### CODE REVIEW

**Comment by pkarashchenko** [comment]
Maybe better to switch keysize to size_t?

**Comment by CV-Bowen** [comment]
> Maybe better to switch keysize to size_t?

Done， i am not sure your meaning, do you mean switch type of keysize to size_t ob basis of this PR? If yes, done.

**Comment by pkarashchenko** [comment]
> > Maybe better to switch keysize to size_t?
> 
> Done， i am not sure your meaning, do you mean switch type of keysize to size_t on basis of this PR? If yes, done.

Yes. I meant that if we change to size_t then we do not need stdint.h. and with stdint.h we need ifndef ASSEMBLY wrapper

**Comment by CV-Bowen** [comment]
> > > Maybe better to switch keysize to size_t?
> > 
> > 
> > Done， i am not sure your meaning, do you mean switch type of keysize to size_t on basis of this PR? If yes, done.
> 
> Yes. I meant that if we change to size_t then we do not need stdint.h. and with stdint.h we need ifndef ASSEMBLY wrapper

I have tried only switch uint32_t to size_t, but still have compile error. In my opinion, crypto.h is the first included file by drivers_initialize.c, and crypto.h use FAR, uint32_t/size_t, this is the reason for compile error.

**Comment by pkarashchenko** [comment]
I definitely know that stdint.h can be include in assembly. I will check maybe sys/types.h is better

**Comment by pkarashchenko** [comment]
@CV-Bowen please check https://github.com/apache/incubator-nuttx/pull/6257

**Comment by CV-Bowen** [comment]
> @CV-Bowen please check #6257

Good.

**Pull request merged**
