### PR TITLE
Fix armv7-a L2CC and apply the code to the sabre-6quad board

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary
- This PR fixes style warnings and compile erros in arm_l2cc_pl310.c and l2cc_pl310.h
- Then I applied the code to the sabre-6quad board
- Also, I removed unnecessary d-cache operation to make boot fast

## Impact
- armv7-a with L2CC
- sabre-6quad:nsh and sabre-6quad:smp

## Testing
- Tested with sabre-6quad:smp (QEMU and dev board)
- Tested with sabre-6quad:nsh (QEMU and dev board)

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hmmm, the following error happenned but the error does not relate to this PR.

```
====================================================================================
Configuration/Tool: stm32f429i-disco/nxwm,CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Disabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
  Enabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
  Building NuttX...
src/chexcalculator.cxx: In member function 'void NxWM::CHexCalculator::updateText()':
Error: src/chexcalculator.cxx:676:38: error: expected ')' before 'PRI64X'
  676 |       std::snprintf(buffer, 24, "%16" PRI64X, m_accum);
      |                    ~                 ^~~~~~~
      |                                      )
Error: src/chexcalculator.cxx:680:36: error: expected ')' before 'PRI64d'
  680 |       std::snprintf(buffer, 24, "%" PRI64d, m_accum);
      |                    ~               ^~~~~~~
      |                                    )
```

**Comment by yamt** [comment]
@masayuki2009 https://github.com/apache/incubator-nuttx-apps/pull/479

**Comment by masayuki2009** [comment]
> @masayuki2009 [apache/incubator-nuttx-apps#479](https://github.com/apache/incubator-nuttx-apps/pull/479)

Thanks!

**Comment by jerpelea** [comment]
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@btashton 
Could you backport this PR to the 10.0 branch?

**Comment by btashton** [comment]
> @btashton 
> Could you backport this PR to the 10.0 branch?
> 

Sure I'll go through these tonight there are a few more as well. I already did this for these two, but if you add the label they will show up in my query so I won't miss them.

**Comment by masayuki2009** [comment]
> > @btashton
> > Could you backport this PR to the 10.0 branch?
> 
> Sure I'll go through these tonight there are a few more as well. I already did this for these two, but if you add the label they will show up in my query so I won't miss them.

@btashton 
Ok, got it.

**Pull request merged**
