### PR TITLE
Samd5e5 - progmem

### PR DESCRIPTION
**Pull request by leomar95**
## Summary
arch: samd5e5:
- Add MTD progmem support.
- NVM USER PAGE IOCTLs support.

boards: metro-m4  Add support for:

- SmartFS inicialization.
- AT24 EEPROM.
- GPIO dev support.
- BQ27426 gauge inicialization.

drives: power
- Add BQ27426 fuel gauge support.

## Impact
- New features available.

## Testing
- Build check only.

Signed-off-by: Leomar Mateus Radke  <leomar@falker.com.br>

### CODE REVIEW

**Comment by acassis** [comment]
Hi @leomar95 there is something wrong with your commit, it is bring 51 commits on it from other people. I suggest you to fork a clean "incubator-nuttx" on github and yes it instead mixing bitbucket and github.

**Comment by patacongo** [comment]
> 
> 
> Hi @leomar95 there is something wrong with your commit, it is bring 51 commits on it from other people. I suggest you to fork a clean "incubator-nuttx" on github and use it instead mixing bitbucket and github.

Bitbucket if just a mirror of github.  Same repository (except Bitbucket is read-only).

I think the PR really just needs to be rebased:

* `git checkout master`
* `git pull upstream master`
* `git check <branch>`
* `git rebase master`
* `git push -f origin <branch>`

**Comment by leomar95** [comment]
> > Hi @leomar95 there is something wrong with your commit, it is bring 51 commits on it from other people. I suggest you to fork a clean "incubator-nuttx" on github and use it instead mixing bitbucket and github.
> 
> Bitbucket is just a mirror of github. Same repository (except Bitbucket is read-only).
> 
> I think the PR really just needs to be rebased:
> 
> * `git checkout master`
> * `git pull upstream master`
> * `git check <branch>`
> * `git rebase master`
> * `git push -f origin <branch>`

I tried these steps, but it didn't work for #1618

**Comment by patacongo** [comment]
> I tried these steps, but it didn't work for #1618

It looks like your also did some 'git merge' .  Merging and rebasing are incompatible because merging screws up the history.  You should rebase only so that you changes are always applied on top of master.  Once you merge, you can never recover the clean branch.  You would have to start over like:

* git -m <oldcode>
* git checkout master
* git pull upstream master
* git checkout -b <newcode>
* git cherry-pick <commits>
* git push -f origin <newcode>

That will re-create a clean branch with only your last changes on top of master.

So, th

**Comment by leomar95** [comment]
> > I tried these steps, but it didn't work for #1618
> 
> It looks like your also did some 'git merge' . Merging and rebasing are incompatible because merging screws up the history. You should rebase only so that you changes are always applied on top of master. Once you merge, you can never recover the clean branch. You would have to start over like:
> 
> * git -m
> * git checkout master
> * git pull upstream master
> * git checkout -b
> * git cherry-pick
> * git push -f origin
> 
> That will re-create a clean branch with only your last changes on top of master.
> 
> So, th

Thanks for your support. I tried your tutorial, but wasn't clear to me. So, i decided with this:
* reset mybranch - git reset origin/master
* git checkout master
* git pull upstream master
* git rebase -i master --> drop the merge commits
* git checkout mybranch
* git rebase master
* git push -f 

It's worked in #1618

**Pull request closed without merging**
