### PR TITLE
Revert "fs: Support the root file system attributes(mode, uid, gid and time) "

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR reverts apache/incubator-nuttx#4118 
- Because there are critical boot issues.

## Impact

- None

## Testing

- N/A

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you share more detailed error info?

**Comment by masayuki2009** [comment]
> @masayuki2009 could you share more detailed error info?

@xiaoxiang781216 
https://github.com/apache/incubator-nuttx/pull/4118#issuecomment-880097209

**Comment by xiaoxiang781216** [comment]
Sorry, I miss the message in that PR. From the panic log, it's enough to just revert "Revert "fs: Move umask to task_info_s". I will investigate the second patch in the real hardware.

**Comment by xiaoxiang781216** [comment]
The root cause is https://github.com/apache/incubator-nuttx/pull/4048 forget to intiailize the idle task's tl_task. I will provide a patch to fix it tonight.

**Review by yamt — APPROVED** [review]

**Comment by yamt** [comment]
@xiaoxiang781216 i feel it makes more sense to revert this for now until your fix gets ready. but it's up to you.

**Comment by xiaoxiang781216** [comment]
Fix here: https://github.com/apache/incubator-nuttx/pull/4158

**Comment by acassis** [comment]
Converted to Draft to avoid people to merger unintentionally

**Comment by masayuki2009** [comment]
The issue was fixed by
https://github.com/apache/incubator-nuttx/pull/4161

**Pull request closed without merging**
