### PR TITLE
libc: Add quick_exit/at_quick_exit declaration to make libcxx happy

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
will provide the real implementation later

### CODE REVIEW

**Comment by yamt** [comment]
my understanding is that:
* this is necessary only if _LIBCPP_HAS_QUICK_EXIT is defined
* _LIBCPP_HAS_QUICK_EXIT should not be defined for nuttx

am i missing something?

**Comment by xiaoxiang781216** [comment]
> my understanding is that:
> 
> * this is necessary only if _LIBCPP_HAS_QUICK_EXIT is defined
> * _LIBCPP_HAS_QUICK_EXIT should not be defined for nuttx
> 
> am i missing something?

Yes, it's true on the real hardware. But it's more complex on simulator(both Linux and macOS) because libcxx has the preprocess logic to detect the compiling target and unfortunately libcxx detect sim target is Linux/macOS but not NuttX.

**Review by yamt — CHANGES_REQUESTED** [review]
in that case, libcxx or sim should be fixed instead.

**Comment by xiaoxiang781216** [comment]
We already implement quick_exit/at_quick_exit in local repo, but hasn't enough free time to upstream yet. This patch just let people can work with libcxx before the upstream.

**Comment by yamt** [comment]
i fixed the underlying problem (libcxx detects wrong set of features) in https://github.com/apache/incubator-nuttx/pull/2063.
this should not be necessry with it.

**Pull request closed without merging**
