### PR TITLE
Nxstyle

### PR DESCRIPTION
**Pull request by johannes-nivus**
Please review. Should address Issue #120, and adds column position checks for right of code comments.

### CODE REVIEW

**Comment by patacongo** [comment]
Since you do not appear to have confidence in my ability to review code, I will has @xiaoxiang781216 to please review and merge.

**Comment by johannes-nivus** [comment]
I'm quite sure you have, but I lack self confidence. And I'm sure I hid a bug somewhere, as often.
Nevertheless I will do some test with your proposed script setup, but I thought you have something similar out of the box to test nxstyle. That's one of the reasons I requested you(!) to review before I file the PR.

**Comment by johannes-nivus** [comment]
And again false positives with another test set...
Only warnings, but I need to fix them. It's late today, I will continue tomorrow.
Please postpone merging.

**Comment by johannes-nivus** [comment]
@patacongo @xiaoxiang781216 What do you think?
Is \sched\semaphore\sem_holder.c:445 an error or is this acceptable?
The backslash after the comment is bothering my current version:

`
#if 0 /* Need to revisit this, but these assumptions seem to be untrue -- \
       * OR there is a bug??? */
`

**Comment by johannes-nivus** [comment]
I answer myself: The backslash is just part of the comment, so it must be ignored.

**Comment by davids5** [comment]
@johannes-nivus - If you run ito more of these it would be of great value, if you would share the section of code that fails and where you think the issues in in nxstyle. By having that context we can add more value here.

**Comment by patacongo** [comment]
> @patacongo @xiaoxiang781216 What do you think?
> Is \sched\semaphore\sem_holder.c:445 an error or is this acceptable?
> The backslash after the comment is bothering my current version:
> 
> `#if 0 /* Need to revisit this, but these assumptions seem to be untrue -- \`
> ` * OR there is a bug??? */`

The backslash should be removed from sem_holder.c.  It is incorrect.

**Comment by johannes-nivus** [comment]
Then I should allow only single-line right of code comments in case of any other than #define preprocessor lines?
I've already seen at least one multiline right of code comment next to #endif also.

**Comment by patacongo** [comment]
The are okay everywhere except for #if type commands.

The line continuation '\' should not be used anywhere in a C file except for in multiple line definitions.

It is incorrect to continue a C comments use \ at the end of one line of the multi-line comment.

it is not the right hand comment that is the issue, it is the use of \

**Comment by patacongo** [comment]
You are familiar with the coding standard document, correct?   https://cwiki.apache.org/confluence/display/NUTTX/Coding+Standard

That is really the specification for nxstyle.  Make sure that anything you do is consistent with and required by that document.

**Comment by johannes-nivus** [comment]
> 
> 
> You are familiar with the coding standard document, correct? https://cwiki.apache.org/confluence/display/NUTTX/Coding+Standard
> 
> That is really the specification for nxstyle. Make sure that anything you do is consistent with and required by that document.

Yes I am (and I always look up the cases I'm modifying/implementing), but I haven't found an paragraph were it's explicitly stated when multiline comments right of code are allowed.
Perhaps I missed it...

**Comment by patacongo** [comment]
>  haven't found an paragraph were it's explicitly stated when multiline comments right of code are allowed.

If they are not prohibited, then they are allowed.  There is much about C programming that is not discussed in the coding standard.

This is the same argument for accepting   #504 : If the kind of indentation that YAMT wanted to do is not explictly prohibited, then it is permitted.

If we find controversial things taht should be prohibited, then we must update the coding style to add the prohibition.

**Comment by johannes-nivus** [comment]
I'm confident with the changes so far.
Running on all c files of sched/ gives the following additional lines:

sched\task\task_vfork.c:340:38: warning: Wrong column position of comment right of code
sched\semaphore\sem_holder.c:445:6: error: No multiline comment right of code allowed here
sched\irq\irq_procfs.c:98:29: warning: Wrong column position of comment right of code

The other output is identical to current master.

include\nuttx\can\can.h passes

Please review and merge if acceptable.

**Comment by patacongo** [comment]
Hmmm... there is discussion in the CS document.  I stand corrected:

"Comments to the Right of Statements. Comments to the right of statements in C source files are discouraged. If such comments are used, they should be (1) very short so that they do not exceed the line width (typically 78 characters), (2) fit on one line, and (3) be aligned so that the comment begins in the same comment on each line. "

It does explicitly prohibit multiple line comments to the right!  That, unfortunately is not realizable.  You simultaneously limit line width, allow comments to the right, and force right hand comments to be a single line.  That doesn't make sense.

Within C code, I have no problem with this prohibitioin.  But in #defines and data definitions, it is essential to provide sufficient information for item on a line-by-line basis.

In general, we must avoid problems by change the coding standard to match the code or tools.  That just opens a Pandora's box.  But we can make well considered and agreed to changes in the coding standard if necessary.

**Comment by patacongo** [comment]
> sched\task\task_vfork.c:340:38: warning: Wrong column position of comment right of code
> sched\semaphore\sem_holder.c:445:6: error: No multiline comment right of code allowed here
> sched\irq\irq_procfs.c:98:29: warning: Wrong column position of comment right of code

PR #507 and #505 should resolve all of these.

**Comment by patacongo** [comment]
One changed behavior I am seeing is for example with this code snippet:

             case RECORD_EXT_SEGADDR: /* Extended segment address record */
               /* The address specified by the data field is multiplied by 16
                * (shifted 4 bits left) and added to the subsequent data record
                * addresses. This allows addressing of up to a megabyte of

nxstyle in the past would have claimed that I need a blank line before the (second) comment.  Now it complains that the second "right hand" comment is not aligned properly.  Both are correct complaints, but the old one was  more interpretable.  Both are fixed in the same way... by adding the blank like before the comment.

             case RECORD_EXT_SEGADDR: /* Extended segment address record */
    +
               /* The address specified by the data field is multiplied by 16
                * (shifted 4 bits left) and added to the subsequent data record
                * addresses. This allows addressing of up to a megabyte of

I don't think that there is a problem here, just a change in behavior.

BTW:  I think you did a great job!  Feel free to add additional functionality to nxstyle.

**Comment by johannes-nivus** [comment]
@patacongo Thanks alot.
Concerning the changed behavior please see #522 
@xiaoxiang781216 
I had a look at #459 that looks really awful. Relax the checks for position of comments? Or keep it as it is?

**Comment by xiaoxiang781216** [comment]
> @patacongo Thanks alot.
> Concerning the changed behavior please see #522
> @xiaoxiang781216
> I had a look at #459 that looks really awful. Relax the checks for position of comments? Or keep it as it is?

The final authorities is @patacongo, both selection is fine for me. Actually I don't really care so much detailed coding style.

**Comment by patacongo** [comment]
I don't have technical concerns.  I believe that the two possible causes of the prblem are indistinguishable.  They important thing is that the issur was found.

If you like you could  change the rpeorted error to indicate that either the right hand comment was not aligned  correctly OR that a blank line is needed.

**Comment by johannes-nivus** [comment]
> 
> If you like you could change the rpeorted error to indicate that either the right hand comment was not aligned correctly OR that a blank line is needed.

I've already done that. As mentioned please see #522

**Comment by patacongo** [comment]
@johannes-nivus I have been trying to contact me via private email.  Can you check the email is being blocked?  Or provide me another contact email?

**Pull request merged**
