### PR TITLE
Fixes build issues associated with ARMv7-m mpu source files.

### PR DESCRIPTION
**Pull request by rippetoej**
As per the discussion the mailing list, this fixes the build issues associated with non-conditional inclusion of ARMv7-m mpu source files. 

Summary of changes
- inline functions within mpu.h converted to macros or moved to up_mpu.c
- mpu.h and up_mpu.c are now conditionally included in build via CONFIG_ARM_MPU

For each chip, I selected a test config and ran flat builds with and without the mpu enabled. When a configuration existed that allowed me to perform a protected build, I check that this completed successfully as well. 

Chips affected by these changes
- imxrt
- kinetis
- lpc17xx
- lpc43xx
- lpc54xx
- sam34
- stm32
- stm32f7
- stm32h7
- stm32l4
- tiva
- xmc4

### CODE REVIEW

**Comment by Ouss4** [comment]
It's not only the style check that failed. There are other build failures.

**Comment by rippetoej** [comment]
@davids5 there were errors when I ran nxstyle against the code, but they were on already existing code. They were mostly all issues related to long lines or spacing of comments to the right of #defines. I thought that fixing them would introduce a lot of noise to the PR. 

I took a quick look at the config that is failing and it appears that MPU support is not enabled. Should I enable it and push the change?

The rest of the builds appear to have all been canceled.

**Comment by yamt** [comment]
sam4cm_cpuindex.c usage seems valid.
i guess register definitions should be provided regardless of CONFIG_ARM_MPU.

wrt nxstyle errors, you can fix them in a separate commit and push them together.

**Comment by yamt** [comment]
ML reference: https://www.mail-archive.com/dev@nuttx.apache.org/msg02794.html

**Comment by rippetoej** [comment]
> sam4cm_cpuindex.c usage seems valid.
> i guess register definitions should be provided regardless of CONFIG_ARM_MPU.

I'm not familiar with the sam4 series or how it is used with SMP here, so if this is what needs to happen I can make the change. In the interest of discussion, it looks like the FPU is exclusive to the CM4P1 core. Could that be another avenue for determining the executing core?

**Comment by rippetoej** [comment]
checkpatch.sh is giving me a few stubborn errors I can't seem to work out

`arch/arm/src/armv7-m/mpu.h:137:65: warning: Wrong column position of comment right of code`
It doesn't like the way the comments are lined up, but the current formatting makes sense.

`arch/arm/src/stm32/stm32_allocateheap.c:106:3: error: Small odd alignment`
Indentation of preprocessor statements seems to be throwing off nxstyle here. Here is the line in question 

```
#if defined(CONFIG_STM32_STM32L15XX)

   /* Set the end of system SRAM */

#  define SRAM1_END CONFIG_RAM_END
```
The comment is lined up with the edge of 'define' starting at column 4. Deleting one space preceding the comment makes the error go away, but now the comment is not lined up with the define (which breaks coding standard rules right?) I have a lot of this same error in stm32_allocateheap.c  

`arch/arm/src/stm32/stm32_allocateheap.c:110:3: error: Bad comment alignment`
This happens with every multi-line comment preceding an indented preprocessor statement. What am I missing here?

Thanks for the help!

**Comment by davids5** [comment]
> This happens with every multi-line comment preceding an indented preprocessor statement. What am I missing here?

@rippetoej Would you laugh if I said a good formatting tool? :)

Things I can tell you are that a blank line resets the column expectation for right col positions.

@johannes-nivus can you lend a hand here or see if nxstyle can be fixed.

**Comment by johannes-nivus** [comment]
@davids5 I will have a look tomorrow morning.
About 07:00 UTC

**Comment by johannes-nivus** [comment]
@davids5 @rippetoej 
Most of the style violations (I looked at) are violations.
Concerning stm32_allocateheap.c:
The starting / of a comment needs to be on an even coloumn. (Except for right of code comments.)
Concerning mpu.h:
Right of code comments are to be aligned, when not separated by an empty line or a line without comment.
There are really some obvious violations there (109/142/150).
136/137/138 is a bit tricky, the only ways to please nxstyle would be adding an empty line, or align the comments (which increases line length).
```
#  define MPU_RASR_TEX_MASK     (7 << MPU_RASR_TEX_SHIFT)
#    define MPU_RASR_TEX_SO     (0 << MPU_RASR_TEX_SHIFT)        /* Strongly Ordered */
#    define MPU_RASR_TEX_NOR    (1 << MPU_RASR_TEX_SHIFT)        /* Normal */
#    define MPU_RASR_TEX_DEV    (2 << MPU_RASR_TEX_SHIFT)        /* Device */
#    define MPU_RASR_TEX_BB(bb) ((4|(bb)) << MPU_RASR_TEX_SHIFT) /* Normal BB AA */

#      define MPU_RASR_CP_NC    (0)  /* Non-cacheable */
#      define MPU_RASR_CP_WBRA  (1)  /* Write back, write and Read- Allocate */
#      define MPU_RASR_CP_WT    (2)  /* Write through, no Write-Allocate */
#      define MPU_RASR_CP_WB    (4)  /* Write back, no Write-Allocate */
#  define MPU_RASR_AP_SHIFT     (24) /* Bits 24-26: Access permission */
```

**Comment by davids5** [comment]
@johannes-nivus Thank you so much for looking into this! 

In defines only can we look at tracking the position of ")" and the offset to the "/*" and do the reset on the index of (line[n-1],")")  < (line[n],")") and if the offset of "/" == the last offset accept it?

So the following would pass
```
#  define MPU_RASR_TEX_MASK     (7 << MPU_RASR_TEX_SHIFT)
#    define MPU_RASR_TEX_SO     (0 << MPU_RASR_TEX_SHIFT)  /* Strongly Ordered */
#    define MPU_RASR_TEX_NOR    (1 << MPU_RASR_TEX_SHIFT)  /* Normal */
#    define MPU_RASR_TEX_DEV    (2 << MPU_RASR_TEX_SHIFT)  /* Device */
#    define MPU_RASR_TEX_BB(bb) ((4|(bb)) << MPU_RASR_TEX_SHIFT)  /* Normal BB AA */

#      define MPU_RASR_CP_NC    (0)  /* Non-cacheable */
#      define MPU_RASR_CP_WBRA  (1)  /* Write back, write and Read- Allocate */
#      define MPU_RASR_CP_WT    (2)  /* Write through, no Write-Allocate */
#      define MPU_RASR_CP_WB    (4)  /* Write back, no Write-Allocate */
#  define MPU_RASR_AP_SHIFT     (24) /* Bits 24-26: Access permission */
```

**Comment by rippetoej** [comment]
@johannes-nivus @davids5 
> Concerning stm32_allocateheap.c:
> The starting / of a comment needs to be on an even coloumn. (Except for right of code comments.)

The coding standard states that a comment should follow the indentation rules for the code below it. Since the code here is an indented preprocessor statement, the spacing ends up being an odd number because of the '#' character. Is my interpretation of this wrong?

> Concerning mpu.h:
> Right of code comments are to be aligned, when not separated by an empty line or a line without comment.
> There are really some obvious violations there (109/142/150).
> 136/137/138 is a bit tricky, the only ways to please nxstyle would be adding an empty line, or align the comments (which increases line length).

Is there a preferred method for solving this issue? The pattern across NuttX in register definitions seems to be only placing a space between defines for new registers. Adding in a space to appease nxstyle at the expense of an established design pattern doesn't seem great. 

What about checking for indentation of #define statements? If the current comment lies on a line at a different level of indentation than the previous comment (as indicated by the number of spaces between the '#' and the 'define'), reset the alignment. This would prevent you from having to insert a space or extend the line while allowing differently indented blocks to have separate comment alignment.

**Comment by rippetoej** [comment]
@johannes-nivus I forgot to thank you for looking over this for me. I appreciate the time!

**Comment by johannes-nivus** [comment]
> The coding standard states that a comment should follow the indentation rules for the code below it. Since the code here is an indented preprocessor statement, the spacing ends up being an odd number because of the '#' character. Is my interpretation of this wrong?
> 
I think your Interpretation is wrong:
Without indentation the starting / would be below the #, one column before the macro text.  With indent 2 the starting / is also 2 columns indented, which means also one column before the macro text.

@davids5 I would prefer my suggestion, with the aligned comments for the TEX bitfields because they're related. But I don't like the need for the empty line because the options belong to the line above the empty line. I need to think about the idea of @rippetoej, this could make sense, but is quite specific.

**Comment by rippetoej** [comment]
> I think your Interpretation is wrong:
> Without indentation the starting / would be below the #, one column before the macro text. With indent 2 the starting / is also 2 columns indented, which means also one column before the macro text.

So what you are saying is that, for proprocessor statements, comments are aligned with the # as the starting point and not the start of the text. As an example:

```
/* comment */  <-- aligned with # as expected
#ifdef  SOME_CONDITION
  /* Correct aligned */  <-- indentation of 2 spaces, aligned on #
#  define SOME_NAME1
   /* Incorrectly aligned */  <-- indentation of 3 spaces, aligned on macro text
#  define SOME_NAME2
#endif
```

Personally I think aligning the comment with the "define" here looks better than obeying the standard 2 space level indentation. It holds better to the idea that we want to align comments with the statement below them. However, I can see this simply being my personal preference.

**Comment by rippetoej** [comment]
Should I wait on this until changes are potentially made to nxstyle? Or should I just make whatever changes will pass the checks?  I feel like this is a fairly important bug fix that should be in the 9.0 release.

**Comment by xiaoxiang781216** [comment]
> @davids5 @johannes-nivus Should I wait on this until changes are potentially made to nxstyle? Or should I just make whatever changes will pass the checks? I feel like this is a fairly important bug fix that should be in the 9.0 release.

@rippetoej but arm-5 has the compiler error which must be fixed before merging.

**Comment by xiaoxiang781216** [comment]
@rippetoej it's better to merge "MPU register definitions included regardless of CONFIG_ARM_MPU setting" into "Fixes build issues associated with ARMv7-m mpu support files" to ensure no break between the patch. You can:
git rebase --interactive HEAD~3
and than reoder and squash the patch
git push -f ...

**Comment by rippetoej** [comment]
@xiaoxiang781216 Good point!  I will do that now.

**Comment by Ouss4** [comment]
The build failure was addressed, the style errors can be silenced but that would either extend the ruler or introduce violations.
Is there any reason to hold this any longer?

**Comment by xiaoxiang781216** [comment]
Yes, let's merge it.

**Pull request merged**
