### PR TITLE
Build simplification

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by Ouss4** [comment]
@xiaoxiang781216 The driver folder under boards is not really a "dummy".  It is not used by any 
board other than the Sony's CXD56 but it can come in handy (I think there were some talks to use it with the boards/STM32 when Matias re-organized the common code)

As you can see it's also handled by the build system (part of `dirlinks`).
https://github.com/apache/incubator-nuttx/blob/23668a4b9b3c15c7367ff21befb4a6f48d01ffb7/tools/Makefile.unix#L310-L314

**Comment by xiaoxiang781216** [comment]
> As you can see it's also handled by the buil

Yes, I know this pattern. This patch just try to reduce the empty boards/arch/chip/drivers for the chip which don't utilize the common chip drivers:
https://github.com/apache/incubator-nuttx/pull/1095/commits/01a50cba731c03f20a787f8199c86a8f35f4f73c#diff-043fcc977f97645d33de793ab09bd262R124-R126
The chip author has two choice:
1.Create boards/arch/chip/drivers folder and put the drivers shared acrossing the board here
2.Let's build system provide a link from drivers/platform to drivers/dummy
The similar approach is used for boards/arch/chip/common and boards/dummy.

**Comment by Ouss4** [comment]
Okay, I get it.  Github didn't help with " boards/arm/a1x/drivers/Kconfig → drivers/dummy/Kconfig"

> The similar approach is used for boards/arch/chip/common and boards/dummy.

boards/arch/chip/common is a little different though, as the Makefile tests if it exists then decides how to link boards/arch/chip/src.  Are you going to change that?

**Comment by xiaoxiang781216** [comment]
> Okay, I get it. Github didn't help with " boards/arm/a1x/drivers/Kconfig → drivers/dummy/Kconfig"
> 
> > The similar approach is used for boards/arch/chip/common and boards/dummy.
> 
> boards/arch/chip/common is a little different though, as the Makefile tests if it exists then decides how to link boards/arch/chip/src. Are you going to change that?

No, it's simple to assign BOARD_DRIVERS_DIR to the different value at the first place and then avoid if/else in the Makefile.unix. The case for common driver is more complicated due to the different number of link need to be created.

**Pull request merged**
