### PR TITLE
CDC ECM Ethernet over USB High Speed for SAMA5D36-Xplained

### PR DESCRIPTION
**Pull request by adamfeuer**
### Summary

* Adds CDC ECM Ethernet over USB High Speed for SAMA5D36-Xplained (and maybe other boards) (most of the code was there already, but didn't work out of the box for the SAMA5D36-Xplained)
* Only SAMA5D36-Xplained has been tested so far

### Impact

* None if you don't use the CDC ECM Ethernet driver
* On SAMA5D36-Xplained, this adds high-speed Internet connectivity over USB 2.0 High Speed. via the USB CDC ECM Gadget driver.
* It may work on other boards too.
* This also fixed full-speed (low-speed) mode for the board too.

### Limitations

* Hasn't been tested on anything other than  SAMA5D36-Xplained board.

### TODO

* Ideally this would include a composite RNDIS device so it would also work seamlessly on Windows. That is for a future PR
* Ideally this would include software to help configuration via mDNS/DNS-SD for plug and play compatibility with Linux and macOS. That is for a future PR.

### Detail

* Only a few lines of C driver code needed to be changed, since the capability was there already. The rest is config and documentation.
* Changes the SAMA5D3-Xplained board bringup to match the SAMA5D3-EK board bringup
* A helper script to configure Linux routing and iptables NAT is also provided, along with documentation on how to use it.

### Testing

* Manual, on a Ubuntu Linux 19.10 system and MacOS 10.14.6 Mojave MacBook Pro.

### How To Verify 

* Follow the new CDC ECM Ethernet over USB instructions in the board README.txt file

### CODE REVIEW

**Comment by adamfeuer** [comment]
@acassis Thanks for merging!

**Comment by adamfeuer** [comment]
@acassis Also thanks for your Ethernet over USB Youtube videos, they are what inspired me to try this. 🙂

**Comment by acassis** [comment]
@adamfeuer It's my pleasure! Nice to know you enjoy it!

**Comment by adamfeuer** [comment]
@acassis Hey by the way, thanks for running nxstyle and fixing the problems. In the future I'll do this myself. Is there a guide for things I should look for when submitting a PR?

**Pull request merged**
