### PR TITLE
arch: arm: sxd56xx: nxstyle fixes

### PR DESCRIPTION
**Pull request by jerpelea**
Fix nxstyle complains

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

### CODE REVIEW

**Comment by acassis** [comment]
Please fix the CamelCases. We already fixed some of Sony CamelCase, but there are many more to be fixed.

**Comment by jerpelea** [comment]
@acassis some of the CamelCases are part of teh API and have to stay as they are for now since they are used downstream in the SDK. I will progressively fix them but now is not possible to fix them all.
If there are no other complains please merge this PR so that I can submit the next one

**Comment by xiaoxiang781216** [comment]
@jerpelea but there are other error too:
1. No indentation line
2. Operator/assignment must be preceded with whitespace
We can fix these before merge, right?

**Comment by jerpelea** [comment]
I am taking a look now

**Pull request merged**
