### PR TITLE
arch/stm32xx/Kconfig: simplify and unify PWM options

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary

- arch/stm32xx/Kconfig: simplify PWM options and unify them among stm32 chips

## Impact
Configurations using PWM for STM32L4/F0/L0/G0 must be updated:
- CONFIG_STM32F0L0G0_TIMx_PWM=y doesn't select CONFIG_PWM=y automatically,
- CONFIG_STM32F0L0G0_PWM_MULTICHAN=y doesn't select CONFIG_PWM_MULTICHAN=y automatically
- CONFIG_STM32L4_TIMx_PWM=y doesn't select CONFIG_PWM=y automatically,
- CONFIG_STM32U5_TIMx_PWM=y doesn't select CONFIG_PWM=y automatically,

## Testing
CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Comment by davids5** [comment]
> Configurations using PWM for STM32L4/F0/L0/G0 must be updated:

@raiden00pl I only saw one, were all the in-tree defconfig updated?

Do we have enough configs to get good CI coverage?

**Comment by raiden00pl** [comment]
@davids5 only nucleo-g070rb/nsh is affected. There is no more PWM configurations for F0/L0/G0 or L4. All other STM32 families don't require any changes (no `select PWM` in arch Kconfig options)

**Review by davids5 — APPROVED** [review]
Thank you @raiden00pl

**Review by hartmannathan — COMMENTED** [review]
Should STM32_PWM, STM32F0L0G0_PWM, STM32F7_PWM, STM32L4_PWM, and STM32U5_PWM be made to select CONFIG_PWM automatically?

**Comment by raiden00pl** [comment]
@hartmannathan Not really. The upper-half PWM driver logic is just an option and it is very limited. We can use the PWM lower-half logic to build more complex and application specific drivers (eg. FOC driver). The same applies to ADC.

**Pull request merged**
