### PR TITLE
Set CONFIG_NET_ETH_PKTSIZE to 1514 for spresense

### PR DESCRIPTION
**Pull request by WaterBirdWayOrigin**
Set CONFIG_NET_ETH_PKTSIZE to 1514 when performing
 $ tools/configure.sh spresense/rndis
configuration

CONFIG_NET_ETH_PKTSIZE defines the size of ethernet packet.
Ethernet packet size is 1514 including the ethernet header.

This commit can send 1514 bytes packet as follow:
  e.g) For OpenWrt Router
  nsh> ping -c 1 -s 1472 192.168.1.1
  PING 192.168.1.1 1472 bytes of data
  1472 bytes from 192.168.1.1: icmp_seq=0 time=0 ms
  1 packets transmitted, 1 received, 0% packet loss, time 1010 ms
  nsh>

https://tools.ietf.org/html/rfc894
said at Frame Format
```
   The minimum length of the data field of a packet sent over an
   Ethernet is 1500 octets, thus the maximum length of an IP datagram
   sent over an Ethernet is 1500 octets.  Implementations are encouraged
   to support full-length packets.
``

Just for your information,
include/nuttx/net/ethernet.h:78:#define ETH_HDRLEN       14     /* Header size: 2*6 + 2 */

Signed-off-by: Koichi Okamoto <Koichi.Okamoto@sony.com>

### CODE REVIEW

**Comment by WaterBirdWayOrigin** [comment]
https://github.com/apache/incubator-nuttx/pull/109#issuecomment-575113032

**Comment by WaterBirdWayOrigin** [comment]
uIP is also used contiki os:
https://github.com/contiki-os/contiki/blob/master/core/net/ip/uipopt.h#L163
/**
 * The size of the uIP packet buffer.
 *
 * The uIP packet buffer should not be smaller than 60 bytes, and does
 * not need to be larger than 1514 bytes. Lower size results in lower
 * TCP throughput, larger size results in higher TCP throughput.
 *
 * \hideinitializer
 */
#ifndef UIP_CONF_BUFFER_SIZE
#define UIP_BUFSIZE (UIP_LINK_MTU + UIP_LLH_LEN)
#else /* UIP_CONF_BUFFER_SIZE */
#define UIP_BUFSIZE (UIP_CONF_BUFFER_SIZE)
#endif /* UIP_CONF_BUFFER_SIZE */

This side is fixed to 1514, not 1500.

**Comment by patacongo** [comment]
" am not sure but I think the last CRC (4Byte) isn't consider by software tcp/ip stack side."  That is my experience too.  The FCS is generated and consumed by hardware.

I've also worked with Ethernet hardware that adds additional information at the end of the packet.

There is a special configuration setting to allow additional space at the end of the packet for this hardware specific stuff.  It is CONFIG_NET_GUARDSIZE.  The total packet allocation size is the max payload (1500) plus the Ethernet header size (14) plus CONFIG_NET_GUARDSIZE.

**Comment by patacongo** [comment]
Don't use uIP documentation.  The NuttX network does include a few things from uIP, but it is an original network and nothing you know about uIP applies here.

Especially anything related to buffering.

**Comment by patacongo** [comment]
The confusion here is between packet size, MTU, and additional FCS bytes.

The MTU does not include either the Ethernet header or the FCS bytes.  CONFIG_NET_ETH_PKTSIZE is not the MTU and does include the Ethernet header (the FCS is provided by the GUARD size, if needed).

So for an MTU of 1500, the correct value of CONFIG_NET_ETH_PKTSIZE is 1514.  So your change is correct.

Too much talking for such a simple change.

**Comment by WaterBirdWayOrigin** [comment]
@patacongo 
Thank you for your confirmation !

> Don't use uIP documentation.
> Too much talking for such a simple change.

I see.  Thank your for your advice.

**Comment by jerpelea** [comment]
@patacongo thanks for clarification

**Pull request merged**
