### PR TITLE
ci: get rust copied to final image.

### PR DESCRIPTION
**Pull request by ptka**
## Summary
Get rust copied to final image.
PR created following the discussions in PR https://github.com/apache/incubator-nuttx/pull/5576

## Impact
ci configuration

## Testing
via ci itself

### CODE REVIEW

**Review by btashton — APPROVED** [review]

**Comment by ptka** [comment]
Thanks for approving ... but it doesn't build. Still the rustc compiler is not found, when building sim:rust.

    Configuration/Tool: sim/rust
    ------------------------------------------------------------------------------------
      Cleaning...
      Configuring...
      Building NuttX...
    make[3]: rustc: Command not found
    make[3]: *** [/github/workspace/sources/apps/Application.mk:212: hello_rust_main.rs.github.workspace.sources.apps.examples.hello_rust.o] Error 127
    make[3]: Target 'all' not remade because of errors.
    make[2]: *** [Makefile:42: /github/workspace/sources/apps/examples/hello_rust_all] Error 2
    make[2]: Target '/github/workspace/sources/apps/libapps.a' not remade because of errors.
    make[1]: *** [Makefile:36: all] Error 2
    make: *** [tools/LibTargets.mk:210: /github/workspace/sources/apps/libapps.a] Error 2
    make: Target 'all' not remade because of errors.
    /github/workspace/sources/nuttx/tools/testbuild.sh: line 252: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
      Normalize sim/rust

**Comment by btashton** [comment]
The docker image used here will not be used until it is merged. (It is uploaded on the master pipeline and not the PR pipeline)

**Comment by btashton** [comment]
Ok I think we are closer. Rustc is available but seems like there is more that is needed?
```
Tool: sim/rust
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
error: no override and no default toolchain set
make[3]: *** [/github/workspace/sources/apps/Application.mk:212: hello_rust_main.rs.github.workspace.sources.apps.examples.hello_rust.o] Error 1
make[3]: Target 'all' not remade because of errors.
make[2]: *** [Makefile:42: /github/workspace/sources/apps/examples/hello_rust_all] Error 2
make[2]: Target '/github/workspace/sources/apps/libapps.a' not remade because of errors.
make[1]: *** [Makefile:36: all] Error 2
make: *** [tools/LibTargets.mk:210: /github/workspace/sources/apps/libapps.a] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 252: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize sim/rust
```

**Comment by ptka** [comment]
I saw it already ... not sure, what this is ... I never saw that error before. My current guess is, that it maybe related to the copy operation, which copies rust installation after installation. This may break something.

**Comment by ptka** [comment]
Okay ... root cause identified ... there's another folder, which is installed in the $HOME directory ... it's '.rustup' and contains the additional stuff. Need to check, if this can be relocated, too.

**Comment by btashton** [comment]
> Okay ... root cause identified ... there's another folder, which is installed in the $HOME directory ... it's '.rustup' and contains the additional stuff. Need to check, if this can be relocated, too.


Maybe just need RUSTUP_HOME set?

https://rust-lang.github.io/rustup/environment-variables.html

**Comment by ptka** [comment]
Correct, that's most likely the solution ... I'm just tweaking my local set-up and will prepare PR.

**Pull request merged**
