### PR TITLE
socket/SOL: sync the SOL index with linux 

### PR DESCRIPTION
**Pull request by anchao**
## Summary
socket/SOL: sync the SOL index with linux 

## Testing

CI check is enough

### CODE REVIEW

**Comment by acassis** [comment]
@PetervdPerk-NXP Could you please review?

**Comment by yamt** [comment]
@anchao is there any benefit to be "sync" with linux?

**Comment by yamt** [comment]
i suspect dense numbers are easier for compilers to optimize switch statements.

**Comment by anchao** [comment]
> @anchao is there any benefit to be "sync" with linux?

Unsynchronized options will cause some compatibility issues, 
for example:

`setsockopt(sock, IPPROTO_IP, IP_ADD_MEMBERSHIP, &mreq, sizeof(mreq));`

```
int psock_setsockopt(FAR struct socket *psock, int level, int option,
                     FAR const void *value, socklen_t value_len)
...
      case SOL_IP:    <-- 
        ret = ipv4_setsockopt(psock, option, value, value_len);
        break;
....
```

this option configure will be failure since IPPROTO_IP and SOL_IP are different definitions in NuttX,
if we want to be fully compatible with posix applications, the experience of adopting Linux will be a good choice.

**Comment by yamt** [comment]
ok. sync with IPPROTO_ makes sense.
actually, shouldn't we just remove all SOL_ constants except SOL_SOCKET, and use IPPROTO_ constants instead?

**Comment by anchao** [comment]
> ok. sync with IPPROTO_ makes sense.
> actually, shouldn't we just remove all SOL_ constants except SOL_SOCKET, and use IPPROTO_ constants instead?

Done, please help to review the following PR:
https://github.com/apache/incubator-nuttx/pull/1291
https://github.com/apache/incubator-nuttx-apps/pull/311

**Comment by jerpelea** [comment]
LGTM

**Pull request merged**
