### PR TITLE
add ltp config for sim

### PR DESCRIPTION
**Pull request by ttnie**
Signed-off-by: nietingting <nietingting@xiaomi.com>

## Summary
add ltp config for sim 
## Impact
no 
## Testing
test on local

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
depends on https://github.com/apache/incubator-nuttx-apps/pull/524

**Comment by v01d** [comment]
@ttnie any updates on this? Builds have expired and can no longer see the failure.

**Comment by ttnie** [comment]
> @ttnie any updates on this? Builds have expired and can no longer see the failure.

Does this pr can merge?

**Comment by v01d** [comment]
Well, this PR is not really ready to be merged. That is why I asked if there was any news on this work.
However, @btashton mentioned that he might prepare a PR to integrate LTP into CI soon.

**Comment by btashton** [comment]
@v01d  There are a few issues that we need to address, I opened an issues over in the app repo with the current blocker that I have. https://github.com/apache/incubator-nuttx-apps/issues/669  Maybe you have some thoughts on that?

**Pull request closed without merging**
