### PR TITLE
boards/arm/stm32l4: Fix nxstyle warning

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Change format only

## Impact
No

## Testing
Pass the CI

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]

**Comment by jerpelea** [comment]
@xiaoxiang781216 you did not do it in place ;)

**Comment by xiaoxiang781216** [comment]
Yes, it is impossible.

**Comment by hartmannathan** [comment]
PR title is wrong? Says nxstyle fix but changes available channels and init of DFSDM?

Did multiple commits get squashed and keep the wrong commit message?

Thanks

**Comment by xiaoxiang781216** [comment]
> PR title is wrong? Says nxstyle fix but changes available channels and init of DFSDM?
> 
> Did multiple commits get squashed and keep the wrong commit message?
> 
> Thanks

The title is right, the change is for fix the following warning only:
```
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:94:58: error: Left bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:94:60: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:94:62: error: Right bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:94:7: error: Right brace must be followed by a blank line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:58: error: Left bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:60: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:62: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:64: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:66: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:68: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:70: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:72: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:74: error: Right bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:80: error: Long line found
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:110:7: error: Right brace must be followed by a blank line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:58: error: Left bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:60: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:62: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:64: error: Missing whitespace after comma
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:66: error: Right bracket not on separate line
boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c:126:7: error: Right brace must be followed by a blank line
```

**Pull request merged**
