### PR TITLE
sched: Don't include nuttx/sched.h inside sched.h

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
But let nuttx/sched.h include sched.h instead to avoid expose nuttx kernel API to userspace

## Impact
Minor, header file reorganize

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Depends on https://github.com/apache/incubator-nuttx-apps/pull/725

**Comment by masayuki2009** [comment]
>Depends on
>apache/incubator-nuttx-apps#725
>apache/incubator-nuttx-apps#728

Both PRs were merged and I restarted the CI job but still failed.

```
====================================================================================
Configuration/Tool: same70-xplained/twm4nx,CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Disabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
  Enabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
  Building NuttX...
vnc/server/vnc_fbdev.c: In function 'up_getvideoinfo':
Error: vnc/server/vnc_fbdev.c:164:3: error: implicit declaration of function 'DEBUGASSERT' [-Werror=implicit-function-declaration]
  164 |   DEBUGASSERT(fbinfo != NULL && vinfo != NULL);
      |   ^~~~~~~~~~~
```

**Comment by xiaoxiang781216** [comment]
====================================================================================
> Configuration/Tool: same70-xplained/twm4nx,CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
> ------------------------------------------------------------------------------------
>   Cleaning...
>   Configuring...
>   Disabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
>   Enabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABIL
>   Building NuttX...
> vnc/server/vnc_fbdev.c: In function 'up_getvideoinfo':
> Error: vnc/server/vnc_fbdev.c:164:3: error: implicit declaration of function 'DEBUGASSERT' [-Werror=implicit-function-declaration]
>   164 |   DEBUGASSERT(fbinfo != NULL && vinfo != NULL);
>       |   ^~~~~~~~~~~
> ```

Fixed.

**Comment by masayuki2009** [comment]
LGTM

**Pull request merged**
