### PR TITLE
risc-v/mpfs: switch to NuttX types for opensbi 

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
switch to NuttX types for opensbi 

## Impact
No impact

## Testing
Pass CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@pkarashchenko it may fail to compile due to the conflict type definition.

**Comment by pkarashchenko** [comment]
> @pkarashchenko it may fail to compile due to the conflict type definition. @eenurkka, should we let open sbi use NuttX definition instead?

I will check it, let me take a look.

**Comment by pkarashchenko** [comment]
Yes. Indeed it will not work. We need to create a separate `OPENSBI_EXTERNAL_SBI_TYPES` header file for opensbi

**Comment by xiaoxiang781216** [comment]
I think it could be fixed by define OPENSBI_EXTERNAL_SBI_TYPES

**Comment by pkarashchenko** [comment]
> I think it could be fixed by define OPENSBI_EXTERNAL_SBI_TYPES

Yes. That's what I did. please take a look
CC: @eenurkka

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Comment by eenurkka** [comment]
Just tested this, works just fine! Thanks!

**Comment by eenurkka** [comment]
Actually, it compiled as I had precompiled stuff underneath; but now, if I take a clean build:

tools/configure.sh icicle:opensbi
make

I get tons of redefinition warnings and errors

**Comment by xiaoxiang781216** [comment]
But, why the CI doesn't have warning or error?
https://github.com/apache/incubator-nuttx/runs/4883947690?check_suite_focus=true

**Comment by eenurkka** [comment]
Yes, I noticed that. It's strange why it goes like that. Local clean build is broken, I wonder if CI does some caching... Will look more into this.

**Comment by pkarashchenko** [comment]
Let's revert change for now.

**Comment by pkarashchenko** [comment]
I just tried clean build and it also fails. I've created https://github.com/apache/incubator-nuttx/pull/5302

**Comment by pkarashchenko** [comment]
There are much more dependencies than `OPENSBI_EXTERNAL_SBI_TYPES`

**Comment by pkarashchenko** [comment]
@eenurkka please try these changes https://github.com/apache/incubator-nuttx/pull/5303

**Comment by pkarashchenko** [comment]
BTW, by default my local build fails with
```
AR (create): libboard.a   mpfs_bringup.o mpfs_appinit.o mpfs_autoleds.o mpfs_boot.o mpfs_emmcsd.o 
make[2]: Leaving directory '/home/pkarashchenko/nuttx-upstream/nuttx/boards/risc-v/mpfs/common'
LD: nuttx
riscv64-unknown-elf-ld: cannot find -lm
make[1]: *** [Makefile:168: nuttx] Error 1
```
Compiler is standard `sudo apt install gcc-riscv64-unknown-elf`:
```
riscv64-unknown-elf-gcc () 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also I noticed that there is no `clean` option for opensbi case, so `distclean` should be used always in case if full rebuild is needed.

**Comment by pkarashchenko** [comment]
I fixed link process in https://github.com/apache/incubator-nuttx/pull/5303 as well

**Pull request merged**
