### PR TITLE
binfmt: Fix a memory leak in ELF loader

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- I noticed that the hello (ELF) application causes a memory leak.
- Finally, I found that the data section is not deallocated.
- This commit fixes this issue.

## Impact

- ELF loader with CONFIG_ARCH_ADDRENV=n

## Testing

- Tested with the following configs
  - sprensense:elf, esp32-devkitc:elf, sabre-6quad:elf
  - spresense:wifi_smp, rv-virt:nsh64, sabre-6quad:netnsh

### CODE REVIEW

**Comment by masayuki2009** [comment]
See https://github.com/apache/incubator-nuttx/pull/6647 as well

**Comment by pkarashchenko** [comment]
@masayuki2009 I think that is not only related to data segment as `ctoralloc` and `dtoralloc` also seems to use `kumm_malloc()` and not `up_textheap_memalign()`, so maybe `textalloc` should use special handling and not `dataalloc`? I mean maybe we can get your previous fix, but modify memory release code to be
```
      for (i = 0; i < BINFMT_NALLOC; i++)
        {
          if (binp->alloc[i])
            {
              binfo("Freeing alloc[%d]: %p\n", i, binp->alloc[i]);
#if defined(CONFIG_ARCH_USE_TEXT_HEAP)
              if (i == 0)
                {
                  up_textheap_free((FAR void *)binp->alloc[i]);
                }
              else
#endif
                {
                  kumm_free((FAR void *)binp->alloc[i]);
                }
            }
        }
```

**Comment by masayuki2009** [comment]
>@masayuki2009 I think that is not only related to data segment as ctoralloc and dtoralloc also seems to use kumm_malloc() and not up_textheap_memalign(),

@pkarashchenko 
I think ctoralloc and dtoralloc should be allocated by up_textheap_memalign() if CONFIG_ARCH_USE_TEXT_HEAP=y.
However, let me confirm them later.

**Comment by xiaoxiang781216** [comment]
ctoralloc/dtoralloc section contain the function pointer which is more like the data not code, but it's always better to confirm with @yamt who introduce the text heap to fix the Harvard architecture issue found on xtensa.

**Comment by masayuki2009** [comment]
>ctoralloc/dtoralloc section contain the function pointer which is more like the data than the code, but it's always better to confirm with @yamt who introduce the text heap to fix the Harvard architecture issue found on xtensa.

@xiaoxiang781216 
I confirmed that you are correct. To test C++ static object in ELF, I created a new PR https://github.com/apache/incubator-nuttx/pull/6684

**Comment by masayuki2009** [comment]
I'll update this PR later based on @pkarashchenko 's suggestion.

**Comment by masayuki2009** [comment]
>I'll update this PR later based on @pkarashchenko 's suggestion.

@xiaoxiang781216 
I've just pushed the commit and also updated the Summary and the Testing

**Review by pkarashchenko — APPROVED** [review]
LGTM!

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
