### PR TITLE
arch: Rename xxx_getsp to up_getsp

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
All modern desgin support stack pointer and it's also an
important information, so let's standardize this interface.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
> But is it exported outside the arch directory?
> 
> If we have plans to do so, it should also be prototype'd in include/nuttx/arch.h.

Many inlince function(e.g. up_irq_save, up_tls_info) doesn't declare in include/nuttx/, but only in arch/xxx/include/, I just follow this convention.

**Comment by Ouss4** [comment]
> Many inlince function(e.g. up_irq_save, up_tls_info) doesn't declare in include/nuttx/, but only in arch/xxx/include/, I just follow this convention.

Yes, that's right, but we still add comments in include/nuttx/arch.h to explain why we don't have a prototype here (e.g. because it's a macro or an inline function).

But the convention is `up_` functions are exported outside the arch directory, while `chip_` or ` arch_` are used only inside the arch directory, this is why I asked if we have plan to use this outside arch.

**Comment by xiaoxiang781216** [comment]
> > Many inlince function(e.g. up_irq_save, up_tls_info) doesn't declare in include/nuttx/, but only in arch/xxx/include/, I just follow this convention.
> 
> Yes, that's right, but we still add comments in include/nuttx/arch.h to explain why we don't have a prototype here (e.g. because it's a macro or an inline function).
> 

Done, the comments is added in include/nuttx/arch.h

> But the convention is `up_` functions are exported outside the arch directory, while `chip_` or ` arch_` are used only inside the arch directory, this is why I asked if we have plans to use this outside arch.

To support TLS, the implementation is already moved from src/up_internal.h into arch/include/arch.h. This PR just make it more clear.

**Review by Ouss4 — APPROVED** [review]
LGTM.

**Pull request merged**
