### PR TITLE
Fix zipme.sh typo error

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
https://github.com/apache/incubator-nuttx/issues/1284#issuecomment-647931278

### CODE REVIEW

**Comment by btashton** [comment]
Looks like that fixed the syntax issue, but I still cannot use the build script to create the tarballs.
```
+ git -C nuttx am ../1285.patch
Applying: tools/zipme.sh: Fix the typo error
Applying: tools/zipme.sh: Add executable bit
+ cd nuttx/tools
+ ./zipme.sh -d -s -k 9750ED7E692B99E2 9.1.0
+ DEBUG=-d
+ shift
+ '[' '!' -z -s ']'
+ case $1 in
+ sign=1
+ shift
+ '[' '!' -z -k ']'
+ case $1 in
+ shift
+ GPG+=' --default-key 9750ED7E692B99E2'
+ shift
+ '[' '!' -z 9.1.0 ']'
+ case $1 in
+ break
+ VERSION=9.1.0
+ '[' -n 9.1.0 ']'
+ VERSIONOPT='-v 9.1.0'
+ for pat in ${EXCLPAT}
+ TAR+=' --exclude=.github'
+ for pat in ${EXCLPAT}
+ TAR+=' --exclude=.asf.yaml'
+ TAR+=' --exclude-vcs-ignores --exclude-vcs'
+ '[' 0 '!=' 0 ']'
+ TAR+=' -czf'
++ basename ./zipme.sh
+ MYNAME=zipme.sh
+ '[' -x /home/bashton/nuttx/apache/tmprelease/nuttx/tools/zipme.sh ']'
+ TRUNKDIR=/home/bashton/nuttx/apache/tmprelease/nuttx/tools/../..
+ NUTTXDIR=/home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx
+ APPSDIR=/home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../apps
+ '[' '!' -d /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../.. ']'
+ cd /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../..
+ '[' '!' -d /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx ']'
+ '[' '!' -d /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../apps ']'
+ cd /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../..
+ echo 'Cleaning the repositories'
Cleaning the repositories
+ '[' 0 '!=' 0 ']'
+ make -C /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx distclean
+ cd /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/Documentation
+ VERSIONSH=/home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/tools/version.sh
+ '[' '!' -x /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/tools/version.sh ']'
+ /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/tools/version.sh -d -v 9.1.0 /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/.version
+ shift
+ '[' '!' -z -v ']'
+ case $1 in
+ shift
+ VERSION=9.1.0
+ shift
+ '[' '!' -z /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/.version ']'
+ case $1 in
+ break
+ OUTFILE=/home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/.version
+ '[' -z 9.1.0 ']'
+ '[' -z 9.1.0 ']'
+ '[' -z /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/.version ']'
++ echo 9.1.0
++ cut -d. -f1
+ MAJOR=9
+ '[' X9 = X9.1.0 ']'
++ echo 9.1.0
++ cut -d. -f2
+ MINOR=1
+ '[' X9.1 = X9.1.0 ']'
++ echo 9.1.0
++ cut -d. -f3
+ PATCH=0
+ '[' -z '' ']'
++ git log --oneline -1
++ cut '-d ' -f1
+ BUILD=0295501
+ '[' -z 0295501 ']'
++ git diff-index --name-only HEAD
++ head -1
+ '[' -n '' ']'
+ echo '#!/bin/bash'
+ echo ''
+ echo 'CONFIG_VERSION_STRING="9.1.0"'
+ echo CONFIG_VERSION_MAJOR=9
+ echo CONFIG_VERSION_MINOR=1
+ echo CONFIG_VERSION_PATCH=0
+ echo 'CONFIG_VERSION_BUILD="0295501"'
+ chmod 755 /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx/.version
+ '[' -z 9.1.0 ']'
+ NUTTX_TARNAME=apache-nuttx-9.1.0-incubating.tar
+ APPS_TARNAME=apache-nuttx-apps-9.1.0-incubating.tar
+ NUTTX_ZIPNAME=apache-nuttx-9.1.0-incubating.tar.gz
+ APPS_ZIPNAME=apache-nuttx-apps-9.1.0-incubating.tar.gz
+ NUTTX_ASCNAME=apache-nuttx-9.1.0-incubating.tar.gz.asc
+ APPS_ASCNAME=apache-nuttx-apps-9.1.0-incubating.tar.gz.asc
+ NUTTX_SHANAME=apache-nuttx-9.1.0-incubating.tar.gz.sha512
+ APPS_SHANAME=apache-nuttx-apps-9.1.0-incubating.tar.gz.sha512
+ '[' -f apache-nuttx-9.1.0-incubating.tar ']'
+ '[' -f apache-nuttx-9.1.0-incubating.tar.gz ']'
+ '[' -f apache-nuttx-apps-9.1.0-incubating.tar ']'
+ '[' -f apache-nuttx-apps-9.1.0-incubating.tar.gz ']'
+ '[' -f apache-nuttx-9.1.0-incubating.tar.gz.asc ']'
+ '[' -f apache-nuttx-apps-9.1.0-incubating.tar.gz.asc ']'
+ '[' -f apache-nuttx-9.1.0-incubating.tar.gz.sha512 ']'
+ '[' -f apache-nuttx-apps-9.1.0-incubating.tar.gz.sha512 ']'
+ echo 'Archiving and zipping nuttx/'
Archiving and zipping nuttx/
++ basename /home/bashton/nuttx/apache/tmprelease/nuttx/tools/../../nuttx
+ tar --exclude=.github --exclude=.asf.yaml --exclude-vcs-ignores --exclude-vcs -czf apache-nuttx-9.1.0-incubating.tar.gz nuttx
tar: nuttx: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
+ echo 'tar of apache-nuttx-9.1.0-incubating.tar.gz failed!'
tar of apache-nuttx-9.1.0-incubating.tar.gz failed!
+ exit 1
```

**Comment by xiaoxiang781216** [comment]
Done, I can generate the package without signing in the local machine.

**Comment by btashton** [comment]
@xiaoxiang781216 Thanks!  I just verified it with my release script applying the patch as well.

**Comment by btashton** [comment]
Let backport this as well for 9.1 to make the next RC easier.

**Pull request merged**
