### PR TITLE
Documentation: introduce hardware platforms documentation

### PR DESCRIPTION
**Pull request by v01d**
## Summary

This is initial groundwork for #2409. It introduces "Supported Platforms" top-level section, which aims to document architectures, SoCs and boards, following an organization similar to that of boards/ directory. Only few stub architectures/SoC currently added so that we can do this incrementally. This PR also includes board documentation for nrf52832-mdk board.

My intention is to move as much board documentation here as possible and only have a README for things not worth exposing in documentation (maybe in the end, we decide to fully use the docs and the READMEs are not used). Moreover, the aim is to start documenting aspects that actually apply to a whole SoC, which are usually mentioned in board READMEs repetitively.

After this we can iterate on the structure for each document and try to keep documents consistent. Maybe we can add a sort of skeleton or template for each level so that we can ensure this.

## Impact

Documentation

## Testing

Built docs locally

### CODE REVIEW

**Comment by v01d** [comment]
@btashton Please check the image size, I'm not sure if it is considered "large" or not.

BTW, I think that it would be really good if people working on BL602/ESP32 can document their SoCs there, as these chips generally require special tooling, flashing/debugging procedures, etc.

**Comment by v01d** [comment]
PS: for inspiration on how to structure the board docs, I think Zephyr docs are a good source. For example: https://docs.zephyrproject.org/latest/boards/arm/96b_neonkey/doc/index.html

**Comment by btashton** [comment]
@v01d Yeah I would be happy to write the bl602 part of this once we have it merged in.  

As for the image I think it is fine, just think we should try to keep them to say 200KB or less per board.

**Comment by v01d** [comment]
I have an nRF52840-MDK incoming so I can document that one as well.

**Review by Zackyong70 — APPROVED** [review]

**Pull request merged**
