### PR TITLE
boards: Remove the unused CONFIG_xxx_CXXINITIALIZE=y

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
since cxx initialization is controlled by CONFIG_HAVE_CXXINITIALIZE now

## Summary
Follow up these two patches:
https://github.com/apache/incubator-nuttx-apps/pull/316
https://github.com/apache/incubator-nuttx/pull/1347

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@patacongo this is the final patch for FLAT/PROTECTED builtin constructor centralization.

**Comment by patacongo** [comment]
I will be merging this change very early after a few checks succeed.  That is because the PR checks are all broken without this change.

[PS:  I was producing the same PR on my machine... you are faster than me!]

**Comment by xiaoxiang781216** [comment]
> machine

mayn't faster than you, I made this path a few days before:).

**Comment by xiaoxiang781216** [comment]
Yes, you are right. I forget this file because this is a new board just upstreamed one month ago. The fix is here: https://github.com/apache/incubator-nuttx/pull/1348

**Comment by davids5** [comment]
@xiaoxiang781216 - there is still a lot of misleading documentation  (some are past release notes.) but this is really wrong now

image

**Comment by xiaoxiang781216** [comment]
OK, I will provide a patch clear the documentation, but keep ReleaseNotes as it since ReleaseNotes describe the history of software and should only be appended not modified.

**Comment by davids5** [comment]
>OK, I will provide a patch clear the documentation, but keep ReleaseNotes as it since ReleaseNotes describe the history of software and should only be appended not modified.

I think that is obvious, right? It does highlight how when Greg use to keep running release notes, changes had proper documentation.  Now maybe you can see the value of filling out all the information in the PR. Stating "intent" makes it clear (especial you you have dribbling in fixes and 2 repos not bound or synchronized (submodules)) what the new structure is, what is effected and why.

**Pull request merged**
