### PR TITLE
boards/arm/imxrt/teensy-4.x: CDC-ACM console support

### PR DESCRIPTION
**Pull request by michallenc**
## Summary

Changed Teensy 4.x configurations to support nsh console over USB (CDC-ACM).

## Testing

Tested on Teensy 4.0 and Teensy 4.1 boards.

### CODE REVIEW

**Comment by btashton** [comment]
@michallenc  Just tested this on the Teensy 4.1 and I am hitting an issue with nsh_session failing:
```
NuttShell (NSH) NuttX-9.1.1
nsh> nsh: nsh_session: readline failed: 9
```

**Comment by michallenc** [comment]
> @michallenc Just tested this on the Teensy 4.1 and I am hitting an issue with nsh_session failing:
> 
> ```
> NuttShell (NSH) NuttX-9.1.1
> nsh> nsh: nsh_session: readline failed: 9
> ```

@btashton  Hi, that´s strange. Everything seems to work fine with gtkterm. Do you have issues with all configurations or just with one particular?

```
NuttShell (NSH) NuttX-9.1.1
nsh> 
nsh> ls dev
/dev:
 console
 null
 ttyACM0
 ttyS0
nsh> ?
help usage:  help [-v] [<cmd>]

  .         cd        echo      hexdump   mb        mw        set       uname     
  [         cp        exec      ifconfig  mkdir     nslookup  sleep     umount    
  ?         cmp       exit      ifdown    mkrd      ps        source    unset     
  basename  dirname   false     ifup      mh        pwd       test      usleep    
  break     dd        free      kill      mount     rm        time      xd        
  cat       df        help      ls        mv        rmdir     true      

Builtin Apps:
  candump  sh       cansend  nsh      
nsh> 
```

**Comment by btashton** [comment]
I just grabbed the hex from CI artifacts and see it on all the configurations.  I think there is a bug impacting usbnsh for all the configurations.  I can try to see what the root cause is here that is causing the invalid fd.  Maybe locally you are using an older version of the apps repo which is why you do not see it?

This was recently reported here on the mailing list for the stm32f4discovery
https://lists.apache.org/thread.html/rc13c19eaf0f34e82cf914fab0a3cde23ce429d1410183c3e961b798b%40%3Cdev.nuttx.apache.org%3E

**Comment by michallenc** [comment]
> I just grabbed the hex from CI artifacts and see it on all the configurations. I think there is a bug impacting usbnsh for all the configurations. I can try to see what the root cause is here that is causing the invalid fd. Maybe locally you are using an older version of the apps repo which is why you do not see it?
> 
> This was recently reported here on the mailing list for the stm32f4discovery
> https://lists.apache.org/thread.html/rc13c19eaf0f34e82cf914fab0a3cde23ce429d1410183c3e961b798b%40%3Cdev.nuttx.apache.org%3E

@btashton Yes, i had an older version of apps, something from middle October I think. It seems the bug originated somewhere in nsh_usbconsole.c in those two commits from October 29th.

**Comment by masayuki2009** [comment]
When I fixed nsh_usbconsole.c in the following PR, it worked with stm32f4discovery.
https://github.com/apache/incubator-nuttx-apps/pull/425

The above PR also relates to the following PR.
https://github.com/apache/incubator-nuttx/pull/1997

**Comment by btashton** [comment]
@masayuki2009 but it is failing in master (apps/is) right now

**Comment by masayuki2009** [comment]
> @masayuki2009 but it is failing in master (apps/os) right now

Perhaps, it is affected by https://github.com/apache/incubator-nuttx/pull/2263

**Comment by masayuki2009** [comment]
> > @masayuki2009 but it is failing in master (apps/os) right now
> 
> Perhaps, it is affected by #2263

I think ```fdopen(0, "r");``` might be needed for nsh_usbconsole.c again which is removed by https://github.com/apache/incubator-nuttx-apps/pull/425

Hi @xiaoxiang781216, 
As reported in NuttX ML, do we need to add ```fdopen(0, "r")``` to nsh_usbconsole.c which was removed by the above PR?

**Comment by xiaoxiang781216** [comment]
But fclose is removed in that patch, that's why I remove fdopen too.

**Comment by masayuki2009** [comment]
> But fclose is removed in that patch, that's why I remove fdopen too.

@xiaoxiang781216 
Yeah, but I needed to add ```fdopen()``` for stdout and stderr in the PR too.

https://github.com/apache/incubator-nuttx-apps/pull/425/commits/2b9d283ed547a6bb6049f1142dea00772c6ac88b

**Comment by xiaoxiang781216** [comment]
So, the reported problem should be fixed by https://github.com/apache/incubator-nuttx-apps/pull/521?

**Review by xiaoxiang781216 — APPROVED** [review]
@michallenc report that the problem get fixed by apache/incubator-nuttx-apps#521, so let merge this patch.

**Pull request merged**
