### PR TITLE
STM32L4: fix 48MHz MSI clock selection logic 

### PR DESCRIPTION
**Pull request by v01d**
## Summary
When MSI clock is selected at 48MHz this change is needed to avoid a hang on boot. It appears that setting the MSION bit when already on brought this problem.  
At the same time, using this higher clock value triggered the selection of the range 1 for core regulator and this also hung during boot. I could not find out why this problem occurs but since this is the default behavior it should introduce any different behavior.
Finally, with this clock speed there wasn't a matching case for the I2C clocking computations. I used ST's tool to get the values for this case. This now allows using I2C with MSI@48MHz as SYSCLK

## Impact
Selection of MSI clock at 48MHz frequency as system clock 

## Testing
I'm using I2C at 48MHz with MSI on STM32L476 and can communicate correctly

### CODE REVIEW

**Comment by acassis** [comment]
Hi Matias, do you have a defconfig that I could use to test it on nucleo-l476rg board?

**Comment by v01d** [comment]
I usually use nsh config for testing. Anyway, clock selection requires editing the board header file. You should change the option at the top so that MSI is used. Then, inside the MSI section of that header, you can select MSI frequency by setting:

#define STM32L4_BOARD_MSIRANGE    RCC_CR_MSIRANGE_48M

and further below you should change:

#define STM32L4_SYSCLK_FREQUENCY  48000000ul

I did my tests using MSI as the main clock so you should disable the PLL with:

#define STM32L4_BOARD_NOPLL

Then choose sysclk by changing this line to:

#define STM32L4_CLK48_SEL         RCC_CCIPR_CLK48SEL_MSI

BTW, to my understanding all those "2*" on CLKIN definitions are not correct. I don't understand where that comes from, since the prescaler for peripheral clocks is clearly not divided by 2 as the comments a few lines above state. Anyway, it should not affect you.

I think clock configuration should really be possible via menuconfig, I might work on that sometime.

**Comment by v01d** [comment]
You can also try other frequencies, but if you're using I2C, I think only other clock option is 16MHz since otherwise I2C timings are not yet defined. But UART should work.

**Comment by acassis** [comment]
Ok, it worked on 48MHz MSI.

These are the modification I did:

**Comment by jerpelea** [comment]
@v01d Please add commit messages for all commits

**Comment by v01d** [comment]
@jerpelea I saw this being requested on other PRs. It is quite confusing to me since I was not aware that this was requirement. Is that written somewhere?
Personally I think that if the requirement is to add a paragraph to every single commit this is a huge added workload. I'm trying to be very detailed and precise in my PR descriptions and I think I use relatively descriptive commit messages. I would appreciate some written guidance on the requirements for PRs so that i don't have to go back on all PRs just to edit every single commit message after the fact.

**Comment by acassis** [comment]
I think the comments are fine. I will merge it!

**Pull request merged**
