### PR TITLE
Fix the CI for CONFIG_BUILD_KERNEL=y

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR consists of the following commits
- commit1: tools: Unix.mk: Generate .tar.gz file with make export
- commit2: boards: sabre-6quad: Add iperf to netknsh/defconfig
- commit3: tools: testbuild.sh: Add exportandimport func
- commit4: boards: arm: Update README.txt regarding CONFIG_BUILD_KERNEL=y

## Impact

- ci with CONFIG_BUILD_KERNEL=y only

## Testing

- Tested with sabre-6quad:netknsh

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hmm, all ci on the macOS was canceled.

**Comment by masayuki2009** [comment]
>tools/mkexport.sh: line 429: zip: command not found

Hmm, we need to install zip command...

**Comment by masayuki2009** [comment]
>Hmm, we need to install zip command...

Let me generate .gz file instead of zip file.

**Comment by pkarashchenko** [comment]
I will restart macOS builds as soon as other will finish

**Comment by masayuki2009** [comment]
Hmm, I need to modify options for make export as well.

```
====================================================================================
Configuration/Tool: sabre-6quad/knsh_smp,CONFIG_ARMV7M_TOOLCHAIN_GNU_EABI
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Disabling CONFIG_ARMV7A_TOOLCHAIN_GNU_EABI
  Enabling CONFIG_ARMV7M_TOOLCHAIN_GNU_EABI
armv7-a/arm_addrenv.c: In function 'up_addrenv_coherent':
Warning: armv7-a/arm_addrenv.c:748:2: warning: #warning REVISIT... causes crashes [-Wcpp]
  748 | #warning REVISIT... causes crashes
      |  ^~~~~~~
make: *** [tools/Unix.mk:660: export] Error 1
```

**Comment by masayuki2009** [comment]
Hmm, I need to fix the warnings.

```
====================================================================================
Configuration/Tool: rv-virt/knsh64
------------------------------------------------------------------------------------
  Cleaning...
On branch master
Your branch is up to date with 'origin/master'.

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)
	testing/cxxtest/Make.dep

nothing to commit, working tree clean
  Configuring...
  Building NuttX...
Warning: common/crt0.c:130:13: warning: 'exec_dtors' defined but not used [-Wunused-function]
 static void exec_dtors(void)
             ^~~~~~~~~~
Warning: common/crt0.c:114:13: warning: 'exec_ctors' defined but not used [-Wunused-function]
 static void exec_ctors(void)
             ^~~~~~~~~~
/github/workspace/sources/apps /github/workspace/sources/nuttx
/github/workspace/sources/nuttx
  Normalize rv-virt/knsh64
```

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
