### PR TITLE
NXP S32K1XX peripheral clock fixes

### PR DESCRIPTION
**Pull request by jarivanewijk**
I have a few changes for NXP S32K1XX. I will split them into three PRs to make it easier for PX4 to backport specific changes if they want to. This is the first and includes these changes:

- Only apply PCC clock divider when it is actually set. This makes it possible to leave the field empty in the peripheral clock config. Most peripherals don't have this divider field in their PCC register, so it allows for cleaner peripheral clock config files (but it does not break existing files).
- Use uppercase "FLEXCAN_CLK" identifiers instead of mixed case "FlexCAN_CLK" for consistency.
- Style fixes.

### CODE REVIEW

**Comment by patacongo** [comment]
Hmmm... I see that you did run nxstyle.  But the current version of nxstyle used in the PR checks is reporting style errors as you see above.  We will have to resolve these before continuing.

**Comment by jarivanewijk** [comment]
@patacongo I see. It refuses to show me the full log output (it says "loading" for minutes), but I'll try to figure out what is causing the issue.

**Comment by patacongo** [comment]
>  It refuses to show me the full log output

You should be able to press "Details" to the righit of PR Check CI / check (pull_request).  That should bring up a window that shows the step(s) that failed.  Expand the failed step and you see all of the nxstyle complaints claimed.

**Comment by davids5** [comment]
@jarivanewijk for the style check. You have 2 options:

1) rebase on current master to pick up the NOW version of the tool
runs style checks again 
and force push

OR

do the following:
```
cd tools
wget https://raw.githubusercontent.com/apache/incubator-nuttx/master/tools/nxstyle.c
make -f Makefile.host
then run tools/checkpatch.sh on your commits.
do not commit the nxstyle.c
```

rebase -i   to clean up and force push

**Comment by jarivanewijk** [comment]
Thanks. @davids5 - I actually used the most recent nxstyle, but I must have made a mistake.

There was one error I missed, and a few long lines that I had ignored because I used nxstyle -m 8. I extended the "rulers" by 8 characters, because it just would not make the code any clearer if I started breaking up these lines. Now everything should be okay.

**Pull request merged**
