### PR TITLE
arch: imxrt: Fix ethernet configuration in Kconfig

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- Fix typo in Kconfig so that we can configure IMXRT_ENET_NRXBUFFERS.

## Impact

- imxrt family with ethernet configuration

## Testing

- imxrt1060-evk:netnsh

### CODE REVIEW

**Comment by masayuki2009** [comment]
Hmmm,

There are build errors in esp32-core:netnsh which is not affected by this PR.

------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize esp32-core/netnsh
30d29
< CONFIG_MAX_WDOGPARMS=2
Saving the new configuration file
HEAD detached at pull/1527/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   boards/xtensa/esp32/esp32-core/configs/netnsh/defconfig

**Comment by masayuki2009** [comment]
> Hmmm,
> 
> There are build errors in esp32-core:netnsh which is not affected by this PR.
> 
> Cleaning...
> Configuring...
> Building NuttX...
> Normalize esp32-core/netnsh
> 30d29
> < CONFIG_MAX_WDOGPARMS=2
> Saving the new configuration file
> HEAD detached at pull/1527/merge
> Changes not staged for commit:
> (use "git add ..." to update what will be committed)
> (use "git checkout -- ..." to discard changes in working directory)
> 
> ```
> modified:   boards/xtensa/esp32/esp32-core/configs/netnsh/defconfig
> ```

I've just sent a new PR to fix.

https://github.com/apache/incubator-nuttx/pull/1528

**Comment by btashton** [comment]
> > Hmmm,
> > 
> > There are build errors in esp32-core:netnsh which is not affected by this PR.
> > 
> > Cleaning...
> > Configuring...
> > Building NuttX...
> > Normalize esp32-core/netnsh
> > 30d29
> > < CONFIG_MAX_WDOGPARMS=2
> > Saving the new configuration file
> > HEAD detached at pull/1527/merge
> > Changes not staged for commit:
> > (use "git add ..." to update what will be committed)
> > (use "git checkout -- ..." to discard changes in working directory)
> > 
> > ```
> > modified:   boards/xtensa/esp32/esp32-core/configs/netnsh/defconfig
> > ```
> 
> I've just sent a new PR to fix.
> 
> https://github.com/apache/incubator-nuttx/pull/1528
> 

It's merged now. Feel free to rebase this one and it should pass.

**Comment by masayuki2009** [comment]
@btashton 

Thanks, the check build passed.

**Pull request merged**
