### PR TITLE
nuttx: rename Makefile/Make.defs/Make.dep to Nuttx.mk/Nuttx.defs/Nuttx.dep

### PR DESCRIPTION
**Pull request by anchao**
Rename "Makefile" to "Nuttx.mk" to ensure the uniqueness
of "Makefile" in different projects, which is meaningful
to avoid frequent overwriting of "Makefile" if we want
to use the same project to compile in different platforms.
which also makes "Nuttx.mk" easier to join other open source
projects (like Android.mk) to avoid unnecessary porting work.

Rename:

Makefile   ->  Nuttx.mk
Make.defs  ->  Nuttx.defs
Make.dep   ->  Nuttx.dep

Signed-off-by: chao.an <anchao@xiaomi.com>

### CODE REVIEW

**Comment by patacongo** [comment]
This change is apaplling.  I don't thing it should be merged.  Let's keep the name Makefile. Nuttx.mk is a horrible idea.

**Comment by xiaoxiang781216** [comment]
> This change is apaplling. I don't thing it should be merged. Let's keep the name Makefile. Nuttx.mk is a horrible idea.

The reason behind this change is that we found many open source projects use Makefile to enter into their build system. If we don't change the Makefile name in apps, it is impossible to incoprate the nuttx build script into the mainline repo.

**Comment by patacongo** [comment]
I still don't like it.  I have no concern for other open source projects.

**Comment by patacongo** [comment]
Thie impacts of a change like this are too great.  This cannot be accepted.  A change like this should at least have a vote from all PPMC member.  It is inappropriate for you to do this unilaterally without agreement from everyone.

**Pull request closed without merging**
