### PR TITLE
arch/sim: Implement up_backtrace

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Support backtrace on simulator

## Impact
sim

## Testing
Pass CI

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Review by gustavonihei — APPROVED** [review]
LGTM

**Comment by normanr** [comment]
very nice, are there plans to support this for risc-v too? It looks like it's only missing the `CMN_CSRCS` condition in the `Make.defs` files.

**Comment by xiaoxiang781216** [comment]
risc-v is already supported by @anchao , you just need add up_backtrace.c into CMN_CSRS and turn on the option.

**Comment by normanr** [comment]
I'm not sure if bl602 has enough space for `ALLSYMS`, but I managed to get backtrace working by adding
```
ifeq ($(CONFIG_SCHED_BACKTRACE),y)
CMN_CSRCS += riscv_backtrace.c
endif
```
to `arch/risc-v/src/bl602/Make.defs`: https://gist.github.com/lupyuen/ccfd90125f9a180b4cfb459e8a57b323#gistcomment-4010689

**Comment by normanr** [comment]
It works great, and with only 15% overhead! (480K --> 550K)

**Pull request merged**
