### PR TITLE
compiler.h: Rename inline_function to always_inline_function

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
reserve inline_function macro for inline keyword

## Impact
Minor

## Testing
Pass CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]
There is another approach with using `#define INLINE` similar to `#define EXTERN` in headers, but using a lower case seems to be closer from style point of view.

**Comment by xiaoxiang781216** [comment]
That could be, but not relate to this change. inline_function map to always_inline is very strange which should be fixed anyway.

**Review by easonxiang — COMMENTED** [review]
This change looks much better for understanding, but it increase the length of the line.
How about use always_inline instead, since it must be a function if it was defined by inline.

**Comment by xiaoxiang781216** [comment]
> This change looks much better for understanding, but it increase the length of the line. How about use always_inline instead, since it must be a function if it was defined by inline.

I am fine with either, @pkarashchenko what's your opinion?

**Comment by pkarashchenko** [comment]
always_inline should be fine

**Comment by xiaoxiang781216** [comment]
After more thought, it's wrong to change the macro to always_inline since if user use this in source code directly:
```
__attribute__ ((always_inline))
```
the marco expanse it to the invalid statement:
```
__attribute__ ((__attribute__ ((always_inline, no_instrument_function))))
```
So, it's better to keep in the current form. @easonxiang @pkarashchenko

**Comment by easonxiang** [comment]
> After more thought, it's wrong to change the macro to always_inline since if user use this in source code directly:
> 
> ```
> __attribute__ ((always_inline))
> ```
> 
> the marco expanse it to the invalid statement:
> 
> ```
> __attribute__ ((__attribute__ ((always_inline, no_instrument_function))))
> ```
> 
> So, it's better to keep in the current form. @easonxiang @pkarashchenko

Yes, It's unavailable to define the same name with gcc key words. We can add some symbol, such as start with `_` or some similar.

**Comment by xiaoxiang781216** [comment]
If so, I prefer add _function suffix like other similar macros

**Comment by easonxiang** [comment]
It seems there is no standard or rules to redefine the gcc features.
If possible to add some unify prefix to these macros, it may be more clear to the users.

**Comment by xiaoxiang781216** [comment]
> It seems there is no standard or rules to redefine the gcc features. If possible to add some unify prefix to these macros, it may be more clear to the users.

it isn't gcc specific feature, many attribute support by other compiler too, just the grammar is different.

**Review by easonxiang — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@pkarashchenko could you merge it?

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
