### PR TITLE
libc/gettextdomain: Fix the typo error

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Report here: https://github.com/apache/incubator-nuttx/pull/4978

## Impact
Kernel build

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
Probably my bad. Now build fails because of unused `g_domain` for kernel build. I will double inspect the current code. Probably I missed something. Let's abandon this change for now

**Comment by pkarashchenko** [comment]
`ta_domain` is under `#ifndef CONFIG_BUILD_KERNEL`, so probably need to change line above as well

**Comment by xiaoxiang781216** [comment]
> `ta_domain` is under `#ifndef CONFIG_BUILD_KERNEL`, so probably need to change line above as well. It is also under `# ifdef CONFIG_LIBC_LOCALE`, so it is probably a good way to add same wrapper in this file

Done.

**Comment by pkarashchenko** [comment]
Ok. Probably ai will change to `#if !defined(CONFIG_BUILD_KERNEL) && defined(CONFIG_LIBC_LOCALE)` in the next commit. Should be fine for now

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
