### PR TITLE
WIP: Support for lpc55xx

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Initial support for lpc55xx targeting LPCXpresso55S69 EVK

Requirements:
- [x] Memory Map
- [x] Builds
- [ ] ARM Interrupt
- [ ] lowserial
- [ ] USART
- [ ] OSTest
- [ ] Peripheral Interrupts
- [ ] IOMUX
- [ ] Clock Config -- Limited support
- [ ] Timer
- [ ] LED/Button
- [ ] FPU

### CODE REVIEW

**Comment by acassis** [comment]
Hi Brennan, I think you forgot to run nxstyle ;-)

**Comment by btashton** [comment]
This will come, I noticed there are a lot of style issues in the lpc54xx that I am working off of.

**Comment by btashton** [comment]
Unfortunately configuring the higher speed clock for the LPC55xx requires changing the core voltage and this is not documented outside of using a binary library they supply.  This has been an issue in the past with other LPC versions, and in one case for the lpc54 they releases a technical with the source for this library, but nothing exists for the lpc55.

I have several people that are sending me boards with this chip and I reached out to a contact at NXP, but I am not super motivated to keep pushing this port forward unless we can get the missing information.

I would hate to see this die here, so if anyone has an NXP contact that could help it would be much appreciated.

**Comment by patacongo** [comment]
> I have several people that are sending me boards with this chip and I reached out to a contact at NXP, but I am not super motivated to keep pushing this port forward unless we can get the missing information.

I had the same issue with another LPC part... the LPC54?  I don't recall.  I resorted to disassembling the objects from the libraries to get the missing functions.  This functions were trivial.  Simple writes of magic values to registers.  Not more than about 2 lines of code.

**Comment by btashton** [comment]
Yeah for the lpc54 there was a technical note published with a dump of the source, but for the lpc55 there is not, and the PMU looks to be quite different.

There are 4 undocumented registers being read from the NXP reserved ROM that are related to process and trim.  For my chip some of them are 0 so I have asked some other people to check as well.

There are three voltages for each process class that represent the Low Med and High speed ranges, so I will probably just implement the higher range at the expense of a little power.

If anyone else an LPC55xx the chip specific registers I am interested values for are:
0x9fcd8
0x9fcdc
0x9fd30
0x9fd40

**Comment by hinxx** [comment]
> If anyone else an LPC55xx the chip specific registers I am interested values for are:
0x9fcd8
0x9fcdc
0x9fd30
0x9fd40

I can try on my OKdo E1 board. I'm quite new to this chip/board. How do I read them out? Directly access the addresses above?

**Comment by btashton** [comment]
> > If anyone else an LPC55xx the chip specific registers I am interested values for are:
> > 0x9fcd8
> > 0x9fcdc
> > 0x9fd30
> > 0x9fd40
> 
> I can try on my OKdo E1 board. I'm quite new to this chip/board. How do I read them out? Directly access the addresses above?

Yeah you can directly access them.  I just connect my jlink and read them via gdb.

**Comment by hinxx** [comment]
> Yeah you can directly access them. I just connect my jlink and read them via gdb.

Did I get this right?

```
(gdb) p/x $0x9fcd8
$9 = 0x0
(gdb) p/x $0x9fcdc
$10 = 0x0
(gdb) p/x $0x9fd30
$11 = 0x0
(gdb) p/x $0x9fd40 
$12 = 0x0
```

**Comment by btashton** [comment]
I think you need a * instead of the $

**Comment by hinxx** [comment]
OK, here we go:
```
(gdb) p/x *0x9fcd8 
$19 = 0x228acf9
(gdb) p/x *0x9fcdc
$20 = 0x1e04498
(gdb) p/x *0x9fd30
$21 = 0x2638bb7
(gdb) p/x *0x9fd40
$22 = 0x250792b
```

**Comment by patacongo** [comment]
> I think you need a * instead of the $

Will GDB let you dereference a constant?  I usually do the more wordy:

(gdb) p /x *(int *)0x9fd40

Most monitors provide additional commands.  I use J-Link and so would do:

(gdb) mon mem32 0x9fd40

**Comment by btashton** [comment]
> Will GDB let you dereference a constant?  I usually do the more wordy:
> 
> (gdb) p /x *(int *)0x9fd40

That is the implied cast so I usually skip it.   But yeah you quickly need to be explicit on the type. 

The mon commands with jlink can be really nice when you want to touch memory that is "special". Sometimes I just fire up jlink CLI to just poke the mem without bothering with gdb. The edu mini probe really got me back on there tools.  I wish the black magic probe supported more hardware, but I cannot say working on a JTAG probe excites me.

**Comment by btashton** [comment]
@hinxx one more question is your chip rev A0 or B1?  There is this guide to identify it.
https://community.nxp.com/servlet/JiveServlet/downloadImage/102-345272-4-294788/pastedImage_2.png

**Comment by hinxx** [comment]
It is 1B revision.

**Pull request closed without merging**
