### PR TITLE
stm32: nxstyle fixes

### PR DESCRIPTION
**Pull request by hartmannathan**
## Summary

arch/arm/include/stm32/irq.h:
arch/arm/src/stm32/hardware/stm32_dma_v1.h:
arch/arm/src/stm32/hardware/stm32_i2c.h:
arch/arm/src/stm32/hardware/stm32_pinmap.h:
arch/arm/src/stm32/stm32_dma.c:
arch/arm/src/stm32/stm32_dumpgpio.c:
arch/arm/src/stm32/stm32_gpio.h:

    * nxstyle fixes, mostly long lines

## Impact

No functional changes. Silences numerous nxstyle errors.

## Testing

Changes pass nxstyle.

### CODE REVIEW

**Comment by hartmannathan** [comment]
Why is it saying that the macOS (sim) test was cancelled?

**Comment by xiaoxiang781216** [comment]
Yes, it is very strange and happen many time from yesterday. @btashton and @liuguo09 . But the change looks good, let's merge it to unblock your work.

**Comment by btashton** [comment]
We are not the only ones facing this for macOS especially recently. For example:
https://github.com/scipy/scipy/issues/12016

I noticed it seemed to get more common when we added more targets and the build time increased, but we are well under the cutoff. I can comment on the forums, but for now rebuilding or using judgement is probably the best. There is a job that runs on master so we can catch things there as well post merge.

**Comment by hartmannathan** [comment]
> We are not the only ones facing this for macOS especially recently. For example:
> [scipy/scipy#12016](https://github.com/scipy/scipy/issues/12016)
> 
> I noticed it seemed to get more common when we added more targets and the build time increased, but we are well under the cutoff. I can comment on the forums, but for now rebuilding or using judgement is probably the best. There is a job that runs on master so we can catch things there as well post merge.

Maybe we should consider detecting which parts of the system are touched by a PR and reducing pre-checks. For example if only a particular architecture is affected, other architectures would not be tested? I don't know if this is feasible.

**Pull request merged**
