### PR TITLE
syslog: Code outside libc shouldn't call nx_vsyslog directly

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
since nx_vsyslog is the implementation detail

### CODE REVIEW

**Comment by patacongo** [comment]
Did the checks not start?

**Comment by patacongo** [comment]
For others, a rebase and forced push has been sufficient to get the checks started.

**Comment by patacongo** [comment]
Seems to always fail on Build / Linux (sim) (pull_request) , but I don't see why.

**Comment by btashton** [comment]
```

  Building NuttX...
make[3]: *** /github/workspace/sources/apps/system/usrsock_rpmsg: No such file or directory.  Stop.
make[2]: *** [Makefile:66: /github/workspace/sources/apps/system/usrsock_rpmsg_context] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:128: context_serialize] Error 2
make: *** [tools/Makefile.unix:368: context] Error 2
  Normalize sim/rpserver
```

**Comment by patacongo** [comment]
> Building NuttX...

Thanks.  So this is a problem in the PR that needs fixin'

**Comment by btashton** [comment]
Yes I noticed that the build on master is broken right now.

**Comment by patacongo** [comment]
> Yes I noticed that the build on master is broken right now.

There is a problem with PRs not in apps/ or nuttx/ that depend on a PR in the other repository.  Right now, we are just merging them and hoping for the best.  We have been lucky in the past but this time it broke the build.

**Comment by btashton** [comment]
Yeah, I'm reworking that some more hopefully this week. Certainly a pain point.

**Pull request merged**
