### PR TITLE
board specific code moved to boards directory

### PR DESCRIPTION
**Pull request by RB-tel**
Board specific implementation are moved from arch folder to boards folder

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Shoud we correct the commit message for this patch:
https://github.com/apache/incubator-nuttx/pull/1030/commits/7c504cc7174aaddcd9490095fccf969b35e63725
Remove this empty patch:
https://github.com/apache/incubator-nuttx/pull/1030/commits/4da5f19ed0f07bef1a75b656be4dd71141e34de9
Merge two nxstyle patch into one:
https://github.com/apache/incubator-nuttx/pull/1030/commits/0bf36ecd2c4fad39a71bcb16d538175b822e7fd8
https://github.com/apache/incubator-nuttx/pull/1030/commits/a56e9f01a491fd2438353fa2847b915dd62e6c1d

@RB-tel I also suggested before that it's better to enable renesas daily check if you take renesas support serously.

**Comment by RB-tel** [comment]
> Shoud we correct the commit message for this patch:
> [7c504cc](https://github.com/apache/incubator-nuttx/commit/7c504cc7174aaddcd9490095fccf969b35e63725)
> Remove this empty patch:
> [4da5f19](https://github.com/apache/incubator-nuttx/commit/4da5f19ed0f07bef1a75b656be4dd71141e34de9)
> Merge two nxstyle patch into one:
> [0bf36ec](https://github.com/apache/incubator-nuttx/commit/0bf36ecd2c4fad39a71bcb16d538175b822e7fd8)
> [a56e9f0](https://github.com/apache/incubator-nuttx/commit/a56e9f01a491fd2438353fa2847b915dd62e6c1d)
> 
> @RB-tel I also suggested before that it's better to enable renesas daily check if you take renesas support serously.

When I run nxstyle check on my repository, I do not get few violations. But when I do PR, the check fails with the violations. I will fix them. Please ignore the PR till I clear the checks.

I am new to github, so doing multiple commits. Will learn the process and try to avoid such things.

**Comment by xiaoxiang781216** [comment]
Maybe your branch contain the old nxstyle, the best workflow is:
git checkout master -- it's better to use other branch instead master
git fetch apache
git rebase apache/master
./tools/checkpatch.sh ....
git rebase --interactive -- squash or remove the patch as needed
git push -f origin master

**Comment by RB-tel** [comment]
> Maybe your branch contain the old nxstyle, the best workflow is:
> git checkout master -- it's better to use other branch instead master
> git fetch apache
> git rebase apache/master
> ./tools/checkpatch.sh ....
> git rebase --interactive -- squash or remove the patch as needed
> git push -f origin master

Thanks a lot. Will use the above suggested workflow.

**Pull request merged**
