### PR TITLE
Enable irtest tool

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
Enable irtest tool
## Testing
Daily test

### CODE REVIEW

**Comment by acassis** [comment]
macOS crashed, I just ask to re-run the CI. "macOS is a life delay" (TM)

**Comment by acassis** [comment]
Guys, any idea why is it failing on macOS even after restart the CI jobs?

**Comment by Donny9** [comment]
> Guys, any idea why is it failing on macOS even after restart the CI jobs?

This failure is caused by irtest app with using the wrong syntax of __attribute__((section)). I'll fix this issue later in this week. Thank you.

**Comment by Donny9** [comment]
> Guys, any idea why is it failing on macOS even after restart the CI jobs?

we need to merge this PR https://github.com/apache/incubator-nuttx-apps/pull/507 to fix this issue on mac. Please review @acassis

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Pull request merged**
