### PR TITLE
[Xtensa/RISC-V] Remove FAR and CODE qualifiers from arch-specific files

### PR DESCRIPTION
**Pull request by gustavonihei**
## Summary
This PR intends to remove all references to the `FAR` and `CODE` qualifiers from **Xtensa** and **RISC-V** files.
`FAR` and `CODE` are defined to nothing on both architectures.

## Impact
Should have no impact.

## Testing
CI build pass.

### CODE REVIEW

**Comment by gustavonihei** [comment]
Please, ignore the nxstyle errors due to mixed case on the ESP32-C3 BLE adapter.
```
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:333:12: error: Mixed case identifier found
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:334:12: error: Mixed case identifier found
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:335:11: error: Mixed case identifier found
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:2407:9: error: Mixed case identifier found
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:2431:2: error: Mixed case identifier found
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c:2455:8: error: Mixed case identifier found
Error: Process completed with exit code 1.
```

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by gustavonihei** [comment]
> @gustavonihei do you plan to apply the same change to other arch(e.g. arm, sim...)?

I think it is important to consider those other archs, but not on this PR.
The changes begin with a simple find/sed, but then the manual changes for nxstyle take a considerable amount of time.

**Comment by xiaoxiang781216** [comment]
I thank we can ignore the style warning in these patches.

**Comment by yamt** [comment]
what's the motivation of the change? make the code look neater?

a downside of this kind of changes is that it can introduce unnecessary differences among implementations which were otherwise more similar.

**Comment by gustavonihei** [comment]
> what's the motivation of the change? make the code look neater?

Exactly. This will make the code cleaner, which benefits readability.
> 
> a downside of this kind of changes is that it can introduce unnecessary differences among implementations which were otherwise more similar.

Soon other archs may also have FAR and CODE removed, so this won’t be an issue.

**Pull request merged**
