### PR TITLE
Fix typos in comments and documentation.

### PR DESCRIPTION
**Pull request by hartmannathan**
This fixes numerous typos, grammar errors, etc., in various docs and many source files (comments only). No functional changes.

I did not run nxstyle against the many files touched by this change. There should not be any new violations. Even if some of the files contain old violations, I think it is best to fix the typos first.

### CODE REVIEW

**Comment by patacongo** [comment]
@hartmannathan  There are three files that are failing the nxstyle check.  The good news that is a lot of files to change to only find three problem files!

With the new nxstyle qualification, it is a disincentive to modify lots of files, even for innocuous changes.

Can you force push changes to those three files?

**Comment by hartmannathan** [comment]
> @hartmannathan There are three files that are failing the nxstyle check. The good news that is a lot of files to change to only find three problem files!
> 
> With the new nxstyle qualification, it is a disincentive to modify lots of files, even for innocuous changes.
> 
> Can you force push changes to those three files?

Where are the failing files listed?

**Comment by patacongo** [comment]
PR Check CI / check (pull_request) Failing after 2m — check Details

Select details

**Comment by patacongo** [comment]
If you do not have time, I can make the changes for you on your behalf.  Let me know.

**Comment by hartmannathan** [comment]
> PR Check CI / check (pull_request) Failing after 2m — check Details
> 
> Select details

Strange. Earlier that was giving me a blank window. Now I see output.

But I don't see three files; I see myriad files with "long line" and other complaints. Which three were you referring to?

You're right that this is a disincentive; though the problem with typos is that once you find one, it's an easy matter to grep for other instances of the same thing and fix them all. But, that touches a lot of files. It looks like we'll need a systematic approach to go through files, directory by directory, and bring everything into compliance with nxstyle over time.

**Comment by patacongo** [comment]
> But I don't see three files; I see myriad files with "long line" and other complaints. Which three were you referring to?

Oops I didn't scroll down.. thre are quite a few more than three.  The file name is on each line.

**Comment by patacongo** [comment]
The "new" rules are, if you touch a file it goes through the still check and if there are any style problems, it fails the pre-merge checks.

**Comment by patacongo** [comment]
@xiaoxiang781216 We talked in the past about costmestic changes to files no being required to go through the same procedure.  Is this an example?  Could this be committed with outstanind coding standard violations.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 We talked in the past about cosmestic changes to files no being required to go through the same procedure. Is this an example? Could this be committed with outstanding coding standard violations.

Yes, I think so. That is why we don't let build depend on check so we can waive the check error case by case.

**Comment by hartmannathan** [comment]
> > @xiaoxiang781216 We talked in the past about cosmestic changes to files no being required to go through the same procedure. Is this an example? Could this be committed with outstanding coding standard violations.
> 
> Yes, I think so. That is why we don't let build depend on check so we can waive the check error case by case.

I agree; since these are typo fixes, even if other outstanding problems remain, this change is moving these files in the right direction.

**Pull request merged**
