### PR TITLE
libxx: Switch the package downloading from 11.0.0.rc1 to 11.0.0

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Impact
Switch rc1 to official release(11.0.0).

### CODE REVIEW

**Review by Ouss4 — APPROVED** [review]

**Comment by btashton** [comment]
@Ouss4 What do you think about including this in the 10.0.0 release.  Seems like it would be best to ship with the release instead of the RC

**Comment by Ouss4** [comment]
> @Ouss4 What do you think about including this in the 10.0.0 release.  Seems like it would be best to ship with the release instead of the RC

@btashton That makes sense.  Let's backprort this one.

**Comment by yamt** [comment]
@xiaoxiang781216 
is there a config for which this builds cleanly?
i tried imxrt1050-evk:libcxxtest and stm32f4discovery:testlibcxx but no luck.

i wanted to build it for sim/macOS. even after fixing several things,
it complains about lack of cbrtf() etc. and the complaint sounds correct as nuttx math.h doesn't have them.

**Comment by xiaoxiang781216** [comment]
@yamt since math library provided by NuttX isn't standard complaint and not optimzed, I would suggest use libc++ with toolchain provided math library. We have test the follow combination which work perfect:

1.  ARM Cortex A/M with libm from newlib
2. Linux simulator with libm from glibc

**Comment by yamt** [comment]
@xiaoxiang781216 can you give me a config for "Linux simulator with libm from glibc"?

**Comment by xiaoxiang781216** [comment]
@yamt here is the patch: https://github.com/xiaoxiang781216/incubator-nuttx/tree/cpp3

**Pull request merged**
