### PR TITLE
New files for pysimCoder

### PR DESCRIPTION
**Pull request by robertobucher**
## Summary
Files under board/arm/stm32f7/nucleo-144
f746-pysim/defconfig
include/board.h
src/nucleo-144.h
src/stm32_appinitialize.c
src//stm32_bringup.c
src/stm32_gpio.c

Configuration for a testing system with:
4 DI
4 DO
2 encoders
2 PWM + complementary channel
4 ADC
LAN

## Impact
STM32F7 nucleo-144 board

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@robertobucher could you rebase your change to remove the merge patch?

**Comment by robertobucher** [comment]
I can't understand exactly what you mean with "remove the merge patch"... I did a pull request of my master branch before putting my modifications and launch  the PR...

**Comment by xiaoxiang781216** [comment]
please see here:
https://github.com/apache/incubator-nuttx/pull/7428/commits
the second commit should be dropped.

**Comment by acassis** [comment]
@robertobucher you need to follow the workflow explained here:
https://nuttx.apache.org/docs/latest/contributing/making-changes.html#git-workflow-with-an-upstream-repository

After creating your commits in your separated branch you need to rebase with mainline (upstream) instead of merging to it.

Basically you will do:
```
$ git rebase upstream/master
```

Normally I only do:
```
$ git rebase upstream
```

It is enough to sync my branch with the upstream code (remember that you need to do "git pull" in the upstream branch before doing it and you need to do it from your development branch)

**Comment by robertobucher** [comment]
I'll try to restart the full PR!

**Pull request closed without merging**
