### PR TITLE
libxx:uclibxx: add patch use overload constructor of filebuf & ostream

### PR DESCRIPTION
**Pull request by zhuyanlinzyl**
overload constructor of filebuf & ostream in uclibxx

## Summary

Bug fix in uclibxx initalize

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@yamt please try this patch.

**Comment by yamt** [comment]
it seems the crash on boot has been fixed by this change.
```
(lldb) target create "./nuttx"
Current executable set to '/Users/yamamoto/git/nuttx/nuttx/nuttx' (x86_64).
(lldb) run
Process 92526 launched: '/Users/yamamoto/git/nuttx/nuttx/nuttx' (x86_64)
test ofstream===========================
printf: Starting test_ostream
printf: Successfully opened /dev/console
cout: Successfully opened /dev/console
Writing this to /dev/console
test iostream===========================
Hello, this is only a test
Print an int: 190
Print a char: d
test vector=============================
v1=1 2 3
Hello World Good Luck 
test map================================
test rtti===============================
extend
```

**Comment by yamt** [comment]
i read the patch but i don't understand how it fixes the crash. can you give me a brief explanation?

**Comment by zhuyanlinzyl** [comment]
The crash is not happen in my GCC build,  When I build same code with CLANG-6.0, 

The crash is in ios_base::Init::Init()

_cout_filebuf.openedFor = ios_base::out

The reason is global object `_cout_filebuf`  was placed in a difference section in CLANG (which specific section I have forgotten now),

when run  _cout_filebuf.openedFor = ios_base::out,   It crash on on this section can't be writing.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by yamt** [comment]
> The crash is not happen in my GCC build, When I build same code with CLANG-6.0,
> 
> The crash is in ios_base::Init::Init()
> 
> _cout_filebuf.openedFor = ios_base::out
> 
> The reason is global object `_cout_filebuf` was placed in a difference section in CLANG (which specific section I have forgotten now),
> 
> when run _cout_filebuf.openedFor = ios_base::out, It crash on on this section can't be writing.

i investigated a bit.

my observations
* the access to cerr.mformat crashes because cerr (specifically its vptr) has not been initialized at this point and mformat is a member of the base class, which is using virtual inheritance.
* gcc seems to produce code which bypasses vtable in this case. it explains why it works with gcc.
* i consider it a bug of uClibc++.

**Comment by xiaoxiang781216** [comment]
Yes, the correct and elegant approach is pass the initial parameter through constructor, like what we have done in this PR.

**Pull request merged**
