### PR TITLE
bl602: Update register maps and lower half drivers

### PR DESCRIPTION
**Pull request by btashton**
## Summary
This brings the BL602 port more in-line with NuttX especially with how registers are handled.

## Testing
Tested on bl602evb board.

```
NuttShell (NSH) NuttX-10.0.1
nsh> uname -a
NuttX 10.0.1 91f2f4b76c-dirty Dec 30 2020 12:28:51 risc-v bl602evb
nsh> sleep 3
nsh> ?
help usage:  help [-v] [<cmd>]

  ?       echo    help    ls      mh      mv      ps      uname   
  cat     free    kill    mb      mount   mw      sleep   usleep  

Builtin Apps:
  timer     getprime  sh        hello     nsh       
nsh> ps
  PID PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0   0 FIFO     Kthread N-- Ready              00000000 008192 008172  99.7%! Idle Task
    1 100 FIFO     Task    --- Running            00000000 008196 001564  19.0%  init
nsh> free
             total       used       free    largest
Umem:       198928      10688     188240     188240
nsh> ls /dev
/dev:
 console
 null
 timer0
 zero
nsh> timer
Open /dev/timer0
  flags: deadbeef timeout: 4294967295 timeleft: 4294967295 nsignals: 0
Set timer interval to 1000000
  flags: deadbeef timeout: 1000000 timeleft: 1000000 nsignals: 0
Attach timer handler
  flags: deadbeef timeout: 1000000 timeleft: 1000000 nsignals: 0
Start the timer
  flags: 00000000 timeout: 1000000 timeleft: 1000000 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 896789 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 786848 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 676850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 566850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 456850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 346850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 236850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 126850 nsignals: 0
  flags: 00000000 timeout: 1000000 timeleft: 16850 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 999575 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 896815 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 786848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 676848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 566848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 456848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 346848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 236848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 126848 nsignals: 1
  flags: 00000000 timeout: 1000000 timeleft: 16848 nsignals: 2
Stop the timer
  flags: 00000000 timeout: 1000000 timeleft: 999647 nsignals: 2
Finished

```

### CODE REVIEW

**Comment by btashton** [comment]
@Virus-V @xiaoxiang781216 @v01d   Here are my change on top of the original PR.

I am having some issues as after some time the clock register that controls the flash and UART seems to get changed
clk_cfg2 (0x40000008)

After clock configuration
```
(gdb) p /x *0x40000008
$29 = 0xff8f1993
```
Some seconds later
```
(gdb) p /x *0x40000008
$30 = 0xff8f2b97
```

If I send data out the UART right after configuring the clock I have no issue.

**Comment by v01d** [comment]
This reminds me of something I found when working on support for GD32VF103: while debugging I could see a register value change if I stepped code (which actually had an effect on code execution, so it was not just a debugging artifact). I eventually concluded it was a `gdb` issue as I found the problem to not occur by using a different one. I think that latest stable version from SiFive was the functional one (you could try downloading from here: https://github.com/sifive/freedom-tools/releases)

**Comment by Virus-V** [comment]
@btashton I have tested your code and I am trying to find out the cause of this problem

**Comment by btashton** [comment]
@Virus-V I found my bug and fixed it.  Made a mistake using the signal number instead of mask on the AHB slave reset call.
```
NuttShell (NSH) NuttX-10.0.1
nsh> uname -a
NuttX 10.0.1 91f2f4b76c-dirty Dec 30 2020 12:28:51 risc-v bl602evb
nsh> sleep 3
nsh> ?
help usage:  help [-v] [<cmd>]

  ?       echo    help    ls      mh      mv      ps      uname   
  cat     free    kill    mb      mount   mw      sleep   usleep  

Builtin Apps:
  timer     getprime  sh        hello     nsh       
nsh> ps
  PID PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0   0 FIFO     Kthread N-- Ready              00000000 008192 008172  99.7%! Idle Task
    1 100 FIFO     Task    --- Running            00000000 008196 001564  19.0%  init
nsh> free
             total       used       free    largest
Umem:       198928      10688     188240     188240
nsh> ls /dev
/dev:
 console
 null
 timer0
 zero
nsh> 
```

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Pull request merged**
