### PR TITLE
arch: arm: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses
 to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Review by xiaoxiang781216 — COMMENTED** [review]
LGTM.

**Comment by jerpelea** [comment]
@xiaoxiang781216 this PR is getting bigger 
do you want it split on soc so that it gest easy to review?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 this PR is getting bigger
> do you want it split on ships so that it gets easy to review?

Either is fine for me, please take your prefer approach, thanks.

**Comment by jerpelea** [comment]
> 
> 
> > @xiaoxiang781216 this PR is getting bigger
> > do you want it split on ships so that it gets easy to review?
> 
> Either is fine for me, please take your prefer approach, thanks.

I will split so that we merged bite size chunks

**Comment by jerpelea** [comment]
@xiaoxiang781216 the include warning can be ignored for now

Please merged it after review

**Comment by jerpelea** [comment]
@xiaoxiang781216

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
