### PR TITLE
sched: Remove volatile from the task list

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
it inappropriate to apply volatile to the task list:
1.The code access task list is already protected by critical section
2.The queue is complex struct, it isn't enough to protect by volatile

## Impact
The generated code is same before and after modification on sabre-6quad:smp:
before:
```
   text    data     bss     dec     hex filename
 129436     240   33484  163160   27d58 nuttx
```
after:
```
   text    data     bss     dec     hex filename
 129436     240   33484  163160   27d58 ../nuttx.list
```

## Testing
Pass CI

### CODE REVIEW

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 the PR description states about "protection by volatile", but volatile just ensures that structure members are always fetched from memory. But in general I agree that if access to the struct is protected by a critical section, then the structure elements can't change its value during protected time. The only question is SMP case where a spin lock might be needed. I will take a look into this change today

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 the PR description states about "protection by volatile", but volatile just ensures that structure members are always fetched from memory. But in general I agree that if access to the struct is protected by a critical section, then the structure elements can't change its value during protected time. The only question is SMP case where a spin lock might be needed. I will take a look into this change today

The critical section hold the spin lock internally in SMP. To verify the change doesn't have any side effect, I compare the generated code on sabre-6quad:smp with and without my patch.

**Review by pkarashchenko — APPROVED** [review]
But if the generated code is the same then why do we need the change ;)

**Comment by xiaoxiang781216** [comment]
> But if the generated code is the same then why do we need the change ;)

avoid the cast to remove volatile which will be in the next PR.

**Comment by xiaoxiang781216** [comment]
@pkarashchenko I add a new patch remove the unnecessary cast.

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
