### PR TITLE
net/local: Rename NET_LOCAL_PATH_PREFIX to NET_LOCAL_VFS_PATH

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
align with other similar config which suffix with _VFS_PATH. See: https://github.com/apache/incubator-nuttx/pull/5422

## Impact
Minor, since nobody change the default setting.

## Testing
Pass CI

### CODE REVIEW

**Comment by pkarashchenko** [comment]
Is this a breaking change?

**Comment by xiaoxiang781216** [comment]
> Is this a breaking change?

Why? no body set CONFIG_NET_LOCAL_PATH_PREFIX in defconfig to other value, I think.

**Comment by pkarashchenko** [comment]
> > Is this a breaking change?
> 
> Why? no body set CONFIG_NET_LOCAL_PATH_PREFIX in defconfig to other value, I think.

In NuttX repos I think nobody, but we do not know about all user apps. What do you think?

**Comment by xiaoxiang781216** [comment]
It's the implementation detail that Unix domain socket use the fifo internally. I believe that most user except the network subsystem expert don't know this fact. Also, we have discussed internally several time to remove this dependence to fix some important problem we found but is very very hard to fix in the current design.

**Comment by xiaoxiang781216** [comment]
Anyway, I mark the PR with "breaking change" label to help the documentation later.

**Comment by pkarashchenko** [comment]
I will try to learn more about when "breaking change" label should be introduced and when not. I'm just thinking that if the config option is renamed then user defconfigs might be broken.

**Comment by hartmannathan** [comment]
Any time we rename a Kconfig that has existed in a released tarball, it is potentially a breaking change to downstream users. I don't know about this specific change but I am just commenting on the "breaking change" label. I think it's a good idea to keep that label here and make sure we mention it in the release notes for the next version.

**Review by pkarashchenko — COMMENTED** [review]
LGTM!

**Pull request merged**
