### PR TITLE
Revert "README.txt: add MacOS section for flock installation"

### PR DESCRIPTION
**Pull request by yamt**
This reverts commit 7a76a97f44138074ebdebd78d997da9381fa3e44.

### CODE REVIEW

**Comment by yamt** [comment]
consider this after https://github.com/apache/incubator-nuttx-apps/pull/81

**Comment by xiaoxiang781216** [comment]
> consider this after [apache/incubator-nuttx-apps#81](https://github.com/apache/incubator-nuttx-apps/pull/81)

But that patch will break some arch. If you really want to use shlock on macOS, it is better to add a bash script and call shlock/flock before check the platform, but keep ARCHIEVE call.
BTW, It's better to check the platform in the bash instead Make.defs.

**Comment by yamt** [comment]
@xiaoxiang781216 which arch does it break?
using shlock on macOS is not the main point of https://github.com/apache/incubator-nuttx-apps/pull/81 .
we can't assume bash, can we? i don't think it's worth to write .bat file for this.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 which arch does it break?
> using shlock on macOS is not the main point of [apache/incubator-nuttx-apps#81](https://github.com/apache/incubator-nuttx-apps/pull/81) .
> we can't assume bash, can we? i don't think it's worth to write .bat file for this.

Here:
https://github.com/FishsemiCode/nuttx/blob/song-u1/arch/ceva/src/song/Toolchain.defs

**Comment by yamt** [comment]
@xiaoxiang781216 it seems using AR via ARNOEMP. but i got your point.

i wrote another alternative. how do you think?
https://github.com/apache/incubator-nuttx-apps/pull/83

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 it seems using AR via ARNOEMP. but i got your point.
> 
> i wrote another alternative. how do you think?
> [apache/incubator-nuttx-apps#83](https://github.com/apache/incubator-nuttx-apps/pull/83)

Has one concern, I reply in that PR.

**Comment by patacongo** [comment]
The z80 and z16 families are different becuse the ZDS II archiver will only archive one file at a time.

**Comment by patacongo** [comment]
@xiaoxiang781216: "we can't assume bash, can we?". Yes, in most cases you can assume bash or similar in all cases except Windows native build.  You should try not to break the Windows native build any more that possible.  That will be revisited in the near future.

Has this discussion reached a conclusion?  Is thie PR ready to be merged?

**Comment by xiaoxiang781216** [comment]
This depend on which approach you want to fix the parellel build issue:
1.Use flock
  a.Close this PR directly
  b.Merge https://github.com/apache/incubator-nuttx/pull/342 and https://github.com/apache/incubator-nuttx-apps/pull/84
2.Or apply this patch and https://github.com/apache/incubator-nuttx-apps/pull/83
  but we may need more test since the change is little big, especially the command line may become very long(basiclly all full path .o archieve into libapps.a in one step).

**Pull request merged**
