### PR TITLE
Add nx_mount2 and nx_umount function

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
These patch series refine the internal function by:
1.Rename clock_systimer to clock_systimetick
2.Add nx_mount and nx_umount2 function

## Testing

Only mix case warning isn't fixed:
```
arch/arm/src/lc823450/lc823450_sddrv_dep.c:98:35: error: Mixed case identifier found
arch/arm/src/lc823450/lc823450_sddrv_dep.c:147:29: error: Mixed case identifier found
```
Work with(because change some mix case macro to upper case):
https://github.com/apache/incubator-nuttx-apps/pull/228

### CODE REVIEW

**Comment by patacongo** [comment]
I prefer to old name

**Comment by patacongo** [comment]
This change is too arbritrary.  I don't think we should permit arbitrary changes with no justification.

**Comment by patacongo** [comment]
The system tick counter is referred to as the system timer or systimer in all documentation.  If you just wanat to add a units to the name, an underbar would make that clearer.  perhaps clock_systimer_tick?

**Comment by patacongo** [comment]
Why does the Title have nothing to do with the Summary?

**Comment by xiaoxiang781216** [comment]
> This change is too arbritrary. I don't think we should permit arbitrary changes with no justification.

We have two similar functions:
1.clock_systimespec return timespec(second plus nanosecond)
2.clock_systimer return clock tick
So I think clock_systimetick is a better name becuase:
1.Align with clock_systimespec
2.Reader can know the time unit immediately
3.All other related timing function use 'time', it's very strange that we use 'timer' here.

**Comment by xiaoxiang781216** [comment]
The macro used by apps is changed to upper case, need work with apache/incubator-nuttx-apps#228:
```
nrf24l01_term.c: In function 'wireless_cfg':
nrf24l01_term.c:122:34: error: 'RATE_1Mbps' undeclared (first use in this function); did you mean 'RATE_1MBPS'?
  122 |   nrf24l01_datarate_t datarate = RATE_1Mbps;
      |                                  ^~~~~~~~~~
      |                                  RATE_1MBPS
nrf24l01_term.c:122:34: note: each undeclared identifier is reported only once for each function it appears in
nrf24l01_term.c:127:14: error: 'DELAY_1000us' undeclared (first use in this function); did you mean 'DELAY_1000US'?
  127 |     .delay = DELAY_1000us
      |              ^~~~~~~~~~~~
      |              DELAY_1000US
```

**Comment by xiaoxiang781216** [comment]
> > This change is too arbritrary. I don't think we should permit arbitrary changes with no justification.
> 
> We have two similar functions:
> 1.clock_systimespec return timespec(second plus nanosecond)
> 2.clock_systimer return clock tick
> These two functions return the same value but with different time unit.
> So I think clock_systimetick is a better name becuase:
> 1.Align with clock_systimespec
> 2.Reader can know the time unit immediately
> 3.All other related timing function use 'time', it's very strange that we use 'timer' here.
> 
> > The system tick counter is referred to as the system timer or systimer in all documentation. If you just wanat to add a units to the name, an underbar would make that clearer. perhaps clock_systimer_tick?
> 
> timer is generally used to represent the event or callback happen in the furture, e.g.:
> getitimer/setitimer/timer_create/timer_settime..
> time is used to represent the timing or clocking:
> clock_gettime/clock_settime/time...
> That is why I drop 'r' and add tick to clock_systimer which make it's more consistent with POSIX naming convention.

@patacongo do you think the justification is enough or I remove "Rename clock_systimer to clock_systimetick" from the PR?
I am fine if you still think the clock_systimer is better than clock_systimetick.

**Comment by patacongo** [comment]
> I am fine if you still think the clock_systimer is better than clock_systimetick.

I don't have strong feelings about names as long as the following the naming conventions.  But think it is not a good practice to change establish names of OS internal functions only because of personal preference.

**Comment by xiaoxiang781216** [comment]
Actually, I don't have any personal preference:). Following the rule(either state in document explicitly or represent in the code base) as much as possible is my most favor. We may introduce some new symbol which is good at that time, but not good at the later since the context change. For example, clock_systimer looks good at the beginning, but it become inconsistent with other similiar function after we add clock_systimespec, clock_getime.... Now, we have decide what we should do next:
1.Keep it as before. then the inconsistence keep increasing and finally we mayn't have a rule to follow.
2.Refactor the code base to make it consistence again.
We don't have choice for the standard defined symbols, but we have the choice for NuttX's symbols.
Here is another example you need decide:
https://github.com/apache/incubator-nuttx/pull/990/commits/4bb943a0c0ab173d7f5eb0178fd3a332726ce861

**Comment by patacongo** [comment]
> Here is another example you need decide:
> [4bb943a](https://github.com/apache/incubator-nuttx/commit/4bb943a0c0ab173d7f5eb0178fd3a332726ce861)

Yes, that is the wrong naming.  **This is in complete complet conflict with what I have been trying to do please remove this commit!    I have get modifying names to INCLUDE the _ in the name.  I have been trying follow a pattern of:

    <subssystem>_<action>_<object>

So the name reads like a sentence who = sched, action = get, get what = stackinfo

Please DO NOT CHANGE THIS NAME.  We must work together and not against each other.  Picked that name because I want it EXACTLY as it is.**

**Comment by patacongo** [comment]
Also I do not like the name clock_systimetick().  It feels like bad English to me.

**Comment by xiaoxiang781216** [comment]
> > Here is another example you need decide:
> > [4bb943a](https://github.com/apache/incubator-nuttx/commit/4bb943a0c0ab173d7f5eb0178fd3a332726ce861)
> 
> Yes, that is the wrong naming. **This is in complete complet conflict with what I have been trying to do please remove this commit! I have get modifying names to INCLUDE the _ in the name. I have been trying follow a pattern of:
> 
> ```
> <subssystem>_<action>_<object>
> ```
> 
> So the name reads like a sentence who = sched, action = get, get what = stackinfo
>
> Please DO NOT CHANGE THIS NAME. We must work together and not against each other. Picked that name because I want it EXACTLY as it is.**

But there are many name already violative your rule:
sched_getaffinity
sched_getcpu
sched_getparam
sched_getscheduler
sched_getstreams
Even NuttX special function:
sem_setprotocol
sem_getprotocol
How we handle these symbol?

**Comment by xiaoxiang781216** [comment]
> Also I do not like the name clock_systimetick(). It feels like bad English to me.

Ok, I will drop clock_systimer from PR.

**Comment by patacongo** [comment]
But this is hard to have a real technical discussion because this is about your ego, not about the engineering work.

**Comment by patacongo** [comment]
> But there are many name already violative your rule:
> sched_getaffinity
> sched_getcpu
> sched_getparam
> sched_getscheduler
> sched_getstreams
> Even NuttX special function:
> sem_setprotocol
> sem_getprotocol
> How we handle these symbol?

Nothing is broken.  Nothing needs to be fixed.  No changes should be made.  There are also many more names that use the _get_ namining

If we want to start renaming everything in world (I vote against that), then we should decide and agree on the naming first.  This is not something that you should be forcing down everyone's throat.  

I prefer the naming that I suggest because it separates the action.  I dislike the naming that you are pushing on us.

**Comment by xiaoxiang781216** [comment]
> But this is hard to have a real technical discussion because this is about your ego, not about the engineering work. This is a name for that: NIH

But what's the engineering work? should it be to define a set of rule and let the team work together to follow the rule as much as possible at least for what we can control?

**Comment by patacongo** [comment]
Please remove the controversional name changes from this PR and lets deal with that separately.  I definitely want to keep the name sched_get_stackinfo().  I just wrote that function and it is an insult to me that you are changing it into a shitty name.

**Comment by xiaoxiang781216** [comment]
Ok, that's fine I have drop sched_get_stackinfo from PR.

**Comment by patacongo** [comment]
This is all very annoying to me.  It is difficult to work in an environment where people are making many, arbitrary changes that are not improvements that but just things they do to satisfy their egos.  Then the changes break the system.  I am not just talking this this PR, but the way things are being done in general.  This is terrmible.  We need to be more professional.

**Comment by patacongo** [comment]
This level of arbitrary code turmoils harms the system.  It does not help.

**Pull request merged**
