### PR TITLE
New features for samd5e5 and metro-m4

### PR DESCRIPTION
**Pull request by leomar95**
## Summary
arch: samd5e5
- Add USB host support.
- Fixes in USB device and i2c.

boards: metro-m4  Add support for:

- vfat auto-mounted on a flash drive;
- i2c inicialization;
- usb-dev cdc;
- sam_usbhost_vbusdrive needs your VBUS implementation.

## Impact
New features available for samd5e5.

## Testing
- Build check only.

Signed-off-by: Leomar Mateus Radke  <leomar@falker.com.br>

### CODE REVIEW

**Comment by johannes-nivus** [comment]
Just a hint:
Some days ago I introduced USB mass storage class state change notifier. PR #1531
I also implemented an automounter based on this for Kinetis Freedom K28.
I have this running with Hub support and can e.g. mount and unmount 3 USB sticks and enumerate another FTDI cable without affecting the automounter.
Perhaps you'd like to have a look. 
Johannes

**Comment by leomar95** [comment]
@johannes-nivus thanks for your hint, i hadn't seen your PR #1531 before the pull-request. #1574 worked for me, but I'll consider your ideas in Freedom K28 the for next commits.

**Comment by acassis** [comment]
Hi Leomar, I will merge these patches, but please consider the idea of assigning the Apache's ICLA and submitting code under Apache license.

**Comment by acassis** [comment]
It appears your branch is not up-to-dated:
"Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

**Comment by leomar95** [comment]
Hi @acassis, i did the merge, but there are still conflicts. I don't understand the error.

**Pull request merged**
