### PR TITLE
Backport #843 to releases/9.0

### PR DESCRIPTION
**Pull request by Ouss4**
Backport #843

### CODE REVIEW

**Comment by Ouss4** [comment]
The tests pull apps' master not releases/9.0, that won't pass with the recent audio changes.

**Comment by patacongo** [comment]
I don't understand the build failure.

**Comment by patacongo** [comment]
> The tests pull apps' master not releases/9.0, that won't pass with the recent audio changes.

What do you recommend?  I think the change is safe, but it must be verified.

**Comment by btashton** [comment]
I think it's safe but let me get my CI fix in so it will build off the correct branch if it is the release branch.

**Comment by Ouss4** [comment]
The changes that Alin did recently to the audio subsystem are not included in the releases/9.0 branch.
When the tests run they pull the latest apps/ (which has the recent changes) and build it with this branch.
It's kind of the same issue where you had to merge that apps/ PR with a build failure.

**Comment by Ouss4** [comment]
> I think it's safe but let me get my CI fix in so it will build off the correct branch if it is the release branch.

Ok thanks.   @patacongo  let's wait for that.

**Comment by btashton** [comment]
I'm going to leave master as the target for testing for now. We can opt to make a release branch later if we want to.

**Comment by xiaoxiang781216** [comment]
build.yml always fetch the peer repo from the master which is fine for the daily working, but fail for relese branch. The right strategy is fetch the peer repo base on the branch the PR will appiled.

**Comment by btashton** [comment]
PR #850 should fix this.  It ended up being larger than I wanted, but I think sets us up better to hand matching repos in the future.

**Comment by Ouss4** [comment]
So when that PR is merged, we bring it to releases/9.0 and I rebase this one.

**Comment by xiaoxiang781216** [comment]
@Ouss4 let's rebase your patch and try whether #850 work as expect

**Comment by Ouss4** [comment]
@xiaoxiang781216  I'll need to first bring the last PR to the release branch.

**Pull request merged**
