### PR TITLE
Net: SocketCAN support

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
## Summary
Adds support for the SocketCAN interface api to Nuttx (https://en.wikipedia.org/wiki/SocketCAN)
Furthermore it includes FlexCAN drivers for S32K1XX and Kinetis which are SocketCAN compatible

Additional changes:
Control messages (CMSG) support for sendmsg() and recvmsg() (POSIX 1003.1g)
SIOCGIFNAME & SIOCGIFNAME ioctl

## Impact
Quite big, changes in NET, libc/net, 

## Testing
Verified on rddrone-uavcans32k146 (S32K146) & rddrone-fmuk66 (Kinetis K66).

Furthermore this patch has already been backported to PX4/NuttX where they verified using their CI that this patch doesn't break any boards using the network stack.

## Additional information

This patch requires changes in apps to support AF_CAN in netlib. https://github.com/apache/incubator-nuttx-apps/pull/294

### CODE REVIEW

**Comment by acassis** [comment]
Hi Peter,
Nice to see finally the SocketCAN coming to master branch!

It appears that you forgot to run nxstyle against the files. It stopped because found many 'long lines' in the file arch/arm/src/kinetis/hardware/kinetis_flexcan.h.

**Comment by PetervdPerk-NXP** [comment]
I did but I wasn't sure what to do with the warnings, this is the output I got

`hovergames@hovergames:~/nuttx/nuttx-master$ ./tools/nxstyle arch/arm/src/kinetis/hardware/kinetis_flexcan.h
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:74:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:75:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:76:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:77:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:78:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:79:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:80:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:81:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:82:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:83:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:84:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:85:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:86:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:87:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:88:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:89:43: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:181:46: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:231:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:232:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:233:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:234:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:235:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:236:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:237:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:238:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:239:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:240:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:241:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:242:45: warning: Wrong column position of comment right of code
arch/arm/src/kinetis/hardware/kinetis_flexcan.h:243:45: warning: Wrong column position of comment right of code
`

**Comment by acassis** [comment]
> I did but I wasn't sure what to do with the warnings, since I didn't change these particular lines. this is the output I got
> 
> `hovergames@hovergames:~/nuttx/nuttx-master$ ./tools/nxstyle arch/arm/src/kinetis/hardware/kinetis_flexcan.h arch/arm/src/kinetis/hardware/kinetis_flexcan.h:74:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:75:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:76:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:77:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:78:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:79:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:80:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:81:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:82:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:83:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:84:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:85:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:86:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:87:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:88:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:89:43: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:181:46: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:231:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:232:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:233:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:234:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:235:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:236:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:237:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:238:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:239:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:240:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:241:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:242:45: warning: Wrong column position of comment right of code arch/arm/src/kinetis/hardware/kinetis_flexcan.h:243:45: warning: Wrong column position of comment right of code `

You need to align the start of the comment block, they need to be visually aligned :-)

**Comment by PetervdPerk-NXP** [comment]
I've fixed the warnings now as well. For the remainder of files that are now giving a NXStyle error, I don't have nice and clean solution for them.

For these files I can't change header:
include/nuttx/can/error.h
include/nuttx/net/ioctl.h

For this file net/devif/devif_poll.c it's existing code (which I haven't changed) with a printf which exceeds the character limit.

**Comment by patacongo** [comment]
There are quite a few build problems... most warnings that are treated as errors.  These all need to be fixed before we can merge.

**Comment by patacongo** [comment]
This PR includes 3rd party code.  We will need to update the LICENSE file.  We can do that after the merge.

**Comment by patacongo** [comment]
PROBLEM:  I already merged the companion companion PR in apps/  the companion failed to build because dependencies on this PR.  But this PR should not be merged now because of real build problems.   This think we have no option but to merge this now and fix the problems separately.  Otherwise, the build will be broken.

**Comment by patacongo** [comment]
Hmmm... but I can't merge because there are conflicts 8(

**Comment by patacongo** [comment]
I will remove the old SocketCAN branch now.

**Pull request merged**
