### PR TITLE
 boards/arm/lpc43xx/bambino-200e/src/lpc43_appinit.c:  Fix typo noted by João Matos.

### PR DESCRIPTION
**Pull request by patacongo**
"fails" should have been "failed"

### CODE REVIEW

**Comment by Ouss4** [comment]
Why are there all those commits? I've seen that in some (all?) of your PRs.
Has @acassis  been squash committing them or cherry picking the last one?

**Comment by acassis** [comment]
Hi Abdelatif, Yes it was squashed. Please see the master for reference.

**Comment by patacongo** [comment]
@Ouss4 Yes, my fork has been corrupted.  I create a clean fork tomorrow so that subsequent PRs won't carry the garbage.  I don't know where all of the garbage comes from.  I probably need to --rebase all of the pulls.  But some are these strange changes of gits that don't have any file changes associated with them.

I believe that if I am religious about rebasing vs pulling I can avoid most of these.  Alan and I have been processing numerous PRs per day so our forks will get dirty rather quickly due to the build-up of human errors. We assure that upstream is clean, however.

**Comment by Ouss4** [comment]
Yes, it looks like the fork got corrupted.

Because they are squashed, could those commits (especailly those with changes) cause an issue? For insatance if the change gets reverted.
Since there is usually only a few (or just one) relevant commits maybe cherry picking is safer.

**Comment by patacongo** [comment]
It is not really "corrupted".  I overstated that.  Two things to note:  All of the "extra commits" but one are not commits are all, they are just merge points.  I synchronize with upstream like:

git fetch upstream
git pull upstream master
git push origin master

The second step creates the merge point because a change was merged into the fork from upstream.  The merge point does not correspond to any changes to files.  It is just noting where I merged from upstream.

There one other no file commit which I don't understand.  I made some error several days ago

The the change, in this case, was juse remove one character and adding two fails -> failed.  Add if you look at what changed in all of the combine commits.  Is is only those two characters.  No nothing is wrong, nothing is "corrupted", everything is great!  But the comments generated by git stink.

I don't know if a rebase vs the pull from upstream will eliminate the merge point, but I don't think so.  I will experiment.  A better approach my be to not try to keep the fork up-to-date until I need to use.

I synchronize the bitbuck repositories the same way.  Each new commit brings in a new merge point too.  I really don't like that but, as far as I know, it is unavoidable.

**Comment by Ouss4** [comment]
Why wouldn't rebasing eliminate the merge point?
It should effectively apply any commit you had on top of master and thus eliminate any merge commit.
But if one had a clean history "just" merge would suffice (provided that fast-forward isn't disabled)

However none of that is a real issue, what I was trying to point out (or understand) is that these "old" commits could apply their changes if they got reverted or the change they had got updated.
Since we are squashing them, they slide unnoticed with the rest of the PR.

I was also trying to suggest cherry picking only the relevant commits. For instance in this PR only the last commit had a relevant change, the others have been merged before.

As a side note:

> git fetch upstream
> git pull upstream master
> git push origin master

 Isn't the fetch redundant?

**Pull request merged**
