### PR TITLE
Implement %ju/%jd printf format

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by jerpelea** [comment]
please add commit messages

**Comment by yamt** [comment]
@jerpelea what's unclear to you?

**Comment by jerpelea** [comment]
Each commit should have title and commit message 
Please add a small description according to the rule

**Comment by yamt** [comment]
@jerpelea where can i find the rule?
i scanned "Code Contribution Workflow". but i failed to find it.

**Comment by jerpelea** [comment]
@yamt 
https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Comment by yamt** [comment]
@jerpelea 
ok, i added some text.

honestly speaking, i feel the original commit messages were good enough for this kind of obvious things though.

**Comment by jerpelea** [comment]
@yamt thanks.

Sometimes is hard to state the obvious but it may be usefull for others to understand the reason

**Pull request merged**
