### PR TITLE
kinetis:Ethernet fixed & better interrupt management

### PR DESCRIPTION
**Pull request by davids5**
## Summary
  After 20 mn to an hr, the device would not respond to ping.

  Initial issue was filed in [PX4 here](https://github.com/PX4/Firmware/issues/15036)

   When any error was detected the buffers descriptors were
   blindly initialized. This caused the TX of the MAC to
   be in a bad state. The correct thing to do, we disable
   the MAC, init the bufffers and re-eanable the MAC.

   The interrupts were being throttled at the NVIC. This been cleaned up.

## Impact

 The Interfaces will now work if there are any errors in the data, It could be induced by unplugging a cable on on a switch (not connected to the device)

## Testing

Test we done on nxp_fmuk66. [See](https://github.com/PX4/Firmware/issues/15036#issuecomment-645206980)

### CODE REVIEW

**Comment by patacongo** [comment]
It is this compatible with the network monitor thread?  If the network goes down in that case, a PHY interrupt would be generated and this would cause the network to take similar action.  It seems that is the network monitor were enabled, you should just take the network down and list the network monitor do its things without interference?

**Comment by davids5** [comment]
@patacongo I updated the description, I think it may have misled you.  

 >The Interfaces will now work if there are any errors in the data, It could be induced by unplugging a cable on on a switch (not connected to the device)

It was not a net up/down and was a Babbling Receive Error Indicating a frame was received with length in excess of RCR[MAX_FL] bytes.

**Comment by patacongo** [comment]
> The correct thing to do, we disable the MAC, init the bufffers and re-eanable the MAC.

I presume that you also renegotiate the link?  If you do these things, the network will do down, then come back up.  In some configurations that will generate PHY interrupts which will kick off activity in the network monitor.  I don't know what will happen in that case.  That is my only concern.

**Comment by davids5** [comment]
@patacongo I see. Is there a config that I can test, or can you suggest what has to be lit to test that case?

**Comment by patacongo** [comment]
> 
> 
> @patacongo I see. Is there a config that I can test, or can you suggest what has to be lit to test that case?

This configurations support the network monitory:

    $ find boards -name defconfig | xargs grep NETINIT_MONITOR
    boards/arm/samv7/same70-xplained/configs/netnsh/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/arm/samv7/samv71-xult/configs/netnsh/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/arm/tiva/dk-tm4c129x/configs/ipv6/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/arm/tiva/dk-tm4c129x/configs/nsh/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/arm/tiva/tm4c1294-launchpad/configs/ipv6/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/arm/tiva/tm4c1294-launchpad/configs/nsh/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/renesas/rx65n/rx65n-grrose/configs/ipv6/defconfig:CONFIG_NETINIT_MONITOR=y
    boards/renesas/rx65n/rx65n-rsk2mb/configs/ipv6/defconfig:CONFIG_NETINIT_MONITOR=y

I am not sure that there is any problem.  But there might be odd behaviors.  The network monitor will do nothing when the network goes down.  But if the PHY reports reports link activity, it will generate an interrupt and the network more will take the network down and bring it back up.  So I think everything survives.

You really should be using the netinit monitor in your projects.  Otherwise, if the network goes down (say because a capable is unplugged), there is nothing that will re-establish the network if the monitor in not enabled.

**Comment by davids5** [comment]
@patacongo Thank you. Got it. I will reconfigure and retest. I will upstream the work next week.

**Comment by patacongo** [comment]
> Thank you. Got it. I will reconfigure and retest. I will upstream the work next week.

Probably no need.. My paranoia is not founded on anything of substance.

**Comment by davids5** [comment]
> Probably no need.. My paranoia is not founded on anything of substance.

I do not see it as paranoia, it is a good thing to ensure it is correct. Thank you for raising it.

To that end, when I dug into enabling NETINIT_MONITOR I found that the ARCH_PHY_INTERRUPT is not lit.  More digging led to the readme for the K66. (Thank you again Greg for documenting it)

I have copied the readme from the k66 here for some context and advise.

**As far as this PR: I think it is safe to bring it in**. It it an improvement in that the MAC will not get stuck as it was. But **long term this driver should support the NETINIT_MONITOR** 

```
  Network Monitor
  ---------------
  By default the network initialization thread will bring-up the network
  then exit, freeing all of the resources that it required.  This is a
  good behavior for systems with limited memory.

  If the CONFIG_NSH_NETINIT_MONITOR option is selected, however, then the
  network initialization thread will persist forever; it will monitor the
  network status.  In the event that the network goes down (for example, if
  a cable is removed), then the thread will monitor the link status and
  attempt to bring the network back up.  In this case the resources
  required for network initialization are never released.

  Pre-requisites:

    - CONFIG_NSH_NETINIT_THREAD as described above.

    - The K64F EMAC block does not support PHY interrupts.  The KSZ8081
      PHY interrupt line is brought to a jumper block and it should be
      possible to connect that some some interrupt port pin.  You would
      need to provide some custom logic in the Freedcom K64F
      configuration to set up that PHY interrupt.

    - In addtion to the PHY interrupt, the Network Monitor also requires the
      following setting:

        CONFIG_NETDEV_PHY_IOCTL. Enable PHY IOCTL commands in the Ethernet
        device driver. Special IOCTL commands must be provided by the Ethernet
        driver to support certain PHY operations that will be needed for link
        management. There operations are not complex and are implemented for
        the Atmel SAMA5 family.

        CONFIG_ARCH_PHY_INTERRUPT. This is not a user selectable option.
        Rather, it is set when you select a board that supports PHY
        interrupts.  For the K64F, like most other architectures, the PHY
        interrupt must be provided via some board-specific GPIO.  In any
        event, the board-specific logic must provide support for the PHY
        interrupt. To do this, the board logic must do two things: (1) It
        must provide the function arch_phy_irq() as described and prototyped
        in the nuttx/include/nuttx/arch.h, and (2) it must select
        CONFIG_ARCH_PHY_INTERRUPT in the board configuration file to
        advertise that it supports arch_phy_irq().

        One other thing: UDP support is required (CONFIG_NET_UDP).

  Given those prerequisites, the network monitor can be selected with these
  additional settings.

    System Type -> Kinetis Ethernet Configuration
      CONFIG_ARCH_PHY_INTERRUPT=y           : (auto-selected)
      CONFIG_NETDEV_PHY_IOCTL=y             : (auto-selected)

    Application Configuration -> NSH Library -> Networking Configuration
      CONFIG_NSH_NETINIT_THREAD             : Enable the network initialization thread
      CONFIG_NSH_NETINIT_MONITOR=y          : Enable the network monitor
      CONFIG_NSH_NETINIT_RETRYMSEC=2000     : Configure the network monitor as you like
      CONFIG_NSH_NETINIT_SIGNO=18
```

The board we are working, does have a GPIO connected to the phy. But it is not defined or used. I believe @PetervdPerk-NXP integrated the T1 phy into the eth driver. So I it would be good to get his input on this.

Since the T1 phy is incorporated in the eth driver, and it already uses pins from the board.h, for enable and INH. We should be able to hook phy interrupt in the it in the driver as well unless there is a compelling reason to have it in board logic.

**Pull request merged**
