### PR TITLE
nuttx/wireless: add wireless event member length helper 

### PR DESCRIPTION
**Pull request by anchao**
## Summary

nuttx/wireless: add wireless event member length helper 

## Impact

wifi scan result (struct iw_event) reassembly.

## Testing

verified on wireless driver module

```
static int wl_format_scan_results(struct wl_dev_s *priv, struct iwreq *iwr)
{
  rtw_scan_result_t *cache;
  struct iw_event *iwe;
  char *start, *stop;
  int i;

  start = iwr->u.data.pointer;
  stop = (char *)iwr->u.data.pointer + iwr->u.data.length;

  for (i = 0; i < priv->scan_count; i++)
    {
      cache = &priv->scan_data[i];

      iwe = (struct iw_event *)start;
      iwe->cmd = SIOCGIWAP;
      iwe->u.ap_addr.sa_family = ARPHRD_ETHER;
      memcpy(&iwe->u.ap_addr.sa_data, cache->BSSID.octet, IFHWADDRLEN);
      start = wl_iwe_add_event(start, stop, iwe, IW_EV_LEN(ap_addr));

      iwe = (struct iw_event *)start;
      iwe->cmd = SIOCGIWESSID;
      iwe->u.essid.flags = 0;
      iwe->u.essid.length = cache->SSID.len;
      iwe->u.essid.pointer = (FAR void *)sizeof(iwe->u.essid);
      memcpy(&iwe->u.essid + 1, cache->SSID.val, cache->SSID.len);
      start = wl_iwe_add_event(start, stop, iwe,
                                   IW_EV_LEN(essid) + ((cache->SSID.len + 3) & -4));

      iwe = (struct iw_event *)start;
      iwe->cmd = IWEVQUAL;
      iwe->u.qual.qual = 0;
      iwe->u.qual.level = cache->signal_strength;
      iwe->u.qual.noise = 0;
      iwe->u.qual.updated |= IW_QUAL_DBM;
      start = wl_iwe_add_event(start, stop, iwe, IW_EV_LEN(qual));

      iwe = (struct iw_event *)start;
      iwe->cmd = SIOCGIWFREQ;
      iwe->u.freq.e = 0;
      iwe->u.freq.m = cache->channel;
      start = wl_iwe_add_event(start, stop, iwe, IW_EV_LEN(freq));

      iwe = (struct iw_event *)start;
      iwe->cmd = SIOCGIWENCODE;
      iwe->u.data.flags = IW_ENCODE_DISABLED;
      iwe->u.data.length = 0;
      iwe->u.essid.pointer = NULL;
      start = wl_iwe_add_event(start, stop, iwe, IW_EV_LEN(data));
    }
  
  return start - (char *)iwr->u.data.pointer;
}

```

### CODE REVIEW

**Comment by v01d** [comment]
@anchao please edit all your PRs, follow the three section template and fill each section. It may feel like a chore but it is there to help reviewers and people creating the release notes for each PR.

**Comment by anchao** [comment]
> @anchao please edit all your PRs, follow the three section template and fill each section. It may feel like a chore but it is there to help reviewers and people creating the release notes for each PR. Try to be as descriptive as possible.

Got, I will update the template later

**Comment by xiaoxiang781216** [comment]
The real change look reasonable:
```
/*
 * A Wireless Event. Contains basically the same data as the ioctl...
 */

#define IW_EV_LEN(field) \
  (offsetof(struct iw_event, u) + sizeof(((union iwreq_data *)0)->field))
```
@v01d how about your thinking?

**Comment by v01d** [comment]
Sorry, I don't really have a comment, I have no idea about this part of NuttX

**Comment by xiaoxiang781216** [comment]
The change is simple to help people calculate the variant event size.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
