### PR TITLE
Rename LIB_ to LIBC_ for all libc Kconfig

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
follow other libc component naming convention. Need mrege with apache/incubator-nuttx-apps#821

## Impact
No real function change

## Testing
Pass CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@Ouss4  this patch can't pass CI because it depends on apache/incubator-nuttx-apps#821. We have to merge both together after you finish review and fix the potential issue after that.

**Comment by Ouss4** [comment]
@xiaoxiang781216 Although the change is simple, I think this would require some consensus from the community as it can break user code. I'd love if we can keep it open for some time to have more eyes.

**Comment by Ouss4** [comment]
I think only thing we can do is to document this in: https://cwiki.apache.org/confluence/display/NUTTX/NuttX+10.2

**Review by Ouss4 — APPROVED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
@Ouss4 the release note update here:
https://cwiki.apache.org/confluence/display/NUTTX/NuttX+10.2#changes-to-kconfig

**Comment by Ouss4** [comment]
@xiaoxiang781216 sorry I had to update this PR since https://github.com/apache/incubator-nuttx-apps/pull/821 is merged.  I didn't notice that this one had a conflict.

**Comment by xiaoxiang781216** [comment]
Ok, no problem. Thanks to fix the conflict.

**Pull request merged**
