### PR TITLE
Check return from nxsem_wait_initialize()

### PR DESCRIPTION
**Pull request by patacongo**
Resolution of Issue 619 will require multiple steps, this part of the first step in that resolution:  Every call to nxsem_wait_uninterruptible() must handle the return value from nxsem_wait_uninterruptible properly.  This commit is only for those files under drivers/audio, drivers/net, and drivers/lcd.

### CODE REVIEW

**Comment by patacongo** [comment]
NOTE to Reviewer:  This PR will fail the nxstyle check because it used definitions from include /fixedmath.h of the form b16HALF.  Either nxstyle or many, many files would have to change to eliminate that complaint.

**Comment by jerpelea** [comment]
unfortunately the patch contains nxstyle changes and the actual patch 
I think that it would be better if in the future we split the commits in 2 patches nxstyle changes and the actual patch

**Comment by Ouss4** [comment]
The build tests run independently of the status of the style check.
There are other build failures.

**Comment by patacongo** [comment]
> There are other build failures.

I think these have been addressed.

**Comment by patacongo** [comment]
I updated nxstyle with PR #672 so that it does not report the "Mixed case identifier" on the fixedmath.h definitions.  However, there are still severl mixed case identier reports on msgId which is a field in a structure defined by the audio system and in broader use outside of these changed files.

**Pull request merged**
