### PR TITLE
Add cxd56xx intstack for SMP

### PR DESCRIPTION
**Pull request by masayuki2009**
## Summary

- This PR introduces cxd56_cpuindex.h
- Also adds interrupt stack for SMP

## Impact

- Affects SMP only

## Testing

- Tested with spresense:wifi_smp with CONFIG_ARCH_INTERRUPTSTACK=2048

### CODE REVIEW

**Comment by masayuki2009** [comment]
@jerpelea

**Comment by Ouss4** [comment]
This is more of an added feature.
@masayuki2009 @btashton do you want to backport it?

**Comment by masayuki2009** [comment]
> This is more of an added feature.
> @masayuki2009 @btashton do you want to backport it?

Actually it's an added feature.
So I think we don't need to backport it.

**Comment by btashton** [comment]
Great. I removed the label.

**Comment by btashton** [comment]
@masayuki2009 I am backporting this so we can take some of the other SMP fixes you wanted backported cleanly.

**Pull request merged**
