### PR TITLE
configure.sh: support custom board build config with absolute path

### PR DESCRIPTION
**Pull request by liuguo09**
## Summary
Also add custom board build with absolute path support in addtion
to relative path.

## Testing
Verified with custom board with relative path and absolute path.

### CODE REVIEW

**Comment by patacongo** [comment]
shouldn't these changes also be made to tools/configure.c?

**Comment by liuguo09** [comment]
Ok, I'll update it later.

**Comment by Ouss4** [comment]
@liuguo09 did you make any progress on that?  Last time I checked `configure.c` was behind when it comes to custom boards.

**Comment by liuguo09** [comment]
> @liuguo09 did you make any progress on that? Last time I checked `configure.c` was behind when it comes to custom boards.

@Ouss4 I have made the configure.c change to support custom board. Please help review.  I only test ./tool/configure under Linux. Could you help to verify on windows if available?

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by Ouss4 — APPROVED** [review]
Thanks @liuguo09.  Tested with an out-of-tree custom board. Works well.

Sorry, I only tested on Linux, don't have a Windows machine.

**Pull request merged**
