### PR TITLE
board: Run ./tools/refresh.sh --silent all

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Follow up https://github.com/apache/incubator-nuttx-apps/pull/884

## Impact
Should same as before

## Testing
Pass CI

### CODE REVIEW

**Comment by Ouss4** [comment]
We had an old issue about disabling some of these commands for security reasons, is this to address the same issue?

**Comment by xiaoxiang781216** [comment]
> We had an old issue about disabling some of these commands for security reasons, is this to address the same issue?

No, this patch try to reduce the image size with default setting when DEFAULT_SMALL is enabled. mb/mh/mw always disable by default regardless DEFAULT_SMALL setting.

**Comment by xiaoxiang781216** [comment]
apache/incubator-nuttx-apps#884 disable some feature by default, so this PR remove these options from defconfig which make the binary size increase temporarily and make CI fail like this:
```
arm-none-eabi-ld: /github/workspace/sources/nuttx/nuttx section `.text' will not fit in region `flash'
```
Please ignore this false alarm.

**Review by Ouss4 — APPROVED** [review]

**Comment by Ouss4** [comment]
All right.  I already merged the apps, this needs to be merged too and we need to keep an eye on the pipeline run on master to make sure that everything is as expected.

**Pull request merged**
