### PR TITLE
[BACKPORT #2348]Fix pause handler for SMP

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
Back ports #2348

### CODE REVIEW

**Comment by Ouss4** [comment]
@masayuki2009 This had a little conflict in the TODO file, please check?

**Comment by btashton** [comment]
@Ouss4 I think if you reapply this patch it will be clean now that I merged the other one. This is why I have be stacking some of these related patches. In a single backport PR.

**Comment by Ouss4** [comment]
> @Ouss4 I think if you reapply this patch it will be clean now that I merged the other one. This is why I have be stacking some of these related patches. In a single backport PR.

Right, I'll drop the last commit, rebase and re-apply.

**Comment by masayuki2009** [comment]
LGTM

**Pull request merged**
