### PR TITLE
Fix nxstyle complants

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by patacongo** [comment]
What say you all... should we indent these kinds of changes by 4 spaces instead of the usual 2?

**Comment by yamt** [comment]
nxstyle told me this.
and i couldn't find any counter-explanations in NuttXCCodingStandard.html.
so i thought it should be.
do you disagree?

**Comment by patacongo** [comment]
> do you disagree?

No, I don't disagree at all.  This situation is this:

- It is and "undocumented" convention to indent all such compound statement by only two spaces.  It is like this in all files.

- This is not documented clearly in the coding standard.  That is probably an oversight.  This is not addressed at all in the coding standard except under  https://cwiki.apache.org/confluence/display/NUTTX/Coding+Standard#indentation where it says that the first level of indentation is 2-spaces.

- I don't think there is anything wrong with changing that convention.  It certainly simplified nxstyle.

I am not opposed so there no reason to argue with me.  I would just like to get the opinion and consenus of others.

**Comment by jerpelea** [comment]
I am for simplifying the convention and making it easy to understand
+1

**Comment by patacongo** [comment]
I think the change seems reasonable, but should be documented in the coding standard.

I see no reason to hold this up.  Having one concurrence is enough to assure that this is not just the personal opinion of KAMT or me.

**Pull request merged**
