### PR TITLE
Documentation: add ESP32 and DevKitC docs

### PR DESCRIPTION
**Pull request by v01d**
## Summary

This adds basic doc for ESP32 SoC and DevKitC board.

## Impact

Add documentation

## Testing

Built documentation

### CODE REVIEW

**Comment by v01d** [comment]
I'm not entirely familiar with ESP32 yet, but I think this documentation is long overdue. I hope this gets the ball rolling and we can document this better. There's more detailed information on the DevKitC board README which could be ported here, but I think it is best if it is done by someone who knows the platform better and is aware of current status of support (I'm not sure how up to date that README is).

**Comment by v01d** [comment]
BTW, I just tried to flash the wapi config to my devkitc and it does now work unless I disable the "save wifi params" option. Can someone explain if this is a bug or how is it supposed to be used? This probably needs to be mentioned in the docs

**Comment by acassis** [comment]
> BTW, I just tried to flash the wapi config to my devkitc and it does now work unless I disable the "save wifi params" option. Can someone explain if this is a bug or how is it supposed to be used? This probably needs to be mentioned in the docs.
> 
> I'm also interested in understanding the wapi tool (with some examples) and learn how to configure WPA2 since it is the most common security setting nowadays.

Did you have enable SPIFlash to have the file system mounted?

**Comment by v01d** [comment]
> > BTW, I just tried to flash the wapi config to my devkitc and it does now work unless I disable the "save wifi params" option. Can someone explain if this is a bug or how is it supposed to be used? This probably needs to be mentioned in the docs.
> > I'm also interested in understanding the wapi tool (with some examples) and learn how to configure WPA2 since it is the most common security setting nowadays.
> 
> Did you have enable SPIFlash to have the file system mounted?

I just loaded wapi config. This config includes `CONFIG_ESP32_SPIFLASH=y`.

**Comment by Ouss4** [comment]
> I just loaded wapi config. This config includes CONFIG_ESP32_SPIFLASH=y.

The wapi config has all what's necessary to run the example.  I did notice however some issues in devkitc in the past with saving the parameters (and thus SPI Flash).  Other boards however never had any problem. Could be that the partition is too large for a 2MB flash.

That said, thanks @v01d  for starting this!!!  I had this in the back of my head for sometime and I let it drag behind.
Regarding licensing, note that Espressif has already submitted an SGA and if there is anything else to be done for the images please let us know.

**Comment by v01d** [comment]
> > I just loaded wapi config. This config includes CONFIG_ESP32_SPIFLASH=y.
> 
> The wapi config has all what's necessary to run the example. I did notice however some issues in devkitc in the past with saving the parameters (and thus SPI Flash). Other boards however never had any problem. Could be that the partition is too large for a 2MB flash.

I have a V2 I believe. It is kind of generic so I'm not entirely sure. The module is WROOM-32 (chip ESP32-D0WDQ6). Flash is recognized as 4MB by esptool. I just re-enabled save params and this is the output I get:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6852
load:0x40078000,len:13276
load:0x40080400,len:3604
entry 0x40080670
I (26) boot: ESP-IDF v4.3-beta1-24-g0bbc721a6 2nd stage bootloader
I (27) boot: compile time 13:14:56
I (27) boot: chip revision: 1
I (31) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (38) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (47) boot.esp32: SPI Flash Size : 4MB
I (52) boot: Enabling RNG early entropy source...
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 factory          factory app      00 00 00010000 00100000
I (75) boot: End of partition table
I (80) boot_comm: chip revision: 1, min. application chip revision: 0
I (87) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=12d8ch ( 77196) map
I (122) esp_image: segment 1: paddr=00022db4 vaddr=3ffb8250 size=0191ch (  6428) load
I (125) esp_image: segment 2: paddr=000246d8 vaddr=40080000 size=00400h (  1024) load
I (129) esp_image: segment 3: paddr=00024ae0 vaddr=40080400 size=0a544h ( 42308) load
I (154) esp_image: segment 4: paddr=0002f02c vaddr=00000000 size=00fech (  4076) 
I (155) esp_image: segment 5: paddr=00030020 vaddr=400d0020 size=648c4h (411844) map
I (310) boot: Loaded app from partition at offset 0x10000
I (310) boot: Disabling RNG early entropy source...
�
NuttShell (NSH) NuttX-10.0.1
nsh> dmesg
[    0.000000] Idle Task: esp32_rng_initialize: Initializing RNG
[    0.030000] init: esp_nvs_get_blob: INFO: No file /mnt/esp/wifi/wifi.misc.log
[    0.090000] init: esp_nvs_set_blob: ERROR: Failed to set open /mnt/esp/wifi/wifi.misc.log
[    0.090000] init: W (86) wifi:[    0.090000] init: nvs_log_init, osi_nvs_set_blob fail, key=log ret=ffffffff
[    0.090000] init: 
[    0.090000] init: esp_wifi_init: ERROR: Failed to initialize WiFi error=-1
[    0.090000] init: esp_wifi_adapter_init: ERROR: Failed to initialize WiFi error=-1
[    0.090000] init: ERROR: Failed to initialize WiFi station
nsh> 
```

I see /mnt/esp/wifi is empty.

> That said, thanks @v01d for starting this!!! I had this in the back of my head for sometime and I let it drag behind.
> Regarding licensing, note that Espressif has already submitted an SGA and if there is anything else to be done for the images please let us know.

Images are from:
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/modules-and-boards.html#esp32-devkitc-v4
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/modules-and-boards-previous.html#esp32-core-board-v2-esp32-devkitc

Copyright is defined here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/COPYRIGHT.html
But there's no mention to documentation so I'm not sure if that means Apache applies or not.

**Comment by Ouss4** [comment]
@v01d are you testing with latest master?  I just retried with a devkitc (that I know I've seen this error before with) but I'm unable to reproduce it.  I even started with a fresh empty flash.

We'll ask regarding licensing.

**Comment by v01d** [comment]
> @v01d are you testing with latest master? I just retried with a devkitc (that I know I've seen this error before with) but I'm unable to reproduce it. I even started with a fresh empty flash.

Yes, I'm using master. I just erased flash and reflashed all binaries. It appears to work now after a reset.
I did flash bootloader/partition before this test today so those were latest ones. Maybe we should add erase_flash to the
bootloader/partition flashing? Otherwise, maybe I can add an instruction to docs to do this erase before flashing them.

> 
> We'll ask regarding licensing.

Great, thanks.

**Comment by Ouss4** [comment]
>  Maybe we should add erase_flash to the
bootloader/partition flashing? Otherwise, maybe I can add an instruction to docs to do this erase before flashing them.

I think an instruction on how to erase the flash if things aren't working is enough. 
The MTD partition we are using for Wifi data or any other data is part of the main flash.  If we erase the flash each time it will erase user data.  So if there is a permanent issue, I'd rather we fix it instead.

**Comment by v01d** [comment]
> > Maybe we should add erase_flash to the
> > bootloader/partition flashing? Otherwise, maybe I can add an instruction to docs to do this erase before flashing them.
> 
> I think an instruction on how to erase the flash if things aren't working is enough.
> The MTD partition we are using for Wifi data or any other data is part of the main flash. If we erase the flash each time it will erase user data. So if there is a permanent issue, I'd rather we fix it instead.

Ok, I just added a note to recommend a flash erase the first time. Hopefully this avoids any similar issue.

**Comment by Ouss4** [comment]
@v01d regarding licensing, the images are part of IDF's documentation and IDF itself is Apache v2, isn't that enough?

**Comment by v01d** [comment]
I think so. However since they are copyrighted to Espressif I think adding this to the NOTICE is needed. I just pushed this change.

**Comment by v01d** [comment]
BTW, I can continue working this PR to include more information on other use cases of WiFi (setting up WPA2 would be good to have in the docs at least). But I'm not really sure how that is done nor if the procedure actually depends on ESP32. If all commands are generic maybe this can be done in another part of the docs ("Wireless Subsystem" perhaps)

**Comment by Ouss4** [comment]
The procedure doesn't depend on the ESP32, it just WAPI commands.  But what command is supported does depend on the support of the hardware.  https://github.com/apache/incubator-nuttx/pull/3139 adds support for almost everything needed by WAPI for ESP32 (just a couple of IOCTL commands are missing).

**Comment by v01d** [comment]
> The procedure doesn't depend on the ESP32, it just WAPI commands. But what command is supported does depend on the support of the hardware. #3139 adds support for almost everything needed by WAPI for ESP32 (just a couple of IOCTL commands are missing).

Ok, we can document that elsewhere then. There's no documentation for using the wapi tool nor how to setup WPA2 AFAIK so it would be good to have it somewhere.

**Comment by v01d** [comment]
I rebased over #3144 which should fix CI here

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
