### PR TITLE
[BACKPORT 2022] arch/armv7-a: Fix the wrong idle stack setup for SMP case

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Backport #2022 

1.Get the stack pointer from sp instead of .Lstkinit's field
2.Make g_idle_topstack point to the end of the idle stack

### CODE REVIEW

**Review by xiaoxiang781216 — COMMENTED** [review]
LGTM.

**Comment by jerpelea** [comment]
LGTM

**Comment by btashton** [comment]
Can someone merge?  The doc failure is unrelated and I suspect due to me opening against the wrong branch originally.

**Comment by masayuki2009** [comment]
LGTM.

**Comment by masayuki2009** [comment]
> Can someone merge? The doc failure is unrelated and I suspect due to me opening against the wrong branch originally.

I've just merged.

**Pull request merged**
