### PR TITLE
cxd56: add initial Nuttx audio driver

### PR DESCRIPTION
**Pull request by jerpelea**
Adds an initial Nuttx audio driver supporting the Spresense CXD56.
Being a work in progress the driver has a number of limitations:
- Audio playback only, no recording yet.
- Only 16 bit stereo playback is supported.
- In practice only 48kHz playback is supported due to missing SRC.
- Configure driver in "Device Drivers --> Audio Device Support".

### CODE REVIEW

**Comment by jerpelea** [comment]
The nxstyle errors come from the audio API and can be ignored

**Comment by jerpelea** [comment]
@acassis @gregory-nutt if there are no concerns please merge

**Comment by patacongo** [comment]
> 
> 
> @acassis @gregory-nutt if there are no concerns please merge

There are still several nxstyle issues... even ignoring Mixed case identifiers.

**Comment by jerpelea** [comment]
@patacongo Ill fix the SDK driver and push in the same commit

**Comment by jerpelea** [comment]
@patacongo done

**Comment by patacongo** [comment]
There is a problem with arm-08, but it is not your problem.  I restarted the check.

**Pull request merged**
