### PR TITLE
WIP: Support for LiteX running on an iCEBreaker FPGA board

### PR DESCRIPTION
**Pull request by btashton**
This is a work in progress DO-NOT-MERGE. 

NSH comes up, but the timers are not yet properly wired in. 

There is also an issue because we are hard coding the base registers for LiteX in the arch rather than allowing for the board to provide some of this information.

The FPGA bitstream can be generated as in the readme included in this PR.
https://github.com/icebreaker-fpga/icebreaker-litex-examples

### CODE REVIEW

**Comment by v01d** [comment]
Regarding how to deal with changing registers, I think that you will always have to deal with generating something. Maybe for the case of a softcore, the arch headers where register addresses are defined should be generated and not hand-written.
In terms of solving this in a more standardized manner, quite a few times I thought about generating these macro definitions from SVD files, which is an XML based description of all peripherals of a chips, with their addresses and descriptions. Bitmasks and so on probably need to be dealt separately, but that is definitely much better than handwriting everything, specially when you have to get the data from the datasheet in PDF form.

A large collection of these files is this: https://github.com/posborne/cmsis-svd/ (see data directory). Maybe you can take the opportunity to write a SVD to header generator following NuttX expected format.

**Comment by v01d** [comment]
Hey @btashton 
I'm wondering if you explored the generation of peripheral addresses from SVD if you're still interested in using devicetrees for this. I ask because I kept working on devicetree parsing and code generation for NuttX and have made considerable progress (I'm able to initialize I2C bus, devices, handle autoleds and buttons) and I could now incorporate the generation of peripheral base addresses easily. While my aim is to generate code for board-logic and this would be in fact arch-level code it would not be officially my goal, but it may be of use for you.

You can check out the tool here: https://gitlab.com/nuttx_projects/dtgen
It may be difficult to understand how it works right now but if you look at the YAML bindings and the mockup you may get an idea.

**Comment by btashton** [comment]
@v01d what I'm thinking about doing here is exposing the base address as config variables since perif themselves are fairly stable, it is just where in the memory they are located changes (as well as how many).  Interested in seeing where you changes go.

**Comment by v01d** [comment]
I just put up my demo project here: https://gitlab.com/nuttx_projects/nuttx_devicetree/demo
The actual nuttx fork is here: https://gitlab.com/nuttx_projects/nuttx_devicetree/nuttx/
You can see some added logic and the generated header for the board.dts file here: https://gitlab.com/nuttx_projects/nuttx_devicetree/nuttx/-/tree/devicetree/boards/arm/stm32/common/dts

**Comment by btashton** [comment]
Need to revisit this now that I know more how the csr works with RISCV.  The machine timer should work as before with systick.

**Comment by btashton** [comment]
I'm closing this out in favour of cleaning up the whole LiteX port.  It needs some work to keep back in line with the current tooling.  LiteX with the VexRiscv can now be easily built to support a quad-core operation, this could be really useful for hammering on the SMP functionality.

**Pull request closed without merging**
