### PR TITLE
power/battery: Move the enumurate to the common place

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
so the userspace program can handle the different battery driver equally

## Impact
Same as before

### CODE REVIEW

**Comment by gustavonihei** [comment]
I'm okay with the changes, but I believe it is important to get the feedback from @masayuki2009, since it may affect to some extent applications targeting the Spresense platform.

**Comment by xiaoxiang781216** [comment]
Ok, add @masayuki2009 as reviewer too.

**Comment by masayuki2009** [comment]
>Ok, add @masayuki2009 as reviewer too. It's safe If user just use enum value, but not type(e.g. battery_monitor_status_e).

I think we need to modify ./sdk/apps/examples/charger/charger_main.c in Spresense SDK.

@SPRESENSE 
Do you have any comments on this PR?

**Comment by SPRESENSE** [comment]
> @SPRESENSE
> Do you have any comments on this PR?

Thanks for mentioning me.
There is no problem if you update `apps/examples/charger/charger_main.c` at the same time.

**Comment by xiaoxiang781216** [comment]
Fix here https://github.com/apache/incubator-nuttx-apps/pull/859

**Pull request merged**
