### PR TITLE
boards/arm/samv7/common: add HSMCI0 boot mount configuration option

### PR DESCRIPTION
**Pull request by pkarashchenko**
## Summary
Add HSMCI0 boot mount configuration option

## Impact
SAMv7 based boards

## Testing
Pass CI

### CODE REVIEW

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@pkarashchenko I noticed you are merging your own PR, we have an agreement to we cannot merge our own PR, although we can merge PR from colleague eve from the same company.

**Comment by xiaoxiang781216** [comment]
@acassis I think @pkarashchenko merge it because you have approve the change.

**Comment by pkarashchenko** [comment]
@acassis sorry for that. I will follow the agreement. I merged changes because you approved it and CI was complete and change is relatively trivial

**Comment by pkarashchenko** [comment]
I saw cases like this https://github.com/apache/incubator-nuttx/pull/5284, so was thinking that it is ok.

**Comment by acassis** [comment]
Don't worry @pkarashchenko I imagined you didn't know about it. Yes, sometimes we it by mistake, for example when you are doing the PR from github interface and think you are click on submit the PR to master project, but you are in the next step to merge it on master.

**Comment by davids5** [comment]
@acassis - Two thoughts here:
1 ) Given the geographical and time differences should we consider that once a review has been done the author can merge it?
2) If only one company does a review, that can lead to undo influence as noted as the ["The Enemies"] (https://github.com/apache/incubator-nuttx/blob/master/INVIOLABLES.md)
Focus on the values of the organization, not the values of the Open Source project. Need to support both.
 I would suggest we change that.

**Comment by acassis** [comment]
@davids5 I think it could be voted since it was defined by others. If you search here in the github history you will find the commit from me that I unintentionally merged and others started to complain about it.

**Pull request merged**
