### PR TITLE
arch: arm: cxd56xx: nxstyle fixes

### PR DESCRIPTION
**Pull request by jerpelea**
nxstyle fixes for cxd56xx

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@jerpelea there is still some "Long line" warning.

**Comment by jerpelea** [comment]
@xiaoxiang781216 I can not see them on a local check
tools/nxstyle arch/arm/src/cxd56xx/cxd56_powermgr.c
arch/arm/src/cxd56xx/cxd56_powermgr.c:988:6: error: Mixed case identifier found
arch/arm/src/cxd56xx/cxd56_powermgr.c:989:6: error: Mixed case identifier found
arch/arm/src/cxd56xx/cxd56_powermgr.c:994:6: error: Mixed case identifier found
arch/arm/src/cxd56xx/cxd56_powermgr.c:997:6: error: Mixed case identifier found
arch/arm/src/cxd56xx/cxd56_powermgr.c:1015:7: error: Mixed case identifier found
arch/arm/src/cxd56xx/cxd56_powermgr.c:1016:2: error: Mixed case identifier found

**Comment by jerpelea** [comment]
tools/nxstyle arch/arm/src/cxd56xx/cxd56_powermgr.h
nothing returned

**Comment by patacongo** [comment]
>  I can not see them on a local check

Because you probably do not have the latest nxstyle.  I commited a change yesterday for a violation that was not being detected by nxstyle.  I re-ran a large from of tests and found 49, new, valid complaints ( #743 and #744)

**Comment by jerpelea** [comment]
@patacongo I was suspecting the same and the error popped after a fetch 
Thanks for pointing it 

I fixed the new warning

**Comment by patacongo** [comment]
> I fixed the new warning

Looks good.  Now only the expected "Mixed case identifier" errors.  I will merge the PR when all of the checks complete.

**Comment by jerpelea** [comment]
@patacongo thanks

**Pull request merged**
