### PR TITLE
libs: Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses  to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Comment by jerpelea** [comment]
@xiaoxiang781216 i am out of ideas howto fix the remaining nxstyle errors

**Review by xiaoxiang781216 — COMMENTED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I am out of ideas howto fix the remaining nxstyle errors

The error is also strange for me:(, anyway, let's merge the copyright fix first. We can address the style issue later.

**Comment by xiaoxiang781216** [comment]
@jerpelea some error happen here:
https://github.com/apache/incubator-nuttx/pull/3277/checks?check_run_id=2252301357

**Comment by Ouss4** [comment]
> > @xiaoxiang781216 I am out of ideas howto fix the remaining nxstyle errors
> 
> The error is also strange for me:(, anyway, let's merge the copyright fix first. We can address the style issue later.

I think it's just nxstyle that's confused with the scientific notation.

**Comment by jerpelea** [comment]
please ignore the error

**Pull request merged**
