### PR TITLE
arch: arm: stmxxx: Author Gregory Nutt: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Gregory Nutt has submitted the SGA and we can migrate the licenses to Apache.

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Comment by jerpelea** [comment]
@xiaoxiang781216 please ignore warning: #include outside of 'Included Files' section

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by jerpelea** [comment]
@xiaoxiang781216 it looks like CI finished. Can we merge it ?

**Comment by xiaoxiang781216** [comment]
The check just finished, let's merge it.

**Comment by jerpelea** [comment]
thanks

**Pull request merged**
