### PR TITLE
tools/ci: Rename sim0x.dat to sim-0x.dat to align with arm-xx.dat

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
To avoid the build break sim0x.dat will remove in the upcoming patch

## Impact
CI for sim

## Testing
Pass CI

### CODE REVIEW

**Review by Ouss4 — APPROVED** [review]
LGTM. Gonna update apps as well?

**Comment by xiaoxiang781216** [comment]
@Ouss4 I am waiting for this patch merging first, otherwise the patch in apps will always fail.

**Comment by btashton** [comment]
@xiaoxiang781216 if you can put the app one up shortly I'll merge them directly to keep the breakage minimal.

**Comment by btashton** [comment]
Ah I see you just added them. Understood I'll merge this now.

**Comment by Ouss4** [comment]
Sorry for the delay @xiaoxiang781216.  Thanks for the merge @btashton.

**Pull request merged**
