### PR TITLE
documentation CI: add step to check valid external links using "linkcheck" sphinx builder

### PR DESCRIPTION
**Pull request by v01d**
## Summary

Add an extra step to the documentation workflow which goes through every external link and tries to access it to check if it is still valid and fail if so.

## Impact

CI

## Testing

Tested locally, will be tested on CI for this PR

### CODE REVIEW

**Comment by v01d** [comment]
Closing since I cannot get the link check output to be visible without failing the build (which is risky and could block unrelated PRs).

**Comment by btashton** [comment]
@v01d You can do this by enabling annotations.  See how I enabled this for nxstyle:
https://github.com/apache/incubator-nuttx/blob/7b965a25d853f72bfc2d6d46fe35a5bab39c653d/.github/workflows/check.yml#L34
https://github.com/apache/incubator-nuttx/blob/7b965a25d853f72bfc2d6d46fe35a5bab39c653d/.github/nxstyle.json#L13

So you would still want to do the `|| true` like you had earlier, but now it would add warning annotations in the build.

**Comment by v01d** [comment]
That was my intention but I got lost in GH documentation on how to use paired with the sphinx action. I don't think it is a priority anyway. I added a "fix broken links using `make linkcheck`" task on #1638 though.

**Comment by btashton** [comment]
Sounds good.  At least the info is here for future reference.  And yes, the matcher docs are basically non-existent, turns out they are based around the same code vscode uses, but you only find that via tickets opened against the github runner.

**Pull request closed without merging**
