### PR TITLE
stm32/stm32h7: fix the configuration of PWM outputs when subsequent channels are not enabled 

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
The previous implementation didn't work properly when subsequent channels were not enabled (eg. CH1 and CH2 disabled, CH3 enabled).

## Impact
stm32 and stm32h7 only. 

## Testing
nucleo-f103rb/pwm

### CODE REVIEW

**Comment by diegoherranz** [comment]
I've tested this on an STM32F103 and after dozens of attempts, I can't reproduce the issue I was seeing on https://github.com/apache/incubator-nuttx/issues/2446.

Just one question. Where did the randomness come from? I can't understand that.

Many thanks for the quick fix!

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by raiden00pl** [comment]
@diegoherranz The PWM output configuration was read from the wrong memory address (in my case it was <g_usart2txbuffer+12>). The fact that most of the time it worked properly was just a coincidence. We have been fooled by randomness :)
Thanks for finding the issue.

**Comment by diegoherranz** [comment]
Thanks for the explanation (and the fix).

**Pull request merged**
