### PR TITLE
arch: serial: fix all TCGETS retrieving zero baud rate

### PR DESCRIPTION
**Pull request by juniskane**
cfsetispeed() now stores baud rate to c_cflag member of
struct termios, so it must not be overridden later on.

### CODE REVIEW

**Comment by juniskane** [comment]
*sigh* I really don't have time to pacify nxstyle for all these serial.c files. The guy from Xiaomi who broke this in 03c795 should really do the cleanup.... :)

**Comment by davids5** [comment]
See https://github.com/apache/incubator-nuttx/pull/1767#issuecomment-712434684

**Comment by xiaoxiang781216** [comment]
> _sigh_ I really don't have time to pacify nxstyle for all these serial.c files. The guy from Xiaomi who broke this in 03c795 should really do the cleanup.... :)

I will fix the rest warning.

**Comment by btashton** [comment]
@juniskane @xiaoxiang781216 I just pushed the rather large nxstyle fixes to this PR.

**Comment by xiaoxiang781216** [comment]
Thanks @btashton!

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by davids5** [comment]
@xiaoxiang781216 @btashton - thank you for fixing this. 

Unfortunately I do not think we are done, it is not enough,  There is a bigger problem with the #1767 change. With that change NuttX can not support any baud rate. This will break many real world radio protocols! #1767 needs to be changed to allow any board rate again.

**Pull request merged**
