### PR TITLE
Add BeagleV Starlight JH7100 and JH7110

### PR DESCRIPTION
**Pull request by robertlipe**
Largely borrowed from C906.
The IRQ code isn't quite right and needs further work.
The port in general needs additional work for networking, storage, VM, and more, but this gets it in motion.

## Summary
BeagleV Starlight is a board that comes in two flavors:
The developer pre-release JH7100 has two U74 cores.
The (eventual) released board will have a JH7110 with four U74s plus GPU and PCI.

## Impact
Other ports aren't impacted. I configured and compiled C906 and K210 to confirm.

## Testing
Tested on pre-release hardware and on Renode.
Boots to an nsh prompt. Interacts fine. Commands run.

### CODE REVIEW

**Comment by acassis** [comment]
Seams like up_irq_save() was defined incorrectly:
Error: /github/workspace/sources/nuttx/include/arch/irq.h:80:26: error: static declaration of 'up_irq_save' follows non-static declaration

**Comment by xiaoxiang781216** [comment]
@robertlipe there is conflict need to resolve first.

**Comment by robertlipe** [comment]
Another scattergun approach with this header. Remove one of the declaration in irq.h. Even though the line numbers are different and the filename is wonly (perhaps one get is via symlink and the other doesn't) I'm running out of ideas and have spent DAYS running localversions of tools/ci/testbuild.sh riscv* without issue. (Well, without issues that are mine.)

**Comment by xiaoxiang781216** [comment]
There are many patch get merged everyday, it's better to fetch the latest code from mainline and then rebase your code on top of it before you update the PR.

**Comment by robertlipe** [comment]
Re:
https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770

I'm still super suspicious of the build environment having a bad ccache or
missed reconfiguration step.

https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770

Configuration/Tool: esp32c3-devkit/pm,CONFIG_RV32IM_TOOLCHAIN_GNU_RVGL
162
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:162>------------------------------------------------------------------------------------

163
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:163>
Cleaning...
164
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:164>
Configuring...
165
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:165>
Disabling CONFIG_RV64GC_TOOLCHAIN_GNU_RVGL
166
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:166>
Enabling CONFIG_RV32IM_TOOLCHAIN_GNU_RVGL
167
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:167>
Building NuttX...
168
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:168>gcc:
error: unrecognized command line option '-msmall-data-limit=0'
169
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:169>
ERROR: gcc failed: 1
170
<https://github.com/apache/incubator-nuttx/pull/3965/checks?check_run_id=2923755770#step:7:170>
command: gcc -MT ./nsh_init.github.workspace.sources.apps.nshlib.o -M
'-fno-builtin' '-ffunction-sections' '-fdata-sections'
'-fstrict-volatile-bitfields' '-msmall-data-limit=0' '-Wall'
'-Wstrict-prototypes' '-Wshadow' '-Wundef' '-g' '-Os'
'-fno-strict-aliasing' '-fno-strength-reduce' '-fomit-frame-pointer'
'-isystem' '/github/workspace/sources/nuttx/include' '-D__NuttX__'
'-D__KERNEL__' '-Wno-cpp' '-Werror' '-pipe' '-I'
'/github/workspace/sources/apps/include' ./nsh_init.c







This code isn't near where I've been. I certainly didn't add
-msmall-data-limit to the esp32 port. In fact, I can run
tools/configure.sh -e esp32c3-devkit/autopm
and get a build that includes
riscv64-unknown-elf-gcc -c -fno-builtin -ffunction-sections -fdata-sections
-fstrict-volatile-bitfields -msmall-data-limit=0 -Wall -Wstrict-prototypes
-Wshadow -Wundef -Os -fno-strict-aliasing -fno-strength-reduce
-fomit-frame-pointer -march=rv32imc -mabi=ilp32 -mdiv -isystem ...
and it compiles to completion. That's using the SiFive GCC, which is
appropriate for the SiFive Core in ESP32-C3.

riscv64-unknown-elf-gcc --version
riscv64-unknown-elf-gcc (SiFive GCC 8.3.0-2019.08.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.

That flag is also known to:
riscv64-unknown-elf-gcc (GCC) 10.2.0

I really think that whatever "gcc" is on this build system, it's an ancient
GCC that isn't suitable for RISC-V development. I can find that flag back
to GCC 7.5 and doing RISC-V development with anything older than that is
just unwise. It's clearly a flag that ESP32-C3 wants:
boards/risc-v/esp32c3/esp32c3-devkit/scripts/Make.defs
46:ARCHCFLAGS = -fno-builtin -ffunction-sections -fdata-sections
-fstrict-volatile-bitfields -msmall-data-limit=0


This reeks of a bad ccache configuration. Can you please either tell me
what "gcc" is in this invocation as I can successfully compile
esp32c3-devkit/autopm with
riscv64-unknown-elf-gcc (SiFive GCC 8.3.0-2019.08.0) 8.3.0
from the SiFive kit. Builds with the official RISC-V chain fail in yet
another way,  but it's probably best to use the SiFive chain anyway.

What is 'gcc' above and how can I reproduce this?

The amount of time I've spent chasing ghosts in this project has dwarfed
the amount of time I've spent working on real contributions...

**Comment by btashton** [comment]
Your PR modified the config for that build, perhaps this was not intentional?

https://github.com/apache/incubator-nuttx/blob/eabc966fdc96c45c709fe72e309a797257306265/boards/risc-v/esp32c3/esp32c3-devkit/configs/pm/defconfig

**Comment by xiaoxiang781216** [comment]
> Your PR modified the config for that build, perhaps this was not intentional?
> 
> [73df060#diff-64378e6952af33260f3280883c578b94dd929fbf6b690c3c23b3e1f41f21fa69](https://github.com/apache/incubator-nuttx/commit/73df0605fb0128714d13a1e42d420727327882c5#diff-64378e6952af33260f3280883c578b94dd929fbf6b690c3c23b3e1f41f21fa69)
> 
> https://github.com/apache/incubator-nuttx/blob/eabc966fdc96c45c709fe72e309a797257306265/boards/risc-v/esp32c3/esp32c3-devkit/configs/pm/defconfig

Remove the esp32c change from the PR, let's see what happen next.
BTW, if the PR pass CI, @robertlipe please squach your change in the reasonable set.

**Comment by robertlipe** [comment]
Again, I really think these errors are bogus.
q
The script calling check patch is using the wrong identifier. THIS PR succeeds fine.
$ tools/checkpatch.sh -g 4069a8e1c3dd4f74dd1baba6581c61f68fa93891
$

ble_adapter isn't in this patch. 
I see it in the code that's already on master
extern bool API_vhci_host_check_send_available
I'm not going to argue about the ESP32 code (heck, I'm exhausted arguing about MY code) but that capitalization is accepted industry norm.
I request a waiver for code I didn't change and that's already been accepted anyway.

nuttx/fs/nfs/nfs_util.c:70:39: error: C++ style comment
This is why you shouldn't implement your own preprocessor casually; they're hard to get right. That line of that file does have a slash slash, but it's not a C++ comment and respelling it like "/./" or soemething to get around goofiness in a tool that's enforcing a rule that hasn't mattered in 30 years would be silly, plus it would actually materially devalue the comment as the code is looking for two literal slashes - that still aren't a C++ comment.
          /* This logic just supports "//" sequences in the path name */
But again, this line isn't in this pull request and has already been there for two years:
be3dd0bac61 (Gregory Nutt     2019-03-01 15:00:00 -0600  70)           /* This logic just supports "//" sequences in the path name */

I request an exemption on this, too, since I didn't change it, it's been there for years, the tool that's checking it is broken, there are many, many occurrences of this already in there tree that haven't been causing problems, and the rule it's enforcing hasn't mattered since the mid/late 1980's

This really just looks like the RISC-V build runner has a corrupt ccache or bad git checkout or something because most of the times it has squawked in this exercise has been about code not even in this pull request and the ghosts I've been made to chase have been moving.

Can someone **please** get to the bottom of all this?

P.S. Assuming you have a fast machine that's the build runner, you can make it faster. cibuild.sh is running rapid make distclean/cnofigure/make cycles. Most of the build are going to thus be cold; EVERYTHING gets recompiled, however, there's one single-process, single-threaded mkdkeps invocation that's slowly computing a dependency graph, even though you're going to have to recompile anything anyway. Just NOT calling mkdeps in this case would be faster.

**Comment by btashton** [comment]
> Again, I really think these errors are bogus.
> q
> The script calling check patch is using the wrong identifier. THIS PR succeeds fine.
> $ tools/checkpatch.sh -g 4069a8e1c3dd4f74dd1baba6581c61f68fa93891
> $
> 
> ble_adapter isn't in this patch. 
> I see it in the code that's already on master
> extern bool API_vhci_host_check_send_available
> I'm not going to argue about the ESP32 code (heck, I'm exhausted arguing about MY code) but that capitalization is accepted industry norm.
> I request a waiver for code I didn't change and that's already been accepted anyway.

If you look at the logs you will see the list of commits being checked. You have merged back in master a couple times so the list of commits include other changes that are not yours including some for the esp code that was flagged by the check and waved.  You will need to rebase and squash to a small set of commits anyway, when you do that this will be resolved. 


The compile errors that exist are for the three configs that you added that need to be refreshed to the minimal form see 
tools/refresh.sh

**Comment by xiaoxiang781216** [comment]
1. First don't merge your patch with the mainline
2. Please run the follow command once:
```
git remote add apache git@github.com:apache/incubator-nuttx.git
```
3. Please do the follow step before you update PR:
```
git fetch apache
git checkout yourbranch
git rebase apache/master
./tools/refresh.sh -silent yourboard:yourconfig
./tools/checkpatch.sh -g HEAD~...HEAD
git push -f origin yourbranch
```

**Comment by acassis** [comment]
@robertlipe it is not about standard (because there are many "Standards"), it is about consistency. People normally don't go to the Linux kernel mailing list and complaint about their coding style that is similar to our.

**Comment by xiaoxiang781216** [comment]
> P.S. Assuming you have a fast machine that's the build runner, you can make it faster. cibuild.sh is running rapid make distclean/cnofigure/make cycles. Most of the build are going to thus be cold; EVERYTHING gets recompiled, however, there's one single-process, single-threaded mkdkeps invocation that's slowly computing a dependency graph, even though you're going to have to recompile anything anyway. Just NOT calling mkdeps in this case would be faster.

Yes, this is the flaw in the build system, actaully there are other known issue with the current Makefile based build system. @protobits try to switch to CMake build system which is much fast than the current one: https://github.com/apache/incubator-nuttx/pull/3965
You can give your feedback and join the dissusion here:
https://lists.apache.org/list.html?dev@nuttx.apache.org:lte=1M:Migrate%20the%20build%20system%20to%20CMake

**Comment by robertlipe** [comment]
This iteration of BeagleV hardware is canceled.  "The BeagleV™-Starlight prototype will not be going into mass production"  It's not clear if the underlying chip, the JH-7100 or its successor, the JH-7110, is going to to into production or not, but it is clear that this patch kit for that combination of board and chip is stillborn as the hardware will never be mass produced.

Sources:
https://beaglev.org/
https://forum.beagleboard.org/t/the-future-of-beaglev-community/30463/4

**Pull request closed without merging**
