### PR TITLE
sched: fix bug in the function nxsched_resume_scheduler

### PR DESCRIPTION
**Pull request by zhaoxiu-zeng**
Don't reset the task's timeslice if no task switch.

Change-Id: Ie59c442f67cbd9337db8dc34ad1714ae8b404bd8

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Please remove Change-Id and the merge commit, @zhaoxiu-zeng .

**Comment by xiaoxiang781216** [comment]
@zhaoxiu-zeng you don't create a new PR for each update, git push -f ... can update the PR directly.

**Comment by zhaoxiu-zeng** [comment]
Got it, thanks! I've closed this and created a new one.

**Comment by xiaoxiang781216** [comment]
Sure, no problem. Let's continue on the new PR this time.

**Pull request closed without merging**
