### PR TITLE
documentation: Add release notes for 11.0.0 release

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
This is a local copy taken from the confluence notes
https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.0.0

## Impact
RELEASE

## Testing
NONE

### CODE REVIEW

**Comment by hartmannathan** [comment]
If there are things to add (e.g., compatibility concerns) should we add them here or in confluence?

**Comment by hartmannathan** [comment]
Specifically, these need changes in out-of-tree boards:

https://github.com/apache/incubator-nuttx/pull/6276 - Remove `-nostartfiles` and `-nodefaultlibs` from individual board `Make.defs`.

https://github.com/apache/incubator-nuttx/pull/6256 - Remove `ARCHWARNINGS = -Wall -Wstrict-prototypes -Wshadow -Wundef` and `ARCHWARNINGSXX = -Wall -Wshadow -Wundef` and then remove `ARCHWARNINGS` and `ARCHWARNINGSXX` from `CFLAGS` and `CXXFLAGS`.

https://github.com/apache/incubator-nuttx/pull/5897 - Remove `-fno-exceptions -fcheck-new` from `ARCHCFLAGS` and `ARCHCXXFLAGS` and change `ARCHCFLAGS =` to `ARCHCFLAGS +=` and `ARCHCXXFLAGS =` to `ARCHCXXFLAGS +=`. C++ exceptions are now managed centrally by Kconfig options `CONFIG_CXX_EXCEPTION` and `CONFIG_CXX_RTTI`.

https://github.com/apache/incubator-nuttx/pull/6144 - Remove from each board:
```
ifeq ($(CONFIG_DEBUG_SYMBOLS),y)
  ARCHOPTIMIZATION = -g
endif
```
and
```
ifeq ($(CONFIG_DEBUG_SYMBOLS),y)
  LDFLAGS += -g
endif
```
as these are now managed centrally by Kconfig option `CONFIG_DEBUG_SYMBOLS`.

https://github.com/apache/incubator-nuttx/pull/6155 - Remove from each board:
```
ifneq ($(CONFIG_DEBUG_NOOPT),y)
  ARCHOPTIMIZATION += $(MAXOPTIMIZATION) -fno-strict-aliasing
endif
```
as these are now managed centrally by Kconfig options `CONFIG_DEBUG_OPTLEVEL` and `CONFIG_DEBUG_FULLOPT`.

https://github.com/apache/incubator-nuttx/pull/5496 - Replace:
```
ifeq ($(CONFIG_CYGWIN_WINTOOL),y)
  ARCHSCRIPT = -T "${shell cygpath -w $(BOARD_DIR)$(DELIM)scripts$(DELIM)$(LDSCRIPT)}"
else
  ARCHSCRIPT = -T$(BOARD_DIR)$(DELIM)scripts$(DELIM)$(LDSCRIPT)
endif
```
with:
```
 ARCHSCRIPT += $(BOARD_DIR)$(DELIM)scripts$(DELIM)$(LDSCRIPT)
```

I think these are all of the breaking changes that require an explanation in the release notes. I'll make sure each PR is tagged with breaking change and build system.

I can add the explanations to the release notes: Are we still using Confluence for that?

**Comment by hartmannathan** [comment]
BTW #6256 is not mentioned in https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.0.0 at all. Is it missing?

**Comment by jerpelea** [comment]
> BTW #6256 is not mentioned in https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.0.0 at all. Is it missing?

it was removed since there is no impact

**Comment by jerpelea** [comment]
> #6276 - Remove `-nostartfiles` and `-nodefaultlibs` from individual board `Make.defs`.
> 
> #6256 - Remove `ARCHWARNINGS = -Wall -Wstrict-prototypes -Wshadow -Wundef` and `ARCHWARNINGSXX = -Wall -Wshadow -Wundef` and then remove `ARCHWARNINGS` and `ARCHWARNINGSXX` from `CFLAGS` and `CXXFLAGS`.
> 
> #5897 - Remove `-fno-exceptions -fcheck-new` from `ARCHCFLAGS` and `ARCHCXXFLAGS` and change `ARCHCFLAGS =` to `ARCHCFLAGS +=` and `ARCHCXXFLAGS =` to `ARCHCXXFLAGS +=`. C++ exceptions are now managed centrally by Kconfig options `CONFIG_CXX_EXCEPTION` and `CONFIG_CXX_RTTI`.
> 
> #6144 - Remove from each board:
> 
> ```
> ifeq ($(CONFIG_DEBUG_SYMBOLS),y)
>   ARCHOPTIMIZATION = -g
> endif
> ```
> 
> and
> 
> ```
> ifeq ($(CONFIG_DEBUG_SYMBOLS),y)
>   LDFLAGS += -g
> endif
> ```
> 
> as these are now managed centrally by Kconfig option `CONFIG_DEBUG_SYMBOLS`.
> 
> #6155 - Remove from each board:
> 
> ```
> ifneq ($(CONFIG_DEBUG_NOOPT),y)
>   ARCHOPTIMIZATION += $(MAXOPTIMIZATION) -fno-strict-aliasing
> endif
> ```
> 
> as these are now managed centrally by Kconfig options `CONFIG_DEBUG_OPTLEVEL` and `CONFIG_DEBUG_FULLOPT`.

done. Thanks

**Comment by jerpelea** [comment]
> If there are things to add (e.g., compatibility concerns) should we add them here or in confluence?

I think that if there is more they should be added in both places

**Comment by xiaoxiang781216** [comment]
@jerpelea there is no file in the PR, is it right?

**Comment by jerpelea** [comment]
@xiaoxiang781216 
I closed this PR and opened a new one 
https://github.com/apache/incubator-nuttx/pull/7006

**Pull request closed without merging**
