### PR TITLE
usbhost: adds a driver for the FTDI FT232R USB to serial converter

### PR DESCRIPTION
**Pull request by NicholasChin**
## Summary
I have created a usbhost driver for the FT232R. The CDC/ACM driver was used as a basis.

## Testing
I have test built using the current head 48c88f2 and the imxrt1020-evk:nsh config with all the Kconfig options I added to support the driver. It builds without warnings from my additions. I have ran NXstyle and addressed the issues from that, but I believe it's giving me a lot of false positives.

### CODE REVIEW

**Comment by patacongo** [comment]
There are a few style problems that need to be fixed before we can do the merge.  There is one in your new files?

drivers/usbhost/usbhost_ft232r.c:831:26: error: Multiple data definitions

But lots in the existing file:  include/nuttx/usb/usbhost.h.  Most of those are probably not yours, but we ask people to clean up style-related problems in an all modified files.  Think of it as your way to contribute to the quality of the OS ;)

**Comment by patacongo** [comment]
I can also help you with the usbhost.h files if you remembered to keep the box check to allow maintainers access to your branch.

**Comment by NicholasChin** [comment]
Oh must have missed that one. The box to allows maintainers access is checked, so you should be able to edit usbhost.c, Greg. However like I was trying to articulate in my initial comment, it seems like most of the nxstyle errors in usbhost.c are false positives.

**Comment by patacongo** [comment]
I am looking at usbhost.h now.  I will try to push something to your branch.

**Comment by NicholasChin** [comment]
I'm at a loss for why checkpatch is reporting:
`drivers/usbhost/usbhost_ft232r.c:831:26: error: Multiple data definitions`

The line it is complaining about is a simple array instantiation and the variable name is unique:
`int divfrac[9] = {0,
                        500,
                        250,
                        125,
                        375,
                        625,
                        750,
                        875,
                        1000};`

**Comment by patacongo** [comment]
I just fixed the nxstyle problems, rebased, and pushed to your branch.

Everything should be good now.

**Comment by patacongo** [comment]
In usbhost.h, the main problem was that there was a missing */ which confused nxstyle.

in the ft232 file, nxstyle was getting upset about the braces not being on the same line, I don't know why it gave such a bogus error string.  That tools is critical, but still needs a lot of work.

**Pull request merged**
