### PR TITLE
NuttX: update licenses to Apache

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
Update the license for several contributors that have submitted ICLA or SGA

## Impact
NONE

## Testing
NONE

### CODE REVIEW

**Comment by jerpelea** [comment]
please do not merge yet!

**Comment by jerpelea** [comment]
NO please leave it open (it should be ready to merge tomorrow)

**Comment by jerpelea** [comment]
I need the CI run to get the list of nxstyle  offender

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by Ouss4 — APPROVED** [review]

**Comment by jerpelea** [comment]
ready for merge

The remaining errors are Mixed Case errors

I think that we should add as exceptions the following:

for data 
*Gb*, *Mb*, *Kb*

time
*us, *ms

What do you think?

**Comment by jerpelea** [comment]
@Ouss4 looks like our mac checks fail

**Comment by v01d** [comment]
It seems to be an "internal error" with GitHub Actions. I would try rebasing and repushing.

**Comment by Ouss4** [comment]
Let's just merge it.  This PR already went through the tests before.

**Pull request merged**
