### PR TITLE
some tcp wip stuff

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by masayuki2009** [comment]
@yamt 

Thanks for fixing it.
I've been testing spresense:rndis_smp in telnet character mode.
It works without any problems so far.
And as long as I can see the packets with the Wireshark, TCP flow control is much improved.

**Review by jerpelea — APPROVED** [review]

**Comment by yamt** [comment]
> @yamt
> 
> Thanks for fixing it.
> I've been testing spresense:rndis_smp in telnet character mode.
> It works without any problems so far.
> And as long as I can see the packets with the Wireshark, TCP flow control is much improved.

thank you for testing.
i will submit a separate PR for the commit once https://github.com/apache/incubator-nuttx/pull/3948 is merged.

**Comment by masayuki2009** [comment]
>i will submit a separate PR for the commit once #3948 is merged.

@yamt 
OK. I confirmed that this PR also includes #3948's commits.
So, let me merge the PR.

**Comment by yamt** [comment]
closing, because this PR is now almost empty.

**Pull request closed without merging**
