### PR TITLE
Remove "kludge" code that came from PIC32

### PR DESCRIPTION
**Pull request by acassis**
## Summary
Remove "kludge" code that came from PIC32
## Impact
Improve code quality
## Testing
ESP32 Ethernet board

### CODE REVIEW

**Comment by Ouss4** [comment]
#1274

**Comment by acassis** [comment]
> #1274

Yes, but we cannot remove it from RISC-V without testing it on some RISC-V board.

**Comment by Ouss4** [comment]
> > #1274
> 
> Yes, but we cannot remove it from RISC-V without testing it on some RISC-V board.

I just want it to show as a reference in the issue's discussion.  I didn't want to link it to the PR, because if I do, it will be closed.
It'd be great if someone who uses RISC-V can verify that and remove the kludge as well.

**Comment by masayuki2009** [comment]
Hi @acassis,

I noticed that you removed the following code which did not come from PIC32.
Actually the code was added to reduce power consumption and is the same as esp-idf's.

```
#if XCHAL_HAVE_INTERRUPTS
  __asm__ __volatile__ ("waiti 0");
#endif
```

**Pull request merged**
