### PR TITLE
arch: rename arch special function name

### PR DESCRIPTION
**Pull request by zyfeier**
## Summary

 Rename arch special function name to arch_xxxxx.c

## Impact

NA

## Testing

sim:nsh

### CODE REVIEW

**Comment by davids5** [comment]
@zyfeier Why? What is the motivation AND justification for this change?

**Comment by zyfeier** [comment]
> @zyfeier Why? What is the motivation AND justification for this change?

@davids5 In the NuttX documentation we can see " An interface which is unique to a certain microprocessor should be prefixed with the name of the microprocessor". So, we modify arch special interface name to meet the requirements.

image

**Comment by xiaoxiang781216** [comment]
This is the continue work from @patacongo :
https://github.com/apache/incubator-nuttx/pull/926
https://github.com/apache/incubator-nuttx/pull/929
https://github.com/apache/incubator-nuttx/pull/930
https://github.com/apache/incubator-nuttx/pull/935
https://github.com/apache/incubator-nuttx/pull/937
https://github.com/apache/incubator-nuttx/pull/940
https://github.com/apache/incubator-nuttx/pull/948
https://github.com/apache/incubator-nuttx/pull/958
https://github.com/apache/incubator-nuttx/pull/958
https://github.com/apache/incubator-nuttx/pull/961

**Comment by hartmannathan** [comment]
Should add "breaking change" label just in case any out-of-tree code calls arch-specific functions?

**Comment by xiaoxiang781216** [comment]
> Should add "breaking change" label just in case any out-of-tree code calls arch-specific functions?

add

**Comment by xiaoxiang781216** [comment]
@davids5 and @pkarashchenko the patch is ready for review, please ignore the first three patch which belong to https://github.com/apache/incubator-nuttx/pull/7599 but this PR depends on them.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
