### PR TITLE
Implement getopt_long() and getopt_long_only()

### PR DESCRIPTION
**Pull request by patacongo**
## Summary

Add implementations of getopt_long() and getopt_long_only()

## Impact

There could be impacts to getop() since that implementation is shared withe new getopts_long() and getops_long_only() implementation.

## Testing

Tested using a modified version of sim:nsh and special getopt test case (part of OS test)

### CODE REVIEW

**Comment by patacongo** [comment]
This is is still a work in progress.  Additional verification is needed.  I have verified that it is backward compatible with the existing getopt() usage, but I still need to develop a OS test test case to verify all of the new options and features added by this PR.

**Comment by patacongo** [comment]
> 
> 
> This is is still a work in progress. Additional verification is needed. I have verified that it is backward compatible with the existing getopt() usage, but I still need to develop a OS test test case to verify all of the new options and features added by this PR.  I will mark the PR "Ready to Review" when I complete that testing.

**Comment by patacongo** [comment]
A test of this new functionality (as well as a regression test of getopt()) has been added.  See "testing/ostest: Add a test of the getopt() family of interfaces. #646".  That is an extension tothe OS test that provides a pretty good test of the getopt() family of functions.  The changes of this PR pass that test with no failures and, I believe, are ready to be merged into master.

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by Ouss4** [comment]
@patacongo @xiaoxiang781216 this broke Xtensa and RISC-V (at least ESP32-C3).  Running `ls` for instance is crashing.
Maybe the issue is related to https://github.com/apache/incubator-nuttx/issues/3241

**Comment by patacongo** [comment]
> @patacongo @xiaoxiang781216 this broke Xtensa and RISC-V (at least ESP32-C3). Running `ls` for instance is crashing.
> Maybe the issue is related to #3241

Is that just a 'ls' with no arguments?  This should not be platform specific.  Can you single step through the ls command to find where the failure is?

**Comment by Ouss4** [comment]
Yes it's `ls` without any argument.  Xtensa has a backtrace builtin, here it is decoded:

```
0x400d3603: xtensa_assert at xtensa_assert.c:93
0x400d36cd: xtensa_user_panic at xtensa_assert.c:320 (discriminator 2)
0x400d3593: xtensa_user at esp32_user.c:390
0x40080856: _xtensa_user_handler at xtensa_user_handler.S:257
0x400dc5b8: getopt_common at lib_getopt_common.c:298
0x400dc32a: getopt at lib_getopt.c:82
0x400d5b2a: cmd_ls at nsh_fscmds.c:1098
0x400d5632: nsh_command at nsh_command.c:1061
0x400d50e9: nsh_execute at nsh_parse.c:741
 (inlined by) nsh_parse_command at nsh_parse.c:2578
0x400d5186: nsh_parse at nsh_parse.c:2662
0x400d4650: nsh_session at nsh_session.c:191
0x400d43aa: nsh_consolemain at nsh_consolemain.c:115
0x400d4370: nsh_main at nsh_main.c:168
0x400d239c: nxtask_startup at task_startup.c:150
0x400d0fb8: nxtask_start at task_start.c:129
```

The line `lib_getopt_common.c:298` is causing the issue.  I'm checking up_create_stack for Xtensa, I also tried with the simulator and an STM32 board, both work fine.

**Comment by patacongo** [comment]
I do see a problem.  Could you try changing line

```
-  for (ndx = 0; longopts[ndx].name[0] != '\0'; ndx++)
+  for (ndx = 0; longopts[ndx].name != NULL; ndx++)

I will push this in a bit, but let's see if that does the job first.
```

**Comment by Ouss4** [comment]
I tried it with esp32-devkitc:nsh, still got a crash at the same line.

**Comment by Ouss4** [comment]
@patacongo a fix as you described in #3241 seems to be working in Xtensa.  I'll do more tests and submit a PR.

**Comment by patacongo** [comment]
@Ouss4 PR #3280 corrects the problem with the NULL pointer dereference (and makes other getopt() improvements that you won't really care about).

**Comment by patacongo** [comment]
> 
> 
> @patacongo a fix as you described in #3241 seems to be working in Xtensa. I'll do more tests and submit a PR.

There is a an issue with stack checking in Xtensa.  However that would only be a problem if stack coloration is enabled, I think.  So I am a little surprised.  I hope that is all there is to it!

**Pull request merged**
