### PR TITLE
arch/sim: Unify the driver initialization function name

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
change the sim_ prefix to the up_ prefix

Change-Id: I78417cbd2d4d68dddaf99c8ecba60ef3197eec5d
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by patacongo** [comment]
sim_ is actually the correct prefix.  See https://cwiki.apache.org/confluence/display/NUTTX/Naming+FAQ
up_ should ONLY be used with common microcontroller interfaces.  So all internal sim interfaces must begin with sim_ not up_.  Only common interfaces accessed outside of sim/ should begin with up_

**Comment by patacongo** [comment]
I think we should close this without merging.  What is your opinion.  Do you disagree with the naming convention?

**Comment by patacongo** [comment]
All of the up_ file names are also wrong.  These should all be sim_ .  The "microcontroller" name should always be used as the file name prefix.  The microntroller name should be the prefix used on all internal functions (including the board/ directories).

The correct change would be to change all of the up_ names to sim_.

**Comment by xiaoxiang781216** [comment]
> I think we should close this without merging. What is your opinion. Do you disagree with the naming convention?

Ok, it's fine to change all private up_ to sim_, the consistent is most important thingfor me. I will find sometime to update the PR, let's close it now.

**Comment by patacongo** [comment]
Yes, there is a big problem with consistency.  I tend to try to define a rule, then slowly bring things into agreement with the rule.  I am too careful and avoid too much turmoil.  A good is example is:  arch/arm/src/armv7-m which has incorrect naming and arch/arm/src/armv7-a which has correct naming.  I planned to change arch/arm/src/armv7-m to follow the convention too someday.

**Pull request closed without merging**
