### PR TITLE
libc: Change OK/ERROR from macro to enum

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
to avoid the conflict with 3rd party library(e.g. protobuf):
https://github.com/protocolbuffers/protobuf/blob/fdc35840b95f56c3aef44a3fc6ae5991f21620a5/src/google/protobuf/stubs/status.h#L47

## Impact
Improve the compatibility

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]

**Comment by yamt** [comment]
why is it conditional on C++?

**Comment by xiaoxiang781216** [comment]
> why is it conditional on C++?

Because many C++ code define OK as enum like this:
```
enum Code {
  OK = 0,
  ....
};
```
And it also follow how ERROR definition in NuttX:
```
#if !defined(__cplusplus)
#  undef  ERROR
#  define ERROR -1
#endif
```

**Comment by yamt** [comment]
is that any reason C++ code does it but C code doesn't?
otherwise, if we care namespace pollution, i guess it's better to remove OK/ERROR unconditionally.
or, make them conditional on `_NUTTX_SOURCE` or whatever.
how do you think?

**Comment by xiaoxiang781216** [comment]
> is that any reason C++ code does it but C code doesn't?
> otherwise, if we care namespace pollution, i guess it's better to remove OK/ERROR unconditionally.

OK/ERROR usage in NuttX is very large, removing OK/ERROR is a huge work.

> or, make them conditional on `_NUTTX_SOURCE` or whatever.
> how do you think?

Yes, it could work, but require we define or undefine _NUTTX_SOURCE in the different case.
Anyway, I change the macro to enum now, so we can avoid the namespace pollution in most case.

**Comment by yamt** [comment]
> > is that any reason C++ code does it but C code doesn't?
> > otherwise, if we care namespace pollution, i guess it's better to remove OK/ERROR unconditionally.
> 
> OK/ERROR usage in NuttX is very large, removing OK/ERROR is a huge work.

i agree.

> 
> > or, make them conditional on `_NUTTX_SOURCE` or whatever.
> > how do you think?
> 
> Yes, it could work, but require we define or undefine _NUTTX_SOURCE in the different case.

i agree.

> Anyway, I change the macro to enum now, so we can avoid the namespace pollution in most case.

unlike C++, enum names are not scoped in C, afaik.

anyway, i'm not against this PR. i just wanted to know if there's really something specific to C++.

**Comment by xiaoxiang781216** [comment]
> > > is that any reason C++ code does it but C code doesn't?
> > > otherwise, if we care namespace pollution, i guess it's better to remove OK/ERROR unconditionally.
> > 
> > 
> > OK/ERROR usage in NuttX is very large, removing OK/ERROR is a huge work.
> 
> i agree.
> 
> > > or, make them conditional on `_NUTTX_SOURCE` or whatever.
> > > how do you think?
> > 
> > 
> > Yes, it could work, but require we define or undefine _NUTTX_SOURCE in the different case.
> 
> i agree.
> 
> > Anyway, I change the macro to enum now, so we can avoid the namespace pollution in most case.
> 
> unlike C++, enum names are not scoped in C, afaik.
> 
> anyway, i'm not against this PR. i just wanted to know if there's really something specific to C++.

Yes, your concern is right: the problem isn't specific to C++. That's why the new change remove `#ifdef __cpluscplus` too.

**Comment by xiaoxiang781216** [comment]
@jerpelea could you merge this PR? all concern from @yamt has been addressed.

**Comment by yamt** [comment]
i'm not sure if it's safe to make them an enum. as they are mostly used as int in the tree. just a vague concern.

**Comment by patacongo** [comment]
> 
> 
> i'm not sure if it's safe to make them an enum. as they are mostly used as int in the tree. just a vague concern.

The most correct thing to do would be to remove the definitions of OK and ERROR and replace them with 0 and -1 as required by specifications.  OK and ERROR are not standard and not portable and best not a part of the OS

Unfortunately, the use of OK and ERROR is pervasive and would be awkward to remove.

**Comment by xiaoxiang781216** [comment]
> > i'm not sure if it's safe to make them an enum. as they are mostly used as int in the tree. just a vague concern.
> 
> The most correct thing to do would be to remove the definitions of OK and ERROR and replace them with 0 and -1 as required by specifications. OK and ERROR are not standard and not portable and best not a part of the OS
> 

@patacongo do you want to replace all OK/ERROR to 0/-1? If yes, I can try.

> Unfortunately, the use of OK and ERROR is pervasive and would be awkward to remove.

Or, take this patch to limit OK/ERROR damage scope.

**Comment by patacongo** [comment]
> > The most correct thing to do would be to remove the definitions of OK and ERROR and replace them with 0 and -1 as required by specifications. OK and ERROR are not standard and not portable and best not a part of the OS
> 
> @patacongo do you want to replace all OK/ERROR to 0/-1? If yes, I can try.

This would be more POSIX conformant since OK/ERROR is non-standard and non-portable.  And it would avoid introducing an enumeration type.

**Pull request merged**
