### PR TITLE
STM32H753II

### PR DESCRIPTION
**Pull request by anpaza**
Basic support for the STM32H753II chip.
It is pretty the same as the STM32H743ZI chip, so it re-uses files from 743, just adding extra #ifdefs. The only difference between 753 and 743 is the addition of cryptographic peripherial.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
> The CI is just style. The value is in the change.

@davids5 , why you bypass the style check? Don't break the rule you vote +1.

**Comment by davids5** [comment]
@xiaoxiang781216 - Oh so that was your argument. 

I will do a separate PR and fix all the style issues once the tools can report the real ones. This contributor has suffered from the tooling issues.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 - Oh so that was your argument.
> 

Yes, I already express my opinion in email thread. We should try our best to follow the rule, right?

> I will do a separate PR and fix all the style issues once the tools can report the real ones. This contributor has suffered from the tooling issues.

But can you ensure the change can pass the build? Yes, this patch is small, how about a little big change?
The better approach is append your style patch to this PR and trigger the precheck again:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by davids5** [comment]
@xiaoxiang781216 

>The better approach is append your style patch to this PR and trigger the precheck again:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

Yes. That it the right approach, and I will do it that way when I have time.

Did you add it to the work flow document?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> 
> > The better approach is append your style patch to this PR and trigger the precheck again:
> > https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> Yes. That it the right approach, and I will do it that way when I have time.
> 
> Did you add it to the work flow document?

The workflow document contain many options now, and it's hard for newbie to follow up. I would prefer that the main body of workflow document just describe the best practice the most contributor use daliy, for example:
1.One method to get source code
2.One method to send PR
3.One method to rework the PR after review
The reader just need follow the sequence step by step, no any if/else at all.
And then the document could list other alternatives or advance usage like this in the note section.

**Comment by davids5** [comment]
> The reader just need follow the sequence step by step, no any if/else at all.
+1

@xiaoxiang781216 good point - maybe it should be 3 pages. 
1 Simple highlevel contributing
2 Contributing workflow
2 Commiter's workflow

**Comment by patacongo** [comment]
Many people have contributed and reviewed that workflow.  It would be extremely bad style to discard that work.  I would have to be opposed to this.

The document must be fully inclusive and represent all people.  If you want a fully compkatible, short version, that would have to be in addition to the work of others and not a replacement for the work others.

Let's not "steam roller" ovee the community

**Pull request merged**
