### PR TITLE
Add support for motor debug messages

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
Add support for motor debug messages and use them in all FOC files.

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by acassis** [comment]
@raiden00pl I noticed there are two motors entry inside Device Drivers one in the middle and other in the bottom:

[ ] Motor driver
[ ] Motor control drivers  ----

Suggestion: merge both and keep it in the middle ;-)

**Comment by v01d** [comment]
> @raiden00pl I noticed there are two motors entries inside Device Drivers one at the middle and other at the bottom:
> 
> [ ] Motor driver
> [ ] Motor control drivers ----
> 
> Suggestion: merge both and keep it in the middle ;-)

Yes, ideally we should make motor.c also use these defines and organize both files inside same directory.

**Comment by raiden00pl** [comment]
I'll move motor.c to drivers/motor later. At this moment I want to finish support for FOC.

**Pull request merged**
