### PR TITLE
Added basic support for nucleo-g431kb board.

### PR DESCRIPTION
**Pull request by daniel-p-carvalho**
## Summary

Added basic support for nucleo-g431kb board.

## Impact

No impacts on other boards are expected.

## Testing

NSH is running properly.

### CODE REVIEW

**Review by hartmannathan — APPROVED** [review]
LGTM. I'm glad to see more development taking place on the STM32G4 family recently. Thanks for adding this board.

**Comment by daniel-p-carvalho** [comment]
I can't understand what is failing in CI check. Is it related with this PR?

**Comment by xiaoxiang781216** [comment]
Please run:
tools/refresh.sh --silent nucleo-g431kb/nsh
We require all defconfig in the normalization form.

**Comment by daniel-p-carvalho** [comment]
It's finished. You can merge to master if you wish.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
