### PR TITLE
Fix suspect DEBUGASSERT() like PR765

### PR DESCRIPTION
**Pull request by hartmannathan**
As pointed out by Şükrü Bahadır Arslan in PR765, function calls
inside DEBUGASSERT() will not be executed if DEBUGASSERT is
disabled. Following that PR, I searched for other instances of
similar errors and found four. As there are many thousands of
DEBUGASSERT in the code, this is *not* an exhaustive fix.

arch/arm/src/tms570/tms570_boot.c:
* In function arm_boot(), call tms570_memtest_complete()
  outside of the DEBUGASSERT(). Otherwise, if DEBUGASSERT is
  disabled, we will never rendezvous with completion of the
  test. (Two instances of this fix.)

arch/arm/src/tms570/tms570_clockconfig.c:
* In function tms570_clockconfig(), call
  tms570_efc_selftest_complete() outside of the DEBUGASSERT()
  for the same reason as above.

boards/arm/sam34/sam4s-xplained-pro/src/sam_boot.c:
* In function board_late_initialize(), call
  sam_watchdog_initialize() outside of the DEBUGASSERT() for
  the same reason as above.

### CODE REVIEW

**Comment by patacongo** [comment]
@hartmannathan You will need to fix the nxstyle complaints.

**Comment by patacongo** [comment]
@hartmannathan these are also appropriate fixes to bring into the 9.0 release, I would think.

**Comment by hartmannathan** [comment]
> @hartmannathan You will need to fix the nxstyle complaints.
> 
> Most likely the "Mixed case identifier" problems will not be fixable (unless they are fully local to the file). Otherwise, we can skip fixing the "Mixed case identifier" problems that span multiple files not included in the PR.

I just pushed a commit that fixes the nxstyle complaints.

I fixed the mixed case identifiers as well. They were fully local to the file.

One of them was a non-static function that does not appear to be called from anywhere in the nuttx repository. It is for dealing with some erratum of the tms570, _errata_SSWF021_45_both_plls(). If we merge this PR it will be called _errata_sswf021_45_both_plls().

**Comment by patacongo** [comment]
> One of them was a non-static function that does not appear to be called from anywhere in the nuttx repository. It is for dealing with some erratum of the tms570, _errata_SSWF021_45_both_plls(). If we merge this PR it will be called _errata_sswf021_45_both_plls().

I don't see any place that it is used.

**Pull request merged**
