### PR TITLE
Add USB Device support for i.MX RT

### PR DESCRIPTION
**Pull request by thomasactia**
arch/arm/src/imxrt/imxrt_usbdev: Add USB Device support for i.MX RT (USB OTG1)

Based on the LPC43xx USB Device driver.

### CODE REVIEW

**Comment by thomasactia** [comment]
TODO:
Extract clock/PLL code.
Style.

**Comment by patacongo** [comment]
DavidS is the designated reviewer.  He will do the merge after reviewing the changes.

**Comment by davids5** [comment]
@patacongo - it is a Draft PR -
image
 Not to be merged until done.

**Comment by thomasactia** [comment]
@davids5 I played some more with the driver and realized that I did not handle the cache for the data pointed to by the dTDs. I have made an update to the code, with the intention of handling the cache close to the edge between SW and HW.

Should I push the code here directly or wait for the review result - what is the usual way? Also, I put in a commit that strips away the old license+copyright header.

Right now, the code is on this branch: https://github.com/thomasactia/incubator-nuttx/commits/imxrt-usbdev-dtd-cache .

**Comment by davids5** [comment]
@thomasactia - Great. I would say push it here. Yon can even squash the commits and force push if you want to clean it up.

**Comment by davids5** [comment]
@thomasactia also run tools/nxstyle on it.

**Comment by thomasactia** [comment]
@davids5 Code has been updated and squashed. Also checked the files with nxstyle and got no errors, except for usbotg.h. I have not increased the number of errors in usbotg.h.

**Comment by davids5** [comment]
@thomasactia - thank you. I will get to this this week.  Is the todo list above still current?

**Comment by thomasactia** [comment]
@davids5 Great! All the things listed in the TODO have been done.

If you wish to compare with the LPC43 driver, I guess it is easiest to do before I did the code style fixing. https://github.com/apache/incubator-nuttx/commit/ff29624ae8e5c0dea0bcf44b597a11904885f94d  has that code. It is missing the cache handling and the header was not yet fixed.

**Pull request merged**
