### PR TITLE
Revert PR #2009

### PR DESCRIPTION
**Pull request by patacongo**
## Summary

We cannot accept any file into the repository that do not have Apache 2.0 lice headers

## Impact

None

## Testing

N/A

### CODE REVIEW

**Comment by patacongo** [comment]
We have to revert these changes.  We don't have an option.

Reverting the changes also removes  some NxStyle fixes and cause the Check to failure.  I think we have to live with that.

**Comment by btashton** [comment]
This is a trivial change that is all of 3 API calls, how else could this be implemented? Are we somehow now prevented for ever adding DAC support for STM32 in boards?

**Comment by patacongo** [comment]
> This is a trivial change that is all of 3 API calls, how else could this be implemented? Are we somehow now prevented for ever adding DAC support for STM32 in boards?

There are many other sources to leverage STM32 DAC files.  Unfortunately, one that has license issues was selected.  Haltian tends to slap their copyight on everything.

So, yes, we can support STM32 DAC.  No we cannot let this code into the repository.  We have to play be the rules.

**Comment by acassis** [comment]
Let's wait for @juniskane response about his ICLA or Haltian's SGA. There are many Haltian contributions from years ago when NuttX was BSD licensed and when Haltian submit their SGA we could change these code to Apache.

**Comment by patacongo** [comment]
> 
> 
> Let's wait for @juniskane response about his ICLA or Haltian's SGA. There are many Haltian contributions from years ago when NuttX was BSD licensed and when Haltian submit their SGA we could change these code to Apache.

Yes, let's wait.  But we must revert the changes while we are waiting.  We cannot break the rules like this.

**Comment by patacongo** [comment]
Is it an option to just add this to the heap of files that need IP clearance?  If that is the case, then we don't have to bother to enforce Apache licensing in PRs at all, do we?

**Comment by btashton** [comment]
We can just revert this, but I stand by my statement that if someone wanted to submit a PR that just made the two API calls under an Apache license I would accept it.

The code to add this is trivial:
```
g_dac = stm32l4_dacinitialize(0);
g_dac_register("/dev/dac0", g_dac);
```

**Comment by btashton** [comment]
@patacongo can you update this PR to only be commit e79ed71a1d5e854589e5db0f094c421a2ab6beae

That is the one that added the new file and the API calls, unless you see some reason to not take the style fixes?

**Comment by patacongo** [comment]
> @patacongo can you update this PR to only be commit [e79ed71](https://github.com/apache/incubator-nuttx/commit/e79ed71a1d5e854589e5db0f094c421a2ab6beae)
> 
> That is the one that reverts adding the new file and the API calls, unless you see some reason to not take the style fixes?

I tried that, but I get a conflict.  The NxStyle fixes modify the new file with the illegal license header as will.  So if you try to take only two of the three commits, you get a CONFLICT.

**Comment by btashton** [comment]
@patacongo 
[0001-Revert-PR-2009.txt](https://github.com/apache/incubator-nuttx/files/5396928/0001-Revert-PR-2009.txt)

this attached patch should apply cleanly on master with `cat 0001-Revert-PR-2009.txt | git am`

**Comment by patacongo** [comment]
> @patacongo
> [0001-Revert-PR-2009.txt](https://github.com/apache/incubator-nuttx/files/5396928/0001-Revert-PR-2009.txt)
> 
> this attached patch should apply cleanly on master with `cat 0001-Revert-PR-2009.txt | git am`

Thanks!  I backed out the three reverts and replaced this with your patch only.

**Review by btashton — APPROVED** [review]
I'll merge once CI finishes

**Comment by patacongo** [comment]
One thing that we could to ameliorate the problem would be to and STM32L4 common driver directory.  These licensing problem applies only to STM32L4.

    boards/arm/stm32l4/nucleo-l432kc/src/stm32_dac.c: *   Copyright (C) 2017 Haltian Ltd. All rights reserved.
    boards/arm/stm32l4/nucleo-l452re/src/stm32_dac.c: *   Copyright (C) 2017 Haltian Ltd. All rights reserved.
    boards/arm/stm32l4/nucleo-l496zg/src/stm32_dac.c: *   Copyright (C) 2017 Haltian Ltd. All rights reserved.
    boards/arm/stm32l4/stm32l4r9ai-disco/src/stm32_dac.c: *   Copyright (C) 2017-2018 Haltian Ltd. All rights reserved.

@acassis @daniel-p-carvalho If all of the STM32L4 board-layer drivers were made common, then any additional STM32L4 driver could included for any STM32L4 board without violated the ASF licensing requirements since there would be only one copy of the file and that one copy can be shared by everyone.

**Pull request merged**
