### PR TITLE
risc-v/esp32c3: Support ESP32-C3 wireless ioctl cmd

### PR DESCRIPTION
**Pull request by cwespressif**
This feature was implemented by Chen Wen chenwen@espressif.com
and reviewed by Abdelatif Guettouche && Gustavo Henrique Nihei.

## Summary

- Support more ESP32-C3 wireless ioctl commands
- Support station and softap mode.

## Impact

- Provide better WAPI support on ESP32-C3

## Testing

- Tested with ESP32-C3-Devkitc

`./tools/configure esp32c3-devkit:wapi`  or `./tools/configure esp32c3-devkit:sta_softap`

### CODE REVIEW

**Comment by acassis** [comment]
Hi @cwespressif please update the board configs:
$ ./tools/refresh.sh --silent esp32c3-devkit:board_config_name

**Comment by cwespressif** [comment]
> Hi @cwespressif please update the board configs:
> $ ./tools/refresh.sh --silent esp32c3-devkit:board_config_name

It is a issue of mismatch in the print output format in `fs/spiffs`, I have fixed these `warnings`.

**Comment by Ouss4** [comment]
@cwespressif please rebase this branch.  There was an issue with an STM32 configuration that seems to be fixed now.

**Comment by cwespressif** [comment]
> @cwespressif please rebase this branch. There was an issue with an STM32 configuration that seems to be fixed now.

Done.

**Review by Ouss4 — APPROVED** [review]

**Pull request merged**
