### PR TITLE
net/tcp/monitor: do not migrate the state to close

### PR DESCRIPTION
**Pull request by anchao**
## Summary

net/tcp/monitor: do not migrate the state to close

1. remove the unnecessary interfaces tcp_close_monitor()

socket flags(s_flags) is a global state for net connection
remove the incorrect update for stop monitor

2. do not start the tcp monitor from duplicated psock

the tcp monitor has already registered in connect callback

This patch also fix the telnet issue reported by:
https://github.com/apache/incubator-nuttx/pull/5434#issuecomment-1035600651

the orignal session fd is closed after dup, the connect state
has incorrectly migrated to close:

```
drivers/net/telnet.c:
 977 static int telnet_session(FAR struct telnet_session_s *session)
 ...
 1031   ret = psock_dup2(psock, &priv->td_psock);
 ...
 1082   nx_close(session->ts_sd);
```

Signed-off-by: chao.an <anchao@xiaomi.com>

## Impact

N/A

## Testing

telnet test

link issue:
https://github.com/apache/incubator-nuttx/pull/5434

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@a-lunev @masayuki2009 could you take look and try?

**Comment by masayuki2009** [comment]
@anchao 
I confirmed that this PR fixes the issue reported in https://github.com/apache/incubator-nuttx/pull/5434#issuecomment-1035600651

However, I think the commit log does not describe the issue.
So please add comments in the commit messages that this commit fixes the issue.

**Comment by anchao** [comment]
> @anchao I confirmed that this PR fixes the issue reported in [#5434 (comment)](https://github.com/apache/incubator-nuttx/pull/5434#issuecomment-1035600651)
> 
> However, I think the commit log does not describe the issue. So please add comments in the commit messages that this commit fixes the issue.

@masayuki2009 san,

I have update the commit message, please review again

**Comment by masayuki2009** [comment]
>I have update the commit message, please review again

@anchao 
LGTM

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by a-lunev** [comment]
Thank you for the patch.
telnetd now is working on sim:tcpblaster config as well.

**Pull request merged**
