### PR TITLE
STM32F412 board support

### PR DESCRIPTION
**Pull request by dakejahl**
## Summary
This PR adds support for the STM32F412. This has been tested with the NUCLEO-F412ZG board from ST, as well a custom board using the F412CE.

#### F412ZG
- UART
- SPI
- CAN

#### F412CE
- UART
- SPI
- CAN
- I2C
- DMA

### CODE REVIEW

**Comment by davids5** [comment]
@dakejahl - please see the Coding standard formatting.  run tools/checkpatch.sh to fix them

**Comment by dakejahl** [comment]
I don't understand how `checkpatch` works. Does it do anything automatically or is the purpose just to show which lines are breaking which rules and then I manually fix them?

**Comment by acassis** [comment]
> I don't understand how `checkpatch` works. Does it do anything automatically or is the purpose just to show which lines are breaking which rules and then I manually fix them?

Hi Jacob,
checkpatch works similar to the checkpatch from Linux kernel.

If you want to see the issues reported by the "Check / check (pull_request)" just click in Details.

I paste it here to make it easier to you: https://pastebin.com/81qH8anp

**Comment by raiden00pl** [comment]
Hi, could you please explain why you created a new *.c file for RCC configuration ?
From what I see, the clock tree for STM32F412 is not much different from other STM32F4.

**Comment by davids5** [comment]
@dakejahl the technical side please look into @raiden00pl query.

On the process side: Unfortunately  this project has limited the committer's ability to do the right type of merge.
image 

Therefor I need to ask to clean up the commit and comments and force push. See [the link and do's and dont's](https://github.com/nuttx-to-asf/incubator-nuttx/blob/master-pr-add-PR-template/.github/PULL_REQUEST_TEMPLATE.md) you can ignore the rest.

**Comment by acassis** [comment]
Congratulations Jacob! Now it is passing in the CI tests. I was going to Merge it when I saw the raiden00pl question about why you created a new file to RCC configuration. Do you think it is possible to use the existing file? @raiden00pl for consistency do you think he could rename stm32f40xxx_rcc.c to stm32f4xxxx_rcc.c ? Also if this RCC is different enough to include many #ifdefs inside stm32f40xxx_rcc.c, then I think it is better to keep it in a different file. What do you think?

**Comment by dakejahl** [comment]
Alright I'll squash and force push as a single commit. I made the extra rcc.c file because I was trying to keep things straight in my head when doing the bringup, and I found it easier to understand the code without all of the extra preprocessor logic. I can probably consolidate it into the generic rcc file and I'll rename it to be stm32f4xxxx_rcc.c

**Comment by dakejahl** [comment]
I took a quick stab at coalescing the rcc files, I don't have time this week to give the proper focused attention to this task (lots of minor painstaking differences) -- retesting to make sure I don't break anything in the process. Might have time next week.

**Comment by acassis** [comment]
Don't worry Jacob, take your time!

**Comment by davids5** [comment]
@acassis @raiden00pl Any reasons not to merge for your side?

**Comment by dakejahl** [comment]
Thanks everyone!

**Pull request merged**
