### PR TITLE
cxd56xx: spresense: Add some improvements and fix bugs for Spresense …

### PR DESCRIPTION
**Pull request by SPRESENSE**
## Summary

Improvements and fixes for Spresense board.

- Add new functions of GNSS
- Support the lower PWM frequency
- Add CONFIG_CPUFREQ_RELEASE_LOCK
- Add high speed ADC support
- Add HPADC input gain configuration
- Add eMMC device
- Frame buffer support
- Fix SD/GNSS/sensor drivers not worked
- Fix build errors
- Fix nxstyle issues

## Impact

Spresense users

## Testing

Tested by Spresense board

### CODE REVIEW

**Comment by jerpelea** [comment]
please fix the build errors

**Comment by SPRESENSE** [comment]
I pushed some patches for CI builds but build still failing. It seems to me that the log contains no errors. How do I fix this?

**Comment by Ouss4** [comment]
> I pushed some patches for CI builds but build still failing. It seems to me that the log contains no errors. How do I fix this?

The errors are related to defconfigs.
```
Normalize spresense/module
33d32
< CONFIG_I2C=y
```
You need to run ./tools/refresh.sh --silent spresense:module to update the defconfig.

**Comment by SPRESENSE** [comment]
@Ouss4 Thanks!

**Comment by masayuki2009** [comment]
Hi @SPRESENSE @jerpelea,

I found that this PR affects gs2200m driver.
Actually, I tried spresense:wifi and it causes assert in the driver when I executed 'renew eth0'

**Comment by masayuki2009** [comment]
> Hi @SPRESENSE @jerpelea,
> 
> I found that this PR affects gs2200m driver.
> Actually, I tried spresense:wifi and it causes assert in the driver when I executed 'renew eth0'

Finally, I found a bug in the gs2200m driver.
I've just sent https://github.com/apache/incubator-nuttx/pull/1475

**Comment by jerpelea** [comment]
@ masayuki2009  thanks for looking into it

**Pull request merged**
