### PR TITLE
libs/libc/arm: use builtin routines instead of aliases of __aeabi_mem*

### PR DESCRIPTION
**Pull request by anchao**
## Summary

libs/libc/arm: use builtin routines instead of aliases of __aeabi_mem*

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

N/A

## Testing

armclang/clang/gcc

### CODE REVIEW

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 do you recall why it was originally added? Was it because we used no-builtin flag?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 do you recall why it was originally added?

Sorry, I can't remember why add these functions:(. But since these functions block armclang LTO link, we can remove these functions first, and watch any bad feedback. Anyway, it's always be good to prefer the implementation provided by compiler.

> Was it because we used no-builtin flag?

https://github.com/apache/incubator-nuttx/pull/5971 is related to no-builtin, not __aeabi_memxxx.

**Review by pkarashchenko — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Since this change simply remove built-in functions implemented on ARM, Let's ignore macOS false alarm.

**Comment by casaroli** [comment]
Sorry for bumping this after 3 years.

> and watch any bad feedback

We finally have some bad feedback 😅 .

It looks like https://github.com/bytecodealliance/wasm-micro-runtime/pull/4718 wants to use these functions.

The problem can be seen [here](https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/19575759345/job/56060485385?pr=4718):
```
LD: nuttx
arm-none-eabi-ld: warning: group_join.o: missing .note.GNU-stack section implies executable stack
arm-none-eabi-ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
arm-none-eabi-ld: /__w/wasm-micro-runtime/wasm-micro-runtime/nuttx/staging/libapps.a(aot_reloc_thumb.c.__w.wasm-micro-runtime.wasm-micro-runtime.apps.interpreters.wamr_1.o):(.data.target_sym_map+0x3f4): undefined reference to `__aeabi_memclr'
arm-none-eabi-ld: /__w/wasm-micro-runtime/wasm-micro-runtime/nuttx/staging/libapps.a(aot_reloc_thumb.c.__w.wasm-micro-runtime.wasm-micro-runtime.apps.interpreters.wamr_1.o):(.data.target_sym_map+0x3fc): undefined reference to `__aeabi_memcpy'
arm-none-eabi-ld: /__w/wasm-micro-runtime/wasm-micro-runtime/nuttx/staging/libapps.a(aot_reloc_thumb.c.__w.wasm-micro-runtime.wasm-micro-runtime.apps.interpreters.wamr_1.o):(.data.target_sym_map+0x404): undefined reference to `__aeabi_memmove'
arm-none-eabi-ld: /__w/wasm-micro-runtime/wasm-micro-runtime/nuttx/staging/libapps.a(aot_reloc_thumb.c.__w.wasm-micro-runtime.wasm-micro-runtime.apps.interpreters.wamr_1.o):(.data.target_sym_map+0x40c): undefined reference to `__aeabi_memset'
```

Should we try to revert this PR?

**Comment by xiaoxiang781216** [comment]
@no1wudi does wasm switch to use _aeabi_xxxx api?

**Comment by no1wudi** [comment]
> @no1wudi does wasm switch to use _aeabi_xxxx api?

Maybe LLVM would produce function call to them direcly in AOT mode for some instruction combinations, I'll take a look.

**Comment by no1wudi** [comment]
@xiaoxiang781216 @casaroli 

## Core Issue
WAMRC generates different memory function calls depending on the target ABI used for ARM compilation.
## Function Call Analysis
### EABI ABIs (eabihf, eabi)
Generate ARM EABI-specific functions:
```
__aeabi_memmove    - Memory block copy for overlapping regions
__aeabi_memclr     - Memory clear/set to zero
```
### GNU ABIs (gnu, gnueabihf)  
Generate standard C library functions:
```
memmove            - Standard memory copy
memset             - Standard memory set
```
## Test Results
| ABI | __aeabi_* Functions | Standard Functions | Status |
|-----|-------------------|-------------------|---------|
| eabihf | YES | NO | Requires ARM EABI library |
| eabi | YES | NO | Requires ARM EABI library |
| gnu | NO | YES | Uses standard libc |
| gnueabihf | NO | YES | Uses standard libc |
## Root Cause
The ABI specification determines which memory function implementations LLVM targets:
- **EABI ABIs**: Generate calls to ARM EABI functions (`__aeabi_*`)
- **GNU ABIs**: Generate calls to standard POSIX functions (`memmove`, `memset`)
This affects compatibility with different C library implementations.

So, I guess restore them can improve compatibiliy with 3rd party generated objects?

**Pull request merged**
