### PR TITLE
sched/task: Simplify the syscall handling of task_spawn

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
It's better to save one argument by returning pid directly.
This change also follow the convention of task_create.
BTW, it is reasonable to adjust the function prototype a
little bit from both implementation and consistency since
task_spawn is NuttX specific API.

## Impact
Change the fucntion prototype of task_spawn

## Testing
Pass CI.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
The build break is fixed from apps side:
https://github.com/apache/incubator-nuttx-apps/pull/710
Please review and commit both patch together.

**Comment by v01d** [comment]
I can't provide a meaningful review since I never used this function. I understand you're removing an unneeded parameter but there are other changes that I don't exactly follow (the disappearing struct and changes to ifdefs related to syscalls).

**Comment by xiaoxiang781216** [comment]
> I can't provide a meaningful review since I never used this function. I understand you're removing an unneeded parameter but there are other changes that I don't exactly follow (the disappearing struct and changes to ifdefs related to syscalls).

Since the old task_spawn has 7 arguments , but syscall can accept maximum 6 arguments, struct has to been created to packet 7 argument into one big argument. With the patch, the argument of task_spawn reduce to 6, so we can remove the workaround(ifdef plus struct).

**Comment by v01d** [comment]
> > I can't provide a meaningful review since I never used this function. I understand you're removing an unneeded parameter but there are other changes that I don't exactly follow (the disappearing struct and changes to ifdefs related to syscalls).
> 
> Since the old task_spawn has 7 arguments , but syscall can accept maximum 6 arguments, struct has to been created to packet 7 argument into one big argument. With the patch, the argument of task_spawn reduce to 6, so we can remove the workaround(ifdef plus struct).

Got it, that makes sense. I'll approve the change, but it is better for someone else more familiar to review.

**Review by v01d — APPROVED** [review]

**Comment by davids5** [comment]
@xiaoxiang781216 - the changes look fine to me. Not getting a clean build is an issue. What is you plan here?

**Comment by xiaoxiang781216** [comment]
we have to merge this PR and https://github.com/apache/incubator-nuttx-apps/pull/710 together. And watch the potential(unlikely) build break.

**Comment by masayuki2009** [comment]
>we have to merge this PR and apache/incubator-nuttx-apps#710 together. And watch the potential(unlikely) build break.

@xiaoxiang781216 
I tried both branches with sabre-6quad:smp (QEMU).

```
CC:  task/task_spawn.c
In file included from /mnt/m2ssd/opensource/github_xiang/nuttx-xiang/include/nuttx/mm/shm.h:30,
                 from /mnt/m2ssd/opensource/github_xiang/nuttx-xiang/include/nuttx/sched.h:41,
                 from /mnt/m2ssd/opensource/github_xiang/nuttx-xiang/include/sched.h:36,
                 from task/task_spawn.c:28:
task/task_spawn.c: In function 'task_spawn':
task/task_spawn.c:321:9: warning: format '%p' expects argument of type 'void *', but argument 3 has type 'int' [-Wformat=]
  321 |   sinfo("pid=%p name=%s entry=%p file_actions=%p attr=%p argv=%p\n",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  322 |         pid, name, entry, file_actions, attr, argv);
      |         ~~~
      |         |
      |         int
task/task_spawn.c:321:15: note: format string is defined here
  321 |   sinfo("pid=%p name=%s entry=%p file_actions=%p attr=%p argv=%p\n",
      |              ~^
      |               |
      |               void *
      |              %d
task/task_spawn.c:332:32: warning: passing argument 1 of 'nxtask_spawn_exec' makes pointer from integer without a cast [-Wint-conversion]
  332 |       return nxtask_spawn_exec(pid, name, entry, attr, argv);
      |                                ^~~
      |                                |
      |                                pid_t {aka short int}
task/task_spawn.c:87:41: note: expected 'pid_t *' {aka 'short int *'} but argument is of type 'pid_t' {aka 'short int'}
   87 | static int nxtask_spawn_exec(FAR pid_t *pidp, FAR const char *name,
      |                                  ~~~~~~~^~~~
task/task_spawn.c:332:14: warning: 'pid' may be used uninitialized in this function [-Wmaybe-uninitialized]
  332 |       return nxtask_spawn_exec(pid, name, entry, attr, argv);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
nsh> ps
  PID CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0   0   0 FIFO     Kthread N-- Assigned           00000000 001024 000392  38.2%  CPU0 IDLE
    1   1   0 FIFO     Kthread N-- Running            00000000 001024 000208  20.3%  CPU1 IDLE
    2   2   0 FIFO     Kthread N-- Running            00000000 001024 000208  20.3%  CPU2 IDLE
    3   3   0 FIFO     Kthread N-- Running            00000000 001024 000208  20.3%  CPU3 IDLE
    5 --- 192 RR       Kthread --- Waiting  Signal    00000000 002032 000192   9.4%  hpwork
    6   0 100 RR       Task    --- Running            00000000 002032 000992  48.8%  init
nsh> hello
arm_dataabort: Data abort. PC: 10813ca8 DFAR: 00001081 DFSR: 0000080d
up_assert: Assertion failed CPU0 at file:armv7-a/arm_dataabort.c line: 160 task: init
up_registerdump: R0: 00000007 00000000 00000000 00000000 00000000 10832808 00001081 108229ba
up_registerdump: R8: 1081766c 1081766c 10832808 fffffff1 1082ea60 10832798 108024a0 10813ca8
up_registerdump: CPSR: 20000053
up_dumpstate: Current sp: 10832670
up_dumpstate: Interrupt stack:
up_dumpstate:   base: 1082aa38
up_dumpstate:   size: 00000800
up_dumpstate:   used: 000000d8
up_dumpstate: User stack:
up_dumpstate:   base: 108321c0
up_dumpstate:   size: 000007f0
up_dumpstate:   used: 0000042c
up_dumpstate: ERROR: Stack pointer is not within the interrupt stack
```

**Comment by xiaoxiang781216** [comment]
@davids5 and @masayuki2009 done, the change pass sabre-6quad:smp test locally. Sorry for late reply, I have a long team building in the last weak.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
Could you please rebase both branches with the latest master?
I think they are still behind the master.

**Comment by xiaoxiang781216** [comment]
Done for both PR, @masayuki2009 please try it.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
Hmm, sim-02 and macOS still fail.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> Hmm, sim-02 and macOS still fail.
> 
> ```
> 
> ====================================================================================
> Configuration/Tool: sim/vpnkit
> ------------------------------------------------------------------------------------
>   Cleaning...
>   Configuring...
>   Building NuttX...
> exec_builtin.c: In function 'exec_builtin':
> Error: exec_builtin.c:195:24: error: passing argument 1 of 'task_spawn' from incompatible pointer type [-Werror=incompatible-pointer-types]
>   195 |       ret = task_spawn(&pid, builtin->name, builtin->main, &file_actions,
>       |                        ^~~~
>       |                        |
>       |                        pid_t * {aka short int *}
> In file included from exec_builtin.c:49:
> ```

@masayuki2009 this error happen inside apps folder. Both this PR and https://github.com/apache/incubator-nuttx-apps/pull/710 need work together.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 
My automatic tests all passed.

**Comment by Ouss4** [comment]
I think this one has broken some builds.

**Pull request merged**
