### PR TITLE
This PR mainly contains some USRSOCK related changes

### PR DESCRIPTION
**Pull request by zhhyu7**
## Summary
This PR mainly contains some USRSOCK related changes
## Impact
This submission depends on the app's submission！

### CODE REVIEW

**Comment by zhhyu7** [comment]
depends on https://github.com/apache/incubator-nuttx-apps/pull/1116

**Comment by zhhyu7** [comment]
depends on https://github.com/apache/incubator-nuttx/pull/5944 too.

**Comment by masayuki2009** [comment]
Hmm, spresense:wifi does not work.
It stops during the boot.

**Comment by zhhyu7** [comment]
> Hmm, spresense:wifi does not work. It stops during the boot.

Could you please help to add these patches one by one to see which caused the problem, Thanks.

**Comment by zhhyu7** [comment]
> Hmm, spresense:wifi does not work. It stops during the boot.

I removed the most suspect patch.

**Comment by xiaoxiang781216** [comment]
> Hmm, spresense:wifi does not work. It stops during the boot.

@zhhyu7 remove the patch which will block client side socket api call if the server side isn't ready. @masayuki2009 could you try the rest patchset again?

**Comment by masayuki2009** [comment]
>I removed the most suspect patch.

@zhhyu7 
spresense:wifi can boot now but the renew command failed.

```
nsh> uname -a
NuttX  10.3.0-RC0 73c2d4ead0 Apr  2 2022 18:06:06 arm spresense
nsh> ps
  PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0 FIFO     Kthread N-- Ready              00000000 001000 000376  37.6%  Idle Task
    1     1 224 RR       Kthread --- Waiting  Signal    00000000 002016 000460  22.8%  hpwork 0x2d054588
    2     2  60 RR       Kthread --- Waiting  Semaphore 00000000 002016 000276  13.6%  lpwork 0x2d054598
    3     3 100 RR       Task    --- Running            00000000 003048 001224  40.1%  spresense_main
    4     4 200 RR       Task    --- Waiting  MQ empty  00000000 001000 000468  46.8%  cxd56_pm_task
nsh> free
                   total       used       free    largest  nused  nfree
        Umem:    1213008      37504    1175504    1175504    106      1
nsh> mount
  /mnt/spif type smartfs
  /proc type procfs
nsh> ifconfig
wlan0	Link encap:Ethernet HWaddr 00:00:00:00:00:00 at UP
	inet addr:0.0.0.0 DRaddr:0.0.0.0 Mask:0.0.0.0

nsh> gs2200m raspi3-g wifi-test-24g & 
gs2200m [5:50]
nsh> renew wlan0
ERROR: dhcpc_request() failed
```

**Comment by xiaoxiang781216** [comment]
@masayuki2009 @zhhyu7 remove all unnecessary change from PR, the change is very simply now, could you try again? Thanks for helping. BTW, could you share a gs2200m to us? We have buy several spresense board but all without WiFi module because it's hard to find the supplier in China market can provide WiFi module.

**Comment by masayuki2009** [comment]
@zhhyu7 @xiaoxiang781216 
I confirmed that spresene:wifi, spresense:wifi_smp and stm32f4discovery:wifi work.

**Review by masayuki2009 — APPROVED** [review]

**Comment by masayuki2009** [comment]
>BTW, could you share a gs2200m to us? We have buy several spresense board but all without WiFi module because it's hard to find a supplier in China market can provide WiFi module.

@xiaoxiang781216 
You can buy the Wi-Fi add-on board from the chip1Stop. They can ship the product to China.

https://www.chip1stop.com/USA/en/view/dispDetail/DispDetail?partId=IDYC-0000001

**Comment by xiaoxiang781216** [comment]
Thanks, I have ordered one so we can verify locally in the next time.

**Pull request merged**
