### PR TITLE
esp32-devkitc:wamr_wasi_debug: pin WAMR version

### PR DESCRIPTION
**Pull request by yamt**
## Summary
The "main" branch occasionally got broken.
It isn't nice to break our (nuttx's) CI every time it happens.

## Testing
locally build-tested with https://github.com/apache/incubator-nuttx-apps/pull/1180

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@yamt could you rebase your patch? look like the server insist to use the cached data instead downloading again.

**Comment by yamt** [comment]
> @yamt could you rebase your patch? look like the server insist to use the cached data instead downloading again.

done.

i guess you need to restart all jobs, not only the failed ones, because it's the "fetch-source" job which needs to be restarted, not the failed one.

**Comment by yamt** [comment]
> Should be nice if we could get automatically the last stable TAG, otherwise it could be lost fixed on this commit version.

for a longer term, maybe we can propose a job to test nuttx build on their ci.

**Comment by yamt** [comment]
> Why is it failing to extract:
> 
> ```
> Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_498cbadd-778c-4799-a999-9152a02f8447/8fd04038-787e-4a61-96d3-b4df35c8c557.tar.gz. return code: 2
> ```

i have no idea.

**Pull request merged**
