### PR TITLE
macOS related documentation updates

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@yamt it's great if you can take time to add precheck for macOS when you fine some free time.

**Comment by yamt** [comment]
@xiaoxiang781216 
is it acceptable to have something separate from the cibuild.sh?
the cibuild.sh thing looks very linux specific and too complex for my taste.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216
> is it acceptable to have something separate from the cibuild.sh?
> the cibuild.sh thing looks very linux specific and too complex for my taste.

Yes, the installation section is very Linux sepecific, but other section(repo sync, build...) is very generic.

For github precheck, all toolchains are preinstalled in the dock image, so the above installation isn't a real issue any more. I suppose that we only need:
1.Prepare a dock image bundled with tools like this:
   https://github.com/apache/incubator-nuttx-testing/blob/master/docker/linux/Dockerfile
2.Add new job for macOS here:
   https://github.com/apache/incubator-nuttx/blob/master/.github/workflows/main.yml
Maybe, it's enough to select/run serveral config from each board in one VM.

**Comment by yamt** [comment]
@xiaoxiang781216 are you suggesting to run macos in docker? is it even possible?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 are you suggesting to run macos in docker? is it even possible?

I don't know it's possible to use docker for macOS. If not, we can switch to use the pure VM image bundled with tools.

**Pull request merged**
