### PR TITLE
boards: Update telnetd related config after apps/nshlib change

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
paired with https://github.com/apache/incubator-nuttx-apps/pull/1362

## Impact
telnetd

## Testing
Pass CI

### CODE REVIEW

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 is this a "breaking change"

**Review by pkarashchenko — APPROVED** [review]

**Review by hartmannathan — COMMENTED** [review]
Since Kconfig names are changing, I agree it needs an entry in the release notes for out-of-tree boards. I'll add the "breaking change" label and get started on release notes for the next version!

**Comment by hartmannathan** [comment]
The new draft release notes for NuttX-11.1.0 is on the CWIKI at [https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.1.0](https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.1.0). When this PR is merged, I will add the changes under "Compatibility Concerns" -> "Renamed or Modified Kconfig Options".

Feel free to document things there as work progresses. It makes for less work around release time. :-)

**Comment by xiaoxiang781216** [comment]
> The new draft release notes for NuttX-11.1.0 is on the CWIKI at https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.1.0. When this PR is merged, I will add the changes under "Compatibility Concerns" -> "Renamed or Modified Kconfig Options".
> 
> Feel free to document things there as work progresses. It makes for less work around release time. :-)

I will update the document after merging.

**Comment by jerpelea** [comment]
Thanks for creating the page
Best regards
Alin

**Pull request merged**
